### PR TITLE
Patch disable add paused if trakt rolling

### PR DESCRIPTION
**Pull request by gborri**

### CODE REVIEW

**Comment by gborri** [comment]
I've tried to squash also this PR but have no success in doing it. There is a lot of mixed commit and the procedure i have adopted for the other doesn't work. Anyone can help?

**Comment by miigotu** [comment]
Do you have a separate remote called `upstream` for the main repo?

**Comment by miigotu** [comment]
By the way, shouldn't a user be able to add a show paused regardless of trakt rolling is enabled? trakt rolling should just not touch the show if it is paused.

**Comment by gborri** [comment]
@miigotu you are right. but the point is: would you  like to add show from trakt watchlist in active or paused mode? if active sickrage starts to downloa, for each show, "number of episode" configured episode.

**Comment by gborri** [comment]
This PR have just cosmetic change asked by @fernandog

**Comment by gborri** [comment]
@miigotu @fernandog i don't know how but i got it. suqashed on #2036

**Pull request closed without merging**
