### PR TITLE
Added the RDI network logo.

### PR DESCRIPTION
**Pull request by neoatomic**
fix for https://github.com/SiCKRAGETV/sickrage-issues/issues/3236

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by duramato** [comment]
@neoatomic afaik that CBC logo ,the RDI logo is this (the on the right) image

**Comment by neoatomic** [comment]
Wiki tells the below is the new 2014 logo. 
https://fr.wikipedia.org/wiki/ICI_RDI#/media/File:ICIRDI_Logo_2014.png

**Comment by duramato** [comment]
@neoatomic i see ,but maybe add like the logo has the "RDI" ?

**Comment by neoatomic** [comment]
I'm happy with the logo i submitted, but feel to create one. :)

**Pull request merged**
