### PR TITLE
Fix "mass edit" subtitle enable action

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/836

@Hellowlol can you try? use this file please

### CODE REVIEW

**Comment by Hellowlol** [comment]
I can, but i dont think that is the feature i want. I want the subtitle field to not be disabled. Thats all.

**Comment by fernandog** [comment]
@Hellowlol that does exactly what you requested. Subtitle check-box won't be grey out

**Comment by Hellowlol** [comment]
Sweet :) thanks.

**Comment by fernandog** [comment]
@Hellowlol worked? Can I merge?

**Comment by Hellowlol** [comment]
I cant check, im still at work ill ping you when i have tested it.

**Comment by abeloin** [comment]
@fernandog Why this PR? You can already enable/disable for multiple shows using the "Edit selected" button. With this PR you loose the ability to know which show are subtitle enable.

**Comment by fernandog** [comment]
@abeloin if the show didn't have subtitle enabled, you couldn't enable it in the mass update page. This page is different from the one where you choose "enable|disable|keep"

**Comment by abeloin** [comment]
@fernandog Have you ever tried to select the show you want subtitles enabled by checking in the edit column and then click "Edit Selected"?

**Comment by fernandog** [comment]
I did. But there is a hidden column just for subtitle. The checkbox for that colums are disabled (not unchecked!)

**Comment by abeloin** [comment]
@fernandog Honestly your breaking expected behavior, now there is no way to know which show has subtitles enable. That column should be like sports, scene, anime it's subtitles status which was wrongly implemented. The subtitles edition should be and is done via edit selected and the subtitle column should be corrected to display a check or a x depending its enable.

**Comment by abeloin** [comment]
This is how it should look like:
Imgur

**Comment by Hellowlol** [comment]
I disgree, should scrap it and just use check boxes on everything imo

**Comment by abeloin** [comment]
Looking further at the code, the column subtitles isn't for adding or removing subtitles it's to force download subtitle, from the code
```
            if curShowID in toSubtitle:
                sickbeard.showQueueScheduler.action.downloadSubtitles(showObj)
                subtitles.append(showObj.name)
```

**Comment by fernandog** [comment]
or "Queue Subtitles"

**Pull request merged**
