### PR TITLE
Use tzwinlocal for sb_timezone on windows.

### PR DESCRIPTION
**Pull request by miigotu**
@labrys did you try this change without the 1970 check? Please try this (and remove the 1970 check from the template). Also try with the 1970 check to see if this is safe to merge for me please, I can't be asked to install windows any time soon =P/

I'll wait until I hear some reports before merging this.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by miigotu** [comment]
@labrys Actually Im just gonna merge it, let me know if it causes issues.

**Comment by labrys** [comment]
I'll try it later today with the tzwinlocal fix but if memory serves tzwinlocal works without the 1970 check.

**Comment by labrys** [comment]
Sorry for the delay but I was testing out a few things.  

First of all keeping the `show.network` check but removing the 1970 check appears to work fine across all platforms for the series I have checked, however, the `tzwinlocal` fix as posted does nothing, since `dateutil.tz` will never import `tzwin.py` so `dateutil.tz.tzwinlocal` will always be `None`.

However:
```python
try:
    from dateutil import tzwin
    sb_timezone = tzwin.tzwinlocal()
except ImportError:
    sb_timezone = tz.tzlocal()
```
will successfully import and use `tzwinlocal` on Windows.  This, however will then cause the following `ValueError` in `main.mako`:
```
Error !
ValueError: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439
% endif Load time: <span class="footerhighlight">${"%.4f" % (time() - sbStartTime)}s</span> / Mako: <span class="footerhighlight">${"%.4f" % (time() - makoStartTime)}s</span> | Branch: <span class="footerhighlight">${sickbeard.BRANCH}</span> | Now: <span class="footerhighlight">${datetime.datetime.now(network_timezones.sb_timezone)}</span> </div> </div> </footer> <script type="text/javascript" src="${srRoot}/js/_bower.min.js?${sbPID}"></script> <script type="text/javascript" src="${srRoot}/js/lib/jquery.cookie.js?${sbPID}"></script>
C:/python/sick.dev/gui/slick/views/layouts/main.mako, line 307:
Now: <span class="footerhighlight">${datetime.datetime.now(network_timezones.sb_timezone)}</span>
C:\python\sick.dev\lib\mako\runtime.py, line 883:
callable_(context, *args, **kwargs)
```
due to an issue with `utcoffset` calculation (dateutil/dateutil#135).

**Pull request merged**
