### PR TITLE
Check if url error code is mapped

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/1194

@Tagforce is it wrong?

### CODE REVIEW

**Comment by TagForce** [comment]
@fernandog Move the def to inside the def for getURL...

So:
```
def getURL(blahblah):
    def codeDescription(codenumber):
        somecodetoexecute_in_codeDescription
    
    codetoexecute_in_getURL
```

That way you can leave the self. off of the call to codeDescription (which will now fail since codeDescription is not part of self.

**Comment by fernandog** [comment]
@TagForce why I created defs there and it worked. Why I can't do it here?

https:// github.com /SiCKRAGETV/SickRage/pull/1532/files

**Comment by TagForce** [comment]
@fernandog You can create it there...  It's just neater to define a function that is only used inside another function within that function.

**Comment by fernandog** [comment]
@TagForce the problem is that we need def download_file too.

**Comment by TagForce** [comment]
@fernandog My bad... I missed the definition for download_file...
Then leave it as is... Does it work with self? If so leave it, otherwise if it works without self. leave it out (it shouldn't need it as it's defined in the same file and not part of a class reference)

**Pull request merged**
