### PR TITLE
Column Selection for displayShow FR#1015

### PR DESCRIPTION
**Pull request by Thraxis**
* Added Colum Selector to displayShow
* removes DISPLAY_FILESIZE from UI and config.ini
* adds file name column (initially hidden)
* anime and regular show column selections are independant

### CODE REVIEW

**Comment by Thraxis** [comment]
Reworked this beast and it now looks to be working correctly and creating a new CSS tag and using the !important for text color fixes the stomping all over other pages text.

@abeloin @fernandog Give it a bit of a spin and kick the tires to see if this takes care of things

**Comment by fernandog** [comment]
@Thraxis 

- I would remove the "Season x" from filename.
- If I adjust the column for a show that has only Season 1, 2 and 3, and open a tv-show with Season 1-5, the widget only applies the saved column to Season 1 to 3. Not to Season 4 and 5.
- The columns width varies from different seasons without reason

image

**Comment by fernandog** [comment]
@Thraxis its happens with special too (second comment above)

**Comment by Thraxis** [comment]
@fernandog  OK back to the drawing / testing board.  Going to have to see what I can do about getting the saved settings to be used for all tables, not  just the ones that were visible.  That or figure out how to make it work as one table ...  

Project for tonight it seems.

**Comment by Thraxis** [comment]
Still working on this one... it's being a beast... will be trying again over the weekend to beat this into shape

**Comment by fernandog** [comment]
Ok!

**Comment by Thraxis** [comment]
@fernandog  @abeloin Ok I think I tamed this beast now..  

Give it a spin and kick the tires.

**Comment by Thraxis** [comment]
Whoops... just noticed the filename is now showing more not less.... need to poke at that a bit

**Comment by fernandog** [comment]
@Thraxis can I merge it?

**Comment by fernandog** [comment]
@Thraxis need rebase

**Comment by Thraxis** [comment]
I'll re-base it again tonight.

**Comment by Thraxis** [comment]
Rebased

**Comment by fernandog** [comment]
@Thraxis did you noticed the cell of season name is black and a lot larger?

**Comment by Thraxis** [comment]
Wonder if the PR lost part of my CSS fix.. let me check

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1797

**Comment by gazzabnumb83** [comment]
can u please stop using this cloud drive

**Comment by Thraxis** [comment]
@gazzabnumb83 What are you talking about?

**Pull request merged**
