### PR TITLE
Remove autoProcessTV scripts (NOT post-processor!) from the repo

### PR DESCRIPTION
**Pull request by miigotu**
Remove news.md and CHANGES.md placeholders from repo and add link to them in the readme
Move tornado into lib
Remove stale TODO.txt
Dont need to install pyOpenSSL for travis on Python 2.7.10

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by Fry-kun** [comment]
So what are users expected to use instead of autoProcessTV scripts?
Looks like my existing install still has them untracked, but they don't work anymore from SABnzbd

**Comment by Wally73** [comment]
read the news page in sickrage

https://github.com/SiCKRAGETV/sickrage-news/blob/gh-pages/news.md#2015-10-22

you can or use the internal processing of sickrage (which I do) or use
nzbToMedia

**Comment by Fry-kun** [comment]
Thanks!
Also, for posterity, I wanted to mention that nzbToMedia is apparently linked to external git in contrib/ directory, so no need to have a separate copy/install elsewhere if using git

**Pull request merged**
