### PR TITLE
Improved BDRip recognition and indentation, removed WEBRip support (a…

### PR DESCRIPTION
**Pull request by medariox**
…s SDDVD can never be WEBRip)

### CODE REVIEW

**Comment by duramato** [comment]
@medariox and what will happen to sddvd releases?

**Comment by medariox** [comment]
@duramato
Nothing will change to SDDVD releases, they will be recognized as usual. This is mostly just cosmetic and removes useless code for the "scene quality" naming pattern.

**Comment by duramato** [comment]
I mean for the naming of sddvd?

**Comment by medariox** [comment]
Nothing changed! Just if you have "scene quality" as naming pattern it won't try to check "WEBRip" in the file name. This has no influence at all on SDDVD naming or any other naming pattern.

**Pull request merged**
