### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by danyboy666**

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Give a description on what the PR is for.
- [ ] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by Arcanemagus** [comment]
As the bot says, you'll need to close this and PR against `dev` not `master`. Also it looks like this should have been part of https://github.com/SiCKRAGETV/SickRage/pull/2806.

**Comment by danyboy666** [comment]
yeah sorry about the botched pull request.

**Comment by fernandog** [comment]
You cant do that! You have to add others files to make a provider work.

**Comment by danyboy666** [comment]
I know that fernandog. This was part of the files i wanted to push but obviously i messed it up. Plus the provider i was planning to add doesn't work with SR. Only in SB.

Again sorry about this botched request.

**Pull request closed without merging**
