### PR TITLE
Add option to use force priority in SAB

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/985

### CODE REVIEW

**Comment by fernandog** [comment]
@tagforce @neoatomic do you use SAB? can you test this? UI and config are working. I didn't test the sab.py code. The user said it worked editing sab.py file. But I want to make sure

**Comment by neoatomic** [comment]
@fernandog I use SAB. but i'm not familiar with the priority stuff from SAB.
Can you merge it with develop.?

**Comment by fernandog** [comment]
@neoatomic 

do this:
stop SR
enter SickRage folder
run in SSH
```
wget -q --no-check-certificate https://github.com/SiCKRAGETV/SickRage/pull/1584.patch
patch -p1 < 1584.patch
```
start SR

**Comment by neoatomic** [comment]
@fernandog Downloads the patch but get an error running the patch...
So cant do it by ssh.

```
/volume1/@appstore/sickbeard-custom/var$ patch -p1 < 1584.patch
/bin/sh: patch: not found
```

**Comment by fernandog** [comment]
@neoatomic merged. try it now please

**Comment by neoatomic** [comment]
@fernandog Did a manual search for an episode. And SR send it to SAB as a high priority.

**Comment by fernandog** [comment]
@neoatomic did you enabled the option in SAB settings to use forced? =)

**Comment by neoatomic** [comment]
@fernandog cant find a setting in SAB for when its paused to allow hight priority anyway...

**Comment by fernandog** [comment]
@neoatomic you must enable allow_high_priority and save.
then go to SAB settings, a "Use forced priority" will appear

**Comment by neoatomic** [comment]
@fernandog allow_high_priority was enabled in SR.  And i set Sabnzb to pause.
Than i manually search for a show and the nzb is send to sabnzb.
But it comes in as a high priority so it is still paused. When i manually set it from high to forced it starts downloading. 
So if i understand it correctly SR needs to send it as forced, but its send as high.

**Comment by fernandog** [comment]
Please update. There is a new setting in Sab settings. See the code pleasd. The .tmpl

**Comment by neoatomic** [comment]
@fernandog I'm trying to update but it doesn't. No errors in the log.
Give me a moment to see why its not.

```
2015-03-18 21:46:45 INFO     EVENT-QUEUE :: Saving config file to disk
2015-03-18 21:50:25 DEBUG    Thread-54 :: Checking if we can use git commands: git version
2015-03-18 21:50:26 DEBUG    Thread-54 :: Executing git version with your shell in /usr/local/sickbeard-custom/var/SickBeard
2015-03-18 21:50:26 DEBUG    Thread-54 :: git version : returned successful
2015-03-18 21:50:26 DEBUG    Thread-54 :: Using: git
2015-03-18 21:50:26 INFO     Thread-54 :: Config backup in progress...
2015-03-18 21:50:38 INFO     Thread-54 :: Config backup successful, updating...
2015-03-18 21:50:38 DEBUG    Thread-54 :: Executing git symbolic-ref -q HEAD with your shell in /usr/local/sickbeard-custom/var/SickBeard
2015-03-18 21:50:38 DEBUG    Thread-54 :: git symbolic-ref -q HEAD : returned successful
2015-03-18 21:50:38 DEBUG    Thread-54 :: Executing git rev-parse HEAD with your shell in /usr/local/sickbeard-custom/var/SickBeard
2015-03-18 21:50:38 DEBUG    Thread-54 :: git rev-parse HEAD : returned successful
2015-03-18 21:50:38 DEBUG    Thread-54 :: Executing git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git with your shell in /usr/local/sickbeard-custom/var/SickBeard
2015-03-18 21:50:39 DEBUG    Thread-54 :: git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git : returned successful
2015-03-18 21:50:39 DEBUG    Thread-54 :: Executing git fetch origin with your shell in /usr/local/sickbeard-custom/var/SickBeard
2015-03-18 21:50:41 DEBUG    Thread-54 :: git fetch origin : returned successful
2015-03-18 21:50:41 DEBUG    Thread-54 :: Executing git rev-parse --verify --quiet "@{upstream}" with your shell in /usr/local/sickbeard-custom/var/SickBeard
2015-03-18 21:50:41 DEBUG    Thread-54 :: git rev-parse --verify --quiet "@{upstream}" : returned successful
2015-03-18 21:50:41 DEBUG    Thread-54 :: Executing git rev-list --left-right "@{upstream}"...HEAD with your shell in /usr/local/sickbeard-custom/var/SickBeard
2015-03-18 21:50:41 DEBUG    Thread-54 :: git rev-list --left-right "@{upstream}"...HEAD : returned successful
2015-03-18 21:50:41 DEBUG    Thread-54 :: cur_commit = 918ee97a7087184890b2cf6d322527fafb5af7e4, newest_commit = 54f56db082c155496758856a847f94d7db6d4ac2, num_commits_behind = 2, num_commits_ahead = 0
2015-03-18 21:50:41 DEBUG    Thread-54 :: Executing git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git with your shell in /usr/local/sickbeard-custom/var/SickBeard
2015-03-18 21:50:41 DEBUG    Thread-54 :: git config remote.origin.url https://github.com/SiCKRAGETV/SickRage.git : returned successful
2015-03-18 21:50:41 DEBUG    Thread-54 :: Executing git symbolic-ref -q HEAD with your shell in /usr/local/sickbeard-custom/var/SickBeard
2015-03-18 21:50:41 DEBUG    Thread-54 :: git symbolic-ref -q HEAD : returned successful
2015-03-18 21:50:41 DEBUG    Thread-54 :: Executing git pull -f origin develop with your shell in /usr/local/sickbeard-custom/var/SickBeard
2015-03-18 21:50:43 DEBUG    Thread-54 :: git pull -f origin develop : returned successful
2015-03-18 21:50:43 DEBUG    Thread-54 :: Executing git rev-parse HEAD with your shell in /usr/local/sickbeard-custom/var/SickBeard
2015-03-18 21:50:43 DEBUG    Thread-54 :: git rev-parse HEAD : returned successful
````

**Comment by neoatomic** [comment]
Got it running again.
Try'd and now its send as normal priority to sabnzb....

```
2015-03-18 22:26:04 INFO     SEARCHQUEUE-RETRY-273181 :: Downloading Better.Call.Saul.S01E06.Five-O.720p.WEB-DL.DD5.1.H.264-CtrlHD from Usenet-Crawler
2015-03-18 22:26:04 INFO     SEARCHQUEUE-RETRY-273181 :: Sending NZB to SABnzbd
2015-03-18 22:26:04 DEBUG    SEARCHQUEUE-RETRY-273181 :: URL: http://localhost:8080/api?ma_password=********&apikey\=**********\&name=https%3A%2F%2Fwww.usenet-crawler.com%2Fgetnzb%2F0e527c304adbee1be12502dd12b64030.nzb%26i%3D233093%26r%3Ddca5263b571290587f0e199a0636d4c8&cat=tv&mode=addurl&ma_username=**********
2015-03-18 22:26:04 DEBUG    SEARCHQUEUE-RETRY-273181 :: Result text from SAB: ok
2015-03-18 22:26:04 DEBUG    SEARCHQUEUE-RETRY-273181 :: NZB sent to SAB successfully
2015-03-18 22:26:04 DEBUG    SEARCHQUEUE-RETRY-273181 :: Checking if we should archive our first best quality match for for episode Better.Call.Saul.S01E06.Five-O.720p.WEB-DL.DD5.1.H.264-CtrlHD
2015-03-18 22:26:04 DEBUG    SEARCHQUEUE-RETRY-273181 :: Using NORMAL regexs
2015-03-18 22:26:04 DEBUG    SEARCHQUEUE-RETRY-273181 :: Parsed /volume1/video/=_Series_=/Better Call Saul/Better.Call.Saul.S01E06.720p.HDTV.X264-DIMENSION into Better Call Saul - S1E6 [ANIME VER: -1] [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-03-18 22:26:05 DEBUG    SEARCHQUEUE-RETRY-273181 :: Using NORMAL regexs
2015-03-18 22:26:05 DEBUG    SEARCHQUEUE-RETRY-273181 :: Using cached parse result for: Better.Call.Saul.S01E06.720p.HDTV.X264-DIMENSION
2015-03-18 22:26:05 DEBUG    SEARCHQUEUE-RETRY-273181 :: formatting pattern: %SN - %Sx%0E - %EN - %QN -> Better Call Saul - 1x06 - Five-O - 720p WEB-DL
2015-03-18 22:26:05 DEBUG    SEARCHQUEUE-RETRY-273181 :: Transaction with 1 queries executed
```

BRANCH: (develop) / COMMIT: (be1b5953f43a386ecd033f15dbe50bf5f2ba604d)

**Comment by neoatomic** [comment]
@fernandog Its working now with the new setting enabled. :)

**Comment by fernandog** [comment]
@neoatomic nice! so even with SAB pause, force will override it and start download, isn't?

**Comment by neoatomic** [comment]
@fernandog  Indeed, it overwrites the pause of Sabnzb when the nzb is send as forced.

**Pull request merged**
