### PR TITLE
Fixes airdate on comingEpisodes

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by fernandog** [comment]
No. I use custom date: Qui, 10. Set 15, 21:00

Qui = Thu

**Comment by OmgImAlexis** [comment]
@fernandog what?

**Comment by fernandog** [comment]
Its not working. I set my SR to use custom date. My custom date is above. Maybe you need to convert the airdate using the user setting.

**Comment by OmgImAlexis** [comment]
I'll have to look into this tomorrow, I don't understand why it wouldn't be working as it uses a number for sorting.

What part isn't working? I need more information than just "it isn't working".

**Comment by fernandog** [comment]
Delete cache and browser cache. Seems working. Sorry.

**Pull request merged**
