### PR TITLE
Add Trakt empty token error message

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/1838

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu can I just "return" instead of raise an exception?

**Comment by miigotu** [comment]
Actually you want to, but i'm not sure if that change fixes the problem.

traktException just passes

**Comment by fernandog** [comment]
@miigotu pass and continues or pass as ignore all next code ?

**Comment by fernandog** [comment]
done

**Comment by miigotu** [comment]
Nuuuu, I meant you were right that you need to use a continue, as the exception is just set to be ignored in lib/trakt/exceptions.py

**Comment by fernandog** [comment]
Why others exceptions dont have return?

**Comment by miigotu** [comment]
Idk, someone else handles the trakt code xD

**Comment by fernandog** [comment]
@miigotu I didnt added the return. Or its ok as it is?

**Comment by miigotu** [comment]
The raise makes it return from there AFAIK.

**Comment by miigotu** [comment]
Should be fine, otherwise we will know in a few hours lol.

**Pull request merged**
