### PR TITLE
Fix for when seeders/Leechers is "---" instead of a number

### PR DESCRIPTION
**Pull request by duramato**
2nd attempt

### CODE REVIEW

**Comment by miigotu** [comment]
can't check right now because I'm on my phone, but is helpers imported?

**Comment by duramato** [comment]
@miigotu yeah ```from sickbeard import helpers```

**Comment by miigotu** [comment]
ok, merging. next time just make sure there is a space after `,`

formatting matters =P

**Comment by duramato** [comment]
@miigotu does it make the code not work?

**Comment by miigotu** [comment]
No, but it will fail build tests later once we start linting in travis builds, so it is a good idea to start getting in the habit of pep8 (except line length if its ridiculous)

**Comment by duramato** [comment]
@just got this 
```    title = item['title']
TypeError: string indices must be integers```
the same fix ,would work for that wont?

**Comment by miigotu** [comment]
no. title is not an int. I guess you need a try that has a continue when it causes an exception.

**Comment by miigotu** [comment]
@duramato better to reference the issue from the PR description (editted for you)

**Pull request merged**
