### PR TITLE
Update TODO

### PR DESCRIPTION
**Pull request by MGaetan89**
I'm not sure about the other items, but this one is implemented.

### CODE REVIEW

**Comment by fernandog** [comment]
@MGaetan89 this file is really old. lol. we don't update that.

https: //github.com/SiCKRAGETV/sickrage-issues/issues/589 first topic. it's the TODO list

**Comment by MGaetan89** [comment]
That's what I thought. So maybe it could just be deleted?

**Comment by fernandog** [comment]
@MGaetan89 no. it's echelon file (the real owner of SR). let's leave it there

**Comment by MGaetan89** [comment]
Ok, I'll leave it there then

**Comment by fernandog** [comment]
@MGaetan89 are you going to check that issue about UI missed episodes vs API missed?

**Comment by MGaetan89** [comment]
Yes, it's the next one on my list. I'll start woking on it tomorrow.
But I don't think I'll be able to send a PR before next week ...

**Comment by fernandog** [comment]
No problem!

**Comment by miigotu** [comment]
I think this file should be just a link to the 'Issues STATS'

**Pull request merged**
