### PR TITLE
Respect timezone setting in displayShow, backlogOverview

### PR DESCRIPTION
**Pull request by fernandog**
@miigotu

history don't need change AFAI checked

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
displayShow:
image

comingEpisodes:
image

**Comment by OmgImAlexis** [comment]
@fernandog DO NOT change the ISO date. That needs to be raw, timezones should only ever be on the airDate.

@miigotu pretty sure this needs to be reverted.

**Comment by fernandog** [comment]
but airdate is wrong. so we need to make isodate = sbdatetime.sbdatetime.sbfdatetime(date)

**Comment by OmgImAlexis** [comment]
@fernandog ISO date is an absolute date from 1970, it should never be changed to work with timezones so unless I'm reading this wrong you only want the timezone fix on the airDate. airDate is the one that's displayed.

**Comment by fernandog** [comment]
yes. as the code is displaying airdate. I fix that. didn't know about isodate.
I don't get the attitude. just tried to fix

**Comment by OmgImAlexis** [comment]
No attitude, literally just woke up and yesterday shit got changed and broke stuff that I fixed. Just annoyed a little when people change shit I finally get working. We're all good.

**Comment by fernandog** [comment]
not yours. 
If I knew we can't change iso, I would fix only airdate.

**Comment by fernandog** [comment]
with my PR reverted:

comingEpisodes:
image

displayShow:
image

**Comment by OmgImAlexis** [comment]
That's definitely airdate then, just change that. The date variable changes both airdate and isodate.

**Pull request merged**
