### PR TITLE
Use unicode instead of string in `sickrage` module

### PR DESCRIPTION
**Pull request by MGaetan89**
I don't know if it was necessary everywhere, but I guess it can hurt, does it?

### CODE REVIEW

**Comment by miigotu** [comment]
I dont think it is ok to do it in mass like this. dict keys can have issues between unicode/ascii

**Comment by MGaetan89** [comment]
So I just remove unicode from dict keys?

**Comment by miigotu** [comment]
For sure. But like everything in encoding.py doesnt need to be done too, and most other places in this PR.

Paths, file and show names/info and function returns need to be unicode, but parameters to python built-ins don't

It's too complicated of a transition to do it all at once like this.

**Comment by MGaetan89** [comment]
Ok, I will update this and let you know when it's done.

**Comment by MGaetan89** [comment]
Updated in https://github.com/SiCKRAGETV/SickRage/commit/846903f0df7d72fc23bd65806221bfe01634992c

**Comment by miigotu** [comment]
Im still scared to merge a batch change like this =P

**Comment by miigotu** [comment]
I dont think this is necessary, and it would be hell to fix the conflicts now =P

**Pull request closed without merging**
