### PR TITLE
Update thepiratebay.py

### PR DESCRIPTION
**Pull request by creamers**
Corrected Root TLD

### CODE REVIEW

**Comment by miigotu** [comment]
1. you never create a PR to master
2. the gd domain is correct.

**Comment by creamers** [comment]
The GD domain is a redirect, according to my sickrage logs when ever it tries to query the GD domain it files. I corrected the domain on my local install and everything is working.

As for commiting wrong, I have never used GIT I am just now learning it.

**Comment by Arcanemagus** [comment]
Guidelines for contributing can be found in [contributing.md](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md).

**Comment by miigotu** [comment]
@creamers it doesnt matter which domain you set it to, it will redirect based on the closest dowmain depending on which country you are in, to one that is not blocked. .gd is used for north america.

**Comment by creamers** [comment]
@miigotu true just seems odd to me that my logs no longer have errors from TPB once the url is changed.

**Comment by miigotu** [comment]
try using .se, as that is the main redirect domain.

**Pull request closed without merging**
