### PR TITLE
Send user locale when submitting issues

### PR DESCRIPTION
**Pull request by fernandog**
@abeloin should we consider NAS/FreeNAS/etc too ?

http://stackoverflow.com/questions/842059/is-there-a-portable-way-to-get-the-current-username-in-python

### CODE REVIEW

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/910

**Comment by fernandog** [comment]
@abeloin 

Just for fun I executed this script https://gist.github.com/fernandog/5c3a650afc3f3a84cf9b to list all OS from all issues with have:
```
Darwin
FreeBSD
FreeNAS
Linux
OSX
Ubuntu
Windows
```

only Windows don't have locale?

**Comment by abeloin** [comment]
@fernandog You shouldn't include the username in the the data sent.

As far as I know, yes windows is the only one without locale

**Comment by fernandog** [comment]
@abeloin ok, will remove it

**Pull request merged**
