### PR TITLE
Remove FTDB provider

### PR DESCRIPTION
**Pull request by adaur**
It is closed since august, it probably won't come back anymore.

Even if it did, all we'd have to do is restore this commit :)

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by duramato** [comment]
@adaur the line ` r'^\[www\.frenchtorrentdb\.com\] ':  'searchre',` needs to stay.. and so does that line on tests

**Comment by adaur** [comment]
Nope, you can't get such torrents anymore since it is not working. There is no need to keep code stripping out the name of a dead tk

**Comment by duramato** [comment]
Yes you can...
http://btdigg.org/search?info_hash=&q=frenchtorrentdb

**Comment by adaur** [comment]
No, the tracker itself is dead. If you load a torrent from your link, it won't load

**Comment by duramato** [comment]
Doesnt really matter the files themselves are still avaiblr on DHT ,it needs to stay

**Comment by adaur** [comment]
Can't you see that all files your link has are *dead*?

No activity since 2 months at least.

Back when the website was online, you would join the tk server, which would give the list of clients you would connect to. Now it is down, so you can't download anything.

This is a private tk, not TPB where you can still download files even when it's down.

**Comment by duramato** [comment]
Do you know what DHT is? If it on BTdigg it is threre from the swarm/DHT and not from a tracker
If they are on there is becouse the dont have the private flag set on the torrent and can atill be downloaded

**Comment by adaur** [comment]
In this case, try to download one of them. I did, it didn't even start.

**Comment by duramato** [comment]
Bad example :P but they need to stay as whe dont know if users manually download them or if people reupload them 
Same as EZTV

**Comment by miigotu** [comment]
@duramato torrent from private providers cannot use DHT or use other trackers.

@adaur I can still get a page when I go to http://www.frenchtorrentdb.com ?

**Comment by duramato** [comment]
@miigotu if its on BTDigg it was crawled from DHT and doesnt have the private flag on the torrent

**Comment by miigotu** [comment]
If it came from btdigg, it was never on ftdb. Since the ftdb torrent had the private flag it was never on a public swarm

**Comment by fernandog** [comment]
so what should we do ?

**Comment by duramato** [comment]
Then it means people are reuploading the files so that nonrelease group needs to stay :p

**Comment by miigotu** [comment]
Well that part can stay, but the provider shouldnt if it is really gone. Im confused because I get a login page when I go to the provider url (no account to try logging in)

Maybe the provider is just blocked where you are @adaur ?

**Comment by duramato** [comment]
Yeah website is also showing up for me now that i check

**Comment by adaur** [comment]
No it's not. It's been showing a mock login page for over 2 months now (ie you enter your credentials and you can't login. If you try to recover your password it says website in maintenance)

**Comment by miigotu** [comment]
@fernandog listen to the french people and merge xD

**Comment by adaur** [comment]
There is a huge discussion over here if you want more information :)

https://www.wareziens.net/forum/topic-29237-topic-unique-frenchtorrentdb-page-1.html

**Comment by fernandog** [comment]
merge as it is? or we will keep the "r'^\[www\.frenchtorrentdb\.com\] ':  'searchre'," ?

**Comment by adaur** [comment]
Do as you want, but I don't see why we should keep it

**Comment by fernandog** [comment]
will merge. Le'ts see if any torrents with [www.frenchtorrentdb.com] appears

**Comment by adaur** [comment]
If the tracker comes back to life, I'll let you know

**Pull request merged**
