### PR TITLE
Add Strike provider

### PR DESCRIPTION
**Pull request by duramato**
This pr adds getstrike.net as a search provider ,a known DHT search engine

### CODE REVIEW

**Comment by duramato** [comment]
@miigotu can you walk me thru , on how to squash the commits?

**Comment by WebSpider** [comment]
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by duramato** [comment]
i tried but i screwed up ,made another PR https://github.com/SiCKRAGETV/SickRage/pull/2488

**Comment by miigotu** [comment]
@duramato for future reference:

```bash
git fetch upstream
git rebase -i upstream/develop
```
leave your first commit as "pick" and the rest set to "fixup" or "squash", do not change anyone elses commits. Save and exit
```bash
git push origin yourbranchname -f
```

**Pull request closed without merging**
