### PR TITLE
Updated torrentday URL

### PR DESCRIPTION
**Pull request by coolius**
Updated torrentday URL to preferred, block-avoiding torrentday.eu

### CODE REVIEW

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1204

this change does not work.

**Comment by coolius** [comment]
How about now

**Comment by fernandog** [comment]
@coolius have you tested? send a log showing it's working.
I tried to fix withou success.
the torrentday.eu has a cloudfare cookie so this code don't work.

**Comment by abeloin** [comment]
@fernandog Working with commit https://github.com/coolius/SickRage/commit/503282694c956ec959bfb8eb97af97dfd2343059

```
2015-01-22 16:11:30 INFO     Starting new HTTPS connection (1): torrentday.eu
2015-01-22 16:11:30 INFO     Starting new HTTPS connection (1): torrentday.eu
2015-01-22 16:11:31 DEBUG    "POST /torrents/ HTTP/1.1" 302 0
2015-01-22 16:11:31 DEBUG    "POST /torrents/ HTTP/1.1" 302 0
2015-01-22 16:11:31 DEBUG    "GET /secure-login.php HTTP/1.1" 200 None
2015-01-22 16:11:31 DEBUG    "GET /secure-login.php HTTP/1.1" 200 None
2015-01-22 16:11:31 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [TorrentDay] :: text: <meta http-equiv="refresh" content="3;URL=/browse.php">^M
<p><br>^M
  </p>^M
<p>&nbsp;</p>^M
<p>&nbsp;</p>^M
<p><br>^M
  <br><br>^M
</p>^M
<div align="center">^M
  <p>Logging you in securely...^M
    ^M
  </p>^M
  <p><img src="pic/login.gif" width="186" height="42" alt=""></p>^M
  <p>If this page appears for more than 5 seconds, <a href="/browse.php">click here</a> to reload.</p>^M
</div>headers:CaseInsensitiveDict({'content-encoding': 'gzip', 'x-powered-by': 'PHP/5.4.36-0+deb7u3', 'transfer-encoding': 'chunked', 'expires': 'Thu, 22 Jan 2015 21:11:31 GMT', 'server': 'cloudflare-nginx', 'connection': 'keep-alive', 'cache-control': 'max-age=0', 'date': 'Thu, 22 Jan 2015 21:11:31 GMT', 'cf-ray': '[scrubbed]', 'content-type': 'text/html'})
2015-01-22 16:23:40 INFO     Starting new HTTPS connection (1): torrentday.eu
2015-01-22 16:23:40 INFO     Starting new HTTPS connection (1): torrentday.eu
2015-01-22 16:23:41 DEBUG    "POST /V3/API/API.php HTTP/1.1" 200 None
2015-01-22 16:23:41 DEBUG    "POST /V3/API/API.php HTTP/1.1" 200 None
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Using ALL regexes
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Converted parsed result Pretty.Little.Liars.S05E15.720p.HDTV.X264-DIMENSION.[NO.RAR] into Pretty Little Liars - S5E16 [ANIME VER: -1] [GROUP: DIMENSION.[NO.RAR]] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Parsed Pretty.Little.Liars.S05E15.720p.HDTV.X264-DIMENSION.[NO.RAR] into Pretty Little Liars - S5E16 [ANIME VER: -1] [GROUP: DIMENSION.[NO.RAR]] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Checking if found episode 5x16 is wanted at quality HD TV
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: any,best = [4, 32, 128] [] and found 4
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Existing episode status: 5 (Skipped)
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Existing episode status is wanted/unaired/skipped, getting found episode
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Found result Pretty.Little.Liars.S05E15.720p.HDTV.X264-DIMENSION.[NO.RAR] at https://torrentday.eu/download.php/[scrubbed]/Pretty.Little.Liars.S05E15.720p.HDTV.X264-DIMENSION%20%5BNO%20RAR%5D.torrent
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Single episode result.
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Using ALL regexes
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Converted parsed result Pretty.Little.Liars.S05E15.720p.HDTV.X264-DIMENSION into Pretty Little Liars - S5E16 [ANIME VER: -1] [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Parsed Pretty.Little.Liars.S05E15.720p.HDTV.X264-DIMENSION into Pretty Little Liars - S5E16 [ANIME VER: -1] [GROUP: DIMENSION] [ABD: False] [ANIME: False] [whichReg: ['standard']]
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Checking if found episode 5x16 is wanted at quality HD TV
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: any,best = [4, 32, 128] [] and found 4
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Existing episode status: 5 (Skipped)
2015-01-22 16:13:10 DEBUG    SEARCHQUEUE-MANUAL-146711 :: [TorrentDay] :: Existing episode status is wanted/unaired/skipped, getting found episode
```

**Comment by fernandog** [comment]
@echel0n you can merge this

**Pull request merged**
