### PR TITLE
Added thousand seperator to free disk space in status

### PR DESCRIPTION
**Pull request by mkjaer**
Having disks above 1 TB it gets difficult to see how much free space you actually have, so I added thousand separators to free disk space on the status page.
This is my first python code ever, but hopefully it is okay.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by duramato** [comment]
@mkjaer you need to squash those commits ,there sould be only our commit in there...

**Comment by miigotu** [comment]
Would you rather see this as human readable bytes? I could add that instead.

```
def readable_bytes(num):
    for modifier in ['bytes', 'KB', 'MB', 'GB']:
        if num < 1024.0:
            return "%3.1f%s" % (num, modifier)
        num /= 1024.0
    return "%3.1f%s" % (num, 'TB')

readable_bytes(724102410)
'690.6MB'
```

**Comment by MGaetan89** [comment]
I'm pretty sure that function already exists somewhere.

**Comment by miigotu** [comment]
sickbeard.helpers if it does. I know I have it going the other way in some providers though.

**Comment by miigotu** [comment]
@MGaetan89 I know why you saw it before, it's in webapi.py AND helpers.py (and has an unlikely failure case if > 1024 TB)

**Comment by miigotu** [comment]
@mkjaer Im going to close this and use that other function
@MGaetan89 I'm going to move that function to sickrage/helper/common.py and use it, OK?

**Comment by MGaetan89** [comment]
OK for me.

**Comment by mkjaer** [comment]
Sorry @duramato, you're right.
@miigotu, that does seem like a much better solution :)

**Pull request closed without merging**
