### PR TITLE
Network Logos

### PR DESCRIPTION
**Pull request by matigonkas**
cottage life, ESPN2 & natgeo

### CODE REVIEW

**Comment by matigonkas** [comment]
@neoatomic  i´ve made them with lowercase now ,btw they work with uppercase, and also added the cottage life logo to the PR

**Comment by neoatomic** [comment]
Thanks for adding the logos.

Strange that they work with uppercase characters on your system. (Windows.?) 
Normally they dont work if uppercase characters are used...

**Comment by matigonkas** [comment]
@neoatomic to teste them i used windows there i know uppercase works dont know about other systems

**Comment by miigotu** [comment]
@matigonkas windows filesystems/file operations are not case sensitive. Mac and Linux are.

About the PR, are these the correct dimensions (same as other images in the same folder)? They look wider than others.

**Comment by matigonkas** [comment]
@miigotu  They should be the same size ,since i used the existing ones as a base for the project on photoshop

**Pull request merged**
