### PR TITLE
Provider domain change - again

### PR DESCRIPTION
**Pull request by bdoner**
NextGen is yet again changing domain. This time it hopefully sticks.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by miigotu** [comment]
Unless their irc comes back up sometime soon, this provider might need removed from SR for lack of surety in changes and lack of stability. I have to verify the safety of this change, direct from the horses mouth.

**Comment by bdoner** [comment]
Understandable. The old domain will stay active for some time. Is it possible to mark the pull request for review later?  

I will comment here as soon as the IRC is alive again.

**Comment by ThomasDK81** [comment]
@miigotu: Please don't delete the provider.
The tracker suffered under the ICANN domain validation.
The solution was to get the nxtgn.info domain.

This has nothing to do with lack of surety in changes and stability.

**Comment by fernandog** [comment]
@bdoner 
This branch has conflicts that must be resolved

git checkout -b bdoner-provider-single_domain_change_again develop
git pull git://github.com/bdoner/SickRage.git provider-single_domain_change_again

git checkout develop
git merge --no-ff bdoner-provider-single_domain_change_again
git push origin develop

**Comment by Kp1003** [comment]
@miigotu: Really, Please don't delete the provider. It's the biggest tracker in Denmark.

As ThomasDK81 wrote, the tracker has suffered under the ICANN domain validation.
This has ABSOLUTELY nothing to do with lack of surety in changes and stability.

**Comment by miigotu** [comment]
3 domains in like a month is kinda sketchy, and their irc is completely gone. Aside from that, there are errors in the provider that I cant fix without an account.

**Comment by Kp1003** [comment]
@miigotu Yeah i know, it's been a bit sketchy the latest month with all the domain changes. But i think and hope they have solved their domain problems as of now. :)

As to the errors in the provider you can't fix without an account,
I will be more than willing to hand you an invite to the site if that means that the provider stays in sickrage...?

Best Regards.
Kp1003

**Comment by bdoner** [comment]
I will fix and commit again. As noted before there has been problems with ICANN and validation since no one want to put their name and address behind the domain. 

The IRC server going down is just an unlucky incident. It's hosted on a dedicated server which sadly suffered a hard drive failure. Getting the new hardware is currently delayed but there's an eta saying about a week. 

The old domain is still valid for now but will not be renewed when it runs out. 

I'm sorry for the inconvenience, I can't do much but a sure you everything is being worked on. 

On Oct 15, 2015 3:15 PM, miigotu <notifications@github.com> wrote:

3 domains in like a month is kinda sketchy, and their irc is completely gone. Aside from that, there are errors in the provider that I cant fix without an account.

**Pull request merged**
