### PR TITLE
Adds option to save history limit selection

### PR DESCRIPTION
**Pull request by WebSpider**
Adds saving history limit by storing it in config.ini

### CODE REVIEW

**Comment by fernandog** [comment]
@WebSpider it's not working anymore. Can you confirm? not working for @neoatomic too

**Comment by duramato** [comment]
i can also confirm it, as its not working for me too

**Comment by WebSpider** [comment]
Which commit/branch?

**Comment by fernandog** [comment]
after mako it stopped working

**Comment by miigotu** [comment]
I'll look at it, its not @WebSpider fault I broke it lol.

**Pull request merged**
