### PR TITLE
Fix Allowed and Preferred Quality selections

### PR DESCRIPTION
**Pull request by mpcaddy**
Lists now get passed through so that all selected qualities from the Allowed and Preferred selections will now get saved instead of just the first selected item in each

### CODE REVIEW

**Comment by Djang0** [comment]
Hi,
If you want travis check to succeed, you should refer to this commit : https://github.com/Djang0/SickRage/commit/fba190cb92d5e4885ab3f7ee40c5ad9e00a2debb
and merge it to your own fork, then re submitting the pull request.

**Comment by neclimdul** [comment]
:+1: Fixes saving.

Doesn't fix edit not reflecting the saved values but that can be a follow up.

**Comment by JBFUK** [comment]
Fixed two issues for me:

1. Quality selection saving
2. Add existing shows would not add multiple shows, it would add the first and quit back to the shows listing.  Now behaves as expected.

Thanks.

**Comment by echel0n** [comment]
New update to DEV branch should have this corrected but if not please perform the PR against that as its a entirely new system then what master is using and will being replacing master soon, thanks!

**Comment by echel0n** [comment]
Ok I see this issue is still present so I'm correcting it now and putting it onto dev branch.

**Pull request closed without merging**
