### PR TITLE
Allow user to Ignore subbed releases based on language names. Used to be hardcoded

### PR DESCRIPTION
**Pull request by fernandog**
In collaboration with @medariox 

https://github.com/SiCKRAGETV/sickrage-issues/issues/3401

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
@miigotu

do you know why I get this? It's not creating the config.
All new configs are created when save_config and we can't get there because of this error

```
 python SickBeard.py
Traceback (most recent call last):
  File "SickBeard.py", line 58, in <module>
    import sickbeard
  File "/home/osmc/SickRage-Fernando/sickbeard/__init__.py", line 37, in <module>
    from sickbeard import metadata
  File "/home/osmc/SickRage-Fernando/sickbeard/metadata/__init__.py", line 22, in <module>
    import kodi, kodi_12plus, mediabrowser, ps3, wdtv, tivo, mede8er
  File "/home/osmc/SickRage-Fernando/sickbeard/metadata/kodi.py", line 19, in <module>
    import generic
  File "/home/osmc/SickRage-Fernando/sickbeard/metadata/generic.py", line 34, in <module>
    from sickbeard.show_name_helpers import allPossibleShowNames
  File "/home/osmc/SickRage-Fernando/sickbeard/show_name_helpers.py", line 43, in <module>
    if sickbeard.IGNORED_SUBS_LIST:
AttributeError: 'module' object has no attribute 'IGNORED_SUBS_LIST'

```

**Comment by fernandog** [comment]
image

**Comment by fernandog** [comment]
@duramato ok? I know you download some dubbed releases

**Comment by neoatomic** [comment]
@fernandog Not sure if this is a good idea. 
You can just place them in ignore words correct.? Also setting defaults will course that users (that want those subs) cant/wont find them.

**Comment by fernandog** [comment]
@neoatomic today is exactly as it is but hardcoded. With this PR, now users can change

**Comment by neoatomic** [comment]
Ok, But still dont think we should add defaults in the field. That will course issues for users that want those.

**Comment by medariox** [comment]
@neoatomic 
I think it's safe to say that if the users didn't notice until now, there is no need to worry about. We are just keeping things as they were before (hardcoded), but with the option to actually allow users to choose what they want and what not.

**Pull request merged**
