### PR TITLE
Personalized InitScript for all Distro's

### PR DESCRIPTION
**Pull request by Carlosgrr**
Changed the InitScript's to start SickRage rather than SickBeard, since it was inherited from SickBeard. Just for readability of code. ;)

### CODE REVIEW

**Comment by fernandog** [comment]
@abeloin @miigotu

**Comment by miigotu** [comment]
I want to do this, but you need to `git fetch upstream && git rebase -i upstream/develop`
16 commits (mostly due to incorrect merging) when one commit is all that is needed is nogo. I was planning on redoing the init scripts myself actually xD.

**Comment by Carlosgrr** [comment]
Sorry but I updated the code using the github web browser, do you have any
other instructions on how to do it?

2015-05-13 13:41 GMT-03:00 Dustyn Gibson <notifications@github.com>:

> I want to do this, but you need to git fetch upstream && git rebase -i
> upstream/develop
> 16 commits (mostly due to incorrect merging) when one commit is all that
> is needed is nogo. I was planning on redoing the init scripts myself
> actually xD.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SiCKRAGETV/SickRage/pull/1905#issuecomment-101740760>.
>



-- 
Gustavo

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1446

**Comment by Carlosgrr** [comment]
I have read and answered on the same PR.

**Comment by miigotu** [comment]
@fernandog @TagForce Changing the sickbeard references in the init scripts will not break any installations. People who already have their init scripts and /etc/default/sickbeard would not get the new scripts unless they manually installed the new ones.

I have already ruled out that people with the script added to /etc/init/sickbeard by means of a link would  have a broken install, as I have already moved the init scripts to a `runscripts` folder, which would have immediately broken any links, yet we have no reports of it as of yet (If they used a link, I bet they are savvy enough to fix a broken link or changed filenames/variables)


However, these changes are not entirely correct in this PR. I pointed out a bug in the first script changed that I looked at above, and as I said, I can do this soonish as I was planning on completely going over each init script and changing the variables and sourced file names as I improve and simplify the scripts themselves.  I don't think there needs to be quite as many of them either, some of them can be combined.

**Comment by miigotu** [comment]
@Carlosgrr As for fixing this PR, you can just go over the files, and fix any problems and then commit to the same branch, and then rebase to meld the new commit into the previous ones, and then force a push. If you do what I said above it will also fix the extra commits.

I can't guide you on the github gui, as it isnt available on linux. I may suggest smartgit as it is cross platform and has more features.  With it, as long as you have upstream configured for your fork, you can just simply do a pull and it fetches and pulls new changes from the upstream. (Or a 'synce' and it fetches, pulls, and pushes in one click) Then you use the menu item to start a new feature or bugfix, and commit to that, and push it, and create a PR. Its much simpler than cmdline (even though I still use cmdline mostly).

**Comment by Carlosgrr** [comment]
>As for fixing this PR, you can just go over the files, and fix any problems and then commit to the same branch, and then rebase to meld the new commit into the previous ones, and then force a push. If you do what I said above it will also fix the extra commits.
Is that the correct way of doing it?
>However, these changes are not entirely correct in this PR. I pointed out a bug in the first script changed that I looked at above, and as I said...
I guess this fix the init.debian, any other problems?
I can do this soonish as I was planning on completely going over each init script and changing the variables and sourced file names as I improve and simplify the scripts themselves. I don't think there needs to be quite as many of them either, some of them can be combined.
I believe another PR would be better for a merge of initscripts, since that is another problem that I don't understand at all...

**Comment by miigotu** [comment]
@Carlosgrr
To clean up those commits:
```
git remote set-url upstream git@github.com:SiCKRAGETV/SickRage.git
git fetch upstream
git checkout Carlosgrr-patch-1
git rebase -i upstream/develop
(In the window that pops up, put a # before any commit that isnt yours, then ctrl+o, enter, ctrl+x)
(You can also move the last one (SickRage.py->SickBeard.py) up just under the debian commit line and change 'pick' to 'f' and it will meld into the debian commit)
git push -u -f origin Carlosgrr-patch-1
```

For future reference, to start a new fix/feature from command line and not have these crazy commits showing up in PR:
```
git fetch upstream
git checkout -b new-branch-name upstream/develop
(make changes and commits)
(if you need to combine any of your own commits, git rebase -i upstream/develop)
git push -u origin new-branch-name
```

**Comment by Carlosgrr** [comment]
>To clean up those commits ...

Thanks! That cleared those commits but I made a hell of a mess trying to do it. :P
Thanks god those commits are more important than my git skills. :D

I believe I have made it correctly this time, right?

**Comment by miigotu** [comment]
Close. All of these scripts could have been done in one commit. So I have taken it upon myself to squash them for you, and committed to develop.
See https://github.com/SiCKRAGETV/SickRage/commit/6e4d57f740f186e548c75610ea30de913e5cd77f

**Pull request closed without merging**
