### PR TITLE
Added new subtitle handler Napiprojekt into Subliminal

### PR DESCRIPTION
**Pull request by murbaniak**
Added new subtitle handler Napiprojekt into Subliminal

### CODE REVIEW

**Comment by fernandog** [comment]
@murbaniak please PR this to subliminal ( https://github.com/Diaoul/subliminal ) - the DEV of the subtitle module

**Comment by murbaniak** [comment]
Yes, I could and I will. Problem is that the Sickrage fork of subliminal is much ahead of the original implementation. More providers supported here etc.

**Comment by miigotu** [comment]
@murbaniak 
Please please revert `lib/subliminal/__init__.py` and squash / rebase so this PR is one commit. After that, if you can confirm this is completely implemented and working well we can merge this.

**Comment by miigotu** [comment]
@murbaniak With no response, I will have to close this soon.

**Comment by DDamian** [comment]
So since it has been closed, there is no chance this feature will be available anytime soon ? :(

**Pull request closed without merging**
