### PR TITLE
WIP Get response text from clients

### PR DESCRIPTION
**Pull request by fernandog**
@miigotu 
Haven't tested yet. Only changed transmission for now.
What do you think about this solution?

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1382

**Comment by fernandog** [comment]
maybe if _request fail we should check here too

```
        if self._request(method='post', data=post_data):

            if self.response.json()['result'] == "success":
                return (True, self.response.json()['result'])
            else:
                return (False, self.response.json()['result']
        else:
            return (False, "error")
```

**Comment by miigotu** [comment]
clients.generic is broken with this PR

**Comment by fernandog** [comment]
Its WIP. What about the solution?

**Comment by miigotu** [comment]
It changes a hella a lot more than it needs to. Only _add_torrent_file and _add_torrent_uri needs changed, to return the status_code instead of true or false.

**Comment by fernandog** [comment]
But the others requests can fail too and return others messages

**Comment by fernandog** [comment]
@miigotu should I continue changing other clients?

**Comment by miigotu** [comment]
No, this doesnt fix the real problem, and this PR is completely fubar.

**Comment by fernandog** [comment]
ok. how to fix this then? know a way?

**Pull request closed without merging**
