### PR TITLE
Made col-status a bit bigger to make proper episodes fit

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by fernandog** [comment]
@OmgImAlexis can you send a screen shot: before and after ?

**Comment by OmgImAlexis** [comment]
This is a snatched best 1080p but it's the same for proper and other long ones. I think 205px is what it needs but 210px accounts for any that're a tad longer.

before

after

**Comment by fernandog** [comment]
never saw this snatched (best)

**Comment by OmgImAlexis** [comment]
That happened after I enabled archive on first match because of https://github.com/SiCKRAGETV/sickrage-issues/issues/2327#issuecomment-124849592

**Comment by fernandog** [comment]
Its not possible to make it auto size?

**Comment by OmgImAlexis** [comment]
You'd probably need to change quite a bit of the stylesheet for auto to work.

auto

**Comment by fernandog** [comment]
Please commit to DEVELOP

**Comment by miigotu** [comment]
Also, it has to be done in light.css too.

**Comment by fernandog** [comment]
@OmgImAlexis please do the same for light.css

**Comment by OmgImAlexis** [comment]
I did it for all three css files on the pull request for develop that you already merged. That's why this one is closed.

**Comment by OmgImAlexis** [comment]
See this https://github.com/SiCKRAGETV/SickRage/pull/2194

**Pull request closed without merging**
