### PR TITLE
Wrong import

### PR DESCRIPTION
**Pull request by miigotu**
SiCKRAGETV/sickrage-issues#1913

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu will this fix both this errrors?

github.com/SiCKRAGETV/sickrage-issues/issues/589#issuecomment-116644646

**Comment by miigotu** [comment]
Yes.

**Comment by fernandog** [comment]
thanks

**Comment by miigotu** [comment]
Sucks this move to new guessit and subliminal, so many changes needed to make them work lol. It shouldnt take too long to get them all working.

**Comment by fernandog** [comment]
abeloin was having trouble too. lot's of changes

check it out: https://github.com/abeloin/SickRage/commits/feature-subliminal080

**Comment by miigotu** [comment]
@fernandog thanks, that should help with a few of the errors I have left. I will work on it tonight more.

**Pull request merged**
