### PR TITLE
Fix freuqency in start queue

### PR DESCRIPTION
**Pull request by gborri**

### CODE REVIEW

**Comment by abeloin** [comment]
@gborri Merged

**Comment by abeloin** [comment]
@gborri Does it really need to be run every 15 minutes? I would think running it 2 or 3 times a days should be enough.

**Comment by fernandog** [comment]
@gborri low powered devices may have problems with this high frequency

**Comment by gborri** [comment]
@abeloin @fernandog if you let me know how to set default value I will change it.

**Pull request merged**
