### PR TITLE
Updated URL

### PR DESCRIPTION
**Pull request by lqkme2**
Changed https://torrentday.eu/ to https://www.torrentday.com/

### CODE REVIEW

**Comment by fernandog** [comment]
@lqkme2 why change?

**Comment by lqkme2** [comment]
I get the JSON error with other domain. How do I use SiCKRAGETV/SickRage and the changed file I made but not impact everyone else?

**Comment by fernandog** [comment]
Open an issue. We are using .eu because .com is blocked in EU

**Comment by lqkme2** [comment]
How do I do that?

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues

**Pull request closed without merging**
