### PR TITLE
Add guessit dependancy stevedore

### PR DESCRIPTION
**Pull request by miigotu**

### CODE REVIEW

**Comment by fernandog** [comment]
@neoatomic did you try after this?

**Comment by matigonkas** [comment]
just pointing out,as it might help (on the latest version)
```
2015-07-01 14:20:45 FINDSUBTITLES :: Error occurred when downloading subtitles: Traceback (most recent call last):
  File "/home/supergonkas/SickRage/sickbeard/tv.py", line 1443, in downloadSubtitles
    video = subliminal.scan_video(self.location, embedded_subtitles=False)
  File "/home/supergonkas/SickRage/lib/subliminal/video.py", line 203, in scan_video
    video = Video.fromguess(path, guessit.guess_file_info(path))
  File "/home/supergonkas/SickRage/lib/subliminal/video.py", line 65, in fromguess
    return Episode.fromguess(name, guess)
  File "/home/supergonkas/SickRage/lib/subliminal/video.py", line 114, in fromguess
    raise ValueError('Insufficient data to process the guess')
ValueError: Insufficient data to process the guess
```

**Comment by neoatomic** [comment]
@fernandog Looks like i missed this update. The error is gone now.

**Comment by fernandog** [comment]
@neoatomic but subtitles are downloaded ok?? Everything ok?

**Comment by miigotu** [comment]
@matigonkas would help more if I knew the full path and filename of the file you got that error from.

It requires at least series name, season, and episode number, nothing more for that step.

It also requires the file be at least 10MB and it matches by file hash for some of the providers (like theSubDB) in order to make a match.

**Comment by matigonkas** [comment]
@miigotu  the file name is Sleepy.Hollow.S01E02.Luna.Rosso.Sangue.DLMux.720p.AC3.iTA.2.0.AC3.ENG.Subs.H264-SATOSHi.mkv
do you need any more info?
also this error happens on startup which for some reasonj makes the Postprossesor thread dead

**Pull request merged**
