### PR TITLE
ntpath is windows only. Some systems override this module and it will…

### PR DESCRIPTION
**Pull request by miigotu**
… work ok, others do not (syno?)

@neoatomic @fernandog this might be the source of the config/cache restore issues, or at least a part of it. ntpath WILL work SOMETIMES on SOME SYSTEMS.

@neoatomic could you check if this fixes the syno restore problems?

### CODE REVIEW

**Comment by fernandog** [comment]
nice! that's odd because it works in my win7

**Comment by miigotu** [comment]
@fernandog ntpath is for Windows. os.path will use ntpath or posixpath depending on the machine it is on.  I think abeloin did this for possible network paths, but it might fail due to that.

**Comment by fernandog** [comment]
but autobackup won't be a NT path isn't? maybe could be an issue for manual backup

**Comment by miigotu** [comment]
Found the other bug, for config and db's. Adding it to this commit in a sec.

**Comment by miigotu** [comment]
It will be whatever path type is for that OS.

Restore of db and config was only working when running in console btw ^

**Comment by miigotu** [comment]
cherry-picked to master. This is a big fix, no more explaining how to manually restore!

**Comment by fernandog** [comment]
thanks!

**Comment by neoatomic** [comment]
@miigotu The browse function of the backup/restore is broken. Can not navigate to a folder anymore for selecting a file for backuping or restoring. Only manually entering the path is possible.

**Comment by fernandog** [comment]
After this PR ? We moved some JS around in another PR
@OmgImAlexis

**Comment by OmgImAlexis** [comment]
@neoatomic open an issue, it's likely a js issue. No point in discussing it here.

**Pull request merged**
