### PR TITLE
PEP8: Comments should start with '# '

### PR DESCRIPTION
**Pull request by labrys**
Comments should start with a leading white space after #.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by miigotu** [comment]
@labrys I'll accept this on if you rebase this. You will have to `git rebase -i` and comment the second commit. After you have a PR going you cant `git pull` you always need to `git rebase`

For future PR, please try not to change so many files at once. It makes it hard to review and easy to miss an error in the automated fixes.

When it comes to pep8 we have learned it is necessary to go file by file and run it in the first stages (at least in SR), because autopep8 and autoflake makes mistakes with a lot of the checks. I'd rather have 100 commits of one file each and no errors than 1 commit with a 100 files changed and no clue if there are errors =P

**Comment by labrys** [comment]
No problem.  So would you also prefer the changes to be all of a single type and do multiple PRs per file or would you prefer just a single PR per file with all the PEP8 changes for the file at once?  Also I don't mind resubmitting this PR file by file either if you want. I'm just getting around to learning Pycharm's git interface so the repetition wouldn't me hurt none :)

**Comment by miigotu** [comment]
File by file is ok, and just make sure any code changes are in a different commit than a formatting change.

This PR is ok if you can get it rebased.

**Comment by labrys** [comment]
Getting ready to head to work so a rebase probably won't happen till morning.

**Comment by labrys** [comment]
@miigotu Thanks for the rebase, something happened with my git install on XP.  Ended up wiping and reinstalling XP from scratch.

**Comment by miigotu** [comment]
@labrys you can always pull branches back down =P

**Pull request closed without merging**
