### PR TITLE
Fixes with ARCHIVED Qualities, we will only use compound ARCHIVED qua…

### PR DESCRIPTION
**Pull request by miigotu**
…lities from now on

### CODE REVIEW

**Comment by fernandog** [comment]
At displayShows: selecting episodes and change status to "Archived 720p-WEBDL" I get:

Error
Invalid status

No logs

**Comment by fernandog** [comment]
Previous status were Downloaded 720p-WEBDL

**Comment by miigotu** [comment]
That has been a problem since before this PR. Its still in progress. This PR fixed another issue.

**Comment by fernandog** [comment]
Ok. Thanks

**Comment by miigotu** [comment]
Found that fix too, will PR soon.

**Pull request merged**
