### PR TITLE
Starting sql and js move from mako

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
Does [this](https://github.com/OmgImAlexis/SickRage/blob/move-sql-js-from-mako/gui/slick/interfaces/default/config_notifications.mako#L1457) need to be removed? It's currently commented out.

**Comment by OmgImAlexis** [comment]
Use ``'', 'checked="checked"'`` not ``"", "checked=\"checked\""`` so it doesn't have to be escaped.

**Comment by OmgImAlexis** [comment]
The last few lines of inc_bottom need looking at they have a ``## FIXME`` on them.

**Comment by miigotu** [comment]
I'll look at that inc_bottom tonight.

**Comment by miigotu** [comment]
Merged in #2284

**Pull request closed without merging**
