### PR TITLE
Added the option 25 and 50 lines to the history page.

### PR DESCRIPTION
**Pull request by neoatomic**
This gives users the option to load less data and speed up the History page loading.

### CODE REVIEW

**Comment by neoatomic** [comment]
Manually selecting 25 or 50 works, but it seems to defealt back to 100 lines. 
Did i forget to add/set something.?

**Comment by fernandog** [comment]
@neoatomic 100 must the the top line

**Comment by neoatomic** [comment]
@fernandog Thank you.
So it is not possible to let SR remember the setting you chose from the drop box.? Its always falls back to 100 lines.?
Was hoping that this way i could set SR to only load 25 lines when opening the history tab.

**Comment by fernandog** [comment]
No. Default is 100. To save we need add to config.ini

**Comment by abeloin** [comment]
@neoatomic @fernandog History page is a good candidate for tablesorter's pager widget

**Comment by fernandog** [comment]
@neoatomic check this PR. It may help you understand how to add settings to config

https://github.com/SiCKRAGETV/SickRage/pull/1286/files

**Comment by fernandog** [comment]
please note there's correct place to put the save info. It's divided by groups

**Pull request closed without merging**
