### PR TITLE
[hotfix] Fix List_associated_files checking wrong folder

### PR DESCRIPTION
**Pull request by TagForce**
- List_associated_files would check the wrong folder when deleting files
- Fixes issue when downloaded file has the same namepattern as the old
file. Would then proceed to delete the new file.

Hotfix, merge with master and develop

### CODE REVIEW

**Comment by TagForce** [comment]
@fernandog @abeloin Hotfix, commited against master, so you guys can update both master and develop. I've tested it.

**Comment by abeloin** [comment]
@TagForce Will be merged soon.

**Comment by abeloin** [comment]
@TagForce Merge done

Also you should use a branch instead of applying the hotfix on master directly.

**Comment by TagForce** [comment]
@abeloin lol... I pushed master to a new branch on gh. Totally forgot to switch to it afterwards.

**Pull request merged**
