### PR TITLE
Added COUNT_SKIPPED_EPISODES

### PR DESCRIPTION
**Pull request by OmgImAlexis**
@miigotu not sure if this properly sets the default as true, this will allow people to hide skipped episodes in the progressbar and the defaults should make it stay as it was before the changes.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
ready to merge or still testing?

**Comment by OmgImAlexis** [comment]
@fernandog need @miigotu to check this, not sure if it's adding the defaults correctly or not.

**Comment by fernandog** [comment]
ok. seems ok to me

**Comment by WebSpider** [comment]
Default is set to 0, as bool.

**Comment by miigotu** [comment]
Touching same files a MG is right now.... And this is kinda making ignored status useless.

**Comment by OmgImAlexis** [comment]
@miigotu I forgot about ignored, should I change it to that? I didn't see ignored listed in the SQL for the progressbar so I figured this would be the best way to do it. :disappointed:

**Comment by miigotu** [comment]
If you just mark your episodes ignored instead of skipped they dont show in the progress bar

**Comment by OmgImAlexis** [comment]
Ugh, I spent an hour "fixing" this. Wish I had known this an hour ago.

**Comment by miigotu** [comment]
Coulda swore I told you about that distinction a few weeks ago =P

**Comment by OmgImAlexis** [comment]
It really needs to be more clearly documented. :cry:

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/wiki/Episode-Status

**Pull request closed without merging**
