### PR TITLE
Adding a download field for the episodes

### PR DESCRIPTION
**Pull request by Ulrar**
Added config option download_url
Added field to configure download_url in general --> interface
Added link to download episodes in the displayShow template, using download_url

### CODE REVIEW

**Comment by fernandog** [comment]
@Ulrar i didn't understand. Can you explain better please?

**Comment by Ulrar** [comment]
It adds a config option where you can set a base url, and then in the displayShow page it adds a columns with a download link generated from that (append the episode name to the base url).
It allow to easily retrieve the episodes from anywhere without having to use ftp or similar. Very useful when sickbeard is hosted on a dedicated server outside the home.

**Comment by fernandog** [comment]
@Ulrar I see. le'ts wait the DEV to analyse this. Have you fully tested?

**Comment by Ulrar** [comment]
I have been using this for a year now on the mr orange sickbeard, just decided to switch to this one this morning. So far looks like it works about the same, I don't see errors related to this.
If the idea is okay I can probably improve it, I have pieces of code to allow the download of subtitles aswell by cliking on the flag.

**Comment by fernandog** [comment]
@Ulrar will it work with reverse proxy? what about accessing SR from a dyndns? how do you get the public ip?

**Comment by Ulrar** [comment]
That's the point of the config option, I don't.
The user set the base url where the shows are available himself.
Personally I have a separate vhost for the episodes.

**Comment by fernandog** [comment]
I see. Nice feature.

**Comment by Ulrar** [comment]
Just noticed, it's not the correct branch. My bad, I'll reopen that correctly in a minute.

**Pull request closed without merging**
