### PR TITLE
Show Filesize in Episode List

### PR DESCRIPTION
**Pull request by TagForce**
- Show the filesize in MB in the episode list if the episode has a
filesize (is Downloaded)

- Feature requested here: https://github.com/SiCKRAGETV/sickrage-issues/issues/487

### CODE REVIEW

**Comment by fernandog** [comment]
@TagForce will this PR make any field wraped in not so large screens?

**Comment by TagForce** [comment]
Ah, uhhh, yes... I'll fix that...
It wraps the Name field as it is...

**Comment by fernandog** [comment]
@TagForce I would add  this as an option.

**Comment by TagForce** [comment]
@fernandog Yeah, I'll add an option to the Interface page to show filesizes.
I'll also fix the wrapping. Crude way of doing it would be to add whitespace: nowrap; to the col-name class, but I'm trying to fix this in a nicer way.

**Pull request closed without merging**
