### PR TITLE
Add Min. number of downloads setting

### PR DESCRIPTION
**Pull request by duramato**
Its only supported on BTDigg atm ,more providers can and probably will come to have that setting

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
rarbg, tpb, kat, hdt and some others have too. it's "peers"

**Comment by duramato** [comment]
your confusing things up ,this is the number of times it was downloaded -.- ,thats the number of people connected to torrent...

**Comment by miigotu** [comment]
@duramato I'm not sure I see a strong enough benefit from this to change our provider template?

**Comment by duramato** [comment]
I myself find this useful to ensure I only get the most popular ones ,and when/if it gets added to other providers that have seeders/leeches will ensure I only have the best results
Just my opinion tho ;)

**Comment by miigotu** [comment]
The idea is for all providers to use a uniform item object. Adding items to the tuple for just a few providers  defeats the purpose of trying to make the providers uniformly maintainable.

**Comment by rarbg** [comment]
The downloads counter is heavily broken on all public trackers. Its pointless to use its as a benchmark of whats most downloaded right now ( at the moment of query )

**Comment by miigotu** [comment]
I agree, having this as an option is not worth it if you weigh having to explain yet another configuration setting to users, and it being unreliable and not being common among all of the providers we use. Just not enough benefit.

**Pull request closed without merging**
