### PR TITLE
Revert "Set episodes with airdate as 'never' to UNAIRED status"

### PR DESCRIPTION
**Pull request by fernandog**
Reverts SiCKRAGETV/SickRage#2122

### CODE REVIEW

**Comment by mbxplex** [comment]
@miigotu is there a reason the newest update is making all my unaired episodes set an WANTED? Does this also also now, respond to Default EP? Because I now have very old, very random EP's marked as wanted for random shows like Jimmy Kimmel Live, The Real World, etc. I'm sure it won't cause an issue since they probably don't exist on the web (anymore) but I have a crazy amount of WANTED EP's now compared to before.

**Comment by miigotu** [comment]
Talk to @fernandog I told him there would be breakage lol.

**Comment by mbxplex** [comment]
@fernandog & @miigotu I dont necessary find it to be a problem yet but at the same time, I never found the old way to be a problem either. I know that EP's with "never" air dates were marked as skipped but once thetvdb or tvrage added a date, SR usually, based on my knowledge, changed the status to the correct one. I know I'm a newbie but I think this could eventually cause a bigger problem if these old EP's are somewhere floating on the internet with the status now marked as Wanted, compared to the old setup of them being Skipped.

**Comment by miigotu** [comment]
He is trying to keep episodes with airdate "never" set as UNAIRED instead of being set to skipped until they have an airdate.

That way when you go to episode status management they don't show up in the list of skipped episodes, and it looks better on the show page.

Besides, if the airdate is never, there are no releases anywhere, or there would be an airdate.

**Comment by fernandog** [comment]
This dont affect WANTED.
this change will be only visible when users REFRESH ALL shows.
it will convert skipped to unaired. There is nothing to do with wanted.

**Comment by mbxplex** [comment]
@fernandog & @miigotu I understand the point of the change but all of the "never aired" episodes now show as wanted, even for extremely old episodes. Is this what the intention was with the update, as showed in the image I posted above?

**Comment by fernandog** [comment]
As I said: no
set all this episodes to SKIPPED and refresh all this shows

**Comment by fernandog** [comment]
@mbxplex user log search field in LOGs and search for:

Episode airs in the future, marking it

and then just for

wanted

post results in GIST and paste url here

**Comment by fernandog** [comment]
@mbxplex so?

@neoatomic

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/92e299e31cec13c31504d8dfc74b066389e8a37f

**Comment by mbxplex** [comment]
@fernandog So, I went back and marked the "unaired" episodes as skipped and updated the shows and they are once again going back and being set as wanted. Here is an example from the logs:

2015-07-18 15:10:16 INFO     DAILYSEARCHER :: New episode Real Sports - 0001 01 01 - The Price of Glory; The Future of Golf; A League of Their Own airs today, setting to default episode status for this show: Wanted
2015-07-18 15:10:16 INFO     DAILYSEARCHER :: New episode Real Sports - 0001 01 01 - 2011 End of Year Roundtable airs today, setting to default episode status for this show: Wanted

**Comment by fernandog** [comment]
that is the correct! the airday = today, then set as WANTED

**Comment by mbxplex** [comment]
@fernandog but it's not ... look.

capture
capture2

**Comment by fernandog** [comment]
@mbxplex do you have Teamviewer?

**Comment by mbxplex** [comment]
@fernandog yep

**Comment by fernandog** [comment]
send info, will delete from here and connect

**Comment by mbxplex** [comment]
@fernandog  UN: 200 470 109        PW: 444rrd

**Comment by miigotu** [comment]
@fernandog datetime.date.fromordinal(1) (it's 1 in the db, but in the object it has been converted)

**Comment by fernandog** [comment]
@miigotu 
dailysearcher is the guilty.

here it assumes its aired. does not check
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/dailysearcher.py#L102

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/dailysearcher.py#L61

should ignore airdate = 1

**Comment by fernandog** [comment]
@mbxplex can i connect again?

**Comment by fernandog** [comment]
@mbxplex fixed in develop. thanks for your patience

**Comment by mbxplex** [comment]
@fernandog sorry... i had to step away for a minute... do you still need my pc?

**Comment by mbxplex** [comment]
@fernandog also, you left dailysearcher.py open in notepad++ ... will this file be updated in the newest commit?

**Comment by mbxplex** [comment]
I can't update. I think it's something you did when you moved things in cmd @fernandog 

2015-07-18 20:21:55 INFO     CHECKVERSION :: Update failed!
2015-07-18 20:21:55 WARNING  CHECKVERSION :: Please enable 'git reset' in settings or stash your changes in local files
2015-07-18 20:21:53 INFO     CHECKVERSION :: Config backup successful, updating...
2015-07-18 20:21:37 INFO     CHECKVERSION :: Config backup in progress...
2015-07-18 20:21:36 INFO     CHECKVERSION :: New update found for SickRage, starting auto-updater ...
2015-07-18 20:21:36 INFO     POSTPROCESSER :: Processing completed
2015-07-18 20:21:36 INFO     POSTPROCESSER :: PostProcessing Path: D:\Downloads\tv
2015-07-18 20:21:36 INFO     MAIN :: Building internal name cache for all shows
2015-07-18 20:21:36 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/

**Comment by fernandog** [comment]
Undo all and save again

**Comment by fernandog** [comment]
Yes

**Comment by mbxplex** [comment]
@fernandog Everything is working great. Glad you guys figured it out. 

So, is there anything I can help? I mean, I can continue to up the TVDB exceptions list, but I'd love to assist in other ways if possible.

**Comment by fernandog** [comment]
@mbxplex 
why would you set a future/unaired episode as IGNORED?

**Comment by mbxplex** [comment]
@fernandog are you just asking me in general? lol

**Comment by fernandog** [comment]
Want feed back from users. Starting with you

**Comment by mbxplex** [comment]
I don't think I would set future ones as ignored as much as unaired ones. Let's say for instance, I don't consider the episode part of the season, and I don't include it in my collection, I would mark that EP as 
ignored. This feature is rarely used for me though.

**Comment by mbxplex** [comment]
@fernandog ... I'll go further in detail with that ... future/unaired to "true/unaired - not part of collection / bad info". Future/unaired I will never mark as Ignored based on the definition of not wanted, zero count towards ind ep count and total ep count.... because I want those EP's when they come out. 

true/unaired (episodes that never really aired because they technically don't exist) ... Example: This UFC Ultimate Fighter EP ... 

capture

This is one I will mark as ignored because it is an EP that doesn't exist in my eyes.

**Comment by miigotu** [comment]
I'm gonna make all airdate 'never' be only unaired status. This means episodes not aired yet, regardless of their season/episode. If there is. An old episode that is airdate never and episodes have been aired after it there is something wrong there.

For older episodes who have aired, but have status unaired or unknown, will be set to default_episode status. If they are skipped or ignored they will stay that way

**Comment by fernandog** [comment]
@mbxplex OK with that?

**Comment by mbxplex** [comment]
@fernandog  & @miigotu wouldn't that be exactly how it was? Because of having to set the Default EP status as WANTED recently so new EPs that will air dont get set as SKIPPED, a lot of people were forced to use "Mass Update" to change all their shows to a new Dfault EP status of WANTED

**Comment by fernandog** [comment]
@mbxplex mass update episodes already aired that have skipped status. NOT all SKIPPED...

**Comment by mbxplex** [comment]
@fernandog I understand now. Makes sense. Go for it guys. You are the developers ... I will always put my trust in you regardless lol.

**Comment by fernandog** [comment]
but we can't think in all use cases that's why we ask users

**Comment by mbxplex** [comment]
I am EST ... I have to step away for now. I will be available again at 12 AM EST. But, If the current status stays leaving old unaired EPs marked as skipped and allowing you guys to mark new unaired EPs as Default EP status, that sounds like a solution.

**Comment by fernandog** [comment]
@mbxplex old/new unaired EPs  should be unraid, isn't?

**Comment by miigotu** [comment]
@mbxplex we cant let old ones stay marked skipped if they are unaired, it defaults the purpose of this fix.
We cant have unaired episodes showing as skipped/ignored or they show up in episode status management, where people accidentally mass set them to wanted.

**Comment by mbxplex** [comment]
@miigotu The one thing I've noticed in the past though was when I would see a future/unaired episode for one of my shows ... let's say "Banshee", I, because I'm weird and I would want SR to be constantly (hopefully) looking for the new season (in case it got leaked). But, after SR would restart, update, or I would choose to do something to trigger some kind of refresh, those EP's I manually marked as WANTED were now back to their original SKIPPED status.

**Comment by mbxplex** [comment]
@miigotu At the same time, none of this caused me any issues ... old EPs getting marked as WANTED ... I was just afraid it COULD eventually cause an issue. The only time I've ever had an issue was when all my shows were originally marked as SKIPPED and I had to changed them to WANTED. But, that was fixed after a quick Mass Update. 

All good on my end. Just once you guys decide to make the change ... let me know what i need to do to keep these old EPs marked SKIPPED...
 Thanks again @fernandog  and @miigotu ... great help as always!

**Comment by miigotu** [comment]
@mbxplex If we allow that, the likelyhood of getting a new leaked season vs a fake is like 1:1000000

I rather limit this situation in the software than allow it and lose precision for the very low chances of getting a season early automatically (at low quality if it is)

**Comment by mbxplex** [comment]
I totally agree ... I love the way SR functions ... the only 2 things I hope to eventually see is selective downloading and Preferred Words on Archive. Besides that, this program does EVERYTHING I need it to and more.

**Comment by miigotu** [comment]
I know, it does more in a day than I could do manually in a week =P

**Comment by mbxplex** [comment]
@miigotu oh btw ... don't merge the pull request on the tvdb exceptions list ... I'm gonna be updating it over the next day or 2

**Pull request merged**
