### PR TITLE
FindSearchResult speed up

### PR DESCRIPTION
**Pull request by gborri**
with this PR if all episode are on cache the search on providers will not be performed.

### CODE REVIEW

**Comment by fernandog** [comment]
@gborri all episodes and all qualities or only Season+Episode?

**Comment by gborri** [comment]
@fernandog I havent undestood your question. Before this PR the code will check for episode on cache all episode has beed found on cache it will search for it on provider then exit. With this PR if all episode is found on cache it will not search on providers

**Comment by fernandog** [comment]
@gborri what if in the provider there's a PROPER?

**Comment by fernandog** [comment]
@gborri or a higher quality one?

**Comment by gborri** [comment]
@fernandog is not a matter of quality or proper. the old code look into the cache, then look onto the provider if in the cache find all episode return result and doesn't manage what have been retrieved by provider. The PR skipp search on provider if all episode is found in cache

**Comment by fernandog** [comment]
@gborri imagine I want HDTV for initial and 1080p WEB for archive. If in the cache there's only HDTV, it will download it without looking the provider for 1080p web (available already)

**Comment by gborri** [comment]
It happen the same with the actual code. I haven't changed the way it works.

Il giorno ven 17 apr 2015 00:10 Fernando <notifications@github.com> ha
scritto:

**Comment by fernandog** [comment]
@TagForce thougts?

**Comment by TagForce** [comment]
@gborri @fernandog What if not all episodes are on cache?
As far as I can tell, if the number of results is lower than the number of the episodes, it will iterate over all the episodes, regardless of if they were found on the cache or not...
So, let's say there's 2 episodes, one of which is on the cache, then in the new else statement it will go over the found one as well.

I don't think this speeds anything up. If they are on the cache they will simply not execute the code you moved (there's a continue at the end of the if). If there are any that are not on cache, ALL of them will be searched, which will undoubtedly take longer.

Right?

**Comment by gborri** [comment]
You are right. i haven't realized that there was the continue code.

**Pull request closed without merging**
