### PR TITLE
Added support for support HEVC (x265)

### PR DESCRIPTION
**Pull request by ipsq**
by changing all 264 with (264|265)

### CODE REVIEW

**Comment by ipsq** [comment]
Wrong commit message, sorry for that.

**Comment by ipsq** [comment]
Should I also add HEVC itself to the list? Some release groups prefer to use HEVC over x265 so this won't pick those up.

**Comment by miigotu** [comment]
@ipsq we cant add HEVC/H265 this way, it would need it's own quality. We have discussed it and the biggest problem is that many users use raspberry pi/pi2 and support for hevc/x265 is limited. IE: they need to be able to distinguish HD/FULLHD from HDHEVC/FULLHDHEVC

**Comment by ipsq** [comment]
But SickRage already downloads files with x265 so it would only be an indicator inside SickRage itself. I don't get why this would  reduce compatibility with Raspberry Pi?

**Comment by miigotu** [comment]
Most embedded devices cannot play hevc well. If you change it this way there is no indication in the gui that it is an HEVC video.

Lets see what some others think about this first.

**Comment by fernandog** [comment]
@miigotu I add x265 and hevc to global ignore words to don't download them.

if this PR only adds the possibility to "read" files with x265 I guess it's no a problem.

We can add an option (default off) that auto adds x265 and hevc to global ignore words.
I don't see we rewriting all qualities to allow/disallow x265. Instead we should filter it.

**Comment by miigotu** [comment]
Ok, I just checked too that hevc gets downloaded but just detected as the wrong quality. Still don't like it that we can't distinguish easily.

I'm worried that something will break =P so if something goes boom I kill you! lol

**Comment by miigotu** [comment]
Create PR to develop -.-

**Comment by fernandog** [comment]
@miigotu wait. just my opinion lol. don't need to merge. we were discussing lol

**Comment by fernandog** [comment]
@miigotu there's no need to point that file is x264 or x265. we don't do that with xvid. why do that with x265

**Comment by ipsq** [comment]
@fernandog My SickRage client did download a file containing x265?

**Comment by fernandog** [comment]
@miigotu or do you think we should add codec in quality? Like 1080p.HDTV.x264 and 1080p.HDTV.x265 ?

In rpi 1080p x265 dont play well. Even 720p

**Comment by ipsq** [comment]
Shouldn't this become an option then? There are a lot of people who **don't** run SickRage on an RPi.

**Comment by fernandog** [comment]
SR downloads OK x265 files.

**Comment by miigotu** [comment]
@ipsq its not about what you run SR on, its about what you play your media on, and I'm better half our users play media on a raspberry pi, pi2 or other embedded board.

We aren't saying that something should not be done, we just have been discussing options for a proper solution. Usually the first most obvious and easy "workaround" is not the best route, and it is better to make a well thought out decision.

It just needs incubated/discussed a bit

**Comment by piejanssens** [comment]
IMO adding the codec to the quality is going to get messy.
Getting to a point where x265 is widely adopted and compatible (like x264 is today) will take some time.
Just a simple "Enable HEVC/x265 releases" checkbox in the Episode Search Settings is easy to configure, easy to find for the end user and doesn't require any filtering words.

**Comment by miigotu** [comment]
Need to have this now, with the hachoir usage now x265 was getting detected as unknown.

**Pull request merged**
