### PR TITLE
tntvillage: Cleanup

### PR DESCRIPTION
**Pull request by abeloin**
The season pack returned invalid results.

See https://github.com/SiCKRAGETV/sickrage-issues/issues/1017 for more info

### CODE REVIEW

**Comment by gborri** [comment]
@abeloin why are you disabling season search pack? why are you saying that the season pack returned invalid result?

**Comment by gborri** [comment]
@abeloin is't not a problem on tntvillage... the error will raise also for other provider.
The error is in the code of findNeededEpisode.

**Comment by gborri** [comment]
@abeloin please don't merge this PR. with this PR you are avoiding the problem not fix it.

**Comment by gborri** [comment]
@abeloin please look at this #1680

**Comment by abeloin** [comment]
@gborri I'm not avoiding the issue.

Anyway, I've changed the PR to only include the cleanup code. Let's continue discussing this in https://github.com/SiCKRAGETV/sickrage-issues/issues/1017

**Comment by gborri** [comment]
@abeloin if you like you can merge also #1683

**Pull request merged**
