### PR TITLE
Added TRAKT_REMOVE_WATCHLIST Function as was before

### PR DESCRIPTION
**Pull request by gborri**
as requested in PR #1400

### CODE REVIEW

**Comment by gborri** [comment]
@EchelonFour if TRAKT_REMOVE_WATCHLIST is not checked, you have to remove episode manually from watchlist. is it wright?

**Comment by EchelonFour** [comment]
it gets removed when you watch it

**Comment by gborri** [comment]
@EchelonFour how? there's no code that take in charge it. How can sickrage know when the episode is watched? it's traktv site that take in charge of it?

**Comment by EchelonFour** [comment]
trakt has plugins for media players that tell trakt everything you watch. I mostly use kodi. https://trakt.tv/downloads

**Comment by abeloin** [comment]
@gborri Is this what you asked in #1400 ?

**Comment by gborri** [comment]
@abeloin yes

**Comment by abeloin** [comment]
@gborri Done

**Comment by gborri** [comment]
@abeloin thanks
 Il 04/mar/2015 20:39 "Alexandre Beloin" <notifications@github.com> ha
scritto:

**Comment by fernandog** [comment]
@gborri can you help me reply this:

https://sickrage.tv/forums/forum/help-support/general-support/20542-trakt-tv-configuration-to-limit-it-to-one-feature

thanks!

**Pull request merged**
