### PR TITLE
Add anime release groups to add new show page

### PR DESCRIPTION
**Pull request by Thraxis**
* Change anime release groups to in memory storage for lowered latency
* Add anime release groups to add new show options page

Ports the following two PR's from SickGear

https://github.com/SickGear/SickGear/pull/162
https://github.com/SickGear/SickGear/pull/153

### CODE REVIEW

**Comment by Thraxis** [comment]
image

**Comment by Thraxis** [comment]
rebased to current dev and merged with #1748

**Comment by Thraxis** [comment]
@abeloin @fernandog Found a couple issues.  Working through them now.

Flag as Do Not Merge for now.

**Comment by Thraxis** [comment]
@abeloin @fernandog I found the issues and have them corrected.  Will be running through my Anime checks and should have confirmation on an all clear this weekend.

**Comment by fernandog** [comment]
@Thraxis as soon you give the ok, will merge it

**Comment by Thraxis** [comment]
@fernandog It looks good to go.  My last bug fix tested out today

**Pull request merged**
