### PR TITLE
Fixed TypeError when reporting indexerID.

### PR DESCRIPTION
**Pull request by jamesorlakin**

### CODE REVIEW

**Comment by fernandog** [comment]
@jamesorlakin dont PR o
on master.

**Comment by jamesorlakin** [comment]
Sorry!

**Comment by fernandog** [comment]
@jamesorlakin what was the error ?

**Comment by jamesorlakin** [comment]
My error log wiped itself but it was concerning concatenating str and int objects on this line.

**Comment by jamesorlakin** [comment]
Found an old copy of the log:

TypeError: cannot concatenate 'str' and 'int' objects
logger.log('No Show Object found for show with indexerID: ' + searchThread.show.indexerid, logger.ERROR)
File "/files/sickbeard/sickbeard/webserve.py", line 1982, in getEpisodes

**Comment by fernandog** [comment]
Which commit are you using?

**Comment by jamesorlakin** [comment]
c1c519b720acfbbc5cec7c5a89c48053e9f1b980

**Comment by fernandog** [comment]
@jamesorlakin this error happens in that commit? If so PR to develop please

**Comment by jamesorlakin** [comment]
Turns out this has already been applied to the development branch by someone else. https://github.com/SiCKRAGETV/sickrage-issues/issues/1349

**Pull request closed without merging**
