### PR TITLE
Small change: add label for deleteFile

### PR DESCRIPTION
**Pull request by theemstra**
When deleting a file, text should be clickable.

### CODE REVIEW

**Comment by fernandog** [comment]
Did you checked if the size of the path+filename wont make the dialog box larger or unreadable? Can you send a screebshot showing this?
thanks

**Comment by theemstra** [comment]
This will not change anything about the size of the path or any filenames.
This is just a usability fix. Screen:

**Comment by theemstra** [comment]
After clicking the red text:
image

**Comment by fernandog** [comment]
I see. sorry! thanks!

**Comment by abeloin** [comment]
@fernandog I'm wondering if it's a good idea or not because now the user can click anywhere on the red text to activate the deleting of all files. Any thought?

**Comment by fernandog** [comment]
@abeloin good point. let's not merge it. this way user must be really sure and click only in the little box.

**Comment by theemstra** [comment]
I do still think that in the usability is pretty important. The user has to click the "Delete" button, then click the red line and the button to actually delete anything.

**Pull request closed without merging**
