### PR TITLE
PNotify Update

### PR DESCRIPTION
**Pull request by Thraxis**
* Add history module to pnotify lib
* Update PNotify to latest master (2015-03-26) for desktop notifications
* URI Encoded SickRage shark logo image for desktop notifications

### CODE REVIEW

**Comment by abeloin** [comment]
@Thraxis just merged this https://github.com/SiCKRAGETV/SickRage/pull/1705, would it conflict with this PR?

**Comment by Thraxis** [comment]
Shouldn't this is just a JS notification system for showing notifications to the webbrowser. 

I can merge my testing branch against develop again tonight and give it a couple shakeout tests to verify

**Comment by fernandog** [comment]
@Thraxis any news on this one?

**Comment by Thraxis** [comment]
Has been working fine since I merged in the latest updates

**Pull request merged**
