### PR TITLE
Remove "aoeu" div from the default "add new shows" template

### PR DESCRIPTION
**Pull request by fl0yd**
first commit removed the div, the second removed a blank line that I should have deleted with the first commit.

### CODE REVIEW

**Comment by fernandog** [comment]
@fl0yd I think this div is used to show other information like the directory of the new created tv-show

**Comment by fl0yd** [comment]
If that's the case, I could at least remove the "aoeu" from the page

**Comment by fernandog** [comment]
@fl0yd can you test adding a show and check if the div is used? I'm on mobile.

**Comment by fl0yd** [comment]
The test succeeded without issue, below is a screen grab of the tab after the edit.

image

**Comment by fernandog** [comment]
I see. bur try this:
select the parent folder, typing a tv-show and the DIV will be filled with the information

**Comment by abeloin** [comment]
@fl0yd Pull request #1192 should fix your issue without having to remove the "aoeu"

**Comment by fernandog** [comment]
this DIV must be hidden until choosing the tv-show. Then will show:

"Adding show Show-name into /path/to/folder/Show-name/"

**Comment by fl0yd** [comment]
Thanks!

**Pull request closed without merging**
