### PR TITLE
Newer domain for IPT

### PR DESCRIPTION
**Pull request by MLWALK3R**
One domain that isn't blocked.

### CODE REVIEW

**Comment by WebSpider** [comment]
Iptorrents.eu is working just fine for me

**Comment by MLWALK3R** [comment]
For people with Sky broadband they cannot. Sky are now intercepting https traffic and blocking .eu .com .ru domains .rocks is the only one not blocked.

**Comment by miigotu** [comment]
Use a different DNS...

**Comment by MLWALK3R** [comment]
@miigotu It's not relevant to DNS...  they're inspecting HSTS headers and blocking the domains changing your DNS does nothing as the server IP addresses are know to sky.

**Comment by miigotu** [comment]
@WebSpider maybe we should implement a feature to allow user to override the built-in url, without them modifying code.

**Comment by MLWALK3R** [comment]
That would make more sense having that option, couchpotato does that ![Image of couchpotato  ] (http://lel.ovh/1440625337)

**Comment by miigotu** [comment]
@MLWALK3R we already allow proxies, but proxy does not change the base url.

**Comment by MLWALK3R** [comment]
@miigotu When I tested the proxy a while ago they didn't seem to work; but it could just been me.

**Comment by MLWALK3R** [comment]
Just tested the proxys

```
22:50:35 ERROR::SEARCHQUEUE-MANUAL-278469 :: [IPTorrents] :: Unable to connect to IPTorrents provider: error [Errno bad handshake] [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert illegal para*eter')]
Traceback (*ost recent call last):
  File "/ho*e/*/SickRage/sickbeard/providers/iptorrents.py", line 96, in _doLogin
    self.session.get(self.urls['login'], ti*eout=30)
  File "/ho*e/*/SickRage/lib/requests/sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "/ho*e/*/SickRage/lib/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/ho*e/*/SickRage/lib/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/ho*e/*/SickRage/lib/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
SSLError: [Errno bad handshake] [('SSL routines', 'SSL23_GET_SERVER_HELLO', 'sslv3 alert illegal para*eter')]
22:50:35 INFO::SEARCHQUEUE-MANUAL-278469 :: [IPTorrents] :: Unable to find a download for: [The Brink - 1x10 - There Will Be Consequences]

**Pull request closed without merging**
