### PR TITLE
Start converting templates for Mako, and replacement of Cheetah

### PR DESCRIPTION
**Pull request by miigotu**
PR's helping me do this conversion are most welcome. The changes in https://github.com/SiCKRAGETV/SickRage/commit/08ea0ec030c64b2a479604747e4f7016c14d7a57
are a good example of a starting point, although it is not complete and bugs will need worked out once everything is changed over.

This will stay in this branch until complete and production ready.

### CODE REVIEW

**Comment by MGaetan89** [comment]
Thanks for merging.
How can we keep track of what's done and not?

**Comment by miigotu** [comment]
I think just keep the tmpl until it's matching mako is finished, then delete the tmpl.

**Comment by OmgImAlexis** [comment]
Check https://github.com/SiCKRAGETV/SickRage/pull/2226 for a more up to date convert.

Should this be closed since I've merged yours into my repo?

**Comment by miigotu** [comment]
Nope the commit hashes should match and be ignored by the merge. Need to keep this open so people see progress.

**Comment by OmgImAlexis** [comment]
Alright cool.

**Comment by miigotu** [comment]
@OmgImAlexis @MGaetan89 SR boots with mako now and about 1/4 of pages working correctlly.

**Comment by WebSpider** [comment]
Since converting rest of the pages is enough work, let me know where i can help.

-----Original Message-----

**Comment by OmgImAlexis** [comment]
@miigotu it's midnight here and I've been up for 2 days. I'll work on whatever you guys have done when I get up in the morning.

**Comment by miigotu** [comment]
@WebSpider not sure where to tell you to jump in xD. I want to avoid duplicate work. Maybe we should make a list of remaining templates and claim them one by one?

**Comment by miigotu** [comment]
Need to make a list of unfinished templates, and finish the webserve.py conversion, so that you guys know where to go. I have just been making the changes in webserve.py as I go -.-

**Comment by WebSpider** [comment]
Exactly why i asked :)

-----Original Message-----

**Comment by miigotu** [comment]
This list is not complete..

config pages arent working yet.

Should be working like the cheetah versions:
show list (home)
display show (displayShow)
news (markdown)
irc (IRC)
changelog (markdown)
help&info (config)
restart (restart, restart_bare)
episode status management (manage_episodeStatuses)
history (history)
log pages (viewlogs, errorlogs)

**Comment by miigotu** [comment]
You guys could test the ones that I have pretty much finished and find anything broken/missed

**Comment by WebSpider** [comment]
I will move my test install to the mako branch in a few hours and test the new templates!

-----Original Message-----

**Comment by miigotu** [comment]
@WebSpider you will need to install mako

either
sudo apt-get install python-mako
or
sudo pip2.7 install mako

**Comment by OmgImAlexis** [comment]
@miigotu not even sure where to start. I'm just getting this 100 or so times.

````
18:19:55 ERROR::Thread-18 :: Failed doing webui callback: Traceback (most recent call last):
  File "/Users/xo/SickRage/sickbeard/webserve.py", line 273, in async_call
    result = function(**kwargs)
  File "/Users/xo/SickRage/sickbeard/webserve.py", line 755, in index
    t = PageTemplate(rh=self, file="home.tmpl")
  File "/Users/xo/SickRage/sickbeard/webserve.py", line 124, in __init__
    super(PageTemplate, self).__init__(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/local/lib/python2.7/site-packages/Cheetah/Template.py", line 1546, in _compile
    self._fileMtime = os.path.getmtime(file)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/genericpath.py", line 62, in getmtime
    return os.stat(filename).st_mtime
````

**Comment by miigotu** [comment]
@OmgImAlexis you must not be up to date on the mako branch because your source is still calling cheetah.

git fetch upstream
git reset --hard upstream/mako

**Comment by OmgImAlexis** [comment]
Oops, forgot to reset. I'll work on some of the stuff now and push after each file. Am I able to push to this pull-request or do I need to start another?

**Comment by OmgImAlexis** [comment]
What do I have to do so I don't have to restart after every change?

**Comment by miigotu** [comment]
@OmgImAlexis Just start it up, and start making changes. try to load the page see if it works, make changes.

Some of webserve.py still needs completed, so some variables aren't set for some of the templates.

**Comment by miigotu** [comment]
Not possible to push direct to this PR btw. When your PR is merged to mako, your commits will show up in this one.

**Comment by OmgImAlexis** [comment]
It looks like it may be caching the files still. For now I've just deleted the cache folder and added ``<%page cached="False"/>`` to the top. I'll remove it once the file is done and recheck.

**Comment by OmgImAlexis** [comment]
@miigotu alright, sounds good. Please mark mine as do not merge.

**Comment by OmgImAlexis** [comment]
For future reference, inline ``<%= %>`` should be changed to ``${}``

**Comment by miigotu** [comment]
@OmgImAlexis we need to try and divide these up somehow, or say which we are going to work on to avoid dupe work and/or conflicts

**Comment by OmgImAlexis** [comment]
Well if noone else is working on them right now I'll just do them one by one so if anyone else wants to work on them start at the bottom. Remember I commit once every 200 - 300 lines and/or at the end of each file I'm working on. That should be enough info that we don't get people working on the same files.

**Comment by OmgImAlexis** [comment]
Fuck Github's slow clone speeds.
``Receiving objects:  15% (5312/34970), 3.25 MiB | 24.00 KiB/s``

**Comment by miigotu** [comment]
I'll just leave it alone for now while you are on it. I'll watch soem shameless and spam IRC xD.

**Comment by miigotu** [comment]
BTW, LOVE atom.io so far, no syntax checking though? I think pyCharm does.

**Comment by WebSpider** [comment]
I just now pulled my test setup to the mako branch, and it runs, but when it tries to render /home, no luck:

Error !
AttributeError: 'module' object has no attribute 'layout'

306    <% fuzzydate = 'airdate' %>
307    % if sickbeard.FUZZY_DATING:
308    fuzzyMoment({
309        dtInline : ${('true', 'false')[sickbeard.layout in 'poster']},
310        containerClass : '.${fuzzydate}',
311        dateHasTime : false,
312        dateFormat : '${sickbeard.DATE_PRESET}',
313        timeFormat : '${sickbeard.TIME_PRESET}',
314        trimZero : ${('false', 'true')[sickbeard.TRIM_ZERO]}

/home/nivo/devel/SickRage/gui/slick/interfaces/default/home.mako, line 309:

309        dtInline : ${('true', 'false')[sickbeard.layout in 'poster']},

/usr/lib/python2.7/dist-packages/mako/runtime.py, line 853:

853  callable_(context, *args, **kwargs)

**Comment by OmgImAlexis** [comment]
Install an addon, there's one for EVERYTHING. When you say "syntax checking" do you mean lint checking or syntax highlighting? There's addons for both for almost EVERY language.

@WebSpider wrap that in a \`\`\`\` if you can.

**Comment by WebSpider** [comment]
pycharm does syntax checks,but it doesnt catch it all

**Comment by miigotu** [comment]
I'll claim trendingShows, status, testRename though. Wanna try atom.io a bit.

**Comment by OmgImAlexis** [comment]
Sounds good. I'll just on IRC now.

**Comment by OmgImAlexis** [comment]
@WebSpider new lines for the \`\`\`\` man.

**Comment by WebSpider** [comment]
@OmgImAlexis yeh yeh, im making coffee and trying to keep an infant from crying at the same time :P

**Comment by OmgImAlexis** [comment]
All's good. I didn't see that on mine. Try pulling from mine instead of what's on there now.

``sickbeard.layout in 'poster'`` should be backwards I think as it's checking for poster inside of the sickbeard.layout array. Not sure why it's like that. Let me check my branch.

**Comment by OmgImAlexis** [comment]
Yep, I'll change that once I've finished cloning the repo. I'm guessing mine didn't show up as I've got no shows on this install.

You running this on a live version?

**Comment by WebSpider** [comment]
@OmgImAlexis my testbed is a simple blackhole setup, with an outdated clone of my live db

**Comment by OmgImAlexis** [comment]
Home and other pages that use the sickbeardTable seem to still have the js bug where the top inputs aren't hidden even though they have the ``hideme`` class.

**Comment by OmgImAlexis** [comment]
screen shot 2015-08-04 at 4 20 47 pm

**Comment by miigotu** [comment]
@OmgImAlexis need to pull from upstream/mako before starting next PR.

In config_notifications all of the ${(' checked="checked"', '')[sickbeard.USE_KODI == True]} are backwards

I know that at least these are not done:
editShow.mako
home_addExistingShow.mako
home_recommendedShows.mako
manage_torrents.mako

**Comment by OmgImAlexis** [comment]
@miigotu I knew there was a file I missed fixing them I just couldn't remember which.

**Comment by OmgImAlexis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/2267

They should all be done apart from imports.

**Comment by miigotu** [comment]
missed an % include or two also xD

**Comment by OmgImAlexis** [comment]
Next person to look at this can fix that. I'm going to go work on https://github.com/OmgImAlexis/olivia

**Pull request merged**
