### PR TITLE
Hide remote IP from log

### PR DESCRIPTION
**Pull request by fernandog**
@duramato or you want to hide local IP?

### CODE REVIEW

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2201

**Comment by Arcanemagus** [comment]
Are you sure you want to include a gigantic library like that when a simple regex will do just as well for the simple use case you have in there?

**Comment by fernandog** [comment]
@Arcanemagus would you like to make a PR for that? I couldn't make regex to check if IP is in those intervals

**Comment by neoatomic** [comment]
Have to agree. That is a lot of code for hiding an ip in the log. :P

**Comment by Arcanemagus** [comment]
This file has essentially the logic you want: https://github.com/ecleese/plexWatchWeb/blob/dev/datafactory/get-user-ip-stats.php

I'm at work so I can't dig into this codebase to apply it here right now.

**Comment by fernandog** [comment]
@Arcanemagus ok! thanks

**Comment by miigotu** [comment]
I agree with everyone else, you don't even need regex, let alone a big ass library =P

**Comment by miigotu** [comment]
http://stackoverflow.com/a/28532296/1338570

if apikey and ip is not local, mask it
else do not mask.

**Pull request closed without merging**
