### PR TITLE
Fixup HDTorrents provider

### PR DESCRIPTION
**Pull request by miigotu**
@fernandog here we go!

### CODE REVIEW

**Comment by fernandog** [comment]
nice! thanks!

**Comment by fernandog** [comment]
@miigotu I guess it's not working. shows no result

cache.db - table hdtorrents is empty (also the others providers. is that right?)

```
2015-07-09 12:37:55 INFO     SEARCHQUEUE-MANUAL-272127 :: Unable to find a download for: [Extant - 2x02 - Morphoses]
2015-07-09 12:37:55 DEBUG    SEARCHQUEUE-MANUAL-272127 :: formatting pattern: %SN - %Sx%0E - %EN -> Extant - 2x02 - Morphoses
2015-07-09 12:37:55 DEBUG    SEARCHQUEUE-MANUAL-272127 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-07-09 12:37:55 DEBUG    SEARCHQUEUE-MANUAL-272127 :: formatting pattern: %SN - %Sx%0E - %EN -> Extant - 2x02 - Morphoses
2015-07-09 12:37:55 DEBUG    SEARCHQUEUE-MANUAL-272127 :: Episode has no release name, replacing it with a generic one: %SN - %Sx%0E - %EN
2015-07-09 12:37:38 DEBUG    SEARCHQUEUE-MANUAL-272127 :: [HDTorrents] :: Search string: https://hd-torrents.org/torrents.php?search=Extant+S02E02&active=1&options=0&category[]=59&category[]=60&category[]=30&category[]=38
2015-07-09 12:37:38 INFO     SEARCHQUEUE-MANUAL-272127 :: [HDTorrents] :: Performing episode search for Extant
2015-07-09 12:37:38 DEBUG    SEARCHQUEUE-MANUAL-272127 :: [HDTorrents] :: Last update was too soon, using old cache: today()-2015-07-09 12:25:30<0:20:00
```

**Comment by fernandog** [comment]
@miigotu can you confirm it's not working? I get no cache items. no log messages with results. It's a RSS. I should at least show rss items and try to parse them

**Comment by miigotu** [comment]
It's not RSS. It's parsing the page. And RSS is not implemented in her provided yet, so off there is no cache items.

**Comment by fernandog** [comment]
will check when I have new wanted episodes but I think the page parsing it's not working

**Comment by fernandog** [comment]
so why it would use cache?

[HDTorrents] :: Last update was too soon, using old cache: 2015-07-14 16:37:45. Updated less then 20 minutes ago

**Comment by miigotu** [comment]
All providers have a cache class. You just can't search hdt with empty string. So the cache has nothing in it right now, until I can implement a feed there.

**Comment by miigotu** [comment]
Both backlog and daily work for me with it.

**Comment by fernandog** [comment]
I'm getting a lot of in browser
"The server made a boo boo, please try later."

do we need to handle that in the code?

**Comment by miigotu** [comment]
Yeah, that's their funky 503.

**Comment by miigotu** [comment]
I still have to revisit all of the providers, other thinks just popped up, and all the rewrite for sub's. Quirks in subtitles need ironed out and I'll go back to them.

**Comment by fernandog** [comment]
ok! thanks

**Comment by fernandog** [comment]
@miigotu low priority: daily search is not working for HDT

I don't search results in log debug messages but I know they exist
Shouldn't these results appear in debug messages?

image

image




```
2015-07-16 12:14:01 INFO     SEARCHQUEUE-DAILY-SEARCH :: No needed episodes found
2015-07-16 12:14:00 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: Transaction with 3 queries executed
2015-07-16 12:14:00 INFO     SEARCHQUEUE-DAILY-SEARCH :: Beginning daily search for new episodes
2015-07-16 00:09:04 INFO     DAILYSEARCHER :: New episode Extant - 2x03 - Empathy for the Devil airs today, setting to default episode status for this show: Wanted
2015-07-16 00:09:03 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-07-15 23:09:02 INFO     DAILYSEARCHER :: New episode Suits - 5x04 - No Puedo Hacerlo airs today, setting to default episode status for this show: Wanted
2015-07-15 23:09:01 INFO     DAILYSEARCHER :: Searching for new released episodes ..
```

**Comment by fernandog** [comment]
@miigotu I added some log messages

```
            tables = html.find('table', attrs={'class': 'mainblockcontenttt'})
            logger.log(u'Tables:' + str(tables), logger.DEBUG)  
            if not tables:
                logger.log(u'Could not find table of torrent', logger.DEBUG)     
                continue
```

And it SR can't find the mainblockcontenttt table

```
DEBUG    SEARCHQUEUE-BACKLOG-258602 :: [HDTorrents] :: Could not find table of torrent
DEBUG    SEARCHQUEUE-BACKLOG-272127 :: [HDTorrents] :: Tables:[]
DEBUG    SEARCHQUEUE-BACKLOG-258602 :: [HDTorrents] :: Search string: https://hd-torrents.org/torrents.php?search=Extant+S03E03&active=1&options=0&category[]=59&category[]=60&category[]=30&category[]=38
```

this mainblockcontenttt is inside another table: hdblock.
I tried do some search and fix but I couldn't

image

**Comment by fernandog** [comment]
when I save the html to a file and run:

```
from BeautifulSoup import BeautifulSoup
data2 = open('hdt.html')
soup = BeautifulSoup(data2)
print len(soup('table'))
tables = soup.find('table', attrs={'class': 'mainblockcontenttt'})
print tables
```

It finds mainblockcontenttt! and Table len = 61

BUT in SickRage I only get 6 !
SEARCHQUEUE-BACKLOG-277462 :: [HDTorrents] :: Len Table:6

```
            tablesLen = len(html('table'))
            logger.log(u'Len Table:' + str(tablesLen), logger.DEBUG)
```

**Pull request merged**
