### PR TITLE
Update dependencies and use minified resources

### PR DESCRIPTION
**Pull request by MGaetan89**
- Update Bootstrap to 3.3.5
- Use minified version of jQuery-UI and jQuery FancyBox
- Remove some unused files in `js/`

I noticed that the `droppable` and `sortable` widgets are removed from jQuery-UI JS file in this PR.
I didn't find any usage of them in the project. Can someone confirm this or should I include them again?

### CODE REVIEW

**Comment by miigotu** [comment]
Should merge and find out?

**Comment by miigotu** [comment]
@MGaetan89 how come all of this became executable? everything in SR needs to be 644, except SickBeard.py, and autoProcessTV/autoProcessTV.py  hellaToSickBeard.py  mediaToSickbeard.py  sabToSickBeard.py

**Comment by MGaetan89** [comment]
I guess those are the permissions of the new files. I will change them back.

**Comment by MGaetan89** [comment]
Permissions are fixed.
The images are still visible in the diff though.

**Comment by MGaetan89** [comment]
Found one place that requires `sortable`: the search providers list. Sorry about that, I will fix that right away.
Still nothing about `droppable`.

**Pull request merged**
