### PR TITLE
Add provider BTDIGG

### PR DESCRIPTION
**Pull request by miigotu**
Rebase of https://github.com/SiCKRAGETV/SickRage/pull/2000

### CODE REVIEW

**Comment by matigonkas** [comment]
@miigotu  ive noticed something now ,when daily search runs it trows an error 
```
Error while searching BTDigg, skipping: TypeError("'NoneType' object has no attribute '__getitem__'",)
```

**Comment by miigotu** [comment]
lol. @matigonkas you used tabs for indents?

**Comment by matigonkas** [comment]
yeah

**Comment by miigotu** [comment]
Always use 4 spaces for indents in python.

Also, the RSS cache is not implemented in that file (should still work for backlog i think). Working on it now.

**Comment by miigotu** [comment]
@matigonkas #2050

**Comment by matigonkas** [comment]
Thanks for fixing it @miigotu ,sorry for it being such a piece of s*** it seems OK now .But on the bright side since i updated it i got already like 20 new downloads that it didnt found previously on any of the public provoviders and some of the private obra só its a big plus :) 
Also do i use tab or 4 spaces? (Didnt quite understod)

**Comment by miigotu** [comment]
Use 4 spaces. Tabs have no place in source code.
Just as a note, rss/daily is useless with btdigg, it is only ok as as backlog provider.

**Pull request merged**
