### PR TITLE
Revert "Replace all mode != 'RSS' with mode is not 'RSS', etc"

### PR DESCRIPTION
**Pull request by sickraged**
`is` is for identity checks not for checking equality.

### CODE REVIEW

**Comment by miigotu** [comment]
Good job, way to break pep8... noob.

**Comment by sickraged** [comment]
@miigotu you are the noob, noob. `is not` is an identity check not an equality check. Do you even know how to code in python?

**Comment by miigotu** [comment]
`<ech3l0n> k fairly sure pythong is case sensitive with its funcs right ?`

**Comment by miigotu** [comment]
basestring with same value has the same identity. get a life.

**Comment by sickraged** [comment]
@miigotu I don't care about your fork. I was going to raise a PR against your fork as well but you seem to be the "virus" yourself.

**Comment by sickraged** [comment]
@miigotu look move along. Your code change was simply incorrect and you should grow up.

**Comment by miigotu** [comment]
Jup, so viral.

```python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> mode = 'RSS'
>>> mode is 'RSS'
True
>>> mode is not 'RSS'
False
>>>
```

**Comment by OmgImAlexis** [comment]
Guessing @sickraged is @echel0n lol

**Comment by miigotu** [comment]
If you see that as incorrect when the interpreter clearly proves it is correct, go argue with the python interpreter.

wannabes I swear.

**Comment by sickraged** [comment]
@OmgImAlexis actually I am not. I previously sent this project code changes to fix your terrible programming practices. I now maintain a private fork because of how terrible your code is :-)

**Comment by miigotu** [comment]
bwahahaha

**Comment by OmgImAlexis** [comment]
@sickraged we've actually fixed most of the errors that were added in while working under @echel0n, most of the code now completely passes all lint, PEP8 and generic unit tests. Hell even the js passes tests which is hasn't even done.

**Comment by sickraged** [comment]
Oh really?

```git clone https://github.com/SickRage/SickRage.git okay
cd okay/sickrage
pep8 . |wc -l
52
```
seems to suggest otherwise :-)

**Comment by sickraged** [comment]
@echel0n please merge this pr :-)

**Comment by miigotu** [comment]
Oh snap, only 52? Much closer than we thought....

**Comment by echel0n** [comment]
For starters sickraged actually isn't me but way to go with bashing on someone cause they where trying to help moron, lastly did you just ever show your elite skillz with ur comparison argument lol

**Comment by sickraged** [comment]
I wonder if there is a way to ban those who are being unhelpful from this project ...

**Comment by miigotu** [comment]
Please merge this =P

**Comment by echel0n** [comment]
@sickraged yes there is and it is being taken care of.

IS comparison is used for object comparison ... maybe now your understand why I said those UnitTests where important lol

**Comment by miigotu** [comment]
"yes there is and it is being taken care of."
have fun with that bag of lies. stop assuming users are stupid enough to believe your brand of crazy.

**Pull request closed without merging**
