### PR TITLE
Hide upgrade div on restart

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by fernandog** [comment]
ow! few lines only. I was trying to use java script to hide the div

**Comment by OmgImAlexis** [comment]
@fernandog haha, hiding things with css is a lot easier. For future referance to add something for a specific page just use the block in the file that has the same name such as `restart.mako`.

**Comment by fernandog** [comment]
thanks!

**Comment by fernandog** [comment]
worked! I will try tomorrow to hide the div when user click "update"

**Comment by OmgImAlexis** [comment]
We can do it when they click update, just use something like this.

````
$('.class_for_update_link_here').on('click', function(){
    $('.upgrade-notification').hide();
});
````

**Comment by fernandog** [comment]
also we can do like CP adding a block page with "SickRage is backing up your data"

I found this but CP looks nicer
http://malsup.com/jquery/block/

```
App.blockPage('Please wait while CouchPotato is being updated with more awesome stuff.', 'Updating');
```

https://github.com/RuudBurger/CouchPotatoServer/blob/develop/couchpotato/core/_base/updater/static/updater.js#L93

**Comment by OmgImAlexis** [comment]
I really don't want to add yet another library for jQuery when it's not needed. Half of the ones we've got now aren't even really needed.
Also keep in mind most of that stuff is in js because of the whole ui being a single page app.

**Comment by fernandog** [comment]
NP. I thought it was some function that only needed to be called.

**Pull request merged**
