### PR TITLE
Add TVChaosUK Provider

### PR DESCRIPTION
**Pull request by miigotu**

### CODE REVIEW

**Comment by miigotu** [comment]
This could use some testing, but should be ok. There is a little of the code that can be improved.

This provider is picky with the search string, and needs .strip() on the returned title as well or it doesnt work.

**Comment by daveyboy37** [comment]
Hey @miigotu 
I just tried a random show that's still running but has been running a while. Midsomer Murders. 
I searched Season 1 & 2 and didn't get any results.
I'm set for all available qualities using season pack with fallback... Any ideas?

**Comment by miigotu** [comment]
Not sure, will have to test that series myself. Im sure there will be a few kinks to work out with this one, but it is nearly there.

**Comment by daveyboy37** [comment]
No worries. I seem to be struggling with every season pack for any show I have tried. Will keep trying a few more. :-)

**Comment by miigotu** [comment]
did you make sure the season pack is on tvchaos? did you try episode only mode? I only tested episode only so far.

**Comment by daveyboy37** [comment]
Yeah season pack is on TVChaos and i tried episode only.The log shows its searching in both cases.

**Comment by daveyboy37** [comment]
2015-09-17 14:05:02 INFO     SEARCHQUEUE-BACKLOG-73650 :: [TvChaosUK] :: Performing season pack search for Bergerac
2015-09-17 14:04:46 INFO     SEARCHQUEUE-BACKLOG-73650 :: [TvChaosUK] :: Performing episode search for Bergerac
2015-09-17 14:04:46 INFO     SEARCHQUEUE-BACKLOG-73650 :: Beginning backlog search for: [Bergerac]
2015-09-17 14:04:44 INFO     Thread-51 :: Sending backlog for Bergerac season 1 because some eps were set to wanted

Then it moves on to the next provider.

**Comment by miigotu** [comment]
well, with debug on you would see why its skipping results. but don't worry I'll do some testing and improve it.

**Comment by daveyboy37** [comment]
@miigotu 
Yeah I did do that afterwards but to my untrained eye it just seemed like it wasn't seeing it.
Anyways no hurry, I'm sure you have more pressing things.

**Comment by miigotu** [comment]
@daveyboy37 So the problem is with TVChaosUK search engine.

`Midsomer Murders - S17E04` as a search string returns results
`Midsomer Murders S17E04` as a search string returns no results

How stupid is that? Sometimes you need the `-` sometimes not, because some titles have it and others don't.

I will try and figure a clean way around it.

**Comment by miigotu** [comment]
@daveyboy37 for now to get it to work, until I fix it in code, you can add the scene exception like this:
`Midsomer Murders -`
`Midsomer Murders`
image

**Comment by daveyboy37** [comment]
Sorry you really got your work cut out with this one haven't ya.
Its kind of a sad looking tracker and quite amateurish, but for a 50+ year old nostalgia freak who has given up on ever getting BTN its a dream come true. :-) 
Thanks again. I will add the exceptions and see how i get on. .

**Comment by daveyboy37** [comment]
I just wanted to add to this that I have had plenty of hits in my client from TVChaos. 
Although mainly I would use it for packs for older shows if you struggle with season pack search don't sweat it. It ain't that difficult to add the show to S/R and then do a manual search on TVChaos itself add a label to deluge and then let SickRage process it. 
Either way the bounty/donation is yours...Cos i really appreciate all the effort you put in. 
You have a paypal addy to send to ?(as a gift of course)

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/wiki/Donations

I'm still gonna finish making that provider work better, I dont like half working providers =P

**Comment by daveyboy37** [comment]
Haha. As i suspected.

Anyway $70 heading your way.

**Comment by miigotu** [comment]
Hey thanks! It really does help! xD

**Comment by daveyboy37** [comment]
Worth every dollar :-)

**Comment by miigotu** [comment]
@daveyboy37 I cant seem to find a single season result on TVChaos site, can you gimme a title of a season torrent to check for?

**Comment by daveyboy37** [comment]
Apart from Midsomer Murders the other I tried was Bergerac 
I dont really know much about the search protocol used but I don't suppose It's relevant that over this side of the pond we call them series rather than seasons?
I'm probably just talking crap aloud lol.

**Comment by miigotu** [comment]
I mean on the actual site. If I search there I cannot find any season/series packs, only individual episodes. So if they arent on the site, it is impossible for me to create them from thin air to make season pack searching work xD

**Comment by daveyboy37** [comment]
Ok. There's a category at the top dedicated to full series packs.

**Comment by daveyboy37** [comment]
About 80% of the site is dedicated to them

**Comment by daveyboy37** [comment]
Holy cow. I just saw the update.
Installed and hit search randomly for Season 1 of Bergerac.
This was from the log.
2015-09-18 13:25:25 DEBUG    SEARCHQUEUE-BACKLOG-73650 :: [TvChaosUK] :: Unable to parse the filename Bergerac.-.Season.1.(1981).DVDRip.XviD into a valid show
2015-09-18 13:25:25 DEBUG    SEARCHQUEUE-BACKLOG-73650 :: [TvChaosUK] :: Found result: Bergerac.-.Season.1.(1981).DVDRip.XviD (https://tvchaosuk.com/download.php?id=50233)

I tried the whole show and it got a hit on Series 3-9. Awesome stuff. :-)
Season 1 and 2 both give the same error. 
Will try another show and see what happens.

**Comment by miigotu** [comment]
@daveyboy37 in sickbeard/providers/tvchaosuk.py around line 190? find this line:

`title = re.sub(r' \(\d{4}\)$', '', title)`
and remove the $ so it looks like:
`title = re.sub(r' \(\d{4}\)', '', title)`

save and restart SR.

That should fix the `2015-09-18 13:25:25 DEBUG SEARCHQUEUE-BACKLOG-73650 :: [TvChaosUK] :: Unable to parse the filename Bergerac.-.Season.1.(1981).DVDRip.XviD into a valid show`

**Comment by daveyboy37** [comment]
@miigotu 
Yet that did it. :-)
All 9 seasons snatched and I'm pretty stoked. 
I will try a couple more shows over the next few days and let you know I get on. That way you can get on with your life.

**Comment by daveyboy37** [comment]
@miigotu 
It looks like they throw any old crap in the file names. Not a year this time but this 
2015-09-18 14:20:31 DEBUG    SEARCHQUEUE-BACKLOG-76342 :: [TvChaosUK] :: Unable to parse the filename Dad's.Army.-.Season.9..Plus.Xmas.Special..Xvid..avi into a valid show
It tends to happen a lot on TVChaos with Christmas specials for the older shows. 
Is there any alteration I can make SR cope with all that un needed junk lol .

**Comment by daveyboy37** [comment]
@miigotu 
Just wow... I'm at a 26 out of 26 seasons success rate now.
 (Once I remembered to do this again after a reinstall)

 title = re.sub(r' \(\d{4}\)$', '', title)
and remove the $ so it looks like:
title = re.sub(r' \(\d{4}\)', '', title)title = re.sub(r' \(\d{4}\)$', '', title)
and remove the $ so it looks like:
title = re.sub(r' \(\d{4}\)', '', title)

Awesome stuff my friend:-)

**Comment by daveyboy37** [comment]
@miigotu 
There is one thing i just noticed. Doing the above is undone on any SickRage updates.
It needs editing each time afterwards.

**Comment by miigotu** [comment]
@daveyboy37 yes, I need to commit it, along with a few other small tweaks next time I get a chance

**Comment by miigotu** [comment]
81d72f831aa37f92273b9ac1ab28c8ea5c61cdfc

**Comment by daveyboy37** [comment]
Jeez... There wasn't a hurry, but thanks all the same :-)

**Pull request merged**
