### PR TITLE
Remove traceback from showupdater

### PR DESCRIPTION
**Pull request by fernandog**
and add more info to log message
https://github.com/SiCKRAGETV/sickrage-issues/issues/370
@TagForce

### CODE REVIEW

**Comment by fernandog** [comment]
@TagForce so this is wrong? so why SR is trying to update twice the show?

**Comment by fernandog** [comment]
@TagForce  but why SR is trying to update twice the show?

**Comment by TagForce** [comment]
@fernandog I have no idea

**Comment by fernandog** [comment]
@TagForce are you sure that when PP finishes it did'nt start a show-refresh to updated the status and quality of the new processed episode?

**Comment by TagForce** [comment]
@fernandog I do think that it should log the message and go to the next show, though. So your PR is fine except the string

**Comment by fernandog** [comment]
updated

**Pull request merged**
