### PR TITLE
Add Provider TPBT

### PR DESCRIPTION
**Pull request by matigonkas**

### CODE REVIEW

**Comment by matigonkas** [comment]
@fernandog is this PR good, against the latest version?

**Comment by fernandog** [comment]
@matigonkas seems ok

**Comment by abeloin** [comment]
The website is using a revoked ssl certificate: https://www.ssllabs.com/ssltest/analyze.html?d=tpbt.org

**Comment by abeloin** [comment]
@matigonkas Until tpbt.org fix their issue with the certificate this won't be merged.

**Comment by matigonkas** [comment]
@abeloin could you check if its still using a revoked ssl certificate ? 
it has changed domain to https://tpbt.ch/

**Comment by abeloin** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=tpbt.ch

**Comment by matigonkas** [comment]
@abeloin so is it good to be merged now?

**Pull request closed without merging**
