### PR TITLE
Fixes "Snatched (Proper) 1080p WEB-DL" not fitting on a single line

### PR DESCRIPTION
**Pull request by OmgImAlexis**
The reason for the massive amount of additions and deletion is my editor "fixed" the indenting to use 4 spaces instead of the tab character.

### CODE REVIEW

**Comment by fernandog** [comment]
The future column widget in comingEpisodes could prevent this too. Indexer column is useless now. Ep name could be hidden too IMO

**Comment by OmgImAlexis** [comment]
@fernandog some people like those columns, no need to remove them. What do you mean "future column widget in comingEpisodes / displayShow"?

**Comment by fernandog** [comment]
Not remove. But add the button 'select columns' like in the /home page.

**Comment by miigotu** [comment]
@OmgImAlexis let me translate. On ComingEpisodes, there is no column selector.

**Comment by OmgImAlexis** [comment]
Oh.. Yeah we should probably add them.

**Pull request merged**
