### PR TITLE
Change Sync to go by episode not by full show

### PR DESCRIPTION
**Pull request by Thraxis**
Fixed collection sync to only add downloaded / archived episodes to the
Trakt Collection instead of the show which automatically added all
episodes.

### CODE REVIEW

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1066

**Comment by gborri** [comment]
Thanks Thraxis, Do you think it is also possible to remove from collection SKIPPED episode in order to clean the situation?

**Comment by Thraxis** [comment]
Removal is possible yes.  There's both the possibility of "SKIPPED" Although this should probably be an seperate config option as any removal from the collection is a bit... scary.

**Comment by gborri** [comment]
@Thraxis i know is a bit scary. If it is possible let it configurable.

**Comment by Thraxis** [comment]
**Status Update:**

* Bulk Library Sync -> Trakt Collection :: Working using status from Sickrage of Archived, or Downloaded
* Bulk Watchlist Sync (Add) -> Trakt Watchlist 
* Bulk Watchlist Sync (Remove) -> Trakt Watchlist 

**Pending**
* Remove from Collection if file doesn't exist
* Update Sync Collection to verify file exists

**Comment by gborri** [comment]
@Thraxis please fix library, for watch list we need to check a bit more the code.

**Comment by gborri** [comment]
@Thraxis for collection, please make an option for removing file from collection if the media doesn't exist. Personally i don't want to remove episode from collection.

**Comment by Thraxis** [comment]
Not sure what else may be broken with the watchlist sync besides what I have already fixed in this PR.

**Comment by gborri** [comment]
@Thraxis personally i haven't seen the problem you have raised. and i think that is better to manage one thing at a time. personally i ahev to dig more on your change proposal for watchlist.

**Comment by Thraxis** [comment]
@gborri 

```python
    def addEpisodeToTraktWatchList(self):

        if sickbeard.TRAKT_SYNC_WATCHLIST and sickbeard.USE_TRAKT:
            logger.log(u"Start looking if some WANTED episode need to be added to watchlist", logger.DEBUG)

            myDB = db.DBConnection()
            sql_selection='select tv_shows.indexer, showid, show_name, season, episode from tv_episodes,tv_shows where tv_shows.indexer_id = tv_episodes.showid and tv_episodes.status in ('+','.join([str(x) for x in Quality.SNATCHED + Quality.SNATCHED_PROPER + [WANTED]])+')'
            episodes = myDB.select(sql_selection)
            if episodes is not None:
                trakt_data = []
                for cur_episode in episodes:
                    newShow = helpers.findCertainShow(sickbeard.showList, int(cur_episode["showid"])) 
                    if not self.check_watchlist(newShow, cur_episode["season"], cur_episode["episode"]):
                        logger.log(u"Episode: Indexer " + str(cur_episode["indexer"]) + ", indexer_id " + str(cur_episode["showid"])+ ", Title " +  str(cur_episode["show_name"]) + " " + str(cur_episode["season"]) + "x" + str(cur_episode["episode"]) + " should be added to watchlist", logger.DEBUG)
                        trakt_data.append((cur_episode["season"], cur_episode["episode"]))

                if len(trakt_data):
                    data = notifiers.trakt_notifier.trakt_episode_data_generate(trakt_data)
                    notifiers.trakt_notifier.update_watchlist(newShow, data_episode=data)
                    self._getEpisodeWatchlist()

            logger.log(u"Stop looking if some WANTED episode need to be added to watchlist", logger.DEBUG)
```

This one just leapt out at me.  it loops through all the episodes adding them all to the same trakt_data variable.  with no regard to the show they belong to.  After it has done all that collection it checks if there is data, then sends the entire list of episodes as belonging to the last show.  removeEpisodeFromTraktWatchList has basically the same issue.

**Comment by gborri** [comment]
@Thraxis is not true what you are saying. the show is specified in this peace of code:

notifiers.trakt_notifier.update_watchlist(newShow, data_episode=data, update="remove")

while episode and season is specified in:

trakt_data.append((**ep_obj.season**, ep_obj.episode))

the changing from dict to json is managed by this function:

notifiers.trakt_notifier.trakt_episode_data_generate(trakt_data)

**Comment by Thraxis** [comment]
@gborri I ran a test three times to verify my findings.  

Add a logger line like below.  You could probably simplify to show.indexerid or show.show_name if you wanted.

``` python
                if len(trakt_data):
                    data = notifiers.trakt_notifier.trakt_episode_data_generate(trakt_data)
                    logger.log(u"Adding Show: %s  to the watchlist with Season Episode Data: %s", %(str(show),json.dumps(data),logger.DEBUG)
                    notifiers.trakt_notifier.update_watchlist(newShow, data_episode=data)
                    self._getEpisodeWatchlist()
```

After a long list of: 
```
Episode: Indexer xxxxxxxxxxxxxxx should be added to watchlist
```
You will see one line of 
``` 
Adding Show xxxxxxxx to the watchlist with Season Episode Data: xxxxxxxxxxxxxxx
```

**Comment by gborri** [comment]
@Thraxis probably we need to make the logging more clear.... i will look into it.

**Comment by gborri** [comment]
@Thraxis i haven't got you. Your point is a problem of logging or a bug?

**Comment by Thraxis** [comment]
Honestly... It doesn't matter,  I was simply trying to point out the issue I found as a courtesy..   Beating a dead horse that I've already fixed in the code I've submitted in this PR. 

Code that I'll be changing again tomorrow as I've seen a few ways to improve what I have currently.

**Comment by Thraxis** [comment]
This should be final changes for this PR.  The only other real feature I would like to add I'll develop as a feature branch and PR when I'm done.

This code is as best as I can make it right now.  It's not compact, but it is fast and does what it is supposed to do.

On my system from initial start of SickRage to completion of all Trakt sync tasks took just under 2 minutes.

345 shows verified against watchlist, 53 episodes added to watchlist and 9312 episodes synced with the collection.

**Comment by gborri** [comment]
@thraxis I've seen that you have removed code from postprocess procedure, could you please add it again?

**Comment by Thraxis** [comment]
I moved the functionality to the trakt notifier.  It reduces duplicated code,  and keeps the code in distinct modules to make future maintenance easier.

**Comment by gborri** [comment]
@thraxis thanks. I haven't seen it

**Comment by Thraxis** [comment]
@gborri It pretty much boiled down to the four lines of code from line 90-94 in the notifiers/trakt.py:
```python
                if sickbeard.TRAKT_SYNC_WATCHLIST:
                    if sickbeard.TRAKT_REMOVE_SERIESLIST:
                        trakt_api.traktRequest("sync/watchlist/remove", data, method='POST')
                    elif sickbeard.TRAKT_REMOVE_WATCHLIST:
                        trakt_api.traktRequest("sync/watchlist/remove", data_episode, method='POST')
```

I should probably make the elif into an separate if checked in sequence after the TRAKT_REMOVE_SERIESLIST as well as generate the episode items for the ep_obj.relatedEps

I don't really see either change as being a stopper or a must do... as the watchlist and collection sync will fix any issues as it runs.

**Comment by gborri** [comment]
@Thraxis why not this way:

 for cur_ep in [ep_obj] + ep_obj.relatedEps:
     notifiers.trakt_notifier.update_library(ep_obj)

is just a bit slower but should work.

@abeloin why the other notification that have ep as parameter aren't in for cycle?

**Comment by Thraxis** [comment]
I pushed some additional fixes to this PR on my repo today... it doesn't seem to be picking it up here yet.

**Comment by abeloin** [comment]
> @abeloin why the other notification that have ep as parameter aren't in for cycle?

@gborri Sorry, can you explain what you are asking as I wasn't following this thread?

**Comment by Thraxis** [comment]
@abeloin I believe gborri is referring to Multi-Episode files.  When post processed they are sent to the notifiers as one single episode object.  For the trakt notifier in particular this meant that only one episode was being sent / removed from trakt (note that I've fixed this problem in the last set of code check-in's)

**Comment by abeloin** [comment]
@Thraxis Ok, thanks for the explanation.

**Comment by Thraxis** [comment]
I've been running stable with this for the past 3 days.  Along with my daily show downloads I've imported two complete multi-season shows (Lost and Heroes) with no issues.

**Comment by Thraxis** [comment]
Single Commit updated to latest develop branch. 4 days running stable

**Comment by fernandog** [comment]
@Thraxis looks like the sync is running multiple times. Also note the "AANone". Looks like an logger.ERROR without an exception:

```
2015-06-08 07:17:11 DEBUG    Thread-16 :: Remove episodes, showid: indexerid 256111, Title Saving Hope from Watchlist
2015-06-08 07:16:53 DEBUG    Thread-63 :: Remove episodes, showid: indexerid 256111, Title Saving Hope from Watchlist
2015-06-08 07:16:40 DEBUG    Thread-25 :: Remove episodes, showid: indexerid 256111, Title Saving Hope from Watchlist
AANone
2015-06-08 07:16:28 DEBUG    Thread-24 :: Remove episodes, showid: indexerid 256111, Title Saving Hope from Watchlist
2015-06-08 07:15:58 DEBUG    Thread-28 :: Remove episodes, showid: indexerid 256111, Title Saving Hope from Watchlist
AANone
2015-06-08 07:11:08 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: Seeing if we need anything from Saving Hope
```

**Comment by Thraxis** [comment]
It's not part of the Trakt sync code it's in webserve.py setStatus all code gborri wrote back in February.

**Comment by fernandog** [comment]
@gborri

**Comment by gborri** [comment]
@fernandog I've looked at the code but have found nothing that make the log repeted. The only reason i suppose is related to someone that push the go button more then one time.
The log is out of the for loop (for managing episode episode).

**Comment by fernandog** [comment]
@gborri 

I have "Remove series - remove the whole series from your watchlist after any download" selected but SR is adding ALL my tv-shows from SR to the watchlist. All this tv-shows have 90% episodes watched. Only 2-3 are new and IMO only they should be in the watchlist until I download the first episode. 

Isn't that the way it's supposed to work?
thanks

**Comment by gborri** [comment]
@fernandog The "Remove series - remove the whole series from your watchlist after any download" is unusefull because if trakt sync watch list is enabled the addShowToTraktWatchList procedure, every time the traktCheker process will run,will add it again.

**Comment by gborri** [comment]
@fernandog if you want to make it work i think you have to store this information on DB.

**Comment by fernandog** [comment]
@gborri if this setting its not working as described the label should be updated.

**Comment by gborri** [comment]
@fernandog i think that is not warking at all (no change in description could be useful). If I'm not wrong is part of @Thraxis code.

**Comment by Thraxis** [comment]
@fernandog @gborri That function was option was already there when I overhauled the trakt code.  The functionality of it replicated what was there before (TRAKT_REMOVE_SERIESLIST was never checked in traktChecker.py)

As for correcting the behavior, I would think the simplest solution would be to (if that option is enabled) to pull a list of all series that have an episode with a "Downloaded" status and block re-adding those shows to the watchlist.

**Comment by gborri** [comment]
@Thraxis for me is fine.

**Comment by fernandog** [comment]
@Thraxis do you mean remove, not adding, isn't?

**Comment by Thraxis** [comment]
@fernandog It actually falls under both

When an episode for is downloaded the trakt Notifier code checks if the remove from watchlist for series and / or episode variables are enabled and sends the "Remove from watchlist" if it is.

Unfortunately the traktChecker code re-adds all shows in your library to the Series Watchlist as well as adding wanted episodes to the Episode watchlist.

So I'll add the code to remove / block series with an episode that has a downloaded status from traktChecker re-adding to the series watchlist, and I'll also dig in to add in the option to remove from the watchlist when a show is deleted.

**Comment by fernandog** [comment]
@thraxis thanks!

**Comment by fernandog** [comment]
@thraxis what if trakt is down. SR will only ask once to remove? Or it will keep trying to remove?

**Comment by Thraxis** [comment]
@fernandog I might have to add an hidden config variable to hold shows to delete to keep telling trakt until it succeeds..

**Comment by fernandog** [comment]
@Thraxis or everytime download watchlist and everytime check/compare all shows/episodes against SR.

**Comment by Thraxis** [comment]
@fernandog The problem is that the primary function of the Trakt watchlist sync was for trakt to add a show to SR if it was in the watchlist.  

I've got a few ideas kicking around on how to handle this, hopefully without having to re-structure all of the traktChecker, trakt notfiication, etc. code

**Pull request merged**
