### PR TITLE
Mako version of imdb_popular feature

### PR DESCRIPTION
**Pull request by jonathanendersby**
Mako version with a few tweaks:

* Years are no longer hardcoded.
* Fetching bigger images from IMDB/Amazon.
* Small style changes.

### CODE REVIEW

**Comment by jonathanendersby** [comment]
Preview:

image

**Comment by WebSpider** [comment]
Hi, and thanks for your redo on mako of this feature!

It is still lacking the configurability we want from features, so I'll check out your branch, and send You a pullreq, so we at least have the ability to turn the feature on and off in config.ini.

Expect it somewhere this week.
Once that is added to the feature, i'll merge it into develop.

Thanks again for making SR more awesome!

-----Original Message-----

**Comment by jonathanendersby** [comment]
@WebSpider Thanks you.

**Comment by duramato** [comment]
How many  items does this show on the add popular shows page? Is this option configurable ? (If not can it be?) Also the "view on imdb" and "add show" probably would look better as bottons
Just  my thoughts and opinions

**Comment by jonathanendersby** [comment]
@duramato It shows 50 (which is the first page of results). Feel free to add configuration options. I feel that 50 is a good number.

I disagree re buttons. They're both links. Obviously the imdb one links to the IMDB page, and the "Add Show" links to "Add Show" page with the show name pre-filled into the search box.

**Comment by WebSpider** [comment]
@jonathanendersby added PR to your repo,https://github.com/jonathanendersby/SickRage/pull/4

**Comment by jonathanendersby** [comment]
@WebSpider  thanks, merged.

**Comment by fernandog** [comment]
need squash into 1 commit

**Comment by WebSpider** [comment]
Unfortunately, I cant do this for @jonathanendersby :)

**Comment by miigotu** [comment]
Actually we can xD

```bash
git checkout develop
git pull
git checkout -b jonathanendersby-imdb_popular_mako develop
git pull https://github.com/jonathanendersby/SickRage.git imdb_popular_mako
git rebase -i develop
git checkout develop
git merge --no-ff jonathanendersby-imdb_popular_mako
git push upstream develop
```

**Comment by jonathanendersby** [comment]
@WebSpider @miigotu Do you want me to do something? I've never squashed, but I'm sure I can figure it out.

**Comment by WebSpider** [comment]
I dont have commit perms on SickRage, as it turns out :)

**Comment by miigotu** [comment]
Done manually, with rebase to https://github.com/SiCKRAGETV/SickRage/commit/9e4a29f3a4e61f22c4ec81737996b2a4cc39d0ab

**Pull request closed without merging**
