### PR TITLE
home filter: change to allow to use parsed data for active(yes/no)

### PR DESCRIPTION
**Pull request by abeloin**
See  https://github.com/SiCKRAGETV/SickRage/pull/1724

### CODE REVIEW

**Comment by abeloin** [comment]
@fernandog

**Comment by Thraxis** [comment]
May want to add Network in there as well, it's not working for filtering either

**Comment by abeloin** [comment]
@Thraxis Network works fine here. The one not working is Downloads, but I don't know how we should handle filtering for that column

**Comment by Thraxis** [comment]
@abeloin Odd.. wasn't working when I tested a minute ago.

The Downloads progress bar filtering is actually done by percentage.  ">20"  "<50" "100" all should work for filtering it

**Comment by abeloin** [comment]
@Thraxis Thanks, I forgot about < > sign, no wonder it wasn't working.

**Comment by Thraxis** [comment]
Ahh... clarification on the Network Filtering...  when you are in Simple Mode the filtering works, When you are in banner mode it does not.

**Comment by fernandog** [comment]
@abeloin thanks!

Downloads: 100 does not work. But >99 do.
Am I doing something wrong?

**Pull request merged**
