### PR TITLE
Crop support image

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/2279

### CODE REVIEW

**Comment by duramato** [comment]
i belive this would be better it where changed to something like "Donate" ,as just support might be missleading

**Comment by fernandog** [comment]
@duramato was checking if fixes user's issue

**Comment by fernandog** [comment]
@duramato new image suggestion?

**Comment by duramato** [comment]
@fernandog maybe something like the paypal donate botton ,i will try tinker and see if i come with something pleasing to the eye

**Comment by fernandog** [comment]
and small ! =)

**Comment by duramato** [comment]
@fernandog  maybe something like this ? i choose red as its a color that suits blue and white for both themes
(dimensions arent right yet)


donate

**Pull request merged**
