### PR TITLE
Add FrenchTorrentDB and Libertalia providers

### PR DESCRIPTION
**Pull request by adaur**
French private trackers

### CODE REVIEW

**Comment by maxcore** [comment]
Work great

**Comment by miigotu** [comment]
I was following you writing this, and at first glance it all looks good except one thing.

It needs to use requests instead of urllib2. This provides automatic session management and cookie handling as well as ssl verifications and SNI (when possible)

**Comment by miigotu** [comment]
I'm going to mark it DNM until we can work through that.

**Comment by maxcore** [comment]
@adaur @raver2046  you can do this ?

**Comment by miigotu** [comment]
Matter of fact, I will be rewriting every provider to follow a standard format soon, so I need these to reference. No such a big deal that they use urllib2 for now.

**Comment by adaur** [comment]
Thanks for the merge! I can rewrite those if need be.

**Comment by miigotu** [comment]
@adaur If you want to make the changes to make them use self.getURL and requests then go ahead and PR. 

After I make the basic template for the new providers, you could also help there if you'd like. They will be designed to be movie/music/season/episode ready.

**Comment by adaur** [comment]
Why not! I'll try to do this :)

I remember that I wanted to use getURL instead of self.opener but I couldn't use it within _doLogin since getURL checks if we are logged or not.

**Pull request merged**
