### PR TITLE
Fix to issue 1460

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/1460

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu do you think it's ok?

**Comment by miigotu** [comment]
That fixes the value error, but masks the real problem I think @fernandog. Plus, it would display the airdate as 01/01/0001 then. And that would be not only confusing but mess up sorting and 'coming episodes' page.

**Comment by fernandog** [comment]
@miigotu this issue is odd. sometimes works, sometimes not. I guess it's related to XEM connectivity issues.

**Comment by miigotu** [comment]
@fernandog Maybe when air date is not provided by tvdb/tvrage, because they dont have the info?

**Comment by fernandog** [comment]
@miigotu the actual code is wrong. s_default=0 will ALWAYS fail

**Comment by miigotu** [comment]
@fernandog It is intended to fail, because we want to be sure that an incorrect date is not added to the db right? If we let it default to 1, then we will never get an error telling us that the date is failing to be populated somewhere else in the code.

**Comment by fernandog** [comment]
@miigotu the problem is the page won't load at all and user won't know what's happening. Log only show traceback without any show info or message. any other solution?

**Comment by fernandog** [comment]
@miigotu also the indexer has correct airdate. So it's not a problem there. Maybe It's a connectivity issue as I said above and SR couldn't fetch the data

**Comment by miigotu** [comment]
@fernandog I think we should find where the date is not being set correctly, and provide an alternative way of getting it. iirc this was only happening when xem was down?

**Comment by fernandog** [comment]
@miigotu I didn't had this issue anymore. Can't debug it anymore

**Comment by miigotu** [comment]
@fernandog maybe we should just close this for now until if/when the issue resurfaces? We can always re-open and rebase this.

**Comment by fernandog** [comment]
@miigotu if this default=0 wil ALWAYS raise an error why set it ?

"def tryInt(s, s_default=0)"

**Comment by miigotu** [comment]
Because it is left there to catch us passing invalid values there by accident. If a -1 gets to here we have a problem somewhere else and we want to know about it instead of workaround it and allow a more complex problem to develop down the road.

**Comment by miigotu** [comment]
Changing this just masks the real problem in SiCKRAGETV/sickrage-issues#1460

**Pull request closed without merging**
