### PR TITLE
Make removed episodes status configurable

### PR DESCRIPTION
**Pull request by gborri**
- [x] enabled SKIP_REMOVED check

### CODE REVIEW

**Comment by fernandog** [comment]
Show this option only if user didnt enabled SKIP_REMOVED

**Comment by gborri** [comment]
Ok.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1032

**Comment by gborri** [comment]
@fernandog the check should be done against SKIP_REMOVED and also against TRAKT_USE_ROLLING_DOWNLOAD. 
EP_DEFAULT_DELETED_STATUS is also used for changing status of watched episode.

**Comment by fernandog** [comment]
@gborri no because the original code dont check that. Of check skip first and then rolling. Dont check both in the same if

**Comment by gborri** [comment]
@fernandog why not checking on the same if?

**Comment by fernandog** [comment]
@gborri I have skip_removed ON and USE_ROLLING_DOWNLOAD OFF

with a single if , the option will appear to me, but it shouldn't

**Comment by gborri** [comment]
you need to use the "or": skip_removed ON or USE_ROLLING_DOWNLOAD 
this way it works.

**Comment by abeloin** [comment]
@gborri squash your commits into one with a rebase, and I'll mere the PR

**Comment by gborri** [comment]
@abeloin I'm feeling crazy..... everytime i rebase or merge i get inside the LFCTRL problem.

**Comment by abeloin** [comment]
@gborri New PR should be ok. PR merged

**Pull request merged**
