### PR TITLE
Choose default language

### PR DESCRIPTION
**Pull request by gborri**
Added in General config the parameter Default Info Language
define sickbeard.DEFAULT_LANGUAGE and used instead of 'en'

### CODE REVIEW

**Comment by gborri** [comment]
@abeloin i probably have problem on my fork

**Comment by gborri** [comment]
@abeloin i have only merged once develop branch from SickRage in orther to have sync with the repo.
could be this the problem? how can i clean my fork? i'm a newby with git

**Comment by abeloin** [comment]
@gborri Have tried the way from my previous comment: https://github.com/SiCKRAGETV/SickRage/pull/1362#issuecomment-75150101 ?

**Comment by gborri** [comment]
@abeloin not yet. I think that the result will be the same. is it possible that i have to rebase my fork?

**Comment by gborri** [comment]
@abeloin i have tried at least 5 times to make manually the change to the new brench created, but always on push appear unwanted commit. can you help me? thaks

**Comment by abeloin** [comment]
Can you explain tstep by step, what you did?

**Comment by fernandog** [comment]
@gborri I had that. My solution as delete my fork and fork it again. I could not clean it because there were merged commits different from original fork.

**Comment by gborri** [comment]
@abeloin i think that the problem is that i have merged with sickragetv fork and then commited it.
now every time i will commit a canhe to make pull request i find commit vandalon.
@fernandog if i drop the fork i think that i will loos the pull request not yet merged

**Comment by fernandog** [comment]
@gborri you can't commit directly to develop. you must always create a branch and them commit! I just learned that =)
develop can't have your commits, only commits from original fork.

**Comment by gborri** [comment]
@fernandog i have learned too. :-)
but how can i have in sync my fork with the sickragetv?

**Comment by fernandog** [comment]
no ideia. you have to undo all your commits (don't know how) OR save that commits, delete fork and fork again

**Comment by skarekrow** [comment]
I've done this method to update my forks before : 
http://www.hpique.com/2013/09/updating-a-fork-directly-from-github . Not 
sure if there's a better method from the web ui, but obviously using git 
on the cli would give you more flexibility.

**Comment by fernandog** [comment]
@skarekrow  "If your fork didn’t have any changes, you will be able to merge it automatically." - I think this is the main problem

**Comment by skarekrow** [comment]
@fernandog You are completely correct. That's my bad. I'm not sure how to do it on the web interface unfortunately.

**Comment by gborri** [comment]
ad thiswhat do you think about this?

git reset --hard {commithash}

**Comment by abeloin** [comment]
@gborri Have tried the instructions from [my previous comment](https://github.com/SiCKRAGETV/SickRage/pull/1362#issuecomment-75150101)?

From my comment: this create branch using sickrage/develop as a reference instead of your fork
* ```git checkout -b clean-develop upstream/develop```

**Comment by gborri** [comment]
@abeloin yes i'gve tied, but the patch gave error. then i tried to start clean and then make changes manually, but it wan't work.

**Comment by abeloin** [comment]
@gborri It is normal for the patch to have some failed hunk as both branch doesn't match exactly. You have to manually resolve the failed hunk then commit the changes.

**Comment by gborri** [comment]
@abeloin it doesen't work. This is the error:

git checkout -b clean-develop sickrage/develop
fatal: Cannot update paths and switch to branch 'clean-develop' at the same time.
Did you intend to checkout 'sickrage/develop' which can not be resolved as commit?

git remote -v
origin  https://github.com/gborri/SickRage.git (fetch)
origin  https://github.com/gborri/SickRage.git (push)
sickrage        https://github.com/SiCKRAGETV/SickRage.git (fetch)
sickrage        https://github.com/SiCKRAGETV/SickRage.git (push)

**Comment by gborri** [comment]
@fernandog @abeloin if i delete the fork, what happen to the open pull request?

**Comment by fernandog** [comment]
don't know. but you can take your PR and save it like this
https://github.com/SiCKRAGETV/SickRage/pull/1365.patch

then you apply the patch to a new fork with a new branch for this.

**Comment by gborri** [comment]
@fernandog @abeloin i got it.
used git reset --hard

**Comment by abeloin** [comment]
> fatal: Cannot update paths and switch to branch 'clean-develop' at the same time.
> Did you intend to checkout 'sickrage/develop' which can not be resolved as commit?

You need to fetch the new changes from the remote sickrage first:
```git fetch sickrage```

**Comment by abeloin** [comment]
@gborri Pull request are stored in SiCKRAGETV not on your fork.

**Comment by abeloin** [comment]
Any of you update their fork sometime? As those are the commands used to maintain a fork updated.

**Comment by gborri** [comment]
@abeloin i haven't undestood your last comment.
after git reset seems to work i have make a test:
checkout a new branch 
fetched 
merged
modified it 
committed
pushed the branch 
the pull request seems to be clean

**Comment by abeloin** [comment]
@gborri Good

What I was saying is to maintain a fork you usually use those command. Example: to update a fork with data from upstream:
* ```git remote add upstream https://github.com/SiCKRAGETV/SickRage.git``` (First time only)
* ```git fetch upstream``` (Pull new data from the upstream branch)
* ```git checkout develop```
* ```git rebase upstream/develop``` (Pull the commit from upstrem/develop to develop)
* ```git push origin develop``` (Push to your github fork)

Now your fork is updated with the changes from upstream

**Comment by gborri** [comment]
Thanks.
Now i have understood what to do.

Giovanni
Il 21/feb/2015 04:38 "Alexandre Beloin" <notifications@github.com> ha
scritto:

**Pull request closed without merging**
