### PR TITLE
Some cleanup

### PR DESCRIPTION
**Pull request by miigotu**

### CODE REVIEW

**Comment by fernandog** [comment]
Minor issue. Missed dot in some lines: %s Error:

%s. Error:

**Comment by miigotu** [comment]
Because if we add a . after a url or path it is hard to see if the path has a . at the end or not when it is failing.

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/2182#issuecomment-124289739.
/opt/SickRage/data/somefile.

**Comment by miigotu** [comment]
Still a lot of work needs done for log lines, they should all be done the same way. This is just a start

**Pull request merged**
