### PR TITLE
Optimize SQL SELECT statements

### PR DESCRIPTION
**Pull request by WebSpider**
Changes SQL SELECT statements to be more specific, and less resource hungry

### CODE REVIEW

**Comment by WebSpider** [comment]
Squashed!

**Comment by fernandog** [comment]
ow! huge PR. did you use any tool to do that or manually??

**Comment by WebSpider** [comment]
It's manual .... But a good IDE helps

**Comment by miigotu** [comment]
@WebSpider Ive reviewed the entire PR (I hate to review so many files in 1 PR but thats a diff conv.)

Everything looks good except the 4 comments I made.

**Comment by WebSpider** [comment]
I'll look at the comments and amend tonight, thanks for the review!

I need to see what you mean with the 3 threads interacting, that wasn't clear to me from looking at the code.

-----Original Message-----

**Comment by miigotu** [comment]
the db test splits off 4 threads and performs the same query with each one. if the query is too fast they don't have as much of a chance to overlap.

**Comment by WebSpider** [comment]
Ah. I never gave testing much attention, tbh. Will update this PR this weekend.

**Pull request closed without merging**
