### PR TITLE
Remove old clients files

### PR DESCRIPTION
**Pull request by fernandog**
@miigotu

### CODE REVIEW

**Comment by fernandog** [comment]
@neoatomic i think this don't work in NAS. Some users reported having the last update but error persists

can you please:
stop SR
create a file called /SickRage/sickbeard/clients/rtorrent.py
create a file called /SickRage/sickbeard/clients/rtorrent.pyc
start SR
make sure that file was deleted

**Comment by neoatomic** [comment]
@fernandog I dont use torrents so i hadn't any *.pyc in the folder. Except for generic.py.
So i removed those 2 files with empty dummy's. But after the restart they where still present. (and still empty.)

**Comment by fernandog** [comment]
So this code does not work for NAS...

**Comment by miigotu** [comment]
generic.py(c) is supposed to be there.

**Comment by miigotu** [comment]
Check my commits just after, I had to hotfix very quickly.

**Comment by fernandog** [comment]
@miigotu still nas users are reporting the same error. The don't work on NAS
@neoatomic confirmed.

**Pull request merged**
