### PR TITLE
ThorsLand

### PR DESCRIPTION
**Pull request by danyboy666**
ThorsLand RSS provider is based on Robert Massa's tvtorrents.py plugin.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [ ] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by miigotu** [comment]
a.) this doesnt even work.
b.) it is submitted to master.

**Comment by danyboy666** [comment]
It did work with sb. 
I'll test and re-submit properly indev branch

**Comment by miigotu** [comment]
Just because something works with SB, does not mean it works directly with SR.

Our code base is nearly unrecognizable compared to SB.

**Comment by danyboy666** [comment]
I'll check it out thanks for the input.

**Comment by danyboy666** [comment]
Since this is a plugin only it's not really that deffren from what SB uses from what i just saw. I've checked torrentleech plugins and it's identical as the one provided  with SB. Anywais i'll test it.

**Comment by miigotu** [comment]
1.) It isnt a plugin.
2.) There are multiple undefined variables in that code.
3.) Do not submit PR that you have not even made an attempt to run at least once.

**Comment by maxcore** [comment]
@danyboy666 
Why you dont use the custom rss ? thorlands work like a charm ;)

**Comment by danyboy666** [comment]
Hey maxcore i did'nt know you were on github also ;)
Anywais that's i've just finished configured since i don't care spending time on python anywais. I'll see how it goes. That "not plugin" i had submitted was based on rss search anywais. I did a test actually to manually search something but i guess i wasn't lucky. It didn't return anything.. I'm going to see how the backlog goes tonight.

**Comment by maxcore** [comment]
@danyboy666 long time no see ! ;)
i dont know why thorland have not a api . The captcha login break the developper to make a real plug in for sickrage.

**Comment by danyboy666** [comment]
Yeah now that i think of it that was the reason i hacked one based on rss to the you the truth. But i don't even think they care about about SR, SB and so on just seing how some people intentionaly messes up their release name without admins caring about it. When i see something like SXXEXX EXXX 20150101 as a title it makes me cringe all over lol.

**Comment by maxcore** [comment]
yep i know but work 99% of the time with all qc show, and  sickrage take from thorlands from the RSS. You can custom the name in the config ! I can't life without Sickrage ;)

**Comment by danyboy666** [comment]
Yeah so much better than the old sickbeard. They certainly did a great job with it.

**Pull request closed without merging**
