### PR TITLE
Missed imports, fixup conditions

### PR DESCRIPTION
**Pull request by miigotu**

### CODE REVIEW

**Comment by MGaetan89** [comment]
So if the user did not configure a username/password, he can not see this?

**Comment by WebSpider** [comment]
I was also wondering about this ... Why the sblogin?

-----Original Message-----

**Comment by miigotu** [comment]
sblogin is True if you have no login configured. Its included so that it is not visible when not logged in.

**Comment by miigotu** [comment]
It is sort of redundant, I missed this:
https://github.com/SiCKRAGETV/SickRage/pull/2445/files#diff-7a62d0eb6a8e5fb4f863e112ea1920b7R216

**Pull request merged**
