### PR TITLE
Missing Network Icons

### PR DESCRIPTION
**Pull request by Peke**
Created Movie Network, XBOX Live and TNT Drama channel icons

### CODE REVIEW

**Comment by fernandog** [comment]
@neoatomic why this can't be merged?

**Comment by neoatomic** [comment]
@fernandog , No. Movie Network logo is 48x32. SR standard is 64x32.

**Comment by Peke** [comment]
Oups, I'll correct this ASAP

**Comment by Peke** [comment]
Done, sorry for that.

**Comment by neoatomic** [comment]
No problem, glad you are able to contribute. :)

**Comment by fernandog** [comment]
still can't merge

"We can’t automatically merge this pull request."

**Comment by neoatomic** [comment]
@fernandog Found the problem, @Peke was using an outdated fork of SR on GitHub.There was already a tnt drama.png logo that i created after Feb. So thats why it didnt let you Merge the PR.
I resubmitted them, should work now.

**Pull request closed without merging**
