### PR TITLE
178.73.198.210 torrent caching website

### PR DESCRIPTION
**Pull request by duramato**
a torrent caching website running the torrage os project afaik, to fill the void of zoink.ch

### CODE REVIEW

**Comment by miigotu** [comment]
Have no clue who is running that.
Not sure if I feel safe adding a site that isn't used by any trackers themselves.

**Comment by neoatomic** [comment]
This looks to be another alternative/option.? http://thetorrent.org/

**Comment by miigotu** [comment]
@neoatomic we can try to use some of those, thanks. I did add btcache.me but it was failing and I forget why so I removed it.

**Comment by fernandog** [comment]
btcache was giving code 200 when it was not 200. remember we talked about?

go sleep! =)

**Comment by duramato** [comment]
and what about itorrents.org ,why was it removed?

**Comment by miigotu** [comment]
Thetorrent and btdig were added.

**Pull request closed without merging**
