### PR TITLE
Fixes SiCKRAGETV/sickrage-issues/issues/3007

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Still needs to be tested but I think this is correct, @miigotu can you confirm?

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by miigotu** [comment]
Exactly how I envisioned it to work. Lets see if we are right.

**Comment by OmgImAlexis** [comment]
Well I don't think it'll cause any harm if we're wrong as it still works fine for x64. Worse comes to worse we just revert and work out another way.

**Comment by miigotu** [comment]
My thought process exactly =P

**Pull request merged**
