### PR TITLE
Add more history page limits

### PR DESCRIPTION
**Pull request by duramato**

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by MGaetan89** [comment]
Instead of adding new options every time, why not use an input with its type set to `number`?

**Comment by OmgImAlexis** [comment]
This probably isn't a good idea since this may crash SR for users with Raspberry Pis and honestly shouldn't be needed. If you need more logs with using less in cli or change the number in the address bar. @fernandog @miigotu please close.

**Comment by fernandog** [comment]
@OmgImAlexis I tested 'all' in my rpi and not an issue. runned fast (like 20s). As it's an option we can accept.

@miigotu ?

**Comment by duramato** [comment]
@OmgImAlexis if it can crash ,then they shouldnt use
same goes for the ALL setting

**Comment by OmgImAlexis** [comment]
I guess as long as it's not going to crash any low powered devices and like in that case like @MGaetan89 said we should have an input box instead.

**Comment by miigotu** [comment]
I think it should be a hard set limit and have buttons to switch pages like 0-100, 100-200, etc.
But thats just me.

**Comment by OmgImAlexis** [comment]
@miigotu we could add that to the bottom of the page, like left and right arrow.


<-- 100                              300 -->

**Comment by duramato** [comment]
@OmgImAlexis i think that would be good as an addition to the way it is now

**Comment by fernandog** [comment]
I like low value: 10 and 25
I dont mind really old history

**Comment by miigotu** [comment]
@OmgImAlexis thats what I was thinking exactly, but probably at the top of the logs too.

**Pull request merged**
