### PR TITLE
Add size to SCC

### PR DESCRIPTION
**Pull request by ROpdebee**
@fernandog size added to SCC provider

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
Thanks!!

**Comment by fernandog** [comment]
@miigotu _convertSize is not something to 
generic?

**Comment by miigotu** [comment]
Nope, not all providers need their size converted, and those who do there are multiple different ways it needs to be split and converted (100KB vs 100KiB vs 100 KB) etc.

**Comment by fernandog** [comment]
ok. thanks

**Pull request merged**
