### PR TITLE
12 feb

### PR DESCRIPTION
**Pull request by bckwltn**

### CODE REVIEW

**Comment by fernandog** [comment]
@bckwltn please close this PR. you can't PR to master

**Comment by fernandog** [comment]
@djack42 is menu bar still broken for you?

**Comment by djack42** [comment]
Yes, the bootstrap has been overwritten again a while back. But my tablet should be able to display it entirely, i have 1200px wide and the menu can't display one one line because of the minimum density in chrome for android. Overriding the minimum density could be a better solution than collapsing the menu...
Or replacing some text menu by a picture like configuration

**Comment by fernandog** [comment]
@djack42 how to fix it? I couldn't identify what changed on this commit. There's A LOT of commits

**Pull request closed without merging**
