### PR TITLE
Add note that SickRage should be updated before submitting errors

### PR DESCRIPTION
**Pull request by miigotu**

### CODE REVIEW

**Comment by MGaetan89** [comment]
Maybe explain how to turn on debug?

**Comment by miigotu** [comment]
@MGaetan89 I think that's getting a little too detailed in a popup, not sure. Know how to add a small tooltip icon with that info in js? lol

**Comment by MGaetan89** [comment]
You're right. Forgot it was a popup :p
What about a link on `debug` that redirects too `/config/general/` in the proper tab? It may need a bit extra work to open the correct tab...

**Comment by miigotu** [comment]
You wanna try that? I can just merge this and you can improve it. I wasn't planning on doing anything that required much thinking this early in the day haha.

**Comment by MGaetan89** [comment]
This early? You mean this late, right? It's a matter of perspective :p
Yeah I can try to do something about that.

**Pull request merged**
