### PR TITLE
Fix for 'module' object has no attribute 'change_TRAKT_USE_ROLLING_DOWNLOAD'

### PR DESCRIPTION
**Pull request by gborri**

### CODE REVIEW

**Comment by abeloin** [comment]
@gborri The function exist in config.py: https://github.com/gborri/SickRage/blob/patch_no-attribute/sickbeard/config.py#L254

**Comment by gborri** [comment]
@abeloin why the exception arise?

On Fri, Apr 10, 2015 at 11:22 AM, Alexandre Beloin <notifications@github.com

**Comment by abeloin** [comment]
@gborri Provide the trace stack or debug log, without it I can only guess...

**Comment by gborri** [comment]
@abeloin forgot about it. the problem was on my fork... i don't know why.

On Fri, Apr 10, 2015 at 12:36 PM, Alexandre Beloin <notifications@github.com

**Comment by abeloin** [comment]
ok, glad it resolved

**Pull request closed without merging**
