### PR TITLE
Added missing россия 1 network logo.

### PR DESCRIPTION
**Pull request by neoatomic**
Added missing россия 1 network logo.

https://github.com/SiCKRAGETV/sickrage-issues/issues/744

### CODE REVIEW

**Comment by abeloin** [comment]
This merge need more testing. Last time the é from télé-québec caused some issue on certain systems.

Ref: https://github.com/SiCKRAGETV/SickRage/pull/1153

**Comment by fernandog** [comment]
@neoatomic uses POSIX am I right? Can you try this in windows?

**Comment by neoatomic** [comment]
I created the logo for testing, thought it could came in handy.

A show with this network : Master i Margarita
Network exact network name : Россия 1

Indeed the Synology uses POSIX. Just got time to test it on my Syno and it doesn't work...

**Comment by neoatomic** [comment]
@abeloin I have submitted the new network logos.
But as they are added to this PR is it possible to merge only them and not the  Россия 1 logo.? or do i need to revert the Россия 1 commit.?

**Comment by abeloin** [comment]
Please submit a new PR, it will be cleaner that way.

**Pull request closed without merging**
