### PR TITLE
Update trakt error checking

### PR DESCRIPTION
**Pull request by fernandog**
The goal is not to show any tracebacks

### CODE REVIEW

**Comment by abeloin** [comment]
You shouldn't do that this way. Catch the raise error instead.

**Comment by fernandog** [comment]
How?

**Comment by abeloin** [comment]
From were the trakt function is call in the code

**Comment by abeloin** [comment]
Example:
try:
    trakt = TraktAPI()
except traktException as e:
    logger.log('I've catched an error and won't show a traceback', log.INFO)

**Comment by abeloin** [comment]
If it's related to https://github.com/SiCKRAGETV/sickrage-issues/issues/669 then change the exception in https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/traktChecker.py#L56 to:
```
except Exception as e:
    logger.log('Trakt: Error Syncing library: {0}'.format(str(e)), logger.DEBUG)
```

**Pull request closed without merging**
