### PR TITLE
Add NZBClub provider

### PR DESCRIPTION
**Pull request by duramato**
Made use of NZBIndex as a template ,since the website rss has some problems
@miigotu

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
@duramato missing. Keep commented until add seeders/leechers parsing

```
                            #Filter unseeded torrent
                            #if seeders < self.minseed or leechers < self.minleech:
                                #if mode != 'RSS':
                                    #logger.log(u"Discarding torrent because it doesn't meet the minimum seeders or leechers: {0} (S:{1} L:{2})".format(title, seeders, leechers), logger.DEBUG)
                                #continue
```

**Comment by duramato** [comment]
@fernandog this is a NZB provider it doesnt even have seeders leechers ,why does it need that?

**Comment by fernandog** [comment]
LOL. Sorry about that

**Pull request closed without merging**
