### PR TITLE
Fix SiCKRAGETV/sickrage-issues/issues/3347

### PR DESCRIPTION
**Pull request by ncksol**
HD-Torrents has some invalid html on the page with search results. Using
the default html parser wasn't returning the correct data. Substituted
it with html5 parser to fix the problem.

P.S. I've also created another PR with a different fix to that issue. Not sure which one would you prefere.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
this does not work for me:

```
2015-10-17 17:54:46 ERROR    SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Could not find table of torrents mainblockcontenttt
2015-10-17 17:54:42 DEBUG    SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Search string: Modern Family S07E04
2015-10-17 17:54:42 DEBUG    SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Search URL: https://hd-torrents.org/torrents.php?search=Modern+Family+S07E04&active=1&options=0&category[]=59&category[]=60&category[]=30&category[]=38
2015-10-17 17:54:42 DEBUG    SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Search Mode: Episode
2015-10-17 17:54:42 INFO     SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Performing episode search for Modern Family
AANone
2015-10-17 17:54:42 ERROR    SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Could not find table of torrents mainblockcontenttt
2015-10-17 17:54:32 DEBUG    SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Search URL: https://hd-torrents.org/torrents.php?search=&active=1&options=0&category[]=59&category[]=60&category[]=30&category[]=38
```

**Comment by ncksol** [comment]
Turns out simply upgrading soup to v4 fixed the problem. No need for html5 parser. I've just tested this pr on my server it has found the episodes that were missing.

**Comment by fernandog** [comment]
@ncksol 

still does not work to me:

```
2015-10-17 18:52:44 INFO     SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Unable to find a download for: [Modern Family - 7x04 - She Crazy]
2015-10-17 18:52:44 ERROR    SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Could not find table of torrents mainblockcontenttt
2015-10-17 18:52:40 INFO     SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Performing episode search for Modern Family
AANone
2015-10-17 18:52:40 ERROR    SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Could not find table of torrents mainblockcontenttt
```

**Comment by fernandog** [comment]
@ncksol 

here is my html:

```
                data = self.getURL(searchURL)
                g = open('hdt.html', 'w')
                g.write(str(data))
                g.close()
```

https://gist.github.com/fernandog/e11a882d060ebcbc237e

**Comment by ncksol** [comment]
Yeah, I can recreate the issue from your html. Somehow it's different from the one I am getting served. I am completely buffled atm as to why the parser cannot find the data. This applies to both of my approaches. None of them work now.
I will need to try this again with a fresh head tomorrow.

**Comment by fernandog** [comment]
NP! This issue is bugging me for quite a while! 
Thanks!

**Comment by miigotu** [comment]
@ncksol Yeah I had the same problem. It works fine for me but not fernandog and duramato -.-

I know sort of what is wrong, its the broken html in each item for the date ie `<bWed, 22, Whatever>`

**Comment by ncksol** [comment]
Ok. So I've started to play with html that fernandog gets served and found out that if I just take the portion that containts the search result data then parser is fine. I decided to cut out anything before the table and it seem to work now. Both on html fernandog gave and the one I am getting served.

**Comment by fernandog** [comment]
@ncksol Awesome! It's working!!

[HDTorrents] :: Discarding torrent because it doesn't meet the minimum seeders or leechers: Modern.Family.S07E04.720p.HDTV.x264-FLEET (**S:0** L:0)
[HDTorrents] :: Discarding torrent because it doesn't meet the minimum seeders or leechers: Modern.Family.S07E04.INTERNAL.720p.HDTV.x264-BATV (**S:0** L:0)

But seeds are wrong:
image

**Comment by fernandog** [comment]
Size is working: `[HDTorrents] :: Size found is: 699148533.76`

**Comment by fernandog** [comment]
@ncksol can you check what's wrong this this? 

https://gist.github.com/fernandog/9f4c3c2417bbc776bd69

No results are all, when 5minutes ago I got results

**Comment by fernandog** [comment]
I found out that there's no cells in the page

```
                        if not cells:
                            logger.log(u"No cells in page", logger.ERROR)
                            continue
```

[HDTorrents] :: No cells in page

**Comment by ncksol** [comment]
@fernandog got the fix for seeders. 
I believe the size was actually reported like that originally. I've not changed any of that code. It specifically takes the data from size cell, then determines whether it's kb/mb/gb/tb and converts it all to bytes.

**Comment by ncksol** [comment]
As for the cells not found, I can't seem to be able to recreate this even with your html. If I feed it to my code and just comes back with valid:
Found result: Modern.Family.S07E04.INTERNAL.720p.HDTV.x264-BATV 
Found result: Modern.Family.S07E04.720p.HDTV.x264-FLEET

**Comment by fernandog** [comment]
NP! What about seed/feed returning 0? Do you know whats wrong?

**Comment by fernandog** [comment]
Ah! that's right. Sorry!

@miigotu any comments on the PR?

**Comment by fernandog** [comment]
@ncksol can you squash into one commit please?

**Comment by ncksol** [comment]
@fernandog unfortunately I have no idea how to do that =D
literally never used git before.

**Comment by fernandog** [comment]
You are using only git web?

**Comment by ncksol** [comment]
No. I have github for windows. But it's pretty basic functionality. Only allows you to push, pull stuff.

**Comment by duramato** [comment]
@ncksol it should have installed git with that
Try opening a terminal on the project folderand do
`git remote -v` it should show 2 origins and 2 upstreams
if it doesnt show the upstream do : `git remote add upstream https://github.com/SiCKRAGETV/SickRage.git `

after that do 

```
git fetch upstream
git rebase -i upstream/develop
 ```

and `leave your first commit as "pick" and the rest set to "fixup" or "squash", do not change anyone elses commits. Save and exit`
Finally do
`git push origin yourbranchname -f`

**Comment by ncksol** [comment]
@duramato thanks! looks like i've managed to do it.

**Comment by fernandog** [comment]
@miigotu any commens before merge?

**Comment by miigotu** [comment]
I must test this before merge =P

**Comment by fernandog** [comment]
I tested and its working fine so far.
Dont know if @duramato tested

**Comment by fernandog** [comment]
@miigotu So did tested?

**Comment by fernandog** [comment]
@ncksol 

Don't know if HDT is passing the correct char to SR or it's only the log:

From website: Carnivàle S02 1080p WEB-DL DD5.1 H.264-BS

```
2015-10-18 20:01:26 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: Attempting to add item to cache: Carniv%C3%A0le.S01.1080p.WEB-DL.DD5.1.H.264-BS
2015-10-18 20:01:26 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: Unable to parse the filename Carniv%C3%A0le.S02.1080p.WEB-DL.DD5.1.H.264-BS into a valid sho
```

**Pull request merged**
