### PR TITLE
Rudimentary Torrentz support - From Scratch

### PR DESCRIPTION
**Pull request by miigotu**
Torrentz went down while I was writing this, so IDK if it is fully working still.

### CODE REVIEW

**Comment by miigotu** [comment]
Can anyone even get torrentz site to load now? If its just gone now I'' close this until its back online.

**Comment by matigonkas** [comment]
@miigotu it is working fine to me ,maybe your ISP blocked it?

**Comment by miigotu** [comment]
Strange, isitdownforeveryoneorjustme even says its gone.

**Comment by miigotu** [comment]
I've never been censored in US before, maybe torrentz blocking a range?:

image

**Comment by miigotu** [comment]
Through a proxy it works, wtf.

**Comment by matigonkas** [comment]
If it works on a begind proxy whould it be a good idea to change the URL to a proxy ,becouse i can imagine more people like having that problem like you..

**Comment by miigotu** [comment]
Their proxy doesnt work for me either:
https://torrentz-proxy.com/
But if I go through hideme.nl it works.

**Comment by miigotu** [comment]
https://www.torrentsmirror.com/ doesnt work either.

**Comment by miigotu** [comment]
I'll have to change my ip and make sure their firewall didnt just block me for spamming them while I was writing this provider -.-

**Comment by miigotu** [comment]
Closed until this goes away:
image

**Comment by matigonkas** [comment]
@miigotu https://torrentfreak.com/chrome-blocks-major-torrent-sites-over-harmful-programs-150710/

**Comment by miigotu** [comment]
I see that, but since I can't even access torrentz.eu this will stay closed until I can.

**Comment by duramato** [comment]
@miigotu are you still not able to connect to it? 
As the warning seems to be fixed now

**Comment by miigotu** [comment]
Just isnt a priority right now.

**Comment by starkillerOG** [comment]
Is https://torrentz.eu/ still going to be added as a free torrent provider?
I am using firefox, and as far as i can see the site is up and running.

**Pull request closed without merging**
