### PR TITLE
Set maxage to today-airdate to limit results to relevant results, and…

### PR DESCRIPTION
**Pull request by miigotu**
… to make sure we get them

Fixes SiCKRAGETV/sickrage-issues#1852

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu what if user uses the conversion to local time? (myself for example). all my airdates are converted to my local time

**Comment by miigotu** [comment]
Thats why it has + 1 day.

cur_params['maxage'] = (datetime.datetime.now() - datetime.datetime.combine(ep_obj.airdate, datetime.datetime.min.time())).days + 1

I could get the tzdata and the ep_obj.show.airs and convert all of the nonsense to a datetime object created with ep_obj.airdate, and then create another datetime object from now() and tzdata, but why bother when we can just add 1 day and be sure 100% that the episode has aired in maxage?

**Comment by miigotu** [comment]
No search can return a result of more than 500 items now (used to be 1000)

maxage is hard limited to 4 days, unless searching for a specific episode or season, which then uses the days since the airdate  +1 for maxage. maxage was previously unlimited.

Cache is kept for 30 minutes (up from 15 minutes)

Time between requests is now 5 seconds, up from 0.2 seconds.

Bogus searches don't happen now.

Proper finder is fixed for newznab.

Who do we need to contact to get SR to stop being blocked? If they aren't willing to work with us, especially after I fixed so many things broken elsewhere and set our limiting twice as much or more than everyone else, then I guess we know there are other motives.

**Comment by Hellowlol** [comment]
What provider blocks at?

**Comment by miigotu** [comment]
Several, ones we know for sure:
lolo.sickbeard.com
nzbs.in

**Comment by Hellowlol** [comment]
Bastards :P

**Comment by miigotu** [comment]
And they are kinda rude about it, and block us without notice.

SiCKRAGETV/sickrage-issues/issues#1556

**Comment by thezoggy** [comment]
to be fair, sickrage devs have had a history of being rude first. sb code had many safegaurds to stop it from hammering indexers. echleon and others have gone out of their way to remove such things. then you guys cry wolf when you get banned. so now you guys change your user agent to mimic sickbeard proper... so now what do you expect now to happen?

**Comment by thezoggy** [comment]
things like this is part of the problem and one example for you to address:
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/common.py#L39

reference:
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/search_queue.py#L187

where if a user backlogs a season, lets say 20 episodes in the season and its split.. thats 20x files it going to ask the site for.. with either a .01 or .05 sec delay. vs sickbeard 2 sec ( https://github.com/midgetspy/Sick-Beard/blob/development/sickbeard/search_queue.py#L140 ). thus you will see sites still throttle you for making quick concurrent requests. 

anyways there is plenty of this type of thing that is done. yes im glad to see you guys finally took steps to address some of your problems but please dont do it at sickbeard's expense. you guys already have a crappy anti sickbeard mentality enough as it is (sickgear reference/kicking other devs out of your chatroom because you dont like to hear problems with sickrage).

we at sickbeard went out of our way to make sure we didnt hammer and bite the sites that feed us, so its just shitty to see sickgear now use sickbeards user agent to try and sidestep its faults (still plenty of ways to identify sickrage - nn admins contact me and ill tell you how).

**Comment by Hellowlol** [comment]
@thezoggy I see your point. I still think it would be better to make a issue, then ban. And sickbeard development has been close to nonexistent after you left the team, I'm glad others has picked up the tourch. In the perfect world I'd like to see the devs work together to make a amazing app, but people doesn't always see things the same way. One might call it feature, one will see it as bloat.

**Comment by miigotu** [comment]
@thezoggy 
Thanks for pointing out that ridiculously low delay between snatches, here I have been focusing on delays between searches, particularly in newznab.

We (SickRage != SickGear) also want to not hammer the sites, and I am in fact working directly with several nzb index staff/owners the past few days, as well as some torrent site owners to improve our support and limit server resource usage.

The plan was never to keep using sickbeard's user agent. It's more like aha you ban me and dont wanna let me know? Ok I'll workaround and have you come talk to me that way, or eventually you will remove the ban.

I want to fix the problems, and have the bans lifted, and return our user-agent to what it is supposed to be.

Since I have drastically improved (and majorly rate limited) searches, and am now bumping those CPU presets from up to 5,2,1, are there any reasons for us to continue to be banned?

**Comment by miigotu** [comment]
no-Spam fixes all verified working. Delays all greater than 5 seconds (mostly 7 seconds, due to search delay + cpu_preset). Can anyone else verify or point out another problem?

**Comment by fernandog** [comment]
@thezoggy I'm sorry about user agent.
after echelon left we are trying out best (I'm a beginner programmer in python). He left this repo with me and I've tried to asked others to help keep SR alive. otherwise SR would be dead 3-4 months ago. @miigotu and @abeloin helped A LOT. myself alone couldn't do all this work so far.

I can tell that since this new team started helping with SR, we didn't kicked anybody. In fact it's the other way around. we want/need more devs to help us coding. We have tons of issues and tons of FR.
Nobody is watching the IRC channel (AFAIK). neither reddit.

What we have a lot here is comparison between SR and SB like "it works in SB but it's not working in SR". sickbeard is still the main app and users know that.

Our TODO list is huge. We have a lot of things to do. And we mean no harm. Just want to make SR better and better.
https://github.com/SiCKRAGETV/sickrage-issues/issues/589#issue-57492030

It's too bad there's lots of forks when everybody could work in one main fork.

**Pull request merged**
