### PR TITLE
Set episodes with airdate as 'never' to UNAIRED status

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/2184

@miigotu agree?

### CODE REVIEW

**Comment by fernandog** [comment]
how something is SKIPPED is was never aired? Code didn't check for aidate = 1, only airdate > today

**Comment by miigotu** [comment]
== not = lol, maybe this will be ok but i'm not sure.

**Comment by fernandog** [comment]
damn! will fix it

**Comment by miigotu** [comment]
Don't worry about silly syntax errors, I mis `:` after method definitions, ifs, and for statements all the time because of C/C++ lol

**Comment by miigotu** [comment]
Btw, are you sure the self.airdate of airdate 'never' is 1 and not `datetime.date.fromordinal(1)` ?

**Comment by fernandog** [comment]
DB value is 1

**Pull request merged**
