### PR TITLE
Manage rolling download

### PR DESCRIPTION
**Pull request by gborri**
With this feature will be the possibility to define how many episode not watched you can have on your disk.
For watching status has been used traktv.

### CODE REVIEW

**Comment by fernandog** [comment]
@gborri we should FULLY test this. What happens when TRAKT is down or 503 unavailable?

watched episodes or not watched? Why should I delete not watched episodes?

**Comment by gborri** [comment]
@fernandog i haven't understood your question. the software doesn't delete episode. it sets only state. In last commit you can choose to which status (ARCHIVED or IGNORED) set. The modification is performed only on show add. New show: It start to make episode WANTED, on deleted show: change status for watched episode.

**Comment by gborri** [comment]
@fernandog if trakt is down the procedure will exit

**Comment by fernandog** [comment]
@gborri from the ref. issue

"Let's say you have 3 episodes of a show. If there were a option to limit the max retained shows (Keep at most: x) where "x" for this particular show is set to only 3, then when SickRage adds a new episode (4th show) it would delete the oldest of the 4. So you would only ever have the 3 newest episodes."

**Comment by gborri** [comment]
@fernandog tis is not the case. the code doesn't work as you said. the code look for the latest SKIPPED episode, check for the latest download and if the condition is met set x number of episode to wanted. that's it. Other case is when adding new show that is already managed by trakt: in this case set to IGNORED or ARCHIVED the old episode already watched. The only test i have not made (i will try) is if you add a show that is already on disk

**Comment by gborri** [comment]
@fernandog the mplementation of the PR is different from what has expressed by the issue as defined by my comment on it

**Comment by fernandog** [comment]
No problem

**Comment by gborri** [comment]
@fernandog tested also in adding existing show

**Comment by abeloin** [comment]
Please rebase to the latest version of develop

**Comment by gborri** [comment]
@abeloin done

**Comment by fernandog** [comment]
@gborri can you make a small wiki about this?

**Comment by gborri** [comment]
@fernandog will try. where i have to put it?

**Comment by fernandog** [comment]
@gborri open as a issue (markdown). then I will add to SickRage repo

**Comment by gborri** [comment]
@fernandog have you some example of some other feature wiki? where you will put it? in order to see how to write it?

**Comment by fernandog** [comment]
@gborri https://github.com/SiCKRAGETV/SickRage/wiki

**Comment by abeloin** [comment]
@fernandog Merging for v4.0.14?

**Comment by fernandog** [comment]
@abeloin ok

**Comment by abeloin** [comment]
@gborri Let me know when the wiki part is done. You can create the wiki page in your gist and post the link here.

**Comment by gborri** [comment]
@fernandog can i clone the wiki page on my repo?

**Comment by abeloin** [comment]
@gborri There's no wiki page on your repo https://github.com/gborri/SickRage/wiki

**Comment by gborri** [comment]
there isn't. how can clone the one on master repo?

**Comment by abeloin** [comment]
@gborri Sorry I just understand what you meant earlier. Tell me which page you need I'll upload it to a gist.

**Comment by gborri** [comment]
@abeloin at least the wiki home, the one on which I have to add the manage
rolling section. I need something to work with on my repo.

Giovanni
Il 26/mar/2015 19:00 "Alexandre Beloin" <notifications@github.com> ha
scritto:

**Comment by abeloin** [comment]
Here's the link: https://gist.github.com/abeloin/ee5aff30f9ba82bdf598
If you need other pages, let me know

**Comment by gborri** [comment]
@abeloin @fernandog the wiki. https://github.com/gborri/SickRage/wiki/Trakt-rolling-download-feature fell free to change it as you want.

**Comment by fernandog** [comment]
@gborri please check:

There's lot of errors in your labels:

"Collect defined number of episodes after last watched one"
That's not clear at all to me

"Number of Episode:"
to
"Quantity of episodes"

"numebr of episode that SickBeard try to download fron last watched episode"
to 
"Episodes that Sickrage will download based on the last watched episode"

"Should new show to be added paused?:" 
to
"Add new show as paused"

"This feauture will try to snatch number of episode if the show is active. Whould you like to add new show in paused mode(this override previous choice)?"
to
"Overrides rolling download feature and add show as paused"

**Comment by fernandog** [comment]
@gborri if add as paused override rolling download, why not simple disable the "rolling download" feature?!

**Comment by fernandog** [comment]
@gborri please check all of this

**Comment by gborri** [comment]
@fernandog the point is not to override the rolling download if check add as paused, but if necessary the opposite. I will try.

**Comment by fernandog** [comment]
@gborri check errors I pointed above

**Comment by gborri** [comment]
#1792

**Comment by gborri** [comment]
@fernandog already done on the patch

**Pull request merged**
