### PR TITLE
Comedy Central Updated Icons

### PR DESCRIPTION
**Pull request by Peke**
@miigotu Hope this time I got it right?

### CODE REVIEW

**Comment by neoatomic** [comment]
@Peke Don't use gray as the main color. 
The logo will not show good on the light SickRage theme. (As the background is also white/gray.)
Thats also the reason why we largely use bright colors in the logos. I made a FAQ some time ago, gives some more details. : 

```
Network logos

What are network logos.?

Network logos show a picture instead of a plain text name in the show overview of Sickrage. 

How does SickRage receive those names.?

The names are automatically provided by the indexers TVDB and TVRage.
In case there are errors in the name please report them to one of the above indexers.

Where are the logos located in Sickrage.? 

They are located under : /SickBeard/gui/slick/images/network

How to add network logos for SickRage.?

First you need to get your hands on a logo for that particular network. Google is your best friend here.
Once that is done use Paint.net or similar program to edit the image.

* Make the background transparent.
* Resize the image to 64x32 pixels.
* Save it as a png.

Some guidelines for the network logos are. :

* Use colord logos.
* Try not to use black or withe.

The last is because Sickrage has two color theme's (Dark and Light). If the logo contains to much of either color it will not show properly/correctly on one of those themes.

Last step is to rename the image. It needs to have the exact name of the network in the show overview list.
Also use only lowercase characters as upper case characters are not recognized.

Example : "Sky Atlantic"   this needs to be renamed to "sky atlantic" So the logo filename will be sky atlantic.png

Note : Special characters are not supported.

When you have the logo ready it needs to be added to SickRage. This is done with a Pull request on GitHub. You can use a program like Sourcetree for submitting.
Alternatively you can also post the logo and exact filename on our SickRage issue tracker 

https://github.com/SiCKRAGETV/sickrage-issues/issues 
```

**Comment by miigotu** [comment]
@Peke perfect, except they are too transparent and not bright colors as @neoatomic said.

**Comment by Peke** [comment]
As I have my own Hosting plan It would be good idea to upload them there and open issue in order to avoid number of commits. I'll see if I can work on few more this weekend. I was trying to keep things as close to Actual current logo as possible.

**Comment by miigotu** [comment]
@Peke its ok to add a few here and there and PR them. No need to upload them anywhere, git handles that for you. You can always rebase and remove or combine commits and modify pull requests by forcing a push.

**Comment by miigotu** [comment]
@Peke were these icons even intended to look that way? It only looks like an alpha channel on here. Maybe wrong png pixel format?

**Comment by Peke** [comment]
Yes, they are in RGB 32 + Alpha format PNG do you suggest that I change them?

**Comment by miigotu** [comment]
Yeah clear/white just doesn't work well with the gui then, lol.

**Comment by miigotu** [comment]
@Peke these cant be used without some color in them. Are you remaking them or should I close this?

**Comment by Peke** [comment]
Sorry for delay I'll do small color change and combine with original colors of older official logos.
I should be done over the weekend and rebase changes.

**Comment by miigotu** [comment]
@Peke did you forget about us? xD

**Comment by Peke** [comment]
Certainly not, I'm just too busy with real life to have a hobby :( eg. beside regular job I got two out of town private contract that needs to be done within two months.

**Comment by Peke** [comment]
DAMN What I screwed again why I can't remove earlier comit and rebase :(

**Comment by miigotu** [comment]
You can @Peke 
git fetch upstream
git rebase -i upstream/develop

**Comment by Peke** [comment]
And from smartgit?

**Comment by miigotu** [comment]
smartgit just click pull in the toolbar, check fetch from all remotes, and the option rebase onto local changes, then pull

**Comment by miigotu** [comment]
The look like this on light theme:
https://raw.githubusercontent.com/Peke/SickRage/feature/Network-Icon-Updates/gui/slick/images/network/comedy%20central%20family.png

**Comment by neoatomic** [comment]
@miigotu Just updated but they don't look to good on the dark theme. :(

**Pull request merged**
