### PR TITLE
Use os.system for file copies

### PR DESCRIPTION
**Pull request by eli-jordan**
When post processing using shutil.copyfile can be very slow. Use
os.system for posix systems

### CODE REVIEW

**Comment by pstadler** [comment]
Please add the same logic for `moveFile`, it's slow as well.

**Comment by echel0n** [comment]
please submit this to dev branch

**Comment by eli-jordan** [comment]
Created pull request against develop https://github.com/SiCKRAGETV/SickRage/pull/1193

**Comment by eli-jordan** [comment]
@pstadler for me moveFile is not slow

**Pull request closed without merging**
