### PR TITLE
Replace language selection in add show.

### PR DESCRIPTION
**Pull request by abeloin**
It now display each language by their name.
Use bootstrap formhelpers 2.3.0 under Apache License v2.0
http://plugins.jquery.com/bfh-language/

### CODE REVIEW

**Comment by abeloin** [comment]
Imgur

**Comment by fernandog** [comment]
Awesome!

**Comment by gborri** [comment]
@abeloin could be useful to modify also editShow.tmpl.
i have seen that also in gui//slick/js/newShow.js there is a call to external to retrieve Language, but i'm not sure if it is used in the code.

**Comment by abeloin** [comment]
Ok I will check

**Comment by abeloin** [comment]
@gborri https://github.com/SiCKRAGETV/SickRage/pull/1416

**Pull request merged**
