### PR TITLE
FR: Add Pause Button on displayShow page

### PR DESCRIPTION
**Pull request by Thraxis**
* Adds a pause button on the displayShowPage to Pause/Unpause a show
without needing to go into editShow.

### CODE REVIEW

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/835

**Comment by abeloin** [comment]
@Thraxis Can you rebase your PR?

**Comment by Thraxis** [comment]
Rebased

**Comment by fernandog** [comment]
@Thraxis it's not working

```
2015-04-14 16:40:47 DEBUG    Thread-62 :: 250487: Not saving show to db - record is not dirty
2015-04-14 16:40:19 DEBUG    Thread-40 :: 250487: Not saving show to db - record is not dirty
2015-04-14 16:39:58 DEBUG    Thread-23 :: 250487: Not saving show to db - record is not dirty
2015-04-14 16:39:55 DEBUG    Thread-31 :: 250487: Not saving show to db - record is not dirty
```

also I would keep the table and yes/no icons as it was and add a top button like the other buttons "Toggle Pause/Unpause" - something like that - instead

**Comment by Thraxis** [comment]
It should be saving the record as soon as the pause / unpause is requested.

The top menu buttons are a special setup I'll have to see if they can be dynamic.

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/1784

**Pull request merged**
