### PR TITLE
Patch tntvillage season pack manage

### PR DESCRIPTION
**Pull request by gborri**

### CODE REVIEW

**Comment by gborri** [comment]
SiCKRAGETV/sickrage-issues#1070

**Comment by abeloin** [comment]
@gborri First, your PR is into master not develop.

Try, `git reset --hard`

**Comment by abeloin** [comment]
@gborri Fix for 1070 is now in master and develop

**Comment by abeloin** [comment]
@gborri You need to remove the 2 files your updating in this PR

**Comment by gborri** [comment]
@abeloin sorry, for PR against master. didn't see it. i can reset hard. but when i merge with sickrage/develop everytime i got this 2 file changed.

**Comment by gborri** [comment]
@abeloin i've seen after post that you have fixed #1070

**Comment by gborri** [comment]
@abeloin i'v tried git reset hard but if i try to rebase the change come up again

**Comment by abeloin** [comment]
Have you tried a git pull?

**Comment by gborri** [comment]
@abeloin redone against develop and clean LF/CTRLF (#1688)

**Pull request closed without merging**
