### PR TITLE
Add column widget selector to "displayShow"

### PR DESCRIPTION
**Pull request by Thraxis**
* Added Colum Selector Widget to displayShow
* Cleaned up CSS to not over-ride SickRage CSS colors and font strength

FR https://github.com/SiCKRAGETV/sickrage-issues/issues/1015

### CODE REVIEW

**Comment by fernandog** [comment]
@Thraxis thanks!
We can remove this setting from UI /config/general/:
Display Filesizes - display filesizes for downloaded episodes on show page
and from config.ini as we can show/hide via column widget

**Comment by abeloin** [comment]
@fernandog @Thraxis For the other part, removal of config option in a new PR it is.

**Comment by fernandog** [comment]
@Thraxis for one show I got this. No javascript error:

image

I enabled in config / Interfaces to show the size of files.
for other show I got this. Note the difference between Season 5 and Season 4:

image

**Comment by Thraxis** [comment]
@fernandog I'm not seeing the issue with the Season 5 / 4 differences on my system....

image

But I am seeing problems with the saved settings when you change between anime and regular shows since the column numbers changes as anime add in the absolute column.  I'll go back and recode to make all the columns available to start and then force hide ones not needed using the column widget.

As for the one not displaying at all.. not sure why that would be

**Comment by abeloin** [comment]
@Thraxis I saw the same problem in the home page, that is why I choose to display all columns and manually set the hidden column manually and use 'saveSort' to save the users change

**Comment by fernandog** [comment]
Thanks!

**Comment by abeloin** [comment]
History page is broken under the new css the color fff was remove from the style.css but never out back in dark.css

**Comment by Thraxis** [comment]
I could swear I had fixed that.  There were so many color: overlaps for the text between all the various CSS tags

**Comment by Thraxis** [comment]
Superseded by https://github.com/SiCKRAGETV/SickRage/pull/1754

**Pull request merged**
