### PR TITLE
Don't remove logs folder when git reset is enabled in UI

### PR DESCRIPTION
**Pull request by fernandog**
git reset should only reset git files not user files
@abeloin what do you think about set "get reset" by default in config.ini?

### CODE REVIEW

**Comment by abeloin** [comment]
@fernandog Small question: why do we need this addition? Line 7 "Logs/*" already prevent the Logs folder from being deleted.

As for the git reset, I think we should further discuss it implication.

**Comment by fernandog** [comment]
/Logs keep only the folder
Logs/* contents of the folder

You can see there is this for the others

**Comment by abeloin** [comment]
They mean exactly the same thing(not exactly in technical term but on the practical they are):
Logs/ : Ignore the folder and its content
Logs/* : Ignore the folder content (Imply keep the folder)

See http://git-scm.com/docs/gitignore for more information.

**Comment by fernandog** [comment]
@abeloin ok. will change this commit and fix the cache/ too

**Comment by fernandog** [comment]
@abeloin done

**Pull request merged**
