### PR TITLE
Auto send user and password when open managetorrents page

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/315

### CODE REVIEW

**Comment by fernandog** [comment]
@abeloin is there a better way to send the password without keep it on page code?

**Comment by abeloin** [comment]
@fernandog None that I'm aware of.

**Comment by Hellowlol** [comment]
Isnt there a redirect you can use at the username and password is hardcoded into the url?

**Comment by abeloin** [comment]
Even if you use a sickrage url then use a 302 to redirect to the final page it will still show in the browser's network developer tools.

Maybe with a tornado handler acting as a proxy could work but my knowledge of Tornado is far to little for me to answer.

**Comment by fernandog** [comment]
what about a javascript function to remove/replace the url with user:pass using regex?

**Comment by abeloin** [comment]
It will still show when using the show source code as the page is pulled from the server directly.

Not to mention, if you use wget or curl.

**Comment by Hellowlol** [comment]
i was thinking something like this:

http://tornado.readthedocs.org/en/latest/guide/structure.html#redirection

app = tornado.web.Application([
    url(r"/app", tornado.web.RedirectHandler,
        dict(url="http://itunes.apple.com/my-app-id")),
    ])

**Comment by fernandog** [comment]
@Hellowlol where do we add the user/pass?

**Comment by abeloin** [comment]
@Hellowlol It will still send a 302 to the browser with the new link(e.g. http://user:pass@deluge.local) and the username and password will be shown in the browser's developer tools.

I think the user have accept the fact that if they want use this feature they better use HTTPS to secure their connection.

The best would if those webui use something like oauth or openid were we could request a token an open the seesion.

**Comment by Hellowlol** [comment]
Yeah, fuck it. :P

**Comment by fernandog** [comment]
=) this is a feature from mr_orange. Don't know if users really use it. I prefer use Transdroid on my phone to see the torrent downloader

**Comment by Hellowlol** [comment]
I that app available for ios aswell? I just use https://github.com/Hellowlol/HTPC-Manager for stuff like that.

**Comment by abeloin** [comment]
Call me old fashion, I open a new tab and type in the address to get access. ;)

In the end, it's boil down to security vs user friendliness, the more secure the less friendly it is and vice versa.

**Pull request merged**
