### PR TITLE
Remove trakt rolling

### PR DESCRIPTION
**Pull request by fernandog**

### CODE REVIEW

**Comment by WebSpider** [comment]
Why is this feature removed? (Sorry, it's probably discussed on IRC, but logging it in github preserves it for eternity)

**Comment by fernandog** [comment]
author it's no getting proper support/fixes. 
it's 'do not merge' to give him some time to fix. It don't fix, will remove it

**Comment by miigotu** [comment]
tbh, I think it's a silly feature, has a very low usage rate, and it breaks SR.

It is a hell of a lot of code for something not many people use, plus extra configuration and maintenance and support.

K.I.S.S.

**Comment by WebSpider** [comment]
I agree with you here.

Should we make a NEWS entry before removal, so we can get someone to support this code, before removing something people may really like?

-----Original Message-----

**Comment by miigotu** [comment]
If the original coder cant fix it, I cant find the bug, fernandog cant find the bug and other cant I think its just remove it.

**Comment by miigotu** [comment]
@fernandog can you update this for mako? I'd like to do this soonish.

**Comment by WebSpider** [comment]
@fernandog let me know if ur busy

**Comment by fernandog** [comment]
Sorry Im away. My kid is sick, allergy all over his body. Taking some time from internet.

**Comment by miigotu** [comment]
@fernandog hope the kid gets better, take your time.

**Comment by miigotu** [comment]
Redone in #2314

**Pull request closed without merging**
