### PR TITLE
Remove size column js as it doesn't exist anymore.

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by fernandog** [comment]
@OmgImAlexis I still have a gray column in my /home page. Cleared browser cache and deleted mako folder

image

**Comment by MGaetan89** [comment]
@OmgImAlexis Did you change the column index in the JS?
I think it would have been easier to revert my PR until the DB is updated :P

**Comment by OmgImAlexis** [comment]
@MGaetan89 there's no way to do that as we've changed all of mako, etc. since then that's why I did it like this. You'll have to go through and change all of the js back manually.

**Comment by miigotu** [comment]
I think it is only the column array index now that needs changed from 7 to 6

**Comment by OmgImAlexis** [comment]
@fernandog is that on master or dev? I don't have the issue at all on my dev install.

**Comment by fernandog** [comment]
Dev

**Comment by OmgImAlexis** [comment]
Try now, miiotu merged another PR into dev and that should fix it.

**Comment by fernandog** [comment]
Working. Thanks

**Pull request merged**
