### PR TITLE
Add locked icon for private providers, and unlocked icon for public.

### PR DESCRIPTION
**Pull request by miigotu**
Add classes to color providers by type: nzb or torrent

Not sure what the colors should be yet, need to test some out.
Will rebase and merge once decided.

image

### CODE REVIEW

**Comment by miigotu** [comment]
@SiCKRAGETV/moderators

**Comment by fernandog** [comment]
thanks!

light theme:
image

I would use a redish color instead of black

**Comment by fernandog** [comment]
@miigotu the black background it's appearing for pubic and private.

**Comment by miigotu** [comment]
@fernandog I didnt do light yet at that time. pull it and check it again

**Comment by fernandog** [comment]
@miigotu 

I would keep white for torrents and grey for nzb 
it's cleaner as we have a lot more torrents 

image

**Comment by fernandog** [comment]
@miigotu 
is it possible to sort by in this order: enabled, public torrents, public nzb, private torrents, private nzb

**Comment by miigotu** [comment]
@fernandog sorting by public/private and torrent/nzb is a separate pr/feature.

**Comment by fernandog** [comment]
@miigotu np. but can we keep the white in light theme?

**Comment by miigotu** [comment]
@fernandog can you track down all of the different FR this closes and link them here/close them?

**Comment by fernandog** [comment]
can we keep the white in light theme as I said here?
https://github.com/SiCKRAGETV/SickRage/pull/2559#issuecomment-142006013

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/2816

**Comment by WebSpider** [comment]
Suggestion: Grey and Orange.. Both are visible in White and Black and not used yet by any other visual element in SR that im aware of. Dont care which color does what.

Will this also affect history view?

-----Original Message-----

**Comment by fernandog** [comment]
Nope

**Pull request merged**
