### PR TITLE
SCC search improvements

### PR DESCRIPTION
**Pull request by ROpdebee**
Updated the searching to use the new 'all' section of SCC. Changed:
- Searching in all categories now requires only one request instead of a request to all the URLs.
- Foreign categories can be handled just as any other, as the new section doesn't include a second link to the language.
- Season pack search also includes their non-scene sections as they release WEB-DL packs there instead of the archive.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
@ROpdebee can you try to get the size so we can remove this?

#FIXME
size = -1

**Comment by neoatomic** [comment]
@ROpdebee Thanks for helping out with submitting some PR's. 
Bedankt. :)

**Comment by ROpdebee** [comment]
@fernandog Oh, that's why that's there. I'll look into it. 
@neoatomic graag gedaan. I'll help where I can (even though I'm kind of a python noob tbh)

**Comment by fernandog** [comment]
we have others providers with FIXME that needs parsing seeders, leechers and size. If you know how to, feel free to PR and help us!

**Pull request merged**
