### PR TITLE
home.tmpl: Fix loading show js error.

### PR DESCRIPTION
**Pull request by abeloin**
Also make sure they are always on top.

### CODE REVIEW

**Comment by fernandog** [comment]
@abeloin what about the first colum "(loading)" ?

**Comment by abeloin** [comment]
@fernandog What about it?

**Comment by fernandog** [comment]
Is a string. Not a date. wasnt that the problem?

**Comment by abeloin** [comment]
No, the javascript error was on line 482. [Tablesorter extraction](https://github.com/abeloin/SickRage/blob/patch-home_loading_shows/gui/slick/interfaces/default/home.tmpl#L92) is looking for span title in that column which was missing.

Also depending on how and/or if you changed the sort order the line was sorted with everything else, so I've added a <tbody class="tablesorter-infoOnly"> which prevent sorting.

**Pull request merged**
