### PR TITLE
NEW OPTION in config/general advanced settings (SSL Verify) - QNAP/Etc

### PR DESCRIPTION
**Pull request by miigotu**
NEW OPTION in config/general advanced settings (SSL Verify)  - Disable this for QNAP SSL problems.

REMOVED OPTION in Trakt notification settings (Disable SSL Verify) - Handled by the new option above

Helps? QNAP

### CODE REVIEW

**Comment by forkless** [comment]
It's a good option to have as the QNAP do not have a root CA store. That said it still throws TLS errors.

```
2015-07-15 16:08:01 INFO     SEARCHQUEUE-MANUAL-92091 :: Skipping MeisterCookier.Aussie.S01E01.PDTV.x264-FQM, URL check failed. Bad result from provider.
AA
AAAttributeError: '_socketobject' object has no attribute 'set_tlsext_host_name'
AA    cnx.set_tlsext_host_name(server_hostname)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 296, in ssl_wrap_socket
AA    ssl_version=resolved_ssl_version)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connection.py", line 238, in connect
AA    conn.connect()
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 762, in _validate_conn
AA    self._validate_conn(conn)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
AA    body=body, headers=headers)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
AA    timeout=timeout
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/adapters.py", line 370, in send
AA    resp = super(CacheControlAdapter, self).send(request, **kw)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/cachecontrol/adapter.py", line 46, in send
AA    r = adapter.send(request, **kwargs)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 576, in send
AA    resp = self.send(prep, **send_kwargs)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 464, in request
AA    return self.request('HEAD', url, **kwargs)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/lib/requests/sessions.py", line 496, in head
AA    resp = session.head(url, timeout=timeout, allow_redirects=True)
AA  File "/share/MD0_DATA/.qpkg/SickBeard-TVRage/SickBeard-TVRage/sickbeard/helpers.py", line 1341, in headURL
2015-07-15 16:08:01 WARNING  SEARCHQUEUE-MANUAL-92091 :: Traceback (most recent call last):

2015-07-15 16:08:01 WARNING  SEARCHQUEUE-MANUAL-92091 :: Unknown exception in headURL https://********.com/indxr/getnzb/18cc1473a3520ef2ae2ef59ac50946dc.nzb&i=1&r=**********
2015-07-15 16:08:01 INFO     SEARCHQUEUE-MANUAL-92091 :: Quality of MeisterCooker.Aussie.S01E01.PDTV.x264-FQM is SDTV
2015-07-15 16:08:01 INFO     SEARCHQUEUE-MANUAL-92091 :: [newzfork] :: Found result MeisterChooker.Ausssie.S01E01.PDTV.x264-FQM at https://********.com/indxr/getnzb/18cc1473a3520ef2ae2ef59ac50946dc.nzb&i=1&r=**********
2015-07-15 16:08:01 INFO     SEARCHQUEUE-MANUAL-92091 :: [newzfork] :: Performing episode search for MeisterCooker Aussie
```

The API seems to connect to the SSL newznab instance fine as it returns a result however fetching it seems to be a problem.

**Comment by miigotu** [comment]
Its not about the root CA store, as we provide that ourselves in SR.  You still need an up to date openssl.

**Comment by forkless** [comment]
The QNAP that is running my SR instance is running of OpenSSL 1.0.1o dated 12 jun 2015, I take it that is recent enough.

What is more puzzling (as you can tell from the log) is that my SR is able to query my SSL newznab instance just fine, however it fails when it starts to retrieve the actual nzb. 

Am I correct in thinking that if you are able to query that SSL server returning a valid result via the newznab API it will have successfully connected with the SSL socket otherwise there wouldn't be a result, right?

**Comment by miigotu** [comment]
Not necessarily, the indexer api might not be operating with a setup requiring SNI, while the actual download location of the NZB may require SNI.

SNI is only available in requests when pyopenSSL>=0.13.1 is installed and working. Installing 0.13.1 is possible on the QNAP, but > 0.13.1 is not due to missing compiler and development headers.

This is in addition to the requirement that the ssl cert not be verified on QNAP.

**Comment by forkless** [comment]
Relief is on its way (at least for x86 QNAP model owners) a community developed package which has a custom Python2.7 included seems to have sorted the pyopenSSL dependency.






Sent from Windows Mail





From: miigotu
Sent: ‎Thursday‎, ‎July‎ ‎16‎, ‎2015 ‎1‎:‎47‎ ‎AM
To: SiCKRAGETV/SickRage
Cc: forkless





Not necessarily, the indexer api might not be operating with a setup requiring SNI, while the actual download location of the NZB may require SNI.

SNI is only available in requests when pyopenSSL>=0.13.1 is installed and working. Installing 0.13.1 is possible on the QNAP, but > 0.13.1 is not due to missing compiler and development headers.

This is in addition to the requirement that the ssl cert not be verified on QNAP.

**Pull request merged**
