### PR TITLE
Trim all trailing spaces from lines in python files, using 's/ &//g'

### PR DESCRIPTION
**Pull request by miigotu**
Trim all trailing spaces from lines in templates, using 's/ &//g'

### CODE REVIEW

**Comment by miigotu** [comment]
@abeloin You think it is ok do do this now while we have few open PR?  Less ppl that need to rebase the better, but this annoys me.

**Comment by abeloin** [comment]
I wouldn't touch the lib folder(except for a few exceptions) as those are from upstream.

I think is is better to create this PR and commit it right after a merge develop->master, it should resolve the rebasing issue

**Comment by miigotu** [comment]
Hmm, was hoping it would be ok to just trim trailing on libs, as you can diff with ignoring whitespace.  I already didn't apply the pep8 to lib because that would totally fuxor diffs.

I will hold off on these until after a develop->master  merge like you suggested.

**Comment by abeloin** [comment]
Regarding the libs, I gave you my personal opinion it doesn't mean it's set in stone. We are the advantages and disadvantages of doing that?

**Comment by miigotu** [comment]
Not really a whole lot of advantage in trim trailing on libs besides making the source smaller a bit, but makes an extra step when updating/diffing libs and makes it harder to follow history before/after via github website ^. I will revert libs and squash before this gets merged.

**Pull request closed without merging**
