### PR TITLE
CSS optimizations

### PR DESCRIPTION
**Pull request by MGaetan89**
This PR:
- Uses the minified version of Bootstrap (the file is about 20 ko smaller than the normal one)
- Removes the unused CSS files
- Removes some duplicates rules in `style.css`
- Removes trailing white spaces

### CODE REVIEW

**Comment by miigotu** [comment]
@MGaetan89 The scroll to top icon is invisible (at least in dark theme, haven't checked light)
```html
<div id="topcontrol" title="Scroll Back to Top" style="position: fixed; bottom: 10px; right: 10px; opacity: 0; cursor: pointer;"><img src="/images/top.gif" width="31" height="11" alt="Jump to top"></div>
```

**Comment by MGaetan89** [comment]
I will check that later.

**Comment by miigotu** [comment]
@MGaetan89 my bad, opacity increases once you scroll down some.

**Comment by MGaetan89** [comment]
Good :)

**Pull request merged**
