### PR TITLE
Fix for SiCKRAGETV/sickrage-issues#1927

### PR DESCRIPTION
**Pull request by MGaetan89**
Issue: SiCKRAGETV/sickrage-issues#1927

### CODE REVIEW

**Comment by neoatomic** [comment]
Thanks for contributing/helping out. :)

**Comment by MGaetan89** [comment]
No problem :smile: 
I'll try to find other issues I can work on.

**Comment by MGaetan89** [comment]
This fix does not work. A `#` is always visible on the page between the show name and the show poster:
Wrong character

I will change that and send a new PR.

**Comment by miigotu** [comment]
It has to be #set blah = $seasonResults.pop(-1); del $blah

**Comment by MGaetan89** [comment]
I sent a new PR with the proper fix. Seem to work now.
Sorry for the issue :/

**Pull request merged**
