### PR TITLE
Remove torrent file after download

### PR DESCRIPTION
**Pull request by gborri**
For now is it working for transmission client.
Need to be implemented remove_torrent_downloaded for other clients.

Hope not to have mess something with this pull request.

I remember some issue on this topic but have no chance to find it.

### CODE REVIEW

**Comment by fernandog** [comment]
@gborri @abeloin this changes DB version. We can't merge this in soon. We have to wait before everything is stable because users are still switching from master<>develop

**Comment by abeloin** [comment]
@gborri Please revert the changes to sickbeard/webserve.py, it should remove the config launch browser.

**Comment by gborri** [comment]
Sorry about that. I had to make a new pull request, this branch was messed up.

**Comment by gborri** [comment]
the new one: #1397

**Pull request closed without merging**
