### PR TITLE
Render a badge with error count on Logs & Errors

### PR DESCRIPTION
**Pull request by VinceVal**
This also removes PageTemplate.arguments['menu'] which I don't think is being used anymore.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
in the future we should add a warning count like errors

**Comment by miigotu** [comment]
@VinceVal conflict.

**Comment by fernandog** [comment]
as soon this PR gets merged I will try to add the warnings

what do you think miigotu?

image

**Comment by fernandog** [comment]
it should add the numbers for warnings in the submenu title

**Pull request merged**
