### PR TITLE
Fix for when seeders/Leechers is "---" instead of a number

### PR DESCRIPTION
**Pull request by duramato**
fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/3028

### CODE REVIEW

**Comment by miigotu** [comment]
that won't work. you can't compare ints and strings.

you need helpers.tryInt

**Comment by duramato** [comment]
@miigotu like this ?```
                        seeders = helpers.tryInt(item['seeders']) or 0
                        leechers = helpers.tryInt(item['leechers']) or 0

**Comment by fernandog** [comment]
helpers.tryInt(item['seeders'],0)

**Comment by duramato** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/2655

**Pull request closed without merging**
