### PR TITLE
Use mako global variables instead of calling `sickbeard.*`

### PR DESCRIPTION
**Pull request by MGaetan89**
Some global mako/template variables were defined in `webserve`.
This PR use them instead of calling `sickbeard.*` directly.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by miigotu** [comment]
@MGaetan89 I kinda like moving the other way (use sickbeard.* instead). sickbeard is imported anyways This way we might be able to eliminate some of those vars.

On the other hand, if you go the route of this PR then sickbeard should not be imported and just vars from sickbeard should be passed as arguments to render.

Thoughts?

**Comment by MGaetan89** [comment]
I agree with your first idea to remove those vars.
I just tried to unify everything with this PR:

**Comment by miigotu** [comment]
Lets sit on this one then and maybe get some more input.

**Comment by OmgImAlexis** [comment]
I'd much rather see everything to go `sickbeard.VAR` as they're seen as constants and leave just the variables within that files as normal vars.

**Comment by miigotu** [comment]
@MGaetan89 @OmgImAlexis lets go the other route then, use sickbeard.THE_VAR wherever possible instead of passing it in. This makes sure the true value is always used rather than whatever it was the last time the local variable was set. We need the true value always in mako if we ever hope to use ajax.

**Pull request closed without merging**
