### PR TITLE
Upped RARBG's cache checking interval to 10min

### PR DESCRIPTION
**Pull request by ROpdebee**
Seems like refreshing RARBG's cache every 5 minutes is a bit of overkill, no?

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
They release a LOT. We have direct contact with the owner. No issues with them

**Comment by ROpdebee** [comment]
Surely they don't release a whole page full of releases in 5 minutes? But okay as you will, allow me to edit the comment then so other noobs don't make the same mistake as me lol

**Comment by fernandog** [comment]
make it 10 so all providers are the same

**Comment by ROpdebee** [comment]
done lol

**Comment by fernandog** [comment]
squash please

**Comment by ROpdebee** [comment]
done, sorry for the wait

**Comment by miigotu** [comment]
10 minutes is still too low, but Ill merge anyways...

**Comment by rarbg** [comment]
@miigotu @fernandog 
With the default limit of 100 that you run on , there is no chance that there will be more than 100 releases in 10 minutes :)

**Comment by miigotu** [comment]
@rarbg yeah I wanted it at 15 or 20 mins, will change it someday soon again.

**Pull request merged**
