### PR TITLE
Update deluged_client.py

### PR DESCRIPTION
**Pull request by jalim**
Add move completed to path functionality to Deluge Daemon.

### CODE REVIEW

**Comment by miigotu** [comment]
@jalim appreciate this, however we cant allow PR to master. You must PR to develop.

**Comment by MGaetan89** [comment]
I'm sure it's possible to make the Travis build fail when a PR is made to `master`.
So people know when they choose the wrong branch, and the error should explain why it fails. Adding a [`Contributing.md`](https://github.com/blog/1184-contributing-guidelines) file at the root of the project may help too.
An other idea: set the default branch to `develop` instead of `master`.

**Comment by miigotu** [comment]
@MGaetan89 we cant set the default branch to develop or all new users will be checking out develop by default...

**Comment by miigotu** [comment]
@MGaetan89 also, there is a SiCKRAGETV/SickRage/blob/master/contributing.md

**Comment by MGaetan89** [comment]
@miigotu Good points. I don't know how I missed the contributing file ...

**Pull request closed without merging**
