### PR TITLE
Random 403 : user_agents list was broken

### PR DESCRIPTION
**Pull request by gboddin**
All HTTP(s) requests might be affected :

 - Commas were missing in the user_agents list, python is treating it as a full string
 - As a result, providers/generic.py uses a user_agent which is too long and causes 403 on providers behind cloudflare (for instance)

Adding the missing commas fixes the issue.

### CODE REVIEW

**Comment by philuxe** [comment]
I have added the missing commas but still getting the same error :+1: 
[T411]::Unable to connect to provider
[T411]::Requested getURL https://api.t411.in/auth returned status code is 403: Forbidden
[T411]::"POST /auth HTTP/1.1" 403 None

**Comment by gboddin** [comment]
Try to : stop Sickrage, remove common.pyc, start Sickrage.

Btw, it seems this repo is dying ... I switched to https://github.com/sickrage/sickrage which accepted the fix (for now).

**Comment by philuxe** [comment]
@gboddin thx dude, it's working now

**Comment by philuxe** [comment]
what do u mean by the "the repo is dying ?"

**Comment by Arcanemagus** [comment]
@echel0n kicked the entire development team out when he came back after a year of doing nothing, the team that has been working on the project for the last year moved to the repo @gboddin linked (the "malicious" one as @echel0n calls it).

Long story short:
This repo has 112 commits, almost entirely by @echel0n since he has been closing most PRs with no comments.
The new repo has 1,553 commits and actually handles people working on it :wink:

For more information see https://github.com/SickRage/sickrage-issues/issues/3.

**Comment by Djang0** [comment]
Hi,
If you want travis check to succeed, you should refer to this commit : https://github.com/Djang0/SickRage/commit/fba190cb92d5e4885ab3f7ee40c5ad9e00a2debb
and merge it to your own fork, then re submitting the pull request.

**Comment by gboddin** [comment]
Naaah thanks ...

**Pull request closed without merging**
