### PR TITLE
Remove Show from SickRage if ended and full watched

### PR DESCRIPTION
**Pull request by gborri**

### CODE REVIEW

**Comment by miigotu** [comment]
Most people don't want to do this. Just because I watched all of a show I should remove it from sickrage? Um no.

**Comment by gborri** [comment]
@miigotu it works only with trakt integration enabled. In this case the watched history is on trakt. By the way, I will make it configurable. Most of the people don't, but some will.

**Comment by miigotu** [comment]
I use trakt, to keep track of what I have watched over time, and to keep wanted lists.
When i finish a show, I usually keep it for family members to watch. Especially my kids' cartoons, which they watch the entire series over and over.

It's easy to let people look at your SR page to see what you have/don't have to pick something to watch ^

**Comment by gborri** [comment]
@miigotu i'm used to remove show after finished to watch. If I make the deletion of show configurable, it's fine for you? So everyone can decide which behavior to adopt?

**Comment by Arcanemagus** [comment]
Just make sure you make the default disabled if this gets merged in. I can see how some people would find this useful but I for one would never want this functionality.

**Comment by miigotu** [comment]
As long as the default is disabled it is fine.

**Comment by abetancort** [comment]
I fully support that the change makes it on the master in my name and that of Ludwig Mies van der Rohe who alway said that "Less was more".

**Comment by miigotu** [comment]
@abetancort I agree lol, I have been severely interested in removing things that are unnecessary and simplifying everything as much as possible. Massive monkey patching and feature adding over time has made the source quite sloppy/disorganized and with much duplicate code.

More == much harder to keep stability, since there are more things to go wrong.

**Comment by Hellowlol** [comment]
I think this is a nice feature. I would never use it my self, as I don't delete anything, but I see it's usefulness for ppl using sickrage as a pvr.

**Comment by abetancort** [comment]
Maybe it's time to stop and go back to the basics. Some quality time standing still in front of a mirror while figuring out what to get rid and how to go become more but with less.  

Alfonso C.  Betancort
Móvil:	     +34 636 044 603
Skype:	     alfonso@betancort.net
Hangouts:    alfonso@betancort.net	
Enviado desde mi iPad Air…


El 28/6/2015, a las 6:53, miigotu <notifications@github.com> escribió:

@abetancort I agree lol, I have been severely interested in removing things that are unnecessary and simplifying everything as much as possible. Massive monkey patching and feature adding over time has made the source quite sloppy/disorganized and with much duplicate code.

More == much harder to keep stability, since there are more things to go wrong.

**Comment by Hellowlol** [comment]
You can't become more with less. It's impossible. Your code may be shorter, less errors prone and the best part your don't have maintain stuff that does not exist, but more? No way. You would need to define the scope of your project and reject anything outside your scope.

**Comment by miigotu** [comment]
@Hellowlol its a figure of speech. It's just meaning you have `more` support, followers, users, recognition with `less` errors, code, configuration, learning curve.

From my years of experience in maintaining various projects in many different languages, this is generally true. I do agree there are exactly 2 types of users though... 1 who wants every possible option/feature/configuration possible, and another who wants simplicity, stability, and reliability over all.

My strategy is usually to start off transforming a project by initially limiting new feature additions as much as possibly while the current code base is streamlined and thoroughly optimized and tested.

After that stage has passed, the best strategy is usually to add features slowly and with great oversight and testing in between. Trivial changes are met with the same skepticism/oversight as major changes, but are quickly integrated if there is evidence of user demand, while major changes are planned deeper and take much more time and testing.

Occasionally, it becomes necessary to start over at that initial stage, and more closely look at how all of the new code interfaces with older code in order to better embed it into the original program flow.

Now this PR, it is really trivial as long as it is properly documented and is optional, and disabled by default. This means it is not a big deal to add it, but I would much rather see resources and time being spent on current problems being worked out rather than features.

ie: In related code, shows removed from SR are sometimes soon added back by trakt, because there is a missing call to remove it from the watchlist.  Also, there is that 'index out of range' exception in the trakt code.

I have been approving some smaller features/additions to keep the feeling of progress alive, but we are 100% in a refactoring and bugfixing stage. It will be this way for the foreseeable future until SR is bug free.

Anyone wanna take a crack at why SR uses 1.5GB of memory on boot when there is no cache present (new boot/cache clear)??? Lol, thats what I have been doing.

**Comment by Hellowlol** [comment]
@miigotu thanks for your answer. I like and agree with your strategy. 

As Python is a easy language to get started with your likely to get prs from hobby programmers (like me), people are  "selfish bastards" only doing x to be able to do y. I can use myself as a example, the only bug fix / optimation I have done is reducing excecuting time of mappedtoineexers as it made htpc manager slow, the rest is new stuff to the api. 

Heavy lifting to generally left to the maintainers/core developers. As for the the huge memory usage during startup, I wouldn't even know where to begin.. And ram is cheap ;)

**Comment by miigotu** [comment]
Ram is cheap but it left my activity led on 100% until it passed (sometimes 20 minutes+)... was due to sql only happening in memory and no commits to db, ending in thousands of cached sql queries, and subsequent queries failing due to noncommitted data. Fixed =P

**Comment by abetancort** [comment]
@Hellowlol 

It's probably one the hardest thing to master in life, but nonetheless achievable and doing "more with less" is what separates geniality from the average; It's not something either mine or new, check who was Ludwig Mies van der Rohe because as he pointed out "the devil (God) is in the details".
 
Dieter Rams reconizes him as one of his forefathers. Dieter is the genius behind iconic designs of Braun –the German firm– during the second half of the XX century, he advanced on Mies design philosophy into what is still known as the bible of design that can be summarized in his “Ten Principles of Good Design”.

Which in turn has been the inspiration of many other geniuses in their respective fields, which range from architecture, furniture, industrial, typography, graphic, interior design, art in general, management, economics, sociology, psychology, structural, material, chemical, electrical engineering, etc... to software and hardware design.

image

The spirit of this design philosophy can be best summarized with just one sentence: "Perfection is finally attained not when there is no longer anything to add, but when there is no longer anything to take away." from Terre des Hommes 1933 by Antoine de Saint-Exupéry (a French aviator, author of the novella "The Little Prince", nowadays still among the top three selling books in the world).

I'll only give an example of someone that has been inspired by this design philosophy, just to show that not only it's feasible but it can be advanced even further while delivering successfully products that most users crave.

Steve Jobs when he took over Pixar Inc. and with the team (John Lasseter et al.) managed to make the then unknow studio the worldwide reference in animation, almost concurrently when he was rehired by the board of Apple Computers Inc. and met Jonny Ives convincing  him not to quit his post in Apple's Design Despartment. From his first keynote -closing the deal with Bill Gates to inject $100 million in new shares and the continued development of MsOffice for Mac OS- the iMac and iPod, until their latest MacBook, OS X El Capitan and iOS 9 under the oversight of Tim Cook.

Apple has not only followed this design philosophy without interruption, but it has put itself at the forefront of its advancement, development and refinement.  In Apple, user experience takes center stage, while hardware specifications do take a step into the back, as they approach their products holistically blurring the boundary between hardware and software.  

By the way, from the huge pile of cash they have today, and knowing that they had to beg for pocket change to the then almighty Bill Gates (it wasn't that long ago)... And just an informed guess, they must have been doing a couple of things right at least.

**Comment by miigotu** [comment]
less configuration = more self explanatory =P
less user interaction = more productive app/people
/spam off
/PRJacking off

**Comment by Hellowlol** [comment]
It know the expression. I just think it's faulty to assume it's always true. I see sr as a enthusiast product, if you want something easier use popcorn time or Netflix. Apple huge success is simple, good design, makes the most of the hardware, everything just works. As long as you use the product as they have intended(locked it in). Else you fucked (and I'm writing this from a iPhone..)

**Comment by Hellowlol** [comment]
@miigotu Wheres the fix? I'm curious how you fixed it.

**Comment by abetancort** [comment]
@Hellowlol let's not hijack the development thread ;-)

**Comment by abetancort** [comment]
###### Why do you need all the TV shows you ever watched on "display" in Shows on Sickrage?

1 **My personal experience**: the day before yesterday, I don't know exactly what happened, but I'm pretty sure it was strictly my fault: I may have forced a full sync with Trakt, brought every dam show I ever watched to Sickrage (I use Plex to directly update what I watch thru a plugin from the Unsupported AppStore) and have been keeping track of what I have see since like ever (I started streaming when Fraiser was airing its first season)... 

2 **Experience**: I can assure anyone that it's a pain to navigate thru pages and pages of shows to check the one that is airing or what I want to snatch or new shows pushed thru my watched list on tratk... 

3 **Solution**: I have ended doing  
i) Wasting endless hours deleting shows while constantly auto-refreshing an already overloaded web page. 
ii) From know on the web interface is going to stay light.  if I haven't finished a show show that's over (discontinued), I have finished downloading or I want to discontinue watching is going to be moved asap to another folder that Plex knows about but Sickrage don't.  

###### _I wonder again why anyone would really want/need Sickrage to display the shows referred in 3.ii in the Shows main page (that doesn't meant Sickrage not knowing about them)._ **What for?** 

i) It only makes the navigation slower, cumbersome and gives a huge kicks the butt to the whole user experience. 
ii) It's totally ineffective and inefficient.
iii) it's a waste of screen real state, cycles, memory, HD space in both the client and the server by making it maintaining, load, and cache assets you don't really need nor want to see. 
iv) Of course the system has to know about these shows, but computers are more fond of bits than formatted webpages and they don't care about posters, images and other similar assets.

###### Why would you want the computer know?

i) SickRage can prevent you from accidentally starting a massive redownload.
ii) SickRage can, after the proper warning, allow you to easily to restore a tvshow back to your Shows in its state previous to "hibernation". a) You might want to continue watching because you kind of miss the show you decided to stop viewing. b) Want to redownload all or part of it to see again alone, with your partner, a friend, your grownup kid, to share it with friend & family that doesn't have a fiber 1Gb Internet connection or whatever.

**Comment by fernandog** [comment]
"navigate thru pages and pages of shows to check the one that is airing or what I want to snatch"

Just the filter it. Hover the mouse in columns names.

**Comment by abetancort** [comment]
@fernando Thanks I'll see how it goes.

**Comment by gborri** [comment]
@miigotu I didn't thought that this small feature could make this log discussion. Bu the way, 

"ie: In related code, shows removed from SR are sometimes soon added back by trakt, because there is a missing call to remove it from the watchlist. Also, there is that 'index out of range' exception in the trakt code." 

It's not really true, in show.deleteShow there is the function which remove show from watchlist. This PR make automatic what today is manually.

The "index out of range" is related to trakt sending empty array.

**Comment by gborri** [comment]
sorry closed by mistake.

**Comment by abetancort** [comment]
@miigotu 

The reappearing shows (resuscitating phenomenon) happened to me too (so it's not an isolated occurrence). 

It's so persistent that I had to stop Trakt Notifications, delete the shows from SR and then take them out from my Trakt watchlist and restart Trakt Notifications on SR. That way I was finally able to get rid of all the resuscitating shows, once and for all.  By the way, I didn't get any errors on SR while the resuscitation was going on... 

Maybe it's not SR fault but just a bug that creeped into the Trakt API that return a true value when you tell it to take the show from the Wachlist. But since the requester (SR) doesn't perform the test of randomly requesting back the new Wachlist to check for inconsistencies it may have gone unnoticed to both parties. Thus no one its aware of the bug, much les reported it yet.

I will try to replicate it again and have a look at the SR debug logs to see if I'm right or not...

**Comment by gborri** [comment]
@miigotu @abeloin are you sure that there were no episode in state wanted? because if there is an episode in the watch list it will re-add the show and set that episode to wanted. if this is a scenario the fix is simple, remove bot show and episode from watchlist.

**Comment by gborri** [comment]
@miigotu @abetancort otherwise the problem could be relate to the remove event not managed by trakt. You need to see for error it is catched by trakt or otherwise the problem is in trakt and no error is returned. It's possible to implement a retry procedure: on traktchecker process we can look for episode in watchlist and remove all show not present on sickrage.

**Comment by gborri** [comment]
@miigotu @abeloin @fernandog I've added the possibility to enable/disable show remove and set default to False. I've also sqashed the commit.

**Comment by fernandog** [comment]
@gborri if user don't delete files, when adding a show it will appear again

**Comment by alzeric** [comment]
Excuse me for butting into this thread, but AFAIK SickRage isn't designed
to manage your movie collection, something like Plex is more suited for
that.  I was under the impression that SickRage was a download manager that
assisted in completing your collection and track up-coming shows.  Honestly
I feel that the downloader has no business handling deleting watched
episodes, however I do understand that people want to use SickRage in their
own manner, but this is kinda getting into left field as to the purpose
SickRage is designed for.  I personally feel this would be better suited in
it's own branch rather then the main production branch.

Granted this is a feature I would never use on my own, i'm just not that
comfortable with something 'Auto' deleting anything on my systems and would
rather manually go through and select if and when I want to delete
something.

**Comment by gborri** [comment]
@ alzeric with this PR you could manage as you described: manually. The point is not to delete media but remove show from . also in sickrage. Also today the software give you the ability to remove media on confirmation, this behavior is not introduced with this PR. Personally I use  and let it manage media and the deletion of the media but I can't dkodisickrage the operation of deletion show from sickrage. The point of this PR is only automation.

**Comment by gborri** [comment]
@miigotu do you think is mergeable?

**Comment by miigotu** [comment]
Sure, but no more features for awhile lol, we need the problems fixed for now.

**Comment by gborri** [comment]
@miigotu ok thanks.

**Pull request merged**
