### PR TITLE
Only keep /cache/images. Delete everything else...

### PR DESCRIPTION
**Pull request by fernandog**
when git clean and update

https://github.com/SiCKRAGETV/sickrage-issues/issues/2661

### CODE REVIEW

**Comment by WebSpider** [comment]
We should also keep provider information cached, no?

**Comment by fernandog** [comment]
rss?

**Comment by WebSpider** [comment]
I was more thinking of indexers .. And on my NAS install i also see subtitle caches, but those maybe from ancient times.

**Comment by MGaetan89** [comment]
I think this is wrong. This will ignore `/cache/images` in Git, but will track every other files/folders in `/cache/`.
I propose the following rules, instead of `/cache/images/`:
```
!/cache/
/cache/*
!/cache/images/
```

See: http://stackoverflow.com/a/5534865/1914223

**Comment by fernandog** [comment]
@MGaetan89 I tried that too. it's erasing cache folder

**Comment by miigotu** [comment]
maybe
```
/cache/
!/cache/mako/
!/cache/sessions/
```

**Comment by fernandog** [comment]
don't work either

**Comment by miigotu** [comment]
This wont work anyways, because git will show it as untracked files then. need to delete the with code instead, when restarting from the updater.

**Comment by OmgImAlexis** [comment]
You might also want to delete directories such as `cache-20150908_213838` or add them to the .gitignore, they get created when you import a backup.

**Pull request merged**
