### PR TITLE
Add SATRip to SDTV

### PR DESCRIPTION
**Pull request by duramato**

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by WebSpider** [comment]
Is satrip scene compliant?

**Comment by miigotu** [comment]
Negative.

**Comment by duramato** [comment]
@WebSpider I cant say it is but it seems so 
Im saying it is becouse if you take a look at any preDB you will see that all of them are ```WS.SATRiP.x264``` or ```SATRip.XviD``` or ```WS.SATRiP.XviD```

**Comment by duramato** [comment]
@miigotu why not? from what what i see this is used for GERMAN scene ,the same way Australian scene releases as PDTV

**Comment by WebSpider** [comment]
WS and FS tags are banned anyways as per https://scenerules.org/t.html?id=2012_SDTVx264_u1.nfo

**Comment by duramato** [comment]
@WebSpider https://scenerules.org/t.html?id=2011_DE_TV.nfo (you will need to translate)

**Comment by SiCKRAGEB0T** [comment]
Thanks for the link! Im Dutch, so german should not be too hard :)

-----Original Message-----

**Comment by WebSpider** [comment]
Lol i am going To change that email adress for the bot account so that that doesn't occur anymore

**Comment by WebSpider** [comment]
@duramato it seems satrip is onlynallowed for xvid in the link you gave, so should we allow h/x264/5 ?

**Comment by duramato** [comment]
@WebSpider i added it to that becouse i saw some releases with x264 on a preDB ,but it could changed

**Pull request merged**
