### PR TITLE
Add TorrentProject link

### PR DESCRIPTION
**Pull request by duramato**
@fernandog & @miigotu is this ok with you guys?

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by miigotu** [comment]
It has to be worded different or something. That makes it seem like its the basis for all of SR =P.  We have dozens of providers....

**Comment by duramato** [comment]
@miigotu open for suggestions :P

**Comment by miigotu** [comment]
Maybe "Supported by..."

Or a wiki page with all of the providers and links, and add a link to the wiki page to the readme....

**Comment by duramato** [comment]
Does this look cool enough? :P
image

**Comment by miigotu** [comment]
Yes, I just feel like it is giving torrentproject preference over other providers that support us also =P

RARBG? NZB.cat? NZBGeek? DogNZB? Others?

@fernandog ?

**Comment by duramato** [comment]
@miigotu add all that are SR friendly too?

**Comment by miigotu** [comment]
@duramato I think that would be more proper than giving only one provider special recognition when they are pretty much equal with the other supporters.

What complicates it is that it makes it seem these are the only providers in SR then. Maybe a full list would be more correct.

This needs discussion.

**Comment by WebSpider** [comment]
I feel torrentproject should stop refusing connections first .... 1940 connection drops in 24hr..

Also: I tend to agree with @miigotu ... They are "just another provider" ... we would have to mention everyone that sponsors the project then.

**Comment by duramato** [comment]
@WebSpider it has all been fixed.. it was SR DDOSing their server..

**Comment by rarbg** [comment]
Thank you for the link guys :P Even tho its broken :D

**Comment by miigotu** [comment]
Broken?

**Comment by rarbg** [comment]
https://github.com/SiCKRAGETV/SickRage/pull/2992

**Comment by duramato** [comment]
@rarbg ups sorry about that :p

**Pull request merged**
