### PR TITLE
Plex Notification fix

### PR DESCRIPTION
**Pull request by Thraxis**
* Ported the Plex Notification changes from SickGear.
* Added the option to use Plex Token vs Username / Password.

### CODE REVIEW

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1123

**Comment by fernandog** [comment]
@Thraxis everything ok with this one too?

**Comment by Thraxis** [comment]
Was looking good

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1078

**Pull request merged**
