### PR TITLE
Show season dir in File Name column on show page

### PR DESCRIPTION
**Pull request by VinceVal**

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
@VinceVal can you send a screenshot after this PR?

**Comment by VinceVal** [comment]
Before:

image

After:

image

**Comment by fernandog** [comment]
@VinceVal what happens if user has flat folders? Show name will appear instead?

I wouldnt merge this PR as we have the Season x at the top of the table.

**Comment by VinceVal** [comment]
Basically, it removes the show location (what you see at the very top of the page) from the episode location. So yes, if you have flat folders, then you just see the episode filename itself. I like this in there because it shows you where the file actually is instead of having to assume. I've had cases where some of my shows were in "Season 1" and some were in "Season 01" and this helped me see that.

**Comment by fernandog** [comment]
ok. np. thanks

**Pull request merged**
