### PR TITLE
Added srRoot to apibuilder

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Added srRoot to apibuilder otherwise it doesn't work at all if you've got a web_root set.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by MGaetan89** [comment]
Do you really need to set all those meta and include two JS files just to set a variable?
That looks kind of counter-effective for me.

**Comment by OmgImAlexis** [comment]
@mgaetan89 this was just a quick fix. I'm redoing the JS and mako files this/next week. For now I've just copied all the stuff from main.mako

**Comment by MGaetan89** [comment]
It's a bit hard to go twice over the same (already done) file for such a
small change. But why not.

**Comment by OmgImAlexis** [comment]
@MGaetan89 I'm looking at splitting the mako files up more this will also mean you can use a layout file for apibuilder and only include the actual body, etc. in it like the other files.

**Comment by MGaetan89** [comment]
I could have done it with the main.mako file, no?
I tried to to keep the apibuilder file simple as it's a single page.

**Comment by OmgImAlexis** [comment]
@MGaetan89 yes and no, I'm guessing you'll want to header different in the apibuilder, I'm still looking into the best way to change that. I'm assuming we can just do the same as the blocks for scripts, etc. but add content into the original block. So if you don't have a block for header in your child view it'll keep the "default", if you do it'll override it.

**Pull request merged**
