### PR TITLE
Add result sorting for providers

### PR DESCRIPTION
**Pull request by fernandog**
when I have more time will check the others

@miigotu 

@duramato this?

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
@miigotu 
also need to add to all

    def _get_size(self, item):
        ***** = item
        if not size:
            size = 0
        return size

**Comment by fernandog** [comment]
@miigotu will set size = 0, leechers = 0 and seed = 1 for providers that don't have this parsing fields, ok?

**Comment by fernandog** [comment]
@miigotu can I add this to generic.py ?

don't need to be         title, url, id, seeders, leechers = item
```
    def _get_title_and_url(self, item):
    
        title = item[0]
        
        if title:
            title = self._clean_title_from_provider(title)

        if download_url:
            download_url = url.replace('&amp;', '&')

        return (title, download_url)


    def _get_size(self, item):

        size = item[2]
        
        if not size:
            size = -1
            
        return size
```

**Comment by Jopand** [comment]
This check-in causes nextgen.py to stop working. It generates an exception, when parsing leechers
It is checking for "ac t_leechers" which isn't there.

The valid html containing leechers info is:
<div id="torrent-leechers"><b><a class="1" href="details.php?id=603159&amp;dllist=1#leechers">1</a></b></div>

and this when there are no leechers:
<div id="torrent-leechers">0</div>

**Comment by miigotu** [comment]
`seeders = int(result.find('div', attrs = {'id' : 'torrent-seeders'}).find('a')['class'][0])`

It isnt checking anything remotely similar to `ac t_leechers`

**Comment by Jopand** [comment]
Try Line 176 in nextgen.py:
leechers = int(result.find('td', attrs = {'class' : 'ac t_leechers'}).string)

I would say that it's pretty similar to "ac t_leechers". . .

**Comment by miigotu** [comment]
@Jopand I will fix that when I get home.

**Comment by Jopand** [comment]
Great:-) 
One more thing: I just tried setting leechers to 0 to avoid that parsing error. Then I got an error saying something about minSeeders and minLeechers. They have to be set to None. It is done in many of the other torrent provider scripts, but not in nextgen...

Also the nextgen url is now nxtgn.info (just changed a couple of days ago)

**Comment by miigotu** [comment]
The url is not changing in code until their irc is back up and I can verify the change.

**Comment by miigotu** [comment]
@Jopand it would be great to get the htmlm for a complete search item, so I can try and parse size from it.

**Comment by Jopand** [comment]
@miigotu According to their homepage, the irc should be back up on irc.nxtgn.info. If I access the site using the old url (nxgn.org), I get redirected to nxtgn.info, but as they say, it's only a matter of time untill that old url is closed. So I really don't see why you shouldn't change the urls.

I've made an example html-file with a search for "the americans s03". It has results containing 0 leechers and more than 0 leechers, and should be parsed in different ways.
I cannot attach it here because of missing write permissions to this repository :-S I'll send you a mail with it right away, so if you don't have it, check your spam folder.

Remember the minSeeders and minLeechers or else you'll just get another error. Happy coding :-)

**Comment by miigotu** [comment]
@Jopand Ive already fixed the seeders/leechers parsing, and minseed and minleech params.

Im only looking to add size parsing to this provider.

**Comment by Jopand** [comment]
@miigotu No, you are not there yet... :-S
As I've said 2 times, there is a difference between 0 leechers and more than 0 leechers...

If there are any leechers, your fix is working, because there is an "a" element containing the number of leechers.
If there are no leechers, there is no "a" element.

**Comment by miigotu** [comment]
Where do you see a in this?
`leechers = int(result.find('div', attrs = {'id' : 'torrent-leechers'}).text)`

**Comment by miigotu** [comment]
My code works as it is now since my PR. Please check develop.

**Comment by Jopand** [comment]
5'ish minutes ago, there was an 'a', but seems like you've fixed it.
I'll test it on my nas and report back if anything goes wrong. You still don't wanna update the url? PLEEEASE :-D

**Comment by Jopand** [comment]
I just tested the nextgen.py from the development branch (all other files are from master branch).
I'm getting the following error:

2015-10-15 10:54:13 DEBUG    SEARCHQUEUE-MANUAL-295743 :: [NextGen] :: Search string: Limitless S01E01 
2015-10-15 10:54:13 DEBUG    SEARCHQUEUE-MANUAL-295743 :: [NextGen] :: Search URL: https://nxgn.org/browse.php?search=Limitless%20S01E01&cat=0&incldead=0&modes=&c7=1&c24=1&c17=1&c22=1&c42=1&c46=1&c26=1&c28=1&c43=1&c4=1&c31=1&c45=1&c33=1
2015-10-15 10:54:25 ERROR    SEARCHQUEUE-MANUAL-295743 :: [NextGen] :: Failed parsing provider. Traceback: Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/providers/nextgen.py", line 164, in _doSearch
    download_url = self.urls['base_url'] + result.find('div', attrs={'id': 'torrent-download'}).a['id']
  File "/usr/local/sickrage/var/SickRage/lib/bs4/element.py", line 905, in __getitem__
    return self.attrs[key]
KeyError: 'id'
Traceback (most recent call last):
  File "/volume1/@appstore/sickrage/var/SickRage/sickbeard/providers/nextgen.py", line 164, in _doSearch
    download_url = self.urls['base_url'] + result.find('div', attrs={'id': 'torrent-download'}).a['id']
  File "/usr/local/sickrage/var/SickRage/lib/bs4/element.py", line 905, in __getitem__
    return self.attrs[key]
KeyError: 'id'

**Comment by miigotu** [comment]
Checking it now. This is a pain without real access...

**Comment by miigotu** [comment]
@Jopand added a commit to devel, pull and try again, thanks.

**Comment by Jopand** [comment]
It is not crashing, but it doesn't solve the problem. It generates an exception at the same line resulting in no parsed item, so it doesn't download any torrents.

**Comment by miigotu** [comment]
Its supposed to generate the exception and be caught there, and then skip to the next item, unless the data you gave me is inaccurate or incomplete.

```python
>>> with open('/home/dusted/Downloads/Nxtgn example.htm', 'r') as page:
...     data = page.read()
... 
>>> html = soup(data, features=["html5lib", "permissive"])
>>> resultsTable = html.find('div', attrs={'id': 'torrent-table-wrapper'})
>>> entries_std = html.find_all('div', attrs={'id': 'torrent-std'})
>>> entries_sticky = html.find_all('div', attrs={'id': 'torrent-sticky'})
>>> entries = entries_std + entries_sticky
>>> for result in entries:
...     title = result.find('div', attrs={'id': 'torrent-udgivelse2-users'}).a['title']
...     download_url = 'https://nxgn.org/' + result.find('div', attrs={'id': 'torrent-download'}).a['id']
...     seeders = int(result.find('div', attrs={'id' : 'torrent-seeders'}).text)
...     leechers = int(result.find('div', attrs={'id' : 'torrent-leechers'}).text)
...     size = result.find('div', attrs={'id' : 'torrent-size'}).text
...     freeleech = result.find('div', attrs={'id': 'browse-mode-F2L'}) is not None
...     print seeders, leechers, freeleech, size, title, download_url
... 
21 1 True 18.081GB The.Americans.S03.Custom.DKsubs.720p.HDTV.x264-RAPiDCOWS https://nxgn.org/download.php?id=603287
8 0 True 2.499GB The.Americans.S03E12-13.Custom.DKsubs.720p.HDTV.x264-RAPiDCOWS https://nxgn.org/download.php?id=603159
5 0 True 2.492GB The.Americans.S03E10-11.Custom.DKsubs.720p.HDTV.x264-RAPiDCOWS https://nxgn.org/download.php?id=602667
5 0 True 1.408GB The.Americans.S03E09.Custom.DKsubs.720p.HDTV.x264-RAPiDCOWS https://nxgn.org/download.php?id=602388
4 0 True 1.445GB The.Americans.S03E08.Custom.DKsubs.720p.HDTV.x264-RAPiDCOWS https://nxgn.org/download.php?id=602251
5 0 True 2.879GB The.Americans.S03E06-07.Custom.DKsubs.720p.HDTV.x264-RAPiDCOWS https://nxgn.org/download.php?id=591950
2 0 False 215.45MB The.Americans.2013.S03E12.HDTV.x264-KILLERS https://nxgn.org/download.php?id=576282
5 0 True 1.372GB The.Americans.S03E05.Custom.DKsubs.720p.HDTV.x264-RAPiDCOWS https://nxgn.org/download.php?id=575058
1 0 False 211.46MB The.Americans.2013.S03E11.INTERNAL.HDTV.x264-BATV https://nxgn.org/download.php?id=573661
2 0 False 208.68MB The.Americans.2013.S03E11.HDTV.x264-ASAP https://nxgn.org/download.php?id=573660
5 0 True 1.394GB The.Americans.S03E04.Custom.DKsubs.720p.HDTV.x264-RAPiDCOWS https://nxgn.org/download.php?id=571762
3 0 False 225.31MB The.Americans.2013.S03E10.HDTV.x264-KILLERS https://nxgn.org/download.php?id=571575
0 1 False 1.317GB The.Americans.2013.S03E10.720p.HDTV.x264-KILLERS https://nxgn.org/download.php?id=571518
2 0 False 230.75MB The.Americans.2013.S03E09.HDTV.x264-KILLERS https://nxgn.org/download.php?id=568487
1 0 False 252.80MB The.Americans.2013.S03E08.PROPER.HDTV.x264-KILLERS https://nxgn.org/download.php?id=565281
1 0 False 239.07MB The.Americans.2013.S03E08.HDTV.x264-ASAP https://nxgn.org/download.php?id=565274
5 0 True 1.485GB The.Americans.S03E03.Custom.DKsubs.720p.HDTV.x264-RAPiDCOWS https://nxgn.org/download.php?id=563244
1 0 False 254.22MB The.Americans.2013.S03E07.INTERNAL.HDTV.x264-BATV https://nxgn.org/download.php?id=562200
1 0 False 1.215GB The.Americans.2013.S03E07.720p.HDTV.x264-IMMERSE https://nxgn.org/download.php?id=562188
1 0 False 261.22MB The.Americans.2013.S03E07.HDTV.x264-ASAP https://nxgn.org/download.php?id=562184
1 0 False 1.473GB The.Americans.2013.S03E06.720p.HDTV.x264-KILLERS https://nxgn.org/download.php?id=559112
1 0 False 264.47MB The.Americans.2013.S03E06.HDTV.x264-KILLERS https://nxgn.org/download.php?id=559099
1 0 False 257.10MB The.Americans.2013.S03E05.HDTV.x264-KILLERS https://nxgn.org/download.php?id=556092
1 0 False 1.407GB The.Americans.2013.S03E05.720p.HDTV.x264-KILLERS https://nxgn.org/download.php?id=556043
7 0 True 1.431GB The.Americans.S03E02.Custom.DKsubs.720p.HDTV.x264-RAPiDCOWS https://nxgn.org/download.php?id=555808
9 0 True 1.676GB The.Americans.S03E01.Custom.DKsubs.720p.HDTV.x264-RAPiDCOWS https://nxgn.org/download.php?id=550770
1 0 False 291.18MB The.Americans.2013.S03E03.HDTV.x264-KILLERS https://nxgn.org/download.php?id=550063
1 0 False 259.66MB The.Americans.2013.S03E02.HDTV.x264-KILLERS https://nxgn.org/download.php?id=546884
1 0 False 301.41MB The.Americans.2013.S03E01.REPACK.HDTV.x264-KILLERS https://nxgn.org/download.php?id=544032
>>> 
```

**Comment by Jopand** [comment]
I've sent you a new example with "Limitless" it finds 4 results, but they all fail... That's kind of a problem :-)

**Comment by miigotu** [comment]
```python
>>> for result in entries:
...     title = result.find('div', attrs={'id': 'torrent-udgivelse2-users'}).a['title']
...     download_url = 'https://nxgn.org/' + result.find('div', attrs={'id': 'torrent-download'}).a['id']
...     seeders = int(result.find('div', attrs={'id' : 'torrent-seeders'}).text)
...     leechers = int(result.find('div', attrs={'id' : 'torrent-leechers'}).text)
...     size = _convertSize(result.find('div', attrs={'id' : 'torrent-size'}).text)
...     freeleech = result.find('div', attrs={'id': 'browse-mode-F2L'}) is not None
...     print seeders, leechers, freeleech, size, title, download_url
... 
Traceback (most recent call last):
  File "<stdin>", line 6, in <module>
TypeError: _convertSize() takes exactly 2 arguments (1 given)
>>> for result in entries:
...     title = result.find('div', attrs={'id': 'torrent-udgivelse2-users'}).a['title']
...     download_url = 'https://nxgn.org/' + result.find('div', attrs={'id': 'torrent-download'}).a['id']
...     seeders = int(result.find('div', attrs={'id' : 'torrent-seeders'}).text)
...     leechers = int(result.find('div', attrs={'id' : 'torrent-leechers'}).text)
...     size = _convertSize(None, result.find('div', attrs={'id' : 'torrent-size'}).text)
...     freeleech = result.find('div', attrs={'id': 'browse-mode-F2L'}) is not None
...     print seeders, leechers, freeleech, size, title, download_url
... 
806 2 True 1099511627.78 Limitless.S01E01.Custom.DKSubs.720p.HDTV.x264-NGSerier https://nxgn.org/download.php?id=627382
18 0 False 1127428915.2 Limitless.S01E01.720p.HDTV.X264-DIMENSION https://nxgn.org/download.php?id=627098
13 0 False 4344359419.9 Limitless.S01E01.1080p.HDTV.X264-DIMENSION https://nxgn.org/download.php?id=627097
5 2 False 345128304.64 Limitless.S01E01.HDTV.x264-LOL https://nxgn.org/download.php?id=626984
```

**Comment by Jopand** [comment]
So what's your conclusion? You are not getting the same error as I am?

**Comment by miigotu** [comment]
Im not getting any error. If you want to lend me your account via email or give me an invite I can verify my code better. Ofc I wouldnt even download anything just testing snatches.

**Comment by Jopand** [comment]
I've sent you an email. Explains why you aren't getting errors.

**Comment by miigotu** [comment]
Test again please.

**Comment by Jopand** [comment]
It didn't work, but changing the urls and 1 line made it work:
changed the download_url parsing line to:"download_url = self.urls['base_url'] + dl['href'] "

**Pull request merged**
