### PR TITLE
Add API methods to check for update and perform update

### PR DESCRIPTION
**Pull request by MGaetan89**
I added the two following methods to SickRage's API:
- `sb.checkversion`:
 - Get information about the current version
 - Get information about the latest version
 - Check if an update is required
 - Get the number of commits between the current version and the latest version
- `sb.update`: update SickRage if necessary

### `sb.checkversion`

Request:

```
GET /?cmd=sb.checkversion
```

Response:

```json
{
    "data": {
        "commits_offset": 0, 
        "current_version": {
            "branch": "develop", 
            "commit": "ddc0fca21d9030612a5c810ecc24463a7f64112b", 
            "version": "v4.0.24"
        }, 
        "latest_version": {
            "branch": "develop", 
            "commit": "3565ec70dc924d8117f506983fc18a9351f487e4", 
            "version": "v4.0.24"
        }, 
        "needs_update": false
    }, 
    "message": "", 
    "result": "success"
}
```

### `sb.update`

Request:

```
GET /?cmd=sb.update
```

Response:

```json
// If no update is necessary
{
    "data": {}, 
    "message": "SickRage is already up to date", 
    "result": "failure"
}

// If the config could not be backed up
{
    "data": {}, 
    "message": "SickRage could not backup config ...", 
    "result": "failure"
}

// If an update was started
{
    "data": {}, 
    "message": "SickRage is updating ...", 
    "result": "success"
}
```

I'm not an expert in Python, but I think that my changes in `sickbeard/versionChecker.py` can be improved.

Reference issue: SiCKRAGETV/sickrage-issues#1780

### CODE REVIEW

**Comment by Hellowlol** [comment]
I'd like this :)

**Comment by fernandog** [comment]
@MGaetan89 mind that the update will force a backup so it may take a while before you receive the response.

**Comment by Hellowlol** [comment]
Yeah, would be better if you you have a parameter to return the response so this can be made faster. (see postprocess for a example)

**Comment by fernandog** [comment]
the backup can fail too. "SickRage is updating". There's no guarantee it will finish with success with only that message

**Comment by Hellowlol** [comment]
True, but your could add a message like update initiated or something like that.

**Comment by fernandog** [comment]
@Hellowlol we have this in UI and in LOG

**Comment by Hellowlol** [comment]
Yeah, but that isnt helpfull for api usage its better got get that as a response imo

**Comment by fernandog** [comment]
just check if both are true:
https://github.com/MGaetan89/SickRage/blob/develop/sickbeard/versionChecker.py#L71

**Comment by MGaetan89** [comment]
Didn't think about the response time. Is there a way to improve this?
@Hellowlol in post process, the action is ran before the response is send, independently of the `return_data` parameter. This parameter just tell if you want the generated data or not.

I will update the PR later to include a message if the backup fail or if the update can not be started.

What do you think about adding a code, as suggested in SiCKRAGETV/sickrage-issues#1765, to represent the response stats. In this case, something like:
- `0` if the update was started/done
- `1` if the update could not start
- `2` if the backup failed

Is there a way to document the response?

**Comment by Hellowlol** [comment]
Yes, the call is returned faster so your "app" dont hang. 

I would like to have something like this:

result: True, msg: the update was started/done
result: False, msg: the update could not start
result: False, msg: the backup failed

**Comment by MGaetan89** [comment]
Ok, I would try that and update the PR later with these changes ;)

**Comment by MGaetan89** [comment]
If updated the PR with the discussed changes.

But I'm not sure what I should do about the delay response. I don't think adding a parameter as in PostProcess is a good choice for this case. Any tip?

**Comment by fernandog** [comment]
@MGaetan89 please squash your commits into one

**Comment by MGaetan89** [comment]
Done

**Comment by fernandog** [comment]
@MGaetan89 have you fully tested hard coding lower/higher DB version here?https://github.com/MGaetan89/SickRage/blob/develop/sickbeard/versionChecker.py#L202

https://github.com/SiCKRAGETV/SickRage/pull/1958/files#diff-8b0a4aef502ce3a2e5af5f428fa91dbfL71

why is True instead of == True ?

**Comment by Hellowlol** [comment]
Pep8

**Comment by fernandog** [comment]
I see. thanks

**Comment by MGaetan89** [comment]
I didn't do any extensive test yet. I'm updating my PR to make sure that I'm doing the right thing here.

Concerning PEP8, my IDE (PyCharm) shows me a lot of warning about that (among other things).

**Comment by MGaetan89** [comment]
Thanks for merging.
I didn't do intensive testing. So if you can test it a bit on your side before pushing to `master`, that would be great :wink:

**Comment by MGaetan89** [comment]
I just integrated this in my Android application and it works as expected.
But as @fernandog said, the success response (`SickRage is updating ...`) is not sent immediately.
I will try to change that. Maybe like @Hellowlol said (using a parameter).

**Comment by miigotu** [comment]
What android app? maybe i should be using it lol.

**Comment by MGaetan89** [comment]
I am working on my own Android application for SickRage.
It is not publicly available on the Play Store yet, but you can get it from the GitHub repo [ShowsRage](https://github.com/MGaetan89/ShowsRage) (in the releases or in the Readme) :wink:

**Comment by miigotu** [comment]
I'm slowly getting started on SquidBeard =P

**Comment by MGaetan89** [comment]
If the API remains the same, it should be able to use my app with it too :D

**Comment by Hellowlol** [comment]
Wow, a new "program"? Will it be a plugin based one like xdm? 

I hope it draws attention from the maintainers for the other fork(s). You could make something amazing (but please keep subtitles )

**Comment by miigotu** [comment]
https://github.com/miigotu/SquidBeard

It's just a pipe dream for now, laying out an optimal structure and I will probably work on it slowly.

**Comment by MGaetan89** [comment]
I think it's a good option to try to start something from scratch. It's easier to remove legacy code and old hacks. Good luck with it :)

**Comment by MGaetan89** [comment]
Back to my original question (:stuck_out_tongue:), any idea how I could update the API to return the `SickRage is updating ...` message immediately?

**Comment by miigotu** [comment]
Not sure, I haven't really messed with how the api works much, so I don't know.

**Comment by Hellowlol** [comment]
Check post process command.

**Comment by MGaetan89** [comment]
@miigotu Not necessarely from an API point of view, but maybe a Python approach?

@Hellowlol I looked there, as you suggested me, but I don't understand how it works XD

**Comment by miigotu** [comment]
_responds before the update... sec.

**Comment by miigotu** [comment]
```python
    def run(self):
        _responds(RESULT_SUCCESS, msg="Update attempt in progress ...")
        checkversion = CheckVersion()

        if checkversion.check_for_new_version():
            if checkversion.run_backup_if_safe():
                checkversion.update()
```

**Comment by miigotu** [comment]
This should probably be in a new call though, as success/failure notifications are lost.

Its like throwing piss in the wind, is it gonna blow back in your face? lol

**Comment by fernandog** [comment]
be carefull with that part of code. it prevents an update when backup fails or there's a new DB version.

**Comment by miigotu** [comment]
Thats why the message is "attempting"

**Comment by MGaetan89** [comment]
Thanks for your comments.

What about this? Do you see a downside? I didn't try it yet, I'm just asking for opinion.
I like the "fail-fast" approach of the current version, so I'd like to keep it if possible.

```python
from threading import Timer

def run(self):
    checkversion = CheckVersion()

    if checkversion.check_for_new_version():
        if checkversion.run_backup_if_safe():
            Timer(0.5, checkversion.update).start()

            return _responds(RESULT_SUCCESS, msg="SickRage is updating ...")

        return _responds(RESULT_FAILURE, msg="SickRage could not backup config ...")

    return _responds(RESULT_FAILURE, msg="SickRage is already up to date")
```

**Comment by miigotu** [comment]
The backup is what takes so long, not the actual update.

**Comment by fernandog** [comment]
takes usually less then 60 seconds (raspberry pi = low cpu_

**Comment by miigotu** [comment]
@MGaetan89 Why can't you put a spinner and have a thread wait for the response in your app? That way you don't lose precision just for rpc.

**Comment by MGaetan89** [comment]
@miigotu I can display a spinner while the update is running, and I will do that. I'm just trying to find the best implementation, and not just thinking for my specific use case.
But for a mobile user, I'm not sure that waiting 60s in front of a spinner waiting for a response is a nice thing.

I didn't notice that the backup is the longest step... So maybe you were right about simply notifying about "attempting" to backup and update SickRage.

**Comment by fernandog** [comment]
are we talking about sickrage UI using phone? or another interface?
there's already a UI.notification showing the back is in progress and another one when backup finishes

**Comment by MGaetan89** [comment]
For my use case, I am talking about an Android application (not the mobile web interface).

The (mobile and desktop) web interface of SickRage handles that just fine.

**Comment by fernandog** [comment]
show a message "Backup in progress...". I wouldn't mind waiting <60s

**Comment by miigotu** [comment]
You could make it respond 2x. Respond that the method succeeded, and when it completes.

Your method call should be run in an asynchronous thread, so they just see a spinner in top of the app or in status bar, but can continue using the app

**Comment by fernandog** [comment]
IMHO I wouldnt let use the app while backup is in progress.

**Comment by MGaetan89** [comment]
I agree with @fernandog.

Maybe it's better to keep it like that for the moment, and change it once a proper implementation is found?
For my application, it won't be too difficult to handle that case.

**Pull request merged**
