### PR TITLE
Fix SiCKRAGETV/sickrage-issues/issues/3286

### PR DESCRIPTION
**Pull request by fernandog**
@miigotu @OmgImAlexis

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by miigotu** [comment]
@fernandog and what happens when the user doesnt have https enabled for plex?

**Comment by fernandog** [comment]
so how to handle that? 
@OmgImAlexis said plex will no longer accept http within a year

**Comment by miigotu** [comment]
Is it always enabled at this point?

**Comment by OmgImAlexis** [comment]
@miigotu https is always enabled, the only time it wouldn't be is when the user completely turns off outside connections and that breaks it anyways as it won't be able to allow a user/pass combo and the plex auth token won't be there as it's set my https://plex.tv not the plex software.

**Comment by OmgImAlexis** [comment]
@fernandog @miigotu Can this please be reverted as it causes more issues than it solves.

**Pull request merged**
