### PR TITLE
Use SxxExx pattern in log (2)

### PR DESCRIPTION
**Pull request by fernandog**
@miigotu sorry about zfill. This was done yesterday. I just missed the PR because I want to make sure travis build wont fail.

### CODE REVIEW

**Comment by miigotu** [comment]
Still switching to zfill? I'm confused

**Comment by fernandog** [comment]
i did this yesterday together with the other. but I had to create an PR to make sure it builds ok. the other one I did in UI

**Comment by miigotu** [comment]
I see, just making sure you know zfill is bad. too much extra processing for each log line (and we have a lot of debug logs) it can impact performance. With my way you don;t even need to cast from into to str or str to int.

`"Found episode by absolute_number: %s which is S%02dE%02d" % (absolute_number, season, episode), logger.DEBUG)`

Is so much simpler than:
`"Found episode by absolute_number:" + str(absolute_number) + " which is " + "S" +  str(season).zfill(2) + "E" + str(episode).zfill(2), logger.DEBUG)`

**Comment by fernandog** [comment]
wont do it know. need to redo all logs messages. zfill was easier to change. closing this then. will do in a couple of days

**Pull request closed without merging**
