### PR TITLE
Fix SiCKRAGETV/sickrage-issues#3347

### PR DESCRIPTION
**Pull request by ncksol**
HD-Torrents has some invalid html on the page with search results. This
is a workaround to load the data by avoiding reading the broken html and
not changing soup parser.

P.S. I've also created another PR with a different fix to that issue. Not sure which one would you prefere.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
Both PR fix the issue?

**Comment by ncksol** [comment]
They both do, but different approach. Only one PR is neede to actually fix the issue. I wasn't sure whether changing parser for soup is too big of a change.

**Comment by fernandog** [comment]
and wit this I get:

```
17:57:32 DEBUG::SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Search URL: https://hd-torrents.org/torrents.php?search=Modern+Family+S07E04&active=1&options=0&category[]=59&category[]=60&category[]=30&category[]=38
17:57:32 DEBUG::SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Search string: Modern Family S07E04
17:57:36 ERROR::SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Error while searching HDTorrents, skipping: 'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/search.py", line 491, in searchProviders
    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
  File "/home/osmc/SickRage/sickbeard/providers/generic.py", line 357, in findSearchResults
    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
  File "/home/osmc/SickRage/sickbeard/providers/hdtorrents.py", line 132, in _doSearch
    downloadCells = html.find_all('td', attrs={'title': 'Download'})
TypeError: 'NoneType' object is not callable
17:57:36 DEBUG::SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/search.py", line 491, in searchProviders
    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
  File "/home/osmc/SickRage/sickbeard/providers/generic.py", line 357, in findSearchResults
    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
  File "/home/osmc/SickRage/sickbeard/providers/hdtorrents.py", line 132, in _doSearch
    downloadCells = html.find_all('td', attrs={'title': 'Download'})
TypeError: 'NoneType' object is not callable

17:57:36 ERROR::SEARCHQUEUE-MANUAL-95011 :: [HDTorrents] :: No NZB/Torrent providers found or enabled in the sickrage config for backlog searches. Please check your settings.
Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/search.py", line 491, in searchProviders
    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
  File "/home/osmc/SickRage/sickbeard/providers/generic.py", line 357, in findSearchResults
    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
  File "/home/osmc/SickRage/sickbeard/providers/hdtorrents.py", line 132, in _doSearch
    downloadCells = html.find_all('td', attrs={'title': 'Download'})
TypeError: 'NoneType' object is not callable

```

**Pull request closed without merging**
