### PR TITLE
Added and Corrected several Network icons

### PR DESCRIPTION
**Pull request by Peke**
Added and Corrected several network Icons

### CODE REVIEW

**Comment by miigotu** [comment]
@Peke better than before, but you still committed onto your develop branch again, and made the pull requests from there.

You missed the first two commands, before any changes are made.

# Fetch new commits from upstream/develop
`git fetch upstream` 
# __Create and switch to a new branch to start a new feature/bugfix/addition__:
`git checkout -b my-feature-name upstream/develop`
# Make changes on the new my-feature-name branch and add your changes to the commit and commit them to my-feature-name branch 
`git add thechangedfile anotherchangedfile`
`git commit -m "Your Commit Message"`
(Or you can add all changes and commit in one line: `git commit -a -m "Your commit message"

# Check your commit log, to make sure its one commit like you intended, and the one before is the last commit on upstream/develop. If not, stop here and `rebase -i upstream/develop`
`git log`

#Push the new branch to your fork
`git push -u origin my-feature-name`

Create pull request on gihub.

**Comment by miigotu** [comment]
To make it easy, JUST THIS TIME, to fix your fork again and not have to redo your work again:
```
git branch -m develop add-network icons
git fetch upstream
git checkout -b develop upstream/develop
git push -u -f origin develop
git push -u origin add-network icons
```
ie: rename (-m for move) develop to add-network icons, fetch latest commits from upstream, create new develop based on upstream/develop, push the new develop to your fork forcing (-f) and update (-u) its location to origin, then push add-network icons to origin and update (-u) its location.

You will have to reopen the pull request, as force updating your develop branch will close this one.

**Comment by miigotu** [comment]
Tell you what, I'll merge it just this time, as it's a trivial PR, but please make sure to fix your fork again and follow my instructions to make this simpler for us both next time.

**Comment by miigotu** [comment]
@Peke If you are willing to switch to smartgit or command line I can help you. I plan on writing a guide for smartgit, since I just discovered how easy it is xD.

**Comment by Peke** [comment]
OK, beleive it or not in my 20+ years of coding I never used GIT I'm used to SVN and frankly old habits die hard, so I'm applying same principles here and git approach is different (and great in Open Source approach). I installed smartgit. Looks like Native GIT is missing number of features needed for this project to work as it should. I thought that it would be simple like with SVN eg. change files in your synched fork -> commit changes ->  open Pull request -> .... but as I see it is not that simple. Beside two kids 8-10h worktime I barely have time to access sickrage on Qnap and see what happened and as a coder I appreciate work invested in this and would like to contribute as much as possible.

Thank you for any help provided.

**Comment by miigotu** [comment]
pretty easy with smartgit, as long as you have the upstream url configured.
open smartgit, in bottom left pane right click upstream and click 'push to..', make sure origin is selected as the remote in the popup and check force pushing, and click push....  Fork is now synced.

Then, click the little down arrow next to 'git flow' in the toolbar and click configure, select full gitflow type and click ok.

Now to start a feature, click the arrow next to gitflow and pick start feature (for everything, feature, fix, whatever, unless it is imminent that a hotfix be made in master, then pick start hotfix)
Name the branch descriptively in the popup and select ok. (This will checkout the new branch too)
Make code changes as normal, the top right pan will show a list of changed files, and when you select them the mid-right pane shows a diff. when you have a file selected you can click 'stage' in the toolbar to add it to be committed. Files not staged are not added to commits.
You can commit by cmdline or by clicking commit in the toolbar and continuing coding for more commits, or proceed to push the branch to origin.

When you are ready, click push on the toolbar, and it will push your branch to origin, where you can create a PR from the github website.

Whatever you do, don't ever pick 'Finish Feature' or it will screw up your develop branch (which is fixed next time you select upstream and pick push to -> origin)

This is just the tip of the iceberg of this powerful application.

**Comment by Peke** [comment]
Thank you. I hope I will not screw thing up next time :)

**Pull request merged**
