### PR TITLE
Fixes for Colum Selector on displayShow

### PR DESCRIPTION
**Pull request by Thraxis**
* removes DISPLAY_FILESIZE from UI and config.ini
* fix no column selector for shows with only 1 season
* display all possible columns and hide those not needed to fix saved
column settings not showing correctly between anime / regular shows
* fixed text color for Add Show link on front page in CSS

### CODE REVIEW

**Comment by fernandog** [comment]
@Thraxis did you tested with the DOWNLOAD column too ? It shows a link so you can download the ep from UI when you have the file in your HDD.

@Tagforce @abeloin Cant find the filename column. Did we removed or it was removed before we joined?

**Comment by Thraxis** [comment]
@fernandog filename was turned into a tooltip when you hover over the episode number

The Download column was in there... I think I forgot to pull it's UI options though.

**Comment by fernandog** [comment]
Dont pull.

**Comment by Thraxis** [comment]
* fixed text color for Add Show link on front page in CSS
* adds file name column
* fixes history and mass edit page text for correct color

**Comment by fernandog** [comment]
@Thraxis can you confirm specials section is not working?

**Comment by fernandog** [comment]
@abeloin should we re-add filename again as a column as we now have the ability to hide it?

**Comment by abeloin** [comment]
@Thraxis History isn't fixed with the new patch

**Comment by abeloin** [comment]
@Thraxis This is what I get on a brand new sickrage:
Imgur
Size, subtitle, download shouldn't be there.
Switching show doesn't reset the options so you end with result these(missing chain liking the js code)
Imgur

I'll revert previous code PR it's not ready for prime time.

**Comment by abeloin** [comment]
@fernandog You should remove it from the changes.md https://github.com/SiCKRAGETV/SickRage/pull/1751

**Comment by abeloin** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1198

**Comment by Thraxis** [comment]
@abeloin that's the CSS that's causing the problem with the history page to begin with. 

I'm finding a bigger error though.  Any show with more than 3 seasons.  Season 3 shows the absolute, scene and scene anime columns only on that season.

As well as issue with the anime and non-anime sharing saved columns

I'll combine the two PR's This one and the other and see if I can figure out the season 3 issue and re-up for testing when I've got those worked out.

**Comment by Thraxis** [comment]
Superseded by https://github.com/SiCKRAGETV/SickRage/pull/1754

**Pull request closed without merging**
