### PR TITLE
Fixes fuzzydates being used & fixes if checks in js

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Since Sickrage sometimes uses `True` and sometimes uses `1` we can't be sure which one will be present on the meta tag so we need to use an array to check for either of them.

### CODE REVIEW

**Comment by fernandog** [comment]
working for me, thanks!

what's the range to be in "In about a month" ?

**Comment by OmgImAlexis** [comment]
Bigger than 30, less than 45.
````
 var words = seconds < 45 && substitute($l.seconds, Math.round(seconds)) ||
        seconds < 90 && substitute($l.minute, 1) ||
        minutes < 45 && substitute($l.minutes, Math.round(minutes)) ||
        minutes < 90 && substitute($l.hour, 1) ||
        hours < 24 && substitute($l.hours, Math.round(hours)) ||
        hours < 42 && substitute($l.day, 1) ||
        days < 30 && substitute($l.days, Math.round(days)) ||
        days < 45 && substitute($l.month, 1) ||
        days < 365 && substitute($l.months, Math.round(days / 30)) ||
        years < 1.5 && substitute($l.year, 1) ||
        substitute($l.years, Math.round(years));
````

**Comment by fernandog** [comment]
less equal or just less?

**Comment by OmgImAlexis** [comment]
Less, I think over 45 days converts to months.

**Comment by MGaetan89** [comment]
Why not cast the value to bool and then check if it's true? That's how it is fine in python.

**Comment by OmgImAlexis** [comment]
@MGaetan89 or maybe we could just set one or the other in Python instead of randomly choosing one. @miigotu any ideas why some of these are `1` and some are `True`?

**Comment by MGaetan89** [comment]
@OmgImAlexis I'm doing that in my refactoring when I see `0` and `1` instead of `False` and `True`. But I can't guarantee I won't miss any.

**Comment by OmgImAlexis** [comment]
Okay, for now I'll leave it as is. Once it's refactored let me know and I'll switch this over to `Boolean("True")`.

**Comment by MGaetan89** [comment]
Sounds to good to me.

**Comment by WebSpider** [comment]
Better yet: We should convert the rest of the code to use True/False. It's one of those PHP habits I need to shake myself as well.

-----Original Message-----

**Comment by MGaetan89** [comment]
Converting the code is a WIP ;=

**Pull request merged**
