### PR TITLE
Remove the reload of sys and setdefaultencoding hack that is frowned …

### PR DESCRIPTION
**Pull request by miigotu**
…upon and unpythonic

Will probably cause encoding issues throughout SR that will need to be addressed as they arise (unless we are really lucky!)

### CODE REVIEW

**Comment by miigotu** [comment]
@SiCKRAGETV/moderators can you guys try this before I merge please?

**Comment by fernandog** [comment]
@miigotu no test at all??

**Comment by fernandog** [comment]
"Will probably cause encoding issues throughout SR that will need to be addressed as they arise" - so user's that will do the test?

**Comment by miigotu** [comment]
I tested it myself.

**Comment by labrys** [comment]
@miigotu Sorry I missed this comment, and wouldn't you know I've been doing my testing on Debian all weekend, tried this on Windows...:chart_with_downwards_trend: <br>...and it dies :skull:  a loud :loudspeaker:  horrible :angry:  painful :hocho:  death :exclamation: 
...with itty-bitty explosions :boom: <br>...and a basket of fruit :apple: :tangerine: :grapes: :pineapple: :pear: :peach: :grey_exclamation: 

:hear_no_evil: :see_no_evil: :speak_no_evil: 

Ok, so not quite, but it does fail to start with:
```
Traceback (most recent call last):
  File "SickBeard.py", line 547, in <module>
    SickRage().start()
  File "SickBeard.py", line 177, in start
    (sys.platform.startswith('win') and sys.getwindowsversion()[0] >= 6 and str(sys.stdout.encoding).lower() in ('cp65001', 'charmap')):
AttributeError: 'UnicodeStdout' object has no attribute 'encoding'
```

**Comment by miigotu** [comment]
@labrys I guess you should do a git pull then, that error has been fixed/

**Comment by labrys** [comment]
I just did before I posted that.  Hmm I'll check and make sure I'm running clean.. might be something leftover.

**Comment by labrys** [comment]
But it looks like it was in the `sys.stdout.encoding` should be `sys.stdout.charset`

**Comment by labrys** [comment]
Nope latest dev still has the bug.... cloned a fresh copy of the dev branch into a new directory and got:
```
Traceback (most recent call last):
  File "SickBeard.py", line 523, in <module>
    SickRage().start()
  File "SickBeard.py", line 155, in start
    (sys.platform.startswith('win') and sys.getwindowsversion()[0] >= 6 and str(sys.stdout.encoding).lower() in ('cp65001', 'charmap')):
AttributeError: 'UnicodeStdout' object has no attribute 'encoding'
```

And it's still calling `sys.stdout.encoding` which doesn't  exist it should be `sys.stdout.charset` (at least on windows)

**Comment by miigotu** [comment]
Nope, hachoir changes `sys.stdout` and `sys.stderr`, so it needs to check:
`getattr(sys.stdout, 'device', sys.stdout).encoding.lower()`

**Pull request merged**
