### PR TITLE
Add NZBIndex provider

### PR DESCRIPTION
**Pull request by duramato**
@miigotu ,i think this one should be all ok :)

### CODE REVIEW

**Comment by miigotu** [comment]
I'll have to go over it for result accuracy, but maxage doesn't seem to be handled here.

nzb providers are a bit different

**Comment by duramato** [comment]
@miigotu almost nailed lol , the only thing (which isnt quite a real problem is the releases titles are like this ```[#scnzb@efnet][554131].Game.of.Thrones.S05E09.PROPER.HDTV.x264-KILLERS.[1-40].-.game.of.thrones.s05e09.proper.hdtv.x264-killers.sfv.yEnc```   )

**Comment by miigotu** [comment]
just need to apply a regex to the title in the provider

**Comment by fernandog** [comment]
@duramato check my providers PR and make the same changes here please

**Comment by miigotu** [comment]
@duramato 
Please remove all functions that start with `def _get` except `_getRSSData`, and fix the conflict, and I will merge.

**Comment by fernandog** [comment]
@duramato needs to make the changes we did in the others providers. Its not the same

**Comment by miigotu** [comment]
Its close enough for now if remove those extra functions. The search_string types are right at least.

**Comment by fernandog** [comment]
Well, let's do it right as It's not merged yet lol

**Pull request closed without merging**
