### PR TITLE
Trakt: Catch all internal server error and log a warning

### PR DESCRIPTION
**Pull request by fernandog**
Previous commit didn't updated line 87

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu I'm still getting the traceback about trakt. I shouldn't appear, should it ?

The code is telling to "pass" but it's not passing.
https://github.com/SiCKRAGETV/SickRage/blob/develop/lib/trakt/exceptions.py#L7
https://github.com/SiCKRAGETV/SickRage/blob/develop/lib/trakt/trakt.py#L110
what's wrong?

````
2015-06-28 14:14:04 INFO     DAILYSEARCHER :: Searching for new released episodes ...
AA
AAtraktServerBusy: 504 Server Error: Gateway Time-out
AA    raise traktServerBusy(e)
AA  File "/home/osmc/SickRage/lib/trakt/trakt.py", line 110, in traktRequest
AA    TraktShowWatchlist = self.trakt_api.traktRequest("sync/watchlist/shows")
AA  File "/home/osmc/SickRage/sickbeard/traktChecker.py", line 447, in _getShowWatchlist
AA    if self._getShowWatchlist():
AA  File "/home/osmc/SickRage/sickbeard/traktChecker.py", line 231, in syncWatchlist
AA    self.syncWatchlist()
AA  File "/home/osmc/SickRage/sickbeard/traktChecker.py", line 82, in run
``

**Comment by abeloin** [comment]
@fernandog Can you provide more logs?

**Comment by miigotu** [comment]
@fernandog `traktServerBusy` is derived from `traktException` which is derived from `Exception`, so a call to any of the trakt exceptions will still emit a traceback.

**Comment by miigotu** [comment]
@fernandog also, to extend my explanation, you are only catching requests.RequestException, and then re-raising with traktServerBusy, with is not caught with an except statement, so the default behavior or the base class Exception is evident.

**Comment by miigotu** [comment]
@fernandog Should I mod this file? It should also be using a persistent session, preferable cached.

**Comment by fernandog** [comment]
@miigotu
Even is there is a 'pass' in the exeptions file??

Sure. Can you fix the exception too ?? Thanks!

**Comment by miigotu** [comment]
@fernandog `pass` does nothing except stop python from throwing a syntax error when no methods are defined. All of the functions of the `Exception` are still a part of the `traktServerBusy` class, so even `Exception.__init__` gets called

I'll take care of it when I get back

**Comment by miigotu** [comment]
@fernandog https://github.com/SiCKRAGETV/SickRage/commit/15a76f27ced027e21fb62fdac77e6ba3c1fa4388

Also forgot in the commit message: url was getting screwed up when called more than one count too.

**Comment by fernandog** [comment]
Will monitor my log for trakt messages. Thanks

**Comment by miigotu** [comment]
@fernandog did you switch to that branch? I don't want to merge it unless it works (at least as good as before)

**Comment by fernandog** [comment]
Yes. Will let you know

**Comment by fernandog** [comment]
PS: I had to switch from cmd line. I receive update failed from UI. No errors. Will investigate later.

**Comment by fernandog** [comment]
2015-07-03 23:00:49 Thread-19 :: Failed doing webui callback: Traceback (most recent call last):
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 259, in async_call
    result = function(**kwargs)
  File "/home/osmc/SickRage/sickbeard/webserve.py", line 1010, in testTrakt
    return notifiers.trakt_notifier.test_notify(username, disable_ssl, blacklist_name)
  File "/home/osmc/SickRage/sickbeard/notifiers/trakt.py", line 222, in test_notify
    trakt_api.validateAccount()
  File "/home/osmc/SickRage/lib/trakt/trakt.py", line 62, in validateAccount
    resp = self.traktRequest('users/settings')
  File "/home/osmc/SickRage/lib/trakt/trakt.py", line 84, in traktRequest
    resp = session.request(method, url + path, headers=headers, timeout=self.timeout,
NameError: global name 'session' is not defined

**Comment by miigotu** [comment]
ew, self.session, I'll push that now

**Comment by miigotu** [comment]
@fernandog committed, git pull and restart SR.

**Comment by fernandog** [comment]
Done. Hit test and seems ok. Now lets wait trakt gets busy. Changed api timout to 5s

**Pull request merged**
