### PR TITLE
add multi-search IPT

### PR DESCRIPTION
**Pull request by daarcm**
adds ability to search for shows in the format SxEE as well as the current SXXEXX format on IPT, sa me code sourced from other providers

### CODE REVIEW

**Comment by fernandog** [comment]
@daarcm is it really working? Have you tested with SxEE and SXXEXX?

**Comment by fernandog** [comment]
@daarcm can you send a few debug log lines showing it's snatching ok?

**Comment by fernandog** [comment]
@daarcm is this still working for you? waiting your reply

**Comment by fernandog** [comment]
@SiCKRAGETV/moderators any of you have IPT to test this?

**Comment by miigotu** [comment]
Eh, sucks my IPT got cancelled from inactivity...

**Comment by miigotu** [comment]
@fernandog Looks safe, it is exactly the same code as in kat.py, oldpiratebay.py, and thepiratebay.py

**Pull request merged**
