### PR TITLE
Fix color in displayShow when manually searching. v2

### PR DESCRIPTION
**Pull request by abeloin**
Changed function getManualSearchStatus to include overview.
Changed all attr to prop

### CODE REVIEW

**Comment by abeloin** [comment]
@fernandog Can you test this PR?

**Comment by fernandog** [comment]
Sure! Let you know In a couple of hours. Baby sitting my son! =)

**Comment by abeloin** [comment]
Enjoy!!

**Comment by abeloin** [comment]
Have you had time to try it?

**Comment by fernandog** [comment]
it was already snatched (pink). I hit manual search and the color now is white,

**Comment by abeloin** [comment]
@fernandog Did you restart sickrage after applying the patch? Can you show me the <td> for that row

**Comment by fernandog** [comment]
@abeloin I always shutdown SR, apply the patch and restart. will apply again and let you know today

**Comment by abeloin** [comment]
I've just tried with the light theme and it's working.

@TagForce Can you test this PR?

**Comment by TagForce** [comment]
@abeloin Seems to be working fine...

**Comment by abeloin** [comment]
@fernandog Can you reproduce the error?

**Comment by fernandog** [comment]
@abeloin strange. seems ok now

**Pull request merged**
