### PR TITLE
Add "[PublicHD]" to removewordlist

### PR DESCRIPTION
**Pull request by duramato**

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
@miigotu can't we do this using regex instead of keeping adding strings to this list?

most use [] and/or www

**Comment by duramato** [comment]
@fernandog from the comment on the code :p 
```
    # Do not remove all [....] suffixes, or it will break anime releases ## Need to verify this is true now
    # Check your database for funky release_names and add them here, to improve failed handling, archiving, and history.
    # select release_name from tv_episodes WHERE LENGTH(release_name);
    # [eSc], [SSG], [GWC] are valid release groups for non-anime
```

**Comment by miigotu** [comment]
We can catch most of them with:

`r'^\[www\..+\..+\] ?-? ? '`

**Comment by fernandog** [comment]
I think only this one won't match with this regex ^^
r'\[NO-RAR\] - \[ www\.torrentday\.com \]$': 'searchre',

**Comment by duramato** [comment]
wont that regex also pick [eSc], [SSG], [GWC] ?
maybe have the regex and a list?

**Comment by fernandog** [comment]
I think is easier to add anime groups instead of torrent groups. or not ?

**Comment by miigotu** [comment]
My regex would catch over half of the list, the rest can be caught just like they are now. With regex every time cpasbian changes domain it wont need any changes here.

**Pull request merged**
