### PR TITLE
Add RSS mode for HDTorrents

### PR DESCRIPTION
**Pull request by fernandog**
For now it works with an empty search string
In the future real RSS must be used

@miigotu There's still a bug - that I thought I had fixed - about HDT only scrapping the first torrent in the table of torrents. the 'torrents' variable contains only one torrent.

@duramato

### CODE REVIEW

**Comment by miigotu** [comment]
bs3 makes 0 difference in that.

**Comment by fernandog** [comment]
without BS3  I get "Could not find table of torrents mainblockcontenttt"

I didn't change BS3/BS4 in this PR, it was a old one

**Comment by fernandog** [comment]
```
2015-09-25 13:47:49 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: Transaction with 4 queries executed
2015-09-25 13:47:49 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: Unable to parse the filename Murdoch.Mysteries.S08.720p.BluRay.x264-Japhson into a valid show
2015-09-25 13:47:49 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: Attempting to add item to cache: Murdoch.Mysteries.S08.720p.BluRay.x264-Japhson
2015-09-25 13:47:49 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: Found result: Murdoch.Mysteries.S08.720p.BluRay.x264-Japhson (https://hd-torrents.org/torrents.php?search=&active=1&order=data&by=DESC&options=0&category[]=59&category[]=60&category[]=30&category[]=38)
2015-09-25 13:47:41 DEBUG    SEARCHQUEUE-DAILY-SEARCH :: [HDTorrents] :: Search mode: RSS
```

**Comment by miigotu** [comment]
Im just gonna ignore this, you are the only one who has issues with hdt and/or bs4.
merge it if you want.

**Comment by duramato** [comment]
@miigotu no ,not the only one i also have

**Comment by fernandog** [comment]
This PR is for RSS mode! 

@duramato has same issue as me but its ok. 

Feel free to ignore.
Its funny th.

**Comment by miigotu** [comment]
@duramato yeah now, since the last change it is broken. Im not going to keep going back over the same provider and fixing it a hundred times.

**Comment by fernandog** [comment]
You dont even read the comments or above log

**Comment by miigotu** [comment]
I do read the comments. the PR BEFORE THIS one broke it AGAIN. I've fixed it 3 times already. and tested it to make sure I get more than one result. You mark this as tested (just like the last one) but obviously it doesn't work if you only get one result.

**Comment by fernandog** [comment]
RSS mode its working.
Please point the PRs that fixes the single result from hdt. AFAIK its one. And that one dont work for me because of VS4

**Comment by fernandog** [comment]
@duramato 

Can you please try this file?
Its the possible hdt fix about single torrent
Please check if that works for you
This file does not have RSS mode.
You must do a manual search for an episode that has multiple qualities in the provider and the quality you want must not be in the first result

https://raw.githubusercontent.com/fernandog/SickRage/b7b2c22e4537029905e26a9270051c9f0b35ed00/sickbeard/providers/hdtorrents.py

**Comment by fernandog** [comment]
I need to figure it out how to fix this:

```
AA
AAAttributeError: 'list' object has no attribute 'keys'
AA    for mode in search_params.keys():
AA  File "/home/osmc/SickRage/sickbeard/providers/hdtorrents.py", line 152, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/home/osmc/SickRage/sickbeard/providers/generic.py", line 354, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/osmc/SickRage/sickbeard/search.py", line 488, in searchProviders
2015-09-25 17:11:24 DEBUG    SEARCHQUEUE-MANUAL-247824 :: [HDTorrents] :: Traceback (most recent call last):
AAAttributeError: 'list' object has no attribute 'keys'
AA    for mode in search_params.keys():
AA  File "/home/osmc/SickRage/sickbeard/providers/hdtorrents.py", line 152, in _doSearch
AA    itemList += self._doSearch(curString, search_mode, len(episodes), epObj=epObj)
AA  File "/home/osmc/SickRage/sickbeard/providers/generic.py", line 354, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "/home/osmc/SickRage/sickbeard/search.py", line 488, in searchProviders
AATraceback (most recent call last):
```

**Comment by WebSpider** [comment]
Lists dont have keys. Dicts do.

-----Original Message-----

**Comment by fernandog** [comment]
Thanks. Other providers like torrentday have the same lines of code. Im confused.

**Comment by miigotu** [comment]
It depends what is returned from get_episode_search_strings, get_season_search_strings and what is called from the tvcache. Its all right there in the provider.

**Comment by miigotu** [comment]
hdtorrents provider doesnt use keys, and neither will the others when providers are rewritten. It is unnecessarily overcomplicated search string handling.

**Comment by fernandog** [comment]
Will check. Thanks

**Comment by duramato** [comment]
The suggested fix by fernadog doesnt seem to work ,getting "[HDTorrents] :: Could not find table of torrents mainblockcontenttt"

**Comment by fernandog** [comment]
This?
https://raw.githubusercontent.com/fernandog/SickRage/b7b2c22e4537029905e26a9270051c9f0b35ed00/sickbeard/providers/hdtorrents.py

**Comment by duramato** [comment]
yes

**Comment by fernandog** [comment]
@miigotu bs4 does not work for @duramato too

**Comment by miigotu** [comment]
bs4 is not the problem.

**Comment by WebSpider** [comment]
Should that not be 'mainockcontent' with only 1 t in the end?

-----Original Message-----

**Comment by miigotu** [comment]
@WebSpider nope, there is also `mainblockcontent` but that is the top block with featured torrents unrelated to the search results. The one for the search is in fact `mainblockcontenttt`

**Comment by fernandog** [comment]
How to explain that bs3 finds mainblockcontenttt (and first torrent) and bs4 dont?

Tried all parsers (html5, etc..) from bs4.
I give up trying to fix this. Already spent days debugging it.

**Comment by miigotu** [comment]
Maybe the .find needs called different. But using an ancient library is not the answer.

**Comment by miigotu** [comment]
Ive done some digging in this. HDTorrents changed their site, and has terribly malformed html.
After fixing the original find, this is where it chokes, and no further torrents can be parsed:
```html
<td align="center" class="mainblockcontent">13:00:13 <bWed, 10 Jun 2015 13:00:13 +0300><bWed, 10 Jun 2015 13:00:13 +0300> 10/06/2015</td>
```

**Comment by miigotu** [comment]
Ill try and regex that out of the data returned before souping it later.

**Comment by fernandog** [comment]
Thanks!

**Pull request closed without merging**
