### PR TITLE
Added the ability to choose displaying columns in home.tmpl.

### PR DESCRIPTION
**Pull request by abeloin**
Added new column "previous episodes", disable by default.

### CODE REVIEW

**Comment by fernandog** [comment]
@abeloin wow! thanks!

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/218

**Comment by TagForce** [comment]
@abeloin 
Now this is awesome!
Works flawlessly. Kudos!

**Comment by fernandog** [comment]
@TagForce @abeloin I was thinking add this column widget to "fix" this:

https://sickrage.tv/forums/forum/main-category/feature-requests/866-filenames-on-show-pages-taking-up-a-lot-of-real-estate

so we can show/hide filesize/filename 

not now, in near future

**Comment by TagForce** [comment]
@fernandog I was thinking the same thing... Just add all columns to the page, and use the column chooser to hide/display them. That way we can lose the "Show file size" option in settings, which people apparently cannot find (as evidenced by the forumpost you linked to just now, because I told them it was there and that is no longer an issue).

**Comment by fernandog** [comment]
@abeloin 

JS / tablesorter does not work while adding shows:

**Comment by abeloin** [comment]
@fernandog let me check

**Comment by abeloin** [comment]
This is what I get:
Imgur
Imgur

**Comment by abeloin** [comment]
@fernandog It's another bug, here without the PR:
! [Imgur](http://i.imgur.com/lJNZevr.png)

**Comment by fernandog** [comment]
@abeloin yes. the problem is the "loading" in the first column. It's no a date. So JS fail.

**Pull request merged**
