### PR TITLE
Made some corrections to recently added network logos

### PR DESCRIPTION
**Pull request by danyboy666**
Corrections to network logos RDI, ARTV, EXPLORA.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by duramato** [comment]
@danyboy666 the black letters will be barely readable on the blac theme

**Comment by neoatomic** [comment]
Also not agreeing/approving this change.

**Comment by danyboy666** [comment]
Yeah I only taught about it afterwards. I'll revert the commit.

**Comment by danyboy666** [comment]
Not to contest this decision in any way but i don't think it looks that bad.

Example: here's a link for another network logo already in SR.
http://i.imgur.com/lvuBIhH.jpg?1

**Comment by duramato** [comment]
@danyboy666 doesnt mean it looks good... 
Try making another color that isnt black or white

**Comment by danyboy666** [comment]
yeah i'll look into it thank you

**Comment by danyboy666** [comment]
This can be closed up thank you for your input.

**Pull request closed without merging**
