### PR TITLE
2492 Make directory when not available

### PR DESCRIPTION
**Pull request by jorgb**
Fix for #2495  
Based upon 'develop' branch this time ;-)

### CODE REVIEW

**Comment by miigotu** [comment]
there are issues with doing it this way. I can explain at least one a little later.

**Comment by miigotu** [comment]
This needs to check if the Show dir exists first. We cannot make directories when the show location might not be set correctly (show moved? archived? disk offline/no mounted?)

**Comment by jorgb** [comment]
That goes beyond my abilities, the code  there needs to be the code that is
executed when "add show" is used as it seems to create a dir just fine
there.

**Comment by miigotu** [comment]
Because the directory must exist. Blindly creating the show directory during post processing is no an option.

**Comment by jorgb** [comment]
So that means it does not get fixed at all?

**Comment by miigotu** [comment]
It isn't broken. You are breaking it by deleting the show folders that SR has made, you said that yourself (even though you linked the wrong issue here).

**Comment by jorgb** [comment]
Never mind then. Happy bug fixing!
- Jorgen

**Comment by ipso** [comment]
What happens if the disk where you store your shows crashed? Do you manually have to re-create the hundreds or thousands of directories before Sickrage will function again?

**Comment by miigotu** [comment]
Hundreds or thousands of Shows? lol.

**Comment by fernandog** [comment]
@jorgb you should check if directory exists first with os.path.exists()

**Comment by jorgb** [comment]
Thanks, but I am done with trying to contribute. To me it feels that if 
the issue I filed is already closed (before helping me making it an 
acceptable PR to merge), that there is no desire to merge it in the end 
anyway.

I filed a feature request as suggested, and trust the original devs, if 
they so desire to implement this, will make it a better fix than I tried 
to do.

With regards,
- Jorgen

**Comment by fernandog** [comment]
@jorgb please try again. everybody here started doing small contributions.

**Comment by ipso** [comment]
I would submit my patch, but Mr. miigotu clearly thinks this is a non issue even though there are numerous requests for it here and in the forums. 

Closing issues before having any real discussion, then laughing at their reasoning is a great way to build a thriving community around a project. Why would anyone bother wasting their time?

**Comment by fernandog** [comment]
@jorgb forgot about this setting:
stop SR, edit your config.ini and set to 1 this

create_missing_show_dirs

**Comment by jorgb** [comment]
Thanks bunches for following up, I will check it out later!

With regards,
- Jorgen

**Pull request closed without merging**
