### PR TITLE
Updated subliminal to 1.1.0.dev0, added no_setup patch, added napipro…

### PR DESCRIPTION
**Pull request by medariox**
…jekt subtitles provider, fixed SiCKRAGETV/sickrage-issues/issues/3251

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu can we ask to author of this PR to PR that here in SR so we can test it ?

@duramato do you use legendas tv also?

https://github.com/Diaoul/subliminal/pull/ 513

**Comment by duramato** [comment]
@fernandog yes i do

**Comment by fernandog** [comment]
nice. So we can have a good feed back to diaol

**Comment by miigotu** [comment]
Why not just pull those commits in?

**Comment by fernandog** [comment]
We can do that. That dev should make corrections only there? Or here?
Also we should ask if the dev agrees. But I think he will. Can we tag him here in SR?

**Comment by miigotu** [comment]
yep. corrections should be made here, then sdded to his PR in subliminal as they are verified

**Comment by fernandog** [comment]
@ratoaq2 is it ok for us to merge your PR here?

**Comment by ratoaq2** [comment]
Of course. It's fully functional, but I'm waiting Diaoul feedback. I can support it and incorporate changes if required.

**Comment by miigotu** [comment]
@ratoaq2 the idea is that if it is tested here, Diaoul is more likely to trust adding it upstream. =P

**Comment by fernandog** [comment]
You can use SR as a more complete test for your code before merge there.

**Comment by ratoaq2** [comment]
I understood it. No problem.

**Comment by fernandog** [comment]
@miigotu how to merge that PR here?

**Comment by miigotu** [comment]
Its not a direct merge, because we use the no_setup patch. @medariox should know how to do it from this: https://patch-diff.githubusercontent.com/raw/Diaoul/subliminal/pull/513.patch

basically just adding subliminal/converters/legendastv.py, subliminal/providers/legendastv.py, and the changes from setup.py to our external provider manager.

@medariox or @ratoaq2 if either of your could add this and add the patch in .build/patches also it would be great.

**Comment by medariox** [comment]
I can try that.
@ratoaq2 
Does LegendasTV need login credentials?

**Comment by ratoaq2** [comment]
Yes, in order to download subtitles you need to be logged in.

**Comment by miigotu** [comment]
@medariox if you are adding login for legendas you may as well add logins for addic7ed and opensubtitles too xD

**Comment by medariox** [comment]
Okay, on it asap.

**Comment by fernandog** [comment]
@ratoaq2 can you join freenode IRC #sickrage ?

**Comment by felipesalomao** [comment]
Legendas.tv is working some way with sickrage ? I am waiting for this so long time, i have open first issue asking it.. I see that @ratoaq2 developed all..but Diaul is very strict guy.. I do not see any progress for 3 weeks.. I think it is almost done to work directly Subliminal or direct on sickrage.. There is some info about it @fernandog or @ratoaq2 ? Would be dream see sickrage downloading perfect subtitles from legendas.tv automatically..

**Comment by ratoaq2** [comment]
I'm a bit busy these weeks but I'll continue the work following Diaoul
suggestions. The remaining tasks are just to follow some code conventions
and to make it more resilient (when dependencies are missing, mostly
because of unrar restrictions).

**Comment by felipesalomao** [comment]
Thank You so much @ratoaq2 ! Your work is awesome, i have been waiting years to see this become true.. And i think 95% of Job is done.. Just few changes to it work for everyone.. You as brazillian know how important and better are subtitles from legendas.tv.. Only they have 100% realible subtitles for all big TV shows and movies..

**Comment by medariox** [comment]
What are you even talking about? Legendas.tv has been implemented in SR since ages...

**Comment by felipesalomao** [comment]
@medariox i cant belive that i do not see that before.. This was added without subliminal update.. it was updated directly here :)).. Enabled here.. Will test on tomorrow epsodes.. Next chalange is enable that in couchpotato too, but i think that only will work when subliminal update it with legendas.tv plugin developed by @ratoaq2 added on subliminal branch..

**Comment by felipesalomao** [comment]
Hi, i am testing legendas.tv provider developed by @ratoaq2, it aways find subtitle.. But i am Habibs problem, dont know if is legendas.tv provider bug or sickrage subtitle module bug.. When i enable only legendas.tv provider, it not download automatically, only clicking CC on TV show page..
Then i opened log, found problem:
2015-11-26 00:06:45 FINDSUBTITLES :: Not enough services selected. At least 1 service is required to search subtitles in the background

Then i was to subtitle settings checo and legendas.tv was unchecked.. But i enabled it and saved settings.. Tried yesterday and today.. Tried restart sickrage too and happened again.. It dont keep legebdas.tv subtitle provider enabled.. After some time it disable for no reason.. Do You know how fix it ?

**Comment by felipesalomao** [comment]
Hi, i dont know what is happening.. Dont know if is legendas.tv provider issue or sickrage issue..

It search for subtitles everyday each 1 hour.. i see on log that it really try find subtitles, but it never download subtitles..  today for example, GOTHAM S02E11 subtitle was published on legendas.tv 20:48.. 
In log i see that it tried look for new subtitles 20:58, 21:58, 22:58 and not downloaded anything.. Only legendas.tv provider is marked.. 

Here have 2 hours difference, so if in log show 22:00, correct time  (my local time is 20:00)..

2015-12-02 01:00:27 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-12-02 00:58:47 INFO     FINDSUBTITLES :: Checking for subtitles
2015-12-02 00:58:44 INFO     CHECKVERSION :: Checking for updates using GIT

2015-12-02 00:00:27 INFO     DAILYSEARCHER :: Searching for new released episodes ...
2015-12-01 23:58:46 INFO     FINDSUBTITLES :: Checking for subtitles
2015-12-01 23:58:44 INFO     CHECKVERSION :: Checking for updates using GIT

2015-12-01 22:58:50 INFO     FINDPROPERS :: Beginning the search for new propers
2015-12-01 22:58:45 INFO     FINDSUBTITLES :: Checking for subtitles
2015-12-01 22:58:43 INFO     CHECKVERSION :: Checking for updates using GIT


Then, as it not downloaded i opened Gotham page in sickrage and clicked on CC button, it found subtitle and downloaded it in 5 seconds..

So legendas.tv provider looks work great, i think.. problem is that it isnt downloading automatically and also Log is too much poor for subtitle module, it only says Checking for subtitles, nothing more, it does not say if found, if not, why.. So its hard discovery whats them problem..

Could you help @ratoaq2 @fernandog @medariox ? 

If need anything, just ask me ! Thanks

**Pull request merged**
