### PR TITLE
Remove webRoot from submenu title

### PR DESCRIPTION
**Pull request by gtosh4**
https://github.com/SiCKRAGETV/SiCKRAGE/commit/4a8fc9c94d6c8019cce01e3245504d6bbd6a7bd1 was a bit overzealous with the `${srWebRoot}`s.

capture

### CODE REVIEW

**Comment by echel0n** [comment]
Applied changes manually and updated develop branch

**Comment by gtosh4** [comment]
Am I doing these PRs wrong? All 6 of my PRs have been closed and made manually (some merged then reverted, some closed and reimplemented).
Apologies if I am, let me know how I can send these so they can be more conveniently merged.

**Comment by echel0n** [comment]
The OFFICIAL GIT server for us is at https://git.sickrage.ca/sickrage/sickrage which is where the PR's should be made on as this repo here on GitHub is just a mirror of our main which is why I'm manually making the changes cause if this repo gets out of sync with our main the it breaks the mirroring

**Comment by gtosh4** [comment]
Is it more convenient for you to stay on github or use git.sickrage.ca for future PRs?

**Comment by echel0n** [comment]
git.sickrage.ca is where PRs should be done, would allow us to work better together

**Pull request closed without merging**
