### PR TITLE
Remove redundant buttons from various pages

### PR DESCRIPTION
**Pull request by VinceVal**
The Add Shows, Manual Post-Processing, and various update buttons are
now redundant since the Shows navbar button is a dropdown. The update
and torrent buttons are on the Manage dropdown.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
Why is this being removed, isn't this what is used for the submenu? @miigotu

**Comment by VinceVal** [comment]
Since all of those options are (now) available on the navbar, @miigotu and I thought it would be good to remove the duplicated buttons.

**Comment by OmgImAlexis** [comment]
The PRs should have been done together with 2 commits so they'd be merged at the same time. Not really sure why they were split. Also doing it that way helps explain what's going on so we don't have things like this happen.

**Comment by VinceVal** [comment]
My original intention wasn't to remove the buttons. @miigotu had already merged #2671 and he then asked via IRC if I thought it would be a good idea to remove the buttons too.

I agree though. Should have been one PR ideally.

**Comment by miigotu** [comment]
@SiCKRAGETV/moderators I'm not sure about this yet. I would like to see the submenu items gone since they are all in the menus anyways, but I am also sure someone will complain.

**Comment by VinceVal** [comment]
@miigotu, agreed. I really like it, but I think it does break mobile/touchscreens. Would be nice if the dropdown code could detect a mobile platform and apply the "disabled" class dynamically, but I'm a little hesitant to put a ton of time into that if Bootstrap is being scrapped soon.

**Comment by VinceVal** [comment]
I might take a look at this tonight... I think we could fairly easily detect touch devices with something like:

    function is_touch_device() {
      return !!('ontouchstart' in window);
    }

...if the main concern is mobile/touch devices. If people have other concerns with this PR, let me know.

**Comment by miigotu** [comment]
Touchscreen is the main concern, I think people can get over the fact of them being gone (they will complain at first, no one likes to change habits)

**Comment by WebSpider** [comment]
Well, as long as we're not removing any functionality, we should be fine with adding a news/changelog that explains what we did.

News would have to be more dummyproof off course.

I admit, I also use the buttons, but this is because of habits, and I for one don't mind changing my habits.

When too many people complain, just make it a knob, so they can turn the buttons back on in settings?

-----Original Message-----

**Comment by fernandog** [comment]
After that PR i can't open menus in tablet/phone.
Can we try function is_touch_device() { ?

**Comment by VinceVal** [comment]
@fernandog yeah I'd say don't merge #2674 with master until we get this figured out. I'm hoping this will be a fairly simple fix with a little JS.

**Comment by miigotu** [comment]
https://github.com/Modernizr/Modernizr/blob/master/feature-detects/touchevents.js

**Comment by OmgImAlexis** [comment]
Added to my todo list.

**Comment by fernandog** [comment]
that @VinceVal change worked for me:

https://github.com/VinceVal/SickRage/commit/6dfbd986d5bd4a5cc63a31b74e7af258a2b413e0

**Comment by OmgImAlexis** [comment]
@fernandog the change VinceVal made shouldn't be merged though as it's an old hack and even if it is added it should be put into script.js and not into the mako file.

**Comment by fernandog** [comment]
Agree about moving to .js
But why is a hack?

**Comment by OmgImAlexis** [comment]
@fernandog the way it's checking if it's a touch device or not isn't correct and isn't what that's meant for.

**Comment by fernandog** [comment]
no problem

**Comment by miigotu** [comment]
For reference, Im adding this link here and in the other PR, so everyone knows the solution we have decided on.

http://getbootstrap.com/components/#btn-dropdowns-split

**Pull request merged**
