### PR TITLE
Removed TVRage network and unused logos.

### PR DESCRIPTION
**Pull request by neoatomic**
Now only TheTVDB logo's are left. Totally saving 1.1MB
Used this recent list of network names. http://pastebin.com/pAsqN2Dm

Still almost 600 TheTVDB logos are missing. http://pastebin.com/LsRvt2NA

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by WebSpider** [comment]
Reading that we are missing 600 logos made me think: Is it really a good solution to include the logos in a theme, or would a GitHub repo that we cache a local copy of be better? (such as white/blacklist and network times)

**Comment by OmgImAlexis** [comment]
@WebSpider they should still be included but I think it'd be a better idea to have them out of the theme directory so just in `gui/image/`. The same goes for other images that aren't theme specific.

**Comment by WebSpider** [comment]
Do we really need 600+ binary files sitting in the repo that a typical user may use only, say, 20 of, for decorational purposes?

**Comment by OmgImAlexis** [comment]
@WebSpider maybe we could zip them and have a command to unzip? @MGaetan89 was looking at adding them all to a sprite sheet so we only had a single file instead of 600+.

**Comment by neoatomic** [comment]
The majority of those 600 are exotic networks that are not worth adding.
The best solutions would be if thetvdb added those logos to there API. They are currently working on a new API, so might be an idea to see if they are interested in that.

**Pull request merged**
