### PR TITLE
PostProcess: Fix lower quality, bigger sized file overwriting current episode.

### PR DESCRIPTION
**Pull request by abeloin**
See https://github.com/SiCKRAGETV/sickrage-issues/issues/1023 for more info

### CODE REVIEW

**Comment by fernandog** [comment]
Nice one!

**Comment by abeloin** [comment]
@TagForce FYI

**Comment by fernandog** [comment]
@abeloin 

what about this part of the code. Is it still checking size instead of quality:
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/postProcessor.py#L137

**Comment by abeloin** [comment]
@fernandog Look at the definition for the function:
Checks if a file exists already and if it does whether it's bigger or smaller than the file we are post processing

**Pull request merged**
