### PR TITLE
CBC (CA) icon Missing

### PR DESCRIPTION
**Pull request by Peke**
Just Copied CBC.PNG icon to CBC (CS).PNG to cover that networks.

### CODE REVIEW

**Comment by miigotu** [comment]
@Peke 5 commits to add an image?

**Comment by Peke** [comment]
Not sure why other commits keep bouncing back?
But http://thetvdb.com/?tab=series&id=289965 really uses this Image and shoould be merged

**Comment by miigotu** [comment]
I cant merge 5 commits to add an image, and I cannot merge a pull request from your develop branch.

1.) You are not syncing your fork correctly.
2. ) Pulls must be from a feature branch

Now that your develop branch is fuxored, you must git fetch upstream and do a reset or rebase to upstream/develop.

to fix your fork:
```
git fetch upstream
git checkout develop
git merge upstream/develop
git rebase -i upstream/develop^
(comment all lines that are your own commits, you never add your own commits to this branch)
ctrl+o, enter, ctrl+x
git push origin -u -f develop

git fetch upstream
git checkout master
git merge upstream/master
git rebase -i upstream/master^
(comment all lines that are your own commits, you never add your own commits to this branch)
ctrl+o, enter, ctrl+x
git push origin -u -f master
```

To start a new feature you plan to PR (notice the branch name describes your feature/pull):
`git checkout -b add-missing-cbc-icon upstream/develop`
(add the new commit to this new branch. if you have more than one when you are done, you need to rebase and change pick to squash or fixup to melt commits into the one above it. Dont meld commits into ones that arent yours)
`git push origin -u add-missing-cbc-icon`
create a new PR to SickRage/develop.

To sync your fork in the future:
```
git fetch upstream
git checkout develop
git merge upstream/develop
git push origin develop

git fetch upstream
git checkout master
git merge upstream/master
git push origin master
```

**Comment by Peke** [comment]
I recreated My respiratory and fork. I'm really still new at GIT.

**Pull request closed without merging**
