### PR TITLE
Add NzbIndex ,update xem icon & add torrentz icon

### PR DESCRIPTION
**Pull request by duramato**
Fixed the comflicts and changed the lines acocrding to @fernandog  ,but didnt undesrstood what you meant @miigotu . Is it to remove   `_get_season_search_strings` `_get_episode_search_strings` `get_title_and_url` & `get_size` ?´
PS: The other PR was broken it was showing unknow repository

### CODE REVIEW

**Comment by miigotu** [comment]
@duramato yes, you need to remove those.

And this part needs done in doSearch before adding the item:
` url = url.replace('/release/', '/download/')`

**Comment by duramato** [comment]
@miigotu ok will do that ,btw could you join irc if you have the time?

**Comment by miigotu** [comment]
I have to remove nzbindex. Its way too unreliable, 503 way too often, and the titles cant reliably be parsed.

This site just isnt a good candidate, sorry.

**Comment by neoatomic** [comment]
@cytec We are not implementing the nzbindex provider as you can see. But maybe the code etc. might be of interest to you.

**Pull request merged**
