### PR TITLE
Added the ability to configure a providers minimum cache time setting.

### PR DESCRIPTION
**Pull request by gsly**
Added the ability to configure a providers minimum cache time setting.
Changed ThePirateBay and KickAssTorrents providers to use this new
configuration attribute.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by duramato** [comment]
@gsly what if a user sets it to 1?
It will pwn the server, wont it?

**Comment by gsly** [comment]
@duramato I never tried setting it to 1, but I think it only comes into play when the daily search happens. Probably should have a minimum value on the user interface.

**Comment by duramato** [comment]
@gsly when need to provent that,maybe and logic if it is less than 10m default to 10min ?

**Comment by miigotu** [comment]
We cannot allow it to be less than what we have set. The mintime is set per provider requirements and at their request. We absolutely cannot allow the user to lower what we have,

**Pull request closed without merging**
