### PR TITLE
Fixes progressbar sorting

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Since @MGaetan89 added the print view we now get back a duplicate result like `33+1 / 3733+1 / 37` instead of `33+1 / 37` so we need to split the string in half.

### CODE REVIEW

**Comment by MGaetan89** [comment]
Didn't think about that :o
Is it a library that provide this feature or custom code? If it's custom code, we could adapt it to use only the visible text in the cell.

**Comment by OmgImAlexis** [comment]
For now the split is fine, it works just as it did before. When I go back over and redo all of the js this week I'll have a look more into this.

It's the jQuery tablesort plugin and it just returns the text of the div that's why it shows up twice.

**Comment by MGaetan89** [comment]
Ok, if it's working now, we can improve this later ;)

**Comment by fernandog** [comment]
Thanks

**Pull request merged**
