### PR TITLE
Monkeypatch shutil.copyfile

### PR DESCRIPTION
**Pull request by abeloin**
Replace shutil.copyfile for a faster copy/move. Replace PR https://github.com/SiCKRAGETV/SickRage/pull/1193 and https://github.com/SiCKRAGETV/SickRage/pull/1262.
See https://github.com/SiCKRAGETV/sickrage-issues/issues/545 for more info.

### CODE REVIEW

**Comment by fernandog** [comment]
@abeloin this PR will change the way PP copy/moves and maybe check permissions and warn user about they? related to all those issues about PP couldn't find the directory.

**Comment by abeloin** [comment]
Nope, this restore the usage of shutil to transfer file and fix the low speed some user experienced on Mac when move failed and use copy instead

**Comment by abeloin** [comment]
I'm waiting until we push the current changes from develop to master before introducing this patch.

**Comment by Thraxis** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/844

Note my solution I believe the import shutil from the \__init__.py file was removed inadvertently

**Pull request merged**
