### PR TITLE
Several network logos

### PR DESCRIPTION
**Pull request by duramato**

### CODE REVIEW

**Comment by alzeric** [comment]
Here is one that is currently missing.  Choose whichever one you like the best.
Not sure how to officially go about submitting these.

This is for WE tv

WE tv
WE tv

**Comment by duramato** [comment]
@alzeric the network`s name is "we tv" ? thats how it appears on SR ?

**Comment by alzeric** [comment]
@duramato it appears as WE tv not "we tv"

**Comment by alzeric** [comment]
Here is a screenshot of Bravo (US) as well.

screenshot_1

This is what is in the current image folder.
screenshot_2

**Comment by duramato** [comment]
@alzeric the bravo (us) logo is now fixed on the dev version `bout the we tv ill make a PR

**Comment by alzeric** [comment]
Cool, I'll have 3 more logos for you here in about 5-10 mins (Japanese Networks / Anime)

sun-tv
chiba tv
teletama

**Comment by alzeric** [comment]
Boy these japanese networks have some funky logos lol.

Shown in SR: chiba tv
chiba tv

Shown in SR: sun-tv
sun-tv

Shown in SR: teletama
teletama

**Comment by duramato** [comment]
lol, ive made a pr with the logos @alzeric  https://github.com/SiCKRAGETV/SickRage/pull/2144

**Pull request merged**
