### PR TITLE
Fix missing code when exception and pylint

### PR DESCRIPTION
**Pull request by fernandog**
Added `_remove_file_failed(filename)` after exception

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by miigotu** [comment]
@fernandog Need to disable your line length warning for pylint in ~/.pylintrc 

Usually breaking in the middle of a log line like that just makes it harder to read.

**Comment by fernandog** [comment]
any other warnings to disable?

**Comment by miigotu** [comment]
This is my pylintrc https://gist.github.com/miigotu/a00b5b18a5a5adbcc6e7

It needs some work, I just fix simple pylint errors, but I read through them all and make sure there isnt anything undefined or w/e.

Maybe someday when we get the pylintrc just right we can add it to .build/ and share it.

**Comment by fernandog** [comment]
why not disable "Module 'sickbeard.logger' has no 'log' member (no-member)"?

**Comment by miigotu** [comment]
Because you can't disable that warning alone without disabling the warning for other modules?
We have to figure out how to override logging correctly to eliminate that warning.
I want it to warn me if someone calls something sickbeard.foobar() and foobar doesnt exist.

**Pull request merged**
