### PR TITLE
Parse size from RARBG results

### PR DESCRIPTION
**Pull request by fernandog**
@miigotu ok?

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by miigotu** [comment]
Yep, just dont forget we need to get hash in the item too eventually =P

Also, for future reference, when logging an exception string should probably use %r instead of %s.

**Comment by fernandog** [comment]
What is the diff %s and %r ?

**Comment by fernandog** [comment]
@miigotu 
batch change? lol

```
$ grep -Ril '%*traceback.format_exc()'
SickBeard.py
sickbeard/search_queue.py
sickbeard/logger.py
sickbeard/show_queue.py
sickbeard/providers/nextgen.py
sickbeard/providers/alpharatio.py
sickbeard/providers/cpasbien.py
sickbeard/providers/hounddawgs.py
sickbeard/providers/tokyotoshokan.py
sickbeard/providers/transmitthenet.py
sickbeard/providers/bluetigers.py
sickbeard/providers/morethantv.py
sickbeard/providers/t411.py
sickbeard/providers/tntvillage.py
sickbeard/providers/freshontv.py
sickbeard/providers/bitsoup.py
sickbeard/providers/rarbg.py
sickbeard/providers/torrentbytes.py
sickbeard/providers/iptorrents.py
sickbeard/providers/kat.py
sickbeard/providers/hdtorrents.py
sickbeard/providers/scenetime.py
sickbeard/providers/torrentleech.py
sickbeard/providers/extratorrent.py
sickbeard/providers/fnt.py
sickbeard/event_queue.py
sickbeard/search.py
sickbeard/webapi.py
sickbeard/helpers.py
sickbeard/scene_numbering.py
sickbeard/clients/rtorrent_client.py
sickbeard/webserve.py
sickbeard/traktChecker.py
sickbeard/properFinder.py
sickbeard/versionChecker.py
sickbeard/notifiers/emailnotify.py
sickbeard/tv.py
sickbeard/scheduler.py

```

**Comment by miigotu** [comment]
I also mean when you do:
```
except Exception as e:
    logger.log(u'blah %r' % ex(e))
```

**Comment by fernandog** [comment]
ex() handle non-ascii chars?

**Comment by miigotu** [comment]
yes thats exactly what its for....

**Comment by fernandog** [comment]
so why my log still have this: xc3\xa7o ?

`logger.log(u"Connection error to getURL %s Error: %s" % (url, ex(e)), logger.WARNING)`

`Connection error to getURL http://sickragetv.github.io/sickrage-news/news.md Error: error ('Connection aborted.', gaierror(-2, 'Nome ou servi\xc3\xa7o desconhecido'))`


https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/helpers.py#L1643

**Pull request merged**
