### PR TITLE
Fix accessing manage torrents from remote

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/349

### CODE REVIEW

**Comment by abeloin** [comment]
DYNDNS_HOSTNAME is only used if LOCALHOST_IP is empty and TORRENT_HOST is set to localhost!!! Mmm, something is not right here ;)
Why can they just use TORRENT_HOST to their dyndns name?

**Comment by fernandog** [comment]
LOCALHOST_IP is for reverse proxy.
because if the dyndns it not proper updated or is down, user couldn't add torrents.

**Comment by fernandog** [comment]
@abeloin any more thoughts/suggestions? here is working

**Comment by abeloin** [comment]
DYNDNS_HOSTNAME is only used if LOCALHOST_IP is empty and TORRENT_HOST is set to localhost!!!

**Comment by fernandog** [comment]
yes. because LOCALHOST_IP is used only for reverse proxy. Wha

**Comment by abeloin** [comment]
Ok I will be less subtle, consider the following code where torrent_host is 192.168.1.1(the machine ip):
```
        if re.search('localhost', sickbeard.TORRENT_HOST):

            if sickbeard.LOCALHOST_IP == '':
                if sickbeard.DYNDNS_HOSTNAME == '':
                    t.webui_url = re.sub('localhost', helpers.get_lan_ip(), sickbeard.TORRENT_HOST)
                else:
                    t.webui_url = re.sub('localhost', sickbeard.DYNDNS_HOSTNAME, sickbeard.TORRENT_HOST)
            else:
                t.webui_url = re.sub('localhost', sickbeard.LOCALHOST_IP, sickbeard.TORRENT_HOST)
        else:
            t.webui_url = sickbeard.TORRENT_HOST
```
0. `if re.search('localhost', sickbeard.TORRENT_HOST):`
  * Did the user entered 'localhost' in the torrent_host value? If true goto 1 else goto 20
1. `if sickbeard.LOCALHOST_IP == '':`
  * Is the value of localhost_ip empty? if it is empty goto 2 else goto 5
2. `if sickbeard.DYNDNS_HOSTNAME == '':`
  * Is the value of dyndns_hostname empty? if it is empty goto 3 else goto 4
3. `t.webui_url = re.sub('localhost', helpers.get_lan_ip(), sickbeard.TORRENT_HOST)` goto 21
  * Take localhost out of torrent_host replace it by the lan ip(192.168.1.1) and return it to the client
4. ` t.webui_url = re.sub('localhost', sickbeard.DYNDNS_HOSTNAME, sickbeard.TORRENT_HOST)` goto 21
  * Take localhost out of torrent_host replace it by dyndns_hostname return it to the client
5. ` t.webui_url = re.sub('localhost', sickbeard.LOCALHOST_IP, sickbeard.TORRENT_HOST)` goto 21
  * Take localhost out of torrent_host replace it by localhost_ip
20. `t.webui_url = sickbeard.TORRENT_HOST` goto 21
  * Put the value of torrent_host as the value to be returned to the client.
21. ...

Do you see it? DYNDNS_HOSTNAME will never be assigned because TORRENT_HOST != to localhost even do localhost = 127.0.0.1 = 192.168.1.1

**Comment by abeloin** [comment]
By the way LOCALHOST_IP isn't used at all for reverse proxy, it is used only by the managetorrent for specifying the ip when someone enter localhost as their torrent host address if the auto-detection fail.

**Comment by fernandog** [comment]
@abeloin so what's you suggestion? use localhost_ip as the dyndns hostname?

**Comment by abeloin** [comment]
No move your code at line 3234:
```
if sickbeard.DYNDNS_HOSTNAME != '':
    t.webui_url = sickbeard.DYNDNS_HOSTNAME
```
This way it is always applied

**Comment by fernandog** [comment]
like this?

in my case my TORRENT_HOST = localhost. so the dyndns won't be applied, is that it?

```
        if sickbeard.DYNDNS_HOSTNAME != '':
            t.webui_url = sickbeard.DYNDNS_HOSTNAME

        if re.search('localhost', sickbeard.TORRENT_HOST):

            if sickbeard.LOCALHOST_IP == '':
                    t.webui_url = re.sub('localhost', helpers.get_lan_ip(), sickbeard.TORRENT_HOST)
            else:
                t.webui_url = re.sub('localhost', sickbeard.LOCALHOST_IP, sickbeard.TORRENT_HOST)
        else:
            t.webui_url = sickbeard.TORRENT_HOST
```

**Comment by abeloin** [comment]
It need to be at the end as if torrent_host = localhost it will be overwriten.
```
        if re.search('localhost', sickbeard.TORRENT_HOST):

            if sickbeard.LOCALHOST_IP == '':
                t.webui_url = re.sub('localhost', helpers.get_lan_ip(), sickbeard.TORRENT_HOST)
            else:
                t.webui_url = re.sub('localhost', sickbeard.LOCALHOST_IP, sickbeard.TORRENT_HOST)
        else:
            t.webui_url = sickbeard.TORRENT_HOST
        
        if sickbeard.DYNDNS_HOSTNAME != '':
            t.webui_url = sickbeard.DYNDNS_HOSTNAME
```

**Comment by fernandog** [comment]
what about this
```
        if re.search('localhost', sickbeard.TORRENT_HOST) and sickbeard.DYNDNS_HOSTNAME == '' :
            if sickbeard.LOCALHOST_IP == '':
                    t.webui_url = re.sub('localhost', helpers.get_lan_ip(), sickbeard.TORRENT_HOST)
            else:
                t.webui_url = re.sub('localhost', sickbeard.LOCALHOST_IP, sickbeard.TORRENT_HOST)
        elif sickbeard.DYNDNS_HOSTNAME != '':
            t.webui_url = sickbeard.DYNDNS_HOSTNAME
        else:
            t.webui_url = sickbeard.TORRENT_HOST
```

**Comment by abeloin** [comment]
Wont work if torrent_host is 192.168.1.1

This, it nearly the same as the one I gave you before
```
        if sickbeard.DYNDNS_HOSTNAME == '':
            t.webui_url = sickbeard.DYNDNS_HOSTNAME
        else:
            if re.search('localhost', sickbeard.TORRENT_HOST):
    
                if sickbeard.LOCALHOST_IP == '':
                    t.webui_url = re.sub('localhost', helpers.get_lan_ip(), sickbeard.TORRENT_HOST)
                else:
                    t.webui_url = re.sub('localhost', sickbeard.LOCALHOST_IP, sickbeard.TORRENT_HOST)
            else:
                t.webui_url = sickbeard.TORRENT_HOST
```

**Comment by fernandog** [comment]
@abeloin done

**Comment by fernandog** [comment]
@abeloin is this ok to merge?

**Comment by abeloin** [comment]
Have you tested it? If so yes.

**Comment by fernandog** [comment]
@abeloin does not work if user uses IP instead of localhost:

re.sub won't work

```
        if sickbeard.DYNDNS_HOSTNAME != '':
            t.webui_url = re.sub('localhost', sickbeard.DYNDNS_HOSTNAME, sickbeard.TORRENT_HOST)
```

**Comment by abeloin** [comment]
I don't understand, where that code come from it's not in the PR:
```
 if sickbeard.DYNDNS_HOSTNAME != '':
t.webui_url = sickbeard.DYNDNS_HOSTNAME
else:
if re.search('localhost', sickbeard.TORRENT_HOST):
if sickbeard.LOCALHOST_IP == '':
t.webui_url = re.sub('localhost', helpers.get_lan_ip(), sickbeard.TORRENT_HOST)
else:
t.webui_url = re.sub('localhost', sickbeard.LOCALHOST_IP, sickbeard.TORRENT_HOST)
else:
t.webui_url = sickbeard.TORRENT_HOST
```

**Comment by fernandog** [comment]
I didn't PR yet. I was wrong. sorry. we need to use the "t.webui_url = re.sub(" .....otherwise it won't get the torrent_host port and protocol

**Comment by abeloin** [comment]
What happen if the the user decides to map the torrent port on the external ip to a different port? I think you should leave it like this and specify in the text that if the external port is other than 80 it must be specified.

**Comment by fernandog** [comment]
@abeloin now its working with IP or localhost. tested both

**Comment by TagForce** [comment]
@fernandog @abeloin What is the use of manage torrents anyway? It's not actually catching and forwarding all the clicks/calls/http get responses inside SR is it? So basically it's just a window inside Sickrage that redirects to the webui for your torrent client.

If that is the case, wouldn't it be easier to just make it a redirect to a new tab? Or it should actually catch everything and be its own webui for the client, but that would make it a 'bit' hard to code.

**Comment by abeloin** [comment]
@TagForce I honestly don't know why a user can't open a second tab or have it sent the user/pass in clear.
For me the whole thing scream security issue, but it look like a lot of users use it so this is why it's maintain I guess.

**Comment by fernandog** [comment]
@abeloin @TagForce I use very few times. we can remove it then. security issues

**Comment by abeloin** [comment]
Instead of removing now, we could add a deprecate warning on the manage torrent page informing users about the removal of that feature in the near future. This way we can have a feedback

**Comment by TagForce** [comment]
@abeloin @fernandog Sounds like a plan. It doesn't really add anything. Deprecate it, then remove it completely.

**Comment by fernandog** [comment]
@miigotu what do you think of this?

**Pull request closed without merging**
