### PR TITLE
Use enzyme to detect embedded subtitles instead of subliminal

### PR DESCRIPTION
**Pull request by medariox**
Fixes https://github.com/SiCKRAGETV/sickrage-issues/issues/3024, https://github.com/SiCKRAGETV/sickrage-issues/issues/2936, https://github.com/SiCKRAGETV/sickrage-issues/issues/2874. Probably also https://github.com/SiCKRAGETV/sickrage-issues/issues/2965.

Credits to @Diaoul for the original code.

### CODE REVIEW

**Comment by Diaoul** [comment]
This is not the proper fix. You should use str for paths, not unicode in python2. The issue is that python getsize tries to automatically encode your unicode into str using what python think is the best encoding for filesystem which is ascii and it fails to do that due to special characters.

If you know the filesystem encoding, I suggest you encode the path *before* you pass it to subliminal. It should do the job as subliminal can work with native strings since 1.1.0 (*not released yet*, see commit https://github.com/Diaoul/subliminal/commit/79fb0442dd30ab4207f4a52fae9c3e8efb1eb451).

I suggest you read the following: https://github.com/mitsuhiko/click/blob/master/docs/python3.rst

**Comment by medariox** [comment]
Thanks for the heads up!

You are surely right, the path should be a str not unicode. Anyway, we do not need scan_video in this context, as we are just looking for embedded subtitles and using e.g. GuessIt would result in an unnecessary additional resource consumption. I think this is an acceptable fix for now.

**Comment by NicoLeOca** [comment]
@medariox 
With this fix, should we expect a better accuracy in language recognition or not?

**Comment by medariox** [comment]
@NicoLeOca 
No, this doesn't change anything on that front.

**Comment by NicoLeOca** [comment]
@medariox @Diaoul 
I got this results then:
image

Where are the issues?
SR and I'll be patient until the whole subtitles thing is updated along with subliminal 1.1
or should I raise issues under enzyme repo?

**Pull request merged**
