### PR TITLE
Update removed words

### PR DESCRIPTION
**Pull request by matigonkas**

### CODE REVIEW

**Comment by miigotu** [comment]
That is at the end of the title?

**Comment by miigotu** [comment]
I think you meant to just put `.\[No RAR\]$` ??? I can't find any other suffix on TD

**Comment by miigotu** [comment]
`Insurgent.2015.HC.720P.WEB-DL.x264.AAC-Chuck [NO RAR]`

**Comment by matigonkas** [comment]
yes 
nope
example : ```Hardcore.Pawn.S01E04.DSR.XviD-OMiCRON [NO-RAR] - [ www.torrentday.com ]```

**Comment by matigonkas** [comment]
Also @miigotu  ive noticed that sr gets the release name from the file first And if it fails from the folder ,is this the intended way?

**Comment by miigotu** [comment]
Yep.

**Pull request merged**
