### PR TITLE
Add DVDMux & BDMux as valid SDDVD qualities

### PR DESCRIPTION
**Pull request by duramato**
as suggested here http://feathub.com/SiCKRAGETV/SickRage/+9

DVDMux ,BDMux are the same as a DVDRip and BDRip ,but with muxed/embebed subs

### CODE REVIEW

**Comment by miigotu** [comment]
aka if we add this then I would start getting subbed or language muxed releases downloaded? Most of our users don't want foreign languages.

**Comment by duramato** [comment]
they already would download ,ist the same case as x265,if they dont whant them then add the language code to ignered list ,like SWE,ITA,RU,etc

**Comment by miigotu** [comment]
what do you mean they already would download? what do they get detected as now?

**Comment by WebSpider** [comment]
It should at lease be configurable, imo. I'm not a fan of non-original audio either, that's what subs are for.

-----Original Message-----

**Comment by duramato** [comment]
@miigotu unknown ,also most muxed releases already are detected normally as they only have the langage code in the name, like Survivor's Remorse S02E02 VOSTFR HDTV

**Comment by duramato** [comment]
@WebSpider unless you configure a ignored word ,it will also download they SR is ,this just adds correct recognision

**Comment by WebSpider** [comment]
Yeah I do have quite some blacklisted words, that's true

-----Original Message-----

**Comment by miigotu** [comment]
Unknown was not originally included in `All` quality setting for exactly this reason, and soon will not be included again.

We need to update the default ignored words again btw. I have it working nice on my main install, but it took quite awhile to get it to be ok.

**Comment by duramato** [comment]
@miigotu Ignored words exist for this reason 
thake this release ```Hannibal.s01e01.WEB-DLRip.XviD.Rus.Eng.BaibaKo.tv``` unless it you have rus added to the ignored words SR will download and detect the quality

**Comment by miigotu** [comment]
It should be in line 286 and 288 also then, lets try and be uniform.

**Comment by duramato** [comment]
@miigotu if you dont mind ,ill do the blu ray part on another pr

**Pull request merged**
