### PR TITLE
Added legendastv subs provider, added login for subs (python), many b…

### PR DESCRIPTION
**Pull request by medariox**
…ug fixes to subliminal, added fix for pol/bul subs, much, much more.

DO NOT MERGE YET

Needs a GUI (make, js) before merging.

Will add a more detailed changelog and a patch asap.

Big thanks to @ratoaq2 for legendastv and @Diaoul for subliminal.

### CODE REVIEW

**Comment by fernandog** [comment]
@ratoaq2 

SR creates POB (pt-br) and POR (pt-pt) in config.ini (SR settings)

how to you translate it to legendastv language codes?

**Comment by fernandog** [comment]
@miigotu we are using opentsubtitles POB in config.ini but i think legendastv don't recognize that

when I run:
```
import sys;sys.path.insert(1, '/home/osmc/SickRage');sys.path.insert(1, '/home/osmc/SickRage/lib')
from sickbeard import subtitles
from babelfish import Language
languages = {Language('pob')}
providers = ['legendastv']

found_subtitles = subtitles.subliminal.download_best_subtitles([video], languages=languages, hearing_impaired=False, only_one=False, providers=providers)
```

I get 
```
Traceback (most recent call last):
  File "sub.py", line 9, in <module>
    languages = {Language('pob')}
  File "/home/osmc/SickRage/lib/babelfish/language.py", line 82, in __init__
    raise ValueError('%r is not a valid language' % language)
ValueError: 'pob' is not a valid language

```

**Comment by fernandog** [comment]
From http://babelfish.readthedocs.org/en/0.1.1/

Country specific language:
>>> language = babelfish.Language('por', 'BR')
>>> language
<Language Portuguese, country=BRAZIL>

so we should add por-BR to config.ini and convert to "Language('por', 'BR')" -
Not POB - as this one is for opensubtitles only
then in opensubtitles we convert to POB

**Comment by fernandog** [comment]
```
from babelfish import Language

language = Language('por', 'BR')
print language

language = Language('por')
print language

language = Language('por','PT')
print language
```

```
pt-BR
pt
pt-PT
```

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/713

**Comment by miigotu** [comment]
@fernandog your code there is wrong compared to how SR does it. Its Language.fromopensubtitles('pob')

**Comment by andremacola** [comment]
is not working

**Comment by felipesalomao** [comment]
legendas.tv is working with sickrage ? How  ?

**Pull request merged**
