### PR TITLE
New Feature - Send log to get support (log can be filtered/searched)

### PR DESCRIPTION
**Pull request by fernandog**
Both **Submit Errors** and **Submit log for Support** now redirect to the ISSUE page

https://github.com/SiCKRAGETV/sickrage-issues/issues/951

### CODE REVIEW

**Comment by fernandog** [comment]
@abeloin what if you add 4 hidden text fields + 1 "send" button in inc_top.tmpl and when user press "submit log for support" we show them, and user must type the "Title","What you did","What happened", "What you expected" and if all four are filled with at least x chars, user can "send" the log?

**Comment by fernandog** [comment]
@TagForce any suggestions?

**Comment by fernandog** [comment]
@abeloin are you going to make another PR about this?

**Comment by abeloin** [comment]
Yes

**Pull request closed without merging**
