### PR TITLE
Support for Foreign Releases based on Show Language

### PR DESCRIPTION
**Pull request by cytec**
see https://github.com/SiCKRAGETV/sickrage-issues/issues/979

### CODE REVIEW

**Comment by fernandog** [comment]
@cytec why remove german and french but not dutch and swedish?

**Comment by cytec** [comment]
@fernandog well i only knew search keywords for german and french, so i only added those... i could have guessed spanish, dutch, swedish etc but i think its better if someone reports and it gets changed then :)

supporting additional languages is now as easy as just adding the ISO Code and the REQUIRED words list to `languageMap` dict in `show_name_helpers`

**Comment by fernandog** [comment]
@cytec shouldn't we add a NOTE in ignore words about show language feature?

**Comment by cytec** [comment]
@fernandog maybe also change this line: https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/interfaces/default/home_newShow.tmpl#L72 so it is more clear that changing the Language in fact will search for releases in that language at least for german/french/english with this changes

adding a NOTE somewhere that there are dynamically added ignore/required words when selecting a language also would be nice, but i don't know if and where to put that note to :/

My fork was basically targeting german users which all knew that changing the quality will result in require german in the release name. Maybe for a much larger and multi language userbase that will not be clear without explicit stating it somewhere.

Im open to suggestions on how to fix/change that. My suggestions:
Change the line mentioned above to reflect the recent changes to something like this:
`This will affect the language of the retrieved metadata and <b>WILL ALLOW</b> SickRage to download non-english TV episodes!`

and here: https://github.com/SiCKRAGETV/SickRage/blob/master/gui/slick/interfaces/default/editShow.tmpl#L79 
something like:

`Show Language: (this will dynamically add required/ignored words for the selected language)`

**Comment by fernandog** [comment]
@abeloin thoughts?

**Comment by abeloin** [comment]
@fernandog Not really

**Comment by cytec** [comment]
@fernandog @abeloin i don't get it... first: `don't merge` tag, then it gets merged, then reverted... and not a single word about any of those decisions :/

Just curious... is this something you don't want or just not as it is right now?

**Comment by fernandog** [comment]
@cytec not right now. We need to make sure our master is stable first. We have a lot of PR for new features that have the "don't merge". Then we need to understand all these new features and make Wikis explaining how to config them and etc. Otherwise we won't be able to support/reply issues from users. I hope you understand!

**Comment by cytec** [comment]
@fernandog yup everything clear now, thanks for the response ;)

**Comment by fernandog** [comment]
@cytec can you still make a wiki full explaining how this works?

will insert here:
https://github.com/SiCKRAGETV/SickRage/wiki

**Comment by cytec** [comment]
I'll do

**Comment by cytec** [comment]
@fernandog since i was unable to edit SickRage Wiki, i've made a page here:
https://github.com/cytec/SickRage/wiki/Multilanguage-Settings

**Comment by fernandog** [comment]
@cytec nice! thanks!

**Comment by cytec** [comment]
I've just added `spanish` and `italian` to the list of supported languages.
Also i'm currently working on language change in `massEdit`

**Comment by fernandog** [comment]
@cytec we are working on a preferred words feature. Isn't better with that feature?

**Comment by cytec** [comment]
@fernandog prefered words would be nice too... so one can prefer a release of a specific group :)

**Comment by fernandog** [comment]
@cytec Or language. I prefer english but I accept italian for example.

**Comment by LexMih** [comment]
Hello,

Would it be possible to add the same show twice without the error: "xxxxxx is already in your show list", so I can have for exemple the same show in English and French in the same library ?
Is there a way around ?

Thank you !

**Pull request merged**
