### PR TITLE
Fix imdb popular

### PR DESCRIPTION
**Pull request by jonathanendersby**
Better handling of exceptions.
Added caching for Images. (bypasses referrer banning).
Converted imdbPopular into a class.
Small style changes.
Small bug fixes.

### CODE REVIEW

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/28d7f48ff513ae739aebc337ce0005f76f9a4acd

**Comment by fernandog** [comment]
@jonathanendersby @miigotu too complex to check if show already is in SR and not suggest it or disable the "add" button ?

**Comment by WebSpider** [comment]
Have to agree here, seeing shows in the overview that are already in SR is a bit annoying.

**Comment by fernandog** [comment]
I like to see my shows are 'popular' - others may not
But there is no point to show add button

**Comment by jonathanendersby** [comment]
It's going to be quite tricky (maybe even impossible) to 100% accurately match up show names (ie strings) with TVDB/TVRage IDs in order to compare the popular list to which shows you already follow on SR. Basically we'd have to do a search against TVDB and the guess which show from the results it the right one... 

That all said, we could decide that if the two name strings (IMDB vs SR) match perfectly, then we grey out that show... But I don't think IMDB follows Scene naming conventions closely enough for this not to get confusing.

Thoughts?

**Comment by miigotu** [comment]
I think its more processing and potential bugginess to attempt to modify the list.  We return the list just as it is on IMDB and there is no problem with that, you can compare how many shows on that list you have vidually.

**Comment by fernandog** [comment]
@jonathanendersby 
all shows have the imdb_id in the database (tv_shows table). Just use that.

**Comment by miigotu** [comment]
@fernandog isn't it more important to get it working without a 20 seconds page load than to worry about disabling a button?

**Comment by jonathanendersby** [comment]
I'll check if the ID in the URL is the actual IMDB ID, and if it is I'll see what I can do re greying out buttons...

But I agree with @miigotu that the initial cache delay is painful and feels broken. Can we not add a call to  imdbPopular.__init__() at startup? Is there a thread for Miscellaneous?

**Comment by miigotu** [comment]
@jonathanendersby there is not currently.

**Pull request closed without merging**
