### PR TITLE
Fix KeyError in findNeededEpisodes

### PR DESCRIPTION
**Pull request by gborri**
Need to be tested a bit more

### CODE REVIEW

**Comment by fernandog** [comment]
@gborri please test and let us know when to merge

**Comment by abeloin** [comment]
@gborri I tried doing that yesterday night with code a lot less complicated than this PR :
```
            _ = curResult["episodes"].split("|")
            if type(episode) != list and len(_) > 1:
                if unicode(episode.episode) in _:
                    curEp = unicode(episode.episode)
                else:
                    continue
            else:
                curEp = _[1]
```
which replace line `curEp = curResult["episodes"].split("|")[1]` in:
```
                continue
            curEp = curResult["episodes"].split("|")[1]
            if not curEp:
```
This isn't a fix, what will end up happening is SR will download the torrent 12 times in the case of the killing when doing a season search because you've return the same data for the 12 episodes. Or 2 times in your case for https://github.com/SiCKRAGETV/sickrage-issues/issues/1017

BTW this PR doesn't work:
```
AANameError: global name 'curResult' is not defined
AA    curSeason = int(curResult["season"])
AA  File "D:\SickRage\sickbeard\tvcache.py", line 355, in findNeededEpisodes
AA    neededEps = self.findNeededEpisodes(episode, manualSearch, downCurQuality)
AA  File "D:\SickRage\sickbeard\tvcache.py", line 301, in searchCache
AA    cacheResult = self.cache.searchCache(epObj, manualSearch, downCurQuality)
AA  File "D:\SickRage\sickbeard\providers\generic.py", line 269, in findSearchResults
AA    searchResults = curProvider.findSearchResults(show, episodes, search_mode, manualSearch, downCurQuality)
AA  File "D:\SickRage\sickbeard\search.py", line 480, in searchProviders
AATraceback (most recent call last):
```

**Comment by abeloin** [comment]
Ref https://github.com/SiCKRAGETV/sickrage-issues/issues/1017

**Comment by gborri** [comment]
@abeloin It won't download 12 times the torrent. it get all the result from cache and rearrange per episode. we got more than 1 torrent for the same episode.

**Comment by gborri** [comment]
@abeloin it won't work for a bug. i cant update for  SiCKRAGETV/sickrage-issues#1070

**Comment by abeloin** [comment]
@gborri Update your branch, a fix was pushed

**Comment by gborri** [comment]
@abeloin I tried to rebase after your fix but the problem has grown.

      gui/slick/interfaces/default/displayShow.tmpl
        gui/slick/js/ajaxEpSearch.js
        gui/slick/js/fuzzyMoment.js
        lib/subliminal/services/tvsubtitles.py
        lib/subliminal/videos.py
        lib/unrar2/.hgignore
        lib/unrar2/MANIFEST.in
        lib/unrar2/UnRAR2.html
        lib/unrar2/UnRARDLL/unrar.h
        lib/unrar2/UnRARDLL/unrardll.txt
        lib/unrar2/UnRARDLL/whatsnew.txt
        lib/unrar2/UnRARDLL/x64/readme.txt
        lib/unrar2/[test].txt
        lib/unrar2/__init__.py
        lib/unrar2/license.txt
        lib/unrar2/setup.py
        lib/unrar2/test_UnRAR2.py

**Comment by abeloin** [comment]
@gborri Make a new one, but before that have look at my comment about the multiple download:https://github.com/SiCKRAGETV/sickrage-issues/issues/1017#issuecomment-87777222 ? There's a pastebin in that comment showing the multiple download

**Comment by fernandog** [comment]
@gborri 
https://github.com/SiCKRAGETV/sickrage-issues/issues/1169

**Pull request closed without merging**
