### PR TITLE
Fix SiCKRAGETV/sickrage-issues/issues/2911

### PR DESCRIPTION
**Pull request by fernandog**
@MGaetan89 ok?

I removed all 'font-family' from the file

Everything seems ok! Issue is fixed

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
@fernandog do not edit library files or minified files.
This is NOT okay.

If you want to fix this it'll need to be an override like all of the other CSS.

**Comment by fernandog** [comment]
inherit ?

**Comment by duramato** [comment]
This has fixed it for me on Chrome
SS comparison
Before: https://usercontent.irccloud-cdn.com/file/qXpqVOGB/
After: https://usercontent.irccloud-cdn.com/file/dJ0PV86E/

**Comment by fernandog** [comment]
@OmgImAlexis but it's a 'custom' version, it was manually created in http://jqueryui.com/download/ AFAIK

**Comment by OmgImAlexis** [comment]
@fernandog it doesn't matter where it was made, library js and css should NEVER be changed. Add an override to the style.css if you need to change something, keep in mind that we're moving away from static library files and towards using bower so most of the library files will only be in the _bower.min.css once I've finished meaning no changes can be in them.

**Comment by fernandog** [comment]
@OmgImAlexis adding !important; to font-family in style.css ?

**Comment by MGaetan89** [comment]
Just for information the bootstrap CSS file was already changed.
This was made because the top menu was too big and the viewport were not large enough.
With the new menu, it should no longer be an issue, and we should be able to use the original file. But as a migration to Bootstrap 4 is in progress, it's not important I guess.

**Comment by fernandog** [comment]
well, i think it's important. seems a quick fix

**Comment by miigotu** [comment]
@fernandog leave the js/css to the people in charge of that. We are just supposed to review/approve their changes there, not make them ourselves at this point.

**Comment by fernandog** [comment]
OK. but this is a simple fix. Will keep waiting...

**Comment by miigotu** [comment]
simple doesn't mean proper.

**Comment by fernandog** [comment]
Not my fix. I said its simple to fix the issue.

**Comment by fernandog** [comment]
@OmgImAlexis @MGaetan89 as BS4 its not near how to fix that issue?

**Comment by MGaetan89** [comment]
We just have to restore the font where it was removed.
I guess it disappeared when I removed duplicated CSS removed a while back.

**Pull request closed without merging**
