### PR TITLE
Use getURL to do post requests, so cache control is used, sessions pe…

### PR DESCRIPTION
**Pull request by miigotu**
…rsist, and global settings such as allow_redirects and SSL Verify are honored. SiCKRAGETV/sickrage-issues#2532

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu I reverted this and the issue about recursions is gone

**Comment by miigotu** [comment]
And without people cant login to their providers.

Reverting this is not the solution, fixing the actual recursion is.

**Comment by fernandog** [comment]
so how everything worked before this? I never had issue with TD and HDT.
Only one provider had issues with login (issue 2532)

**Comment by miigotu** [comment]
@fernandog just because it worked for you does not mean it worked for everyone else. This is why we have an assload of issues before this for ipt and scc and TL/TD.

If the users system did not work perfect for SSL they could not log into these sites for searches.

Be a little more patient and a little less demanding geez. We already work at a hella fast pace and get A LOT of shit done quick, and this will be fixed soon enough. Reverting it doesn't make sense because then a proper fix will likely be forgotten and never get done.

**Comment by fernandog** [comment]
I'm patient. This issue is from 7 days ago only.
As I said in IRC, fall season is in the corner and we need a stable master (kind of) and keep all new features in develop or feature branch and keep them there until fully tested IMHO. Otherwise we will have a LOT more issues/complains about shows not being downloaded.

**Pull request merged**
