### PR TITLE
Change message about unable to find show

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/1959

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu why invalid syntax?? There's no line break.

```
    logger.log(u"Show name with ID %s don't exist in %s anymore. Please change/delete your local .nfo file or remove it from your TRAKT watchlist") %
                                                                                                                                                    ^
SyntaxError: invalid syntax
```

**Comment by abeloin** [comment]
@fernandog Check your parenthesis

**Comment by abeloin** [comment]
Using format:
```
logger.log(u"Show name with ID {show_id} don't exist in {indexer_name} anymore. Please change/delete your local .nfo file or remove it from your TRAKT watchlist".format(show_id = self.indexer_id, indexer_name = sickbeard.indexerApi(self.indexer).name), logger.ERROR)
```
printf-style:
```
logger.log(u"Show name with ID %s don't exist in %s anymore. Please change/delete your local .nfo file or remove it from your TRAKT watchlist" % (str(self.indexer_id), str(sickbeard.indexerApi(self.indexer).name)), logger.ERROR)
```

**Comment by fernandog** [comment]
it's crashing about other thing:

```
======================================================================
FAIL: test_SNI_URLS (ssl_sni_tests.SNI_Tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/SiCKRAGETV/SickRage/tests/ssl_sni_tests.py", line 53, in test_SNI_URLS
    self.assertEqual(requests.get(provider.url).status_code, 200)
AssertionError: 504 != 200

```

**Comment by abeloin** [comment]
One of the 3 providers is returning an http 504(gateway timeout) instead of 200.

You can ignore it

**Pull request merged**
