### PR TITLE
Refactor /comingEpisodes/ to /schedule/ in GUI and save sort

### PR DESCRIPTION
**Pull request by VinceVal**
Also added a check for General/default_page to make sure it's valid.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
@MGaetan89 is this OK? need to change something in the apibuilder/api ?

**Comment by fernandog** [comment]
@miigotu

**Comment by MGaetan89** [comment]
@fernandog API/API builder should not be impacted by this as it concerns the web part.

**Pull request merged**
