### PR TITLE
Move the js from mako to .js files

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
@MGaetan89 does this look okay? I know I broke a few things with my last few commits.

**Comment by MGaetan89** [comment]
Quickly looked at it, and it looks good to me.

**Comment by OmgImAlexis** [comment]
By the way I'm redoing a lot of the home.js logic for the sorting functions and moving to using data elements so if you need to change anything with that you may need to wait till after I've finished this.

**Comment by MGaetan89** [comment]
I'm on the API builder for the moment, so you can have fun on the home ;)
If we are not planning anything there, we won't block each other.

**Comment by OmgImAlexis** [comment]
All's good, just thought I'd let you know. :+1:

**Comment by OmgImAlexis** [comment]
@fernandog or @miigotu when you get the chance can this please be merged into develop.

**Comment by miigotu** [comment]
tested everything you actually changed? filterRow and table sorting?

**Comment by OmgImAlexis** [comment]
@miigotu yep, as far as I can tell it all works fine. The only problem I had was the reset button and I've fixed that.

**Comment by miigotu** [comment]
Ok, merged another release just before adding this, because we just fixed a hella stuff in hotfixes yesterday morning.

**Comment by OmgImAlexis** [comment]
Alright. :+1:

**Comment by miigotu** [comment]
Going to work on merging /js/*.js and /js/new/*.js ?

**Comment by OmgImAlexis** [comment]
Yes, first all js from mako files is to be moved into `/js/new/*.js` and then I'm going to lint all of the old stuff and merge everything into single files per page along with common files like the tablesorting parsers. Once @MGaetan89 gets the api finished and we get the new parts up and going I should be able to remove the `<%block name="metas">` as well.

**Comment by miigotu** [comment]
Btw, the last round was a big speed improvement for me, good job.

**Comment by OmgImAlexis** [comment]
Woo! Guessing a lot of that's from linting. That's another reason why I want to get the js out of the mako files. My linter goes crazy thinking .mako files are pure HTML and thinks the `<%block>` sections are weird regex that aren't closed so I can't actually lint the js. Once it's in it's own file it's fine.

**Pull request merged**
