### PR TITLE
Add TPBT provider

### PR DESCRIPTION
**Pull request by matigonkas**
Add provider for tpbt.org a torrent website using the OpenBay project

### CODE REVIEW

**Comment by fernandog** [comment]
@matigonkas is this fully tested?

**Comment by matigonkas** [comment]
yes @fernandog it should be all good now . I also added a icon for National Geographic Channel (is it good @neoatomic ?)

**Comment by neoatomic** [comment]
@matigonkas Yes, logo its fine. Thanks for adding.

**Comment by fernandog** [comment]
@matigonkas still testing, isn't?

**Comment by matigonkas** [comment]
yes @fernandog been running for the last couple of days but so far hadnt got any issues ,so it should be ready to be merged.

**Comment by abeloin** [comment]
@matigonkas Please rebase to the latest version of the develop branch

**Comment by matigonkas** [comment]
@abeloin is it ok now?

**Comment by abeloin** [comment]
@matigonkas Nope, try:
```
git fetch
git rebase origin/develop
```

**Pull request closed without merging**
