### PR TITLE
Fix warnings in webapi.py

### PR DESCRIPTION
**Pull request by MGaetan89**
This PR only fix warnings and comply to PEP8:
- Remove unused imports
- Rename variables/methods/...
- Format code

This is still a WIP, so don't merge it yet.

### CODE REVIEW

**Comment by MGaetan89** [comment]
Ow, the diff is too big so GitHub doesn't display it :/

There is always the hard way https://github.com/SiCKRAGETV/SickRage/pull/2137.diff :stuck_out_tongue:

**Comment by miigotu** [comment]
@MGaetan89 I rather wait and do this on the entire source in one commit with autopep8

**Comment by MGaetan89** [comment]
Ok, I understand. So I just close this PR?

**Comment by miigotu** [comment]
Yes, because you changed more than just pep8 in one commit =P, it makes history impossible to follow:

silly example how I know:
```
-            indexerShow = helpers.mapIndexersToShow(curShow)
+            indexer_show = helpers.mapIndexersToShow(curShow)
```

**Comment by MGaetan89** [comment]
pyCharm recommended my to use only lowercase variables/methods name.
I didn't know there is a tool to automatically do that. It will be a lot easier to do it with `autopep8` lol

**Comment by miigotu** [comment]
I think I'm gonna try and get used to using pyCharm, never used it before (but I've used Android Studio, also jetbrains)

I mostly do my coding right in nano or vim these days

**Pull request closed without merging**
