### PR TITLE
Fix accent issue on system with locale like POSIX.

### PR DESCRIPTION
**Pull request by abeloin**
Network image télé-québec.png issue with locale like POSIX
See SiCKRAGETV/sickrage-issues#427 for more info

### CODE REVIEW

**Comment by maxcore** [comment]
Thx merci :)

**Comment by fernandog** [comment]
@abeloin should we merge this or force user to use UTF-8?

**Comment by abeloin** [comment]
@fernandog I think we should merge it. Sadly, not all systems(mostly embedded) have the proper locale. Ultimately the way network logos works right now should be changed to a table lookup that retrieve the proper logo as the current way can't cope with all the languages(e.g: Mandarin, Russian, ...)

**Comment by fernandog** [comment]
Ok!

**Pull request merged**
