### PR TITLE
Cache control fix

### PR DESCRIPTION
**Pull request by normtown**
Force CacheControl to use MkdirLockFile. Addresses https://github.com/SiCKRAGETV/sickrage-issues/issues/2118?_pjax=%23js-repo-pjax-container

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
Please rebase so you only have your commit.

**Comment by miigotu** [comment]
Also, I'm trying to figure out if MkDirLockFile has negative implications on unix, so is the community:

From the documentation:
```
Note The current implementation uses os.link() on Unix, but since that function is unavailable on Windows it uses os.mkdir() there. At this point it’s not clear that using the os.mkdir() method would be insufficient on Unix systems. If it proves to be adequate on Unix then the implementation could be simplified and truly cross-platform locking would be possible.
```
and:
```
By default, the LockFile object refers to the mkdirlockfile.MkdirLockFile class on Windows. On all other platforms it refers to the linklockfile.LinkLockFile class.
```

Documentation is here:
https://pythonhosted.org/lockfile/lockfile.html#lockfile.linklockfile.LinkLockFile

Im curious about this: https://pythonhosted.org/lockfile/lockfile.html#lockfile.sqlitelockfile.SQLiteLockFile

and the `threaded` parameter.

**Comment by miigotu** [comment]
@normtown I will merge this on command line and push it for you.

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/commit/7b584bc9702a03b922a515f4eeb405384c1ed624

**Comment by normtown** [comment]
Thanks. Sorry about the messy pull request. FYI, I tested this locally on OSX, Ubuntu, and in my Unraid Docker container (sans-cache disk). Pretty confident it will work without issue in most cases, but obviously I can't guarantee. Can revisit with more comprehensive feature detection if this causes issues for folks.

**Comment by miigotu** [comment]
I think is should be ok, every os/filesystem supports the mkdir syscall, not all support the link syscall.n The library itself is in transition to possibly of just making linklockfile be an alias of mkdirlockfile.

**Comment by miigotu** [comment]
We might need to patch pylockfile for OSX...
https://bugs.launchpad.net/pylockfile/+bug/1463968

**Comment by normtown** [comment]
Nice find. I'll try to take a look this week. Might also explore the
SQLLite lock class.

**Pull request closed without merging**
