### PR TITLE
Display "Add anime" after the anime table

### PR DESCRIPTION
**Pull request by MGaetan89**

### CODE REVIEW

**Comment by miigotu** [comment]
em, rebase?

**Comment by miigotu** [comment]
`git rebase upstream/develop`

**Comment by miigotu** [comment]
Im gonna be a squash nazi for the next week or so at least. Last develop->master merge was > 140 commits in 6 days or so.

**Comment by MGaetan89** [comment]
No problem, I understand. Maybe the SR bot could post a comment when the label "Rebase/Squash" is added with instructions about what to do? This would reduce your amount of work.

For some reason, I did not manage to get this branch (`patch-1`) locally. So I redid the changes and submitted an other PR: https://github.com/SiCKRAGETV/SickRage/pull/2464

**Comment by miigotu** [comment]
@MGaetan89 Agree about the bot. But we can't get it set up because I'm not an owner and I don't know how to explain how to do it to @fernandog

**Comment by MGaetan89** [comment]
I don't know either :/

**Pull request closed without merging**
