### PR TITLE
New T411 domain

### PR DESCRIPTION
**Pull request by alex-ikse**

### CODE REVIEW

**Comment by echel0n** [comment]
Closed as this has been manually added into both master/develop branches ... thanks!

**Comment by HLFH** [comment]
@echel0n Fuck you for having closed the Sickrage fork by filling [a fake DMCA request](https://github.com/github/dmca/blob/master/2017/2017-07-17-SiCKRAGE.md).

 https://github.com/SickRage/SickRage/
Your fork of SickBeard is unworthy for two reasons:
 - you [don't respect](https://www.reddit.com/r/sickrage/comments/6oep02/false_dmca_request_has_taken_our_repos_down/) the open source community
 - by being unfair with other open source developers, you lose contributors, so your fork has now less interesting and valuable commits compared to the [SickRage fork](https://github.com/SickRage/SickRage/commits/master).

**Comment by alzeric** [comment]
HLFH Have you found the new fork yet?  Check out the Reddit page and you'll
find the real authors and contributors who have been maintaining it for the
duration of any major worthwhile update over there.  They started up their
own git and have moved things over to that for the time being.  And you are
right it truly is a shame scum like this effects our great community and is
trying to benefit off the backs of the real development team.  And the
people that care about SickRage and it's future development will find the
new team's repository and continue supporting the project the way it's
meant to be supported.

**Comment by HLFH** [comment]
@alzeric https://github.com/SickRage/sickrage.github.io/issues/252#issuecomment-319333652
I believe SickRage will reopen on Monday maximum.

**Pull request closed without merging**
