### PR TITLE
Prevent TraktRolling/TraktChecker queue to crash on trakt api error

### PR DESCRIPTION
**Pull request by gborri**

### CODE REVIEW

**Comment by Thraxis** [comment]
This should really be handled in the Trakt.py (API) file

**Comment by gborri** [comment]
@Thraxis it seems to be handled but it crash (seen from server status: alice-->red false)

**Comment by miigotu** [comment]
Agreed, the log line would only need added once in `self.trakt_api.traktRequest` and should include the requested uri, instead of a generic `could not connect`.  Where it fails/hangs I bet is some invalid data getting added to the returned list when the connection fails or trakt returns something funky, which is then ran through the for loop which follows the request.  Imho, this cannot be merged as is.

**Comment by miigotu** [comment]
Fix it in `trakt_api.traktRequest` and re-submit if you want this changed. Closing this.

**Pull request closed without merging**
