### PR TITLE
Show warning message to enable git reset or stash changes

### PR DESCRIPTION
**Pull request by fernandog**
@abeloin done!

```
2015-03-16 13:19:17 INFO     CHECKVERSION :: Update failed!
2015-03-16 13:19:17 INFO     CHECKVERSION :: Please enable 'git reset' in settings or stash your changes in local files
2015-03-16 13:19:09 INFO     CHECKVERSION :: Config backup successful, updating...
2015-03-16 13:18:08 INFO     CHECKVERSION :: Config backup in progress...
2015-03-16 13:18:07 INFO     CHECKVERSION :: New update found for SickRage, starting auto-updater ...
2015-03-16 13:18:02 INFO     MAIN :: Building internal name cache for all shows
2015-03-16 13:18:02 INFO     MAIN :: No scene exceptions update needed
2015-03-16 13:18:02 INFO     TORNADO :: Starting SickRage on http://0.0.0.0:8081/
```

### CODE REVIEW

**Comment by abeloin** [comment]
@fernandog Try changing `logger.log(u"Update failed!")` to `logger.log(u"Update failed!", logger.WARNING)

**Comment by fernandog** [comment]
@abeloin I can't reproduce the stash errors.

git reset --hard HEAD^
downloaded 1544.patch and 1550.patch
applied
started SR
and SR updaded. no stash errors! shouldn't detect I had changed my local file?

**Comment by fernandog** [comment]
it's not a logger.log problem I think. It only prints that AANone. I remember when this appear that I tried with logger.ERROR

when I added another log.logger, another AANone appeared

```
2015-03-13 11:53:32 ERROR    CHECKVERSION :: Please enabled 'git reset' in settings or stash your changes in local files
None
2015-03-13 11:53:33 ERROR    CHECKVERSION :: Returning false
None
2015-03-13 11:53:33 INFO     CHECKVERSION :: Update failed!
```

```
2015-03-13 12:03:18 ERROR    CHECKVERSION :: Please enabled 'git reset' in settings or stash your changes in local files
None
2015-03-13 12:03:18 ERROR    CHECKVERSION :: Update failed!
None
```

**Comment by abeloin** [comment]
@fernandog The stash error will appear if git pull will overwrite a file that has been modified and need to be updated.

**Comment by fernandog** [comment]
get it.
what about that append AA. what is the point of that? Seems x is None. But this only happens with my PR

**Pull request merged**
