### PR TITLE
Add AmActive to schedulers

### PR DESCRIPTION
**Pull request by fernandog**
Obs: Subtitle scheduler has def __init__(self)

https://github.com/SiCKRAGETV/sickrage-issues/issues/2552

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu This will fix the "N/A" in server status

image

**Comment by fernandog** [comment]
@miigotu didn't fix subtitles finder. Can't understand why.

**Comment by miigotu** [comment]
You need to add an `__init__()` that initializes self.amActive = False for subtitle finder @fernandog

**Comment by miigotu** [comment]
Going to do it now...

**Pull request merged**
