### PR TITLE
Update sublimnal to 1.0.1, subtitle logic in subtitles.py, much more

### PR DESCRIPTION
**Pull request by medariox**
This PR brings a few important changes:
- Subliminal updated to version 1.0.1
- Performance has been dramatically improved! Now the video file is scanned 1 time at most.
- The most important subtitle functions are now located in subtitles.py
- Subtitles will be refreshed now, before they are downloaded (avoids unnecessary download attempts)
- Added support for alpha3 country codes (e.g. "eng")
- Overall improvement of code logic (e.g. embedded subtitles are only being searched for, if desired)

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by WebSpider** [comment]
Thanks very much!

**Comment by miigotu** [comment]
@medariox ew you ended up having to patch the lib itself? x.X

**Comment by medariox** [comment]
@miigotu 
Sadly yes :( I didn't find any other way to make it work...

**Comment by WebSpider** [comment]
Any chance to get the patches accepted upstream, so we can follow the standard lib again?

**Comment by miigotu** [comment]
@WebSpider nope. The patch is actually in subliminal in a no_setup branch, but Diaoul is not keeping the branch up to date.

For now we will add a .patch with the differences in .build/patches/subliminal

**Pull request merged**
