### PR TITLE
update xthor add quotes to search string

### PR DESCRIPTION
**Pull request by raver2046**
add quotes to search string for better results in searching.

### CODE REVIEW

**Comment by miigotu** [comment]
Not really the correct solution, But I will merge it for now until I can rework the params.

**Comment by raver2046** [comment]
Yes but it works.

**Comment by miigotu** [comment]
When my kid doesnt listen I could kick him in the face and it would work, but is it the correct way?

**Comment by raver2046** [comment]
i try to do with my poor knowledge dude

**Comment by miigotu** [comment]
not being mean there, just making a point. If you want to learn, when someone who knows says "its not the best way" a good response would be "OK. which way would be better?" instead of "but it works".

That's why I said I would merge it, so it would work until I could make it use the better process later and maybe ping you to show you then.

**Pull request merged**
