### PR TITLE
Add daily search footer highlight updater

### PR DESCRIPTION
**Pull request by DungFu**
Added javascript code to update the daily search timeLeft footer highlight every second when the tab is active. The Date.now() logic is required so that the time properly updates when the tab is inactive. The timeLeft will also reset using the cycle time when the timeLeft reaches or goes below 0.

### CODE REVIEW

**Comment by DungFu** [comment]
updated to handle days correctly.

**Comment by fernandog** [comment]
@DungFu please squash the commits into one

**Comment by abeloin** [comment]
@fernandog Don't think this should be merged as when the status page will auto refresh it will have to query the server for that kind of info which then this code could use it to display the information.

**Comment by fernandog** [comment]
@abeloin ok!

@DungFu we now have a status page with all threads (develop). We won't merge this. Feel free to do other PRs. thanks!

**Pull request closed without merging**
