### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by sethwarsh**

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Give a description on what the PR is for.
- [ ] Make sure you send a PR against the DEVELOP branch
- [ ] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
Why are you trying to merge dev into master?

**Comment by sethwarsh** [comment]
Its an error. I'm just trying to switch my installation to download from the develop library.

Sorry.

Can you tell me how I can make that change it doesn't accept it in the web ui?

S

**Comment by OmgImAlexis** [comment]
Close this pull request, if you don't know how to switch to develop then you shouldn't be doing it. There is NO support at all if you're using that branch and there's no good reason to switch to it.

**Pull request closed without merging**
