### PR TITLE
Trakt: Catch all requests exceptions

### PR DESCRIPTION
**Pull request by abeloin**
See https://github.com/SiCKRAGETV/sickrage-issues/issues/616 for more info

### CODE REVIEW

**Comment by fernandog** [comment]
@abeloin 

got an traceback
```
2015-02-16 17:14:23 DEBUG    Thread-13 :: Getting recommended shows from Trakt.tv
AA
AAtraktException: 520 Server Error: Origin Error
AA    raise traktException(e)
AA  File "/home/pi/SickRage/lib/trakt/trakt.py", line 47, in validateAccount
AA    self.validateAccount()
AA  File "/home/pi/SickRage/lib/trakt/trakt.py", line 57, in traktRequest
AA    watchlist = self.trakt_api.traktRequest("sync/watchlist/shows")
AA  File "/home/pi/SickRage/sickbeard/traktChecker.py", line 150, in updateShows
AA    self.updateShows()
AA  File "/home/pi/SickRage/sickbeard/traktChecker.py", line 50, in run
2015-02-16 17:14:12 DEBUG    TRAKTCHECKER :: Traceback (most recent call last):
```

**Comment by abeloin** [comment]
@fernandog Can you provide the whole for thread-13

**Comment by abeloin** [comment]
@fernandog I'm unable to generate a traceback:
```2015-02-16 15:59:50 WARNING  Thread-45 :: Could not connect to Trakt service: error 520 Server Error: Origin Error```

**Comment by fernandog** [comment]
@abeloin seems ok!

```
2015-02-16 22:44:57 WARNING  Thread-29 :: Could not connect to Trakt service: error HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=1)
2015-02-16 22:44:56 DEBUG    Thread-29 :: Getting recommended shows from Trakt.tv
```

**Comment by abeloin** [comment]
@fernandog Merging then.

**Pull request merged**
