### PR TITLE
Shutil: Fix compatibility with Python 2.6

### PR DESCRIPTION
**Pull request by abeloin**
See https://github.com/SiCKRAGETV/sickrage-issues/issues/844 for more info

### CODE REVIEW

**Comment by shadowjustice** [comment]
This fix does not work for my box:
Hardware: Excito B3
**Operating system**:
Distributor ID: Debian
Description: Debian GNU/Linux 6.0.8 (squeeze)
Release: 6.0.8
Codename: squeeze

**Python version**:
Python 2.6.6 (r266:84292, Dec 27 2010, 21:57:32)
[GCC 4.4.5 20100902 (prerelease)] on linux2

**Error**:
<code>
Traceback (most recent call last):
  File "SickBeard.py", line 33, in <module>
    import lib.shutil_custom
  File "/home/programs/programs/sickbeard/lib/shutil_custom/__init__.py", line 6
SyntaxError: Non-ASCII character '\xc3' in file /home/programs/programs/sickbeard/lib/shutil_custom/__init__.py on line 6, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
</code>

**Comment by abeloin** [comment]
@shadowjustice How did you patched the file as there is no non-ascii characters in the patch?

**Comment by faidwen** [comment]
I had installed Python 2.7 alongside, I reverted the SR calls back to 2.6.6 applied the patch, and restarted.  Everything appears to work correctly with this patch installed on 2.6.6

Thanks

**Comment by abeloin** [comment]
@faidwen Thanks for the testing

**Comment by shadowjustice** [comment]
@abeloin I copy and pasted your changes into __init__.py in the shuttle custom folder with nano. (I log on my box with ssh)

**Comment by abeloin** [comment]
Can you try to update as the PR was merged? Let me know if you still have the error.

**Comment by shadowjustice** [comment]
@abeloin as mentioned before it is fixed now. I checked it with a mac os x terminal and found the error

**Pull request merged**
