### PR TITLE
Check if restore directory is empty to not restore

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/665

### CODE REVIEW

**Comment by abeloin** [comment]
@fernandog This commit makes no sense you just pull the content of that folder and do nothing with it

**Comment by fernandog** [comment]
@abeloin what if user has an empty "restore" folder?  Restore process will fail

**Comment by abeloin** [comment]
Better use try...except instead.

**Comment by fernandog** [comment]
will you add this to your commit? I'm closing mines.

**Comment by abeloin** [comment]
It's already in https://github.com/SiCKRAGETV/SickRage/pull/1358 . Each of the 2 steps are now enclosed with a try...except.

**Pull request closed without merging**
