### PR TITLE
Show log message when force propers when they are disabled

### PR DESCRIPTION
**Pull request by fernandog**

### CODE REVIEW

**Comment by abeloin** [comment]
@fernandog This message seem to be not needed, as the queue is not started if false(see sickbeard/__init__.py#L1353)

**Comment by fernandog** [comment]
@abeloin even force search? so why there's that check if is enabled?

**Comment by abeloin** [comment]
@fernandog Yes because the force search, set the variable to force the search but since the scheduler is not active it never happend.

See https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/scheduler.py#L47

**Comment by abeloin** [comment]
@fernandog What you could do is disable the force search proper in Manage Searches when it's not enable

**Pull request closed without merging**
