### PR TITLE
Restart with exec

### PR DESCRIPTION
**Pull request by dgholz**
fix for SiCKRAGETV/sickrage-issues#794

### CODE REVIEW

**Comment by dgholz** [comment]
rebased on latest develop

**Comment by Hellowlol** [comment]
Remember to change the api aswell if this gets merged

**Comment by fernandog** [comment]
@dgholz @Hellowlol 

is this helpful for your issue?
https://github.com/SiCKRAGETV/SickRage/pull/1590

**Comment by Hellowlol** [comment]
No really, but that because there is no issue for me.

**Pull request closed without merging**
