### PR TITLE
Added msg for partial download of multi-episode torrent isn't supported

### PR DESCRIPTION
**Pull request by gborri**
Fix SiCKRAGETV/sickrage-issues#1017

### CODE REVIEW

**Comment by gborri** [comment]
@abeloin i've removed the logging and followed your suggestion

**Comment by gborri** [comment]
@abeloin if you prefer my solution, let me know i will revert the last change.

**Comment by fernandog** [comment]
@gborri no errors with this PR?

**Comment by gborri** [comment]
@fernandog i've teste it with check available episode in which the error was stressed and i haven't find any problem.

**Comment by fernandog** [comment]
@gborri log message appears ok everytime

**Comment by gborri** [comment]
@fernandog yes

**Pull request merged**
