### PR TITLE
Add private or public label next to providers

### PR DESCRIPTION
**Pull request by fernandog**
**Need to adjust the box size**

@SiCKRAGETV/moderators suggestions?

providers

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Not a moderator, but I would say an icon denoting their status would be better.

**Comment by MGaetan89** [comment]
I like the idea of the icon, but I think it would be too much icons in each row (one for the provider, one to sort the providers and one for public/private).

**Comment by fernandog** [comment]
I tried to add color but isnt possible (AFAIK).

Adding icone needs a lot more coding and Im not expert.

**Comment by Arcanemagus** [comment]
As it stands the text method is breaking the UI (See the KickAssTorrents line).

**Comment by fernandog** [comment]
see my first comment in this PR

@Thraxis do you know a better way? I'm not an expert in html

**Comment by Thraxis** [comment]
Could use a CSS to change the color of the box / text if it is public / private. Otherwise it's increase the size of the box and / or use an icon of some kind  (padlock?)

**Comment by fernandog** [comment]
@Thraxis I couldnt increase size. Any hint?

Too complicated to add the padlock for private?
is it possible to order by public/private first then to name?

**Comment by miigotu** [comment]
.change the color of the box. Matches the idea of the rest of the theme then like episode status'

**Comment by Thraxis** [comment]
Something like this?
image

image

**Comment by Thraxis** [comment]
It's not 100% accurate as not all private trackers have a 'username' field (You'll notice BTN and Rarbg for example)

**Comment by fernandog** [comment]
Maybe instead of check username check for password. Some are just 'user' I think

**Comment by fernandog** [comment]
Rarbg is public

**Comment by Thraxis** [comment]
BTN just has API Key

**Comment by miigotu** [comment]
Maybe you could add a field to the nzb and torrent classes in generic.py, like access_type = 'public', and set it to 'private' in the init of each private indexer/tracker

**Comment by miigotu** [comment]
Then you just check against that in the template, and set the css class by it.

**Comment by fernandog** [comment]
@Thraxis do you want to try or should I fix the box size and merge it ?

**Comment by fernandog** [comment]
@Thraxis 
updated my code to handle passkey and api_key

**Comment by Thraxis** [comment]
@fernandog The problem with sorting is the purpose of that screen is to allow the user to order the providers as to how they want them searched (my understanding )

I think we need to do like miigotu suggested.  There needs to be a property in the provider module to tell if it is public or private.

You can have public providers that use API Keys, etc.

**Comment by miigotu** [comment]
Are enabled providers still moved to the top of the list in the user order?

**Comment by fernandog** [comment]
@miigotu neved saw that behavior. it's does not auto move AFAIK. user must move top

**Comment by miigotu** [comment]
I could have swore it used to, after you clicked save and refresh. That is easy to add btw. Keeps the user order, but all enabled are at the top.

**Comment by fernandog** [comment]
@miigotu sorry. yes. only when you save. the code "str(int(x.isEnabled()))" order by enabled

**Comment by miigotu** [comment]
Except I just checked, and it doesnt do it anymore xD.

**Comment by fernandog** [comment]
not working. strange

**Comment by fernandog** [comment]
@miigotu 

"add a field to the nzb and torrent classes in generic.py,"

how we will get this information from template file?

**Comment by miigotu** [comment]
it would be like $curProvider.name except it would be $curProvider.isPrivate or something.

**Comment by fernandog** [comment]
@miigotu 

here? https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/providers/rarbg.py#L66

**Comment by miigotu** [comment]
There would work, but I think it would be cleaner to do it in providers/generic.py Line46 as an argument to __init__, and modify any calls to init in every provider and in class NZBProvider and class TorrentProvider. This way you get an error if you missed a provider or if someone adds a provider in the future which is missing the value.

```
def __init__(self, name, public):
    self.public = public
```

**Comment by miigotu** [comment]
Then in the css there should be probably 4 new attributes, .publicNZB, .privateNZB, .publicTorrent, .privateTorrent, each with a unique color.

Then you set the class by providerType and public

**Comment by fernandog** [comment]
@Thraxis are you still interested in doing this?? thanks!

**Comment by fernandog** [comment]
@Thraxis please??

**Comment by miigotu** [comment]
I think hes waiting on the public privat fields in the providers

**Comment by fernandog** [comment]
But we will do two PRs for that? One for fields and one for template?

**Comment by miigotu** [comment]
I want to make a feature branch here, add the private/public attribute to the providers myself, and Thraxis or someone else can PR to that feature branch after. That is how more than one person works on a feature and adds commits without PR each on develop (and having half done work in develop).

**Pull request closed without merging**
