### PR TITLE
Fix error 32 file in use when rotating logfiles on windows

### PR DESCRIPTION
**Pull request by TagForce**
- Added logging.shutdown() on stopping/restarting SR. Should release
opened logfiles.

### CODE REVIEW

**Comment by fernandog** [comment]
@TagForce ready to merge?

**Comment by TagForce** [comment]
@fernandog Yes.

**Comment by fernandog** [comment]
@TagForce ok! we are labeling PR. if your are always tested I will always label as Tested

**Comment by fernandog** [comment]
@TagForce merged

**Comment by TagForce** [comment]
@fernandog Yeah, I will only PR stuff I have personally tested. However, sometimes I will ask others to test it as well... I'll mention that in a comment, so that you know not to add Tested just yet. Usually I'll ask users or you and abeloin to test it from the commit itself, though.

**Pull request merged**
