### PR TITLE
Warn if backlog search days is less than oldest episode

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/1018

It does not count paused shows with wanted episodes

### CODE REVIEW

**Comment by gborri** [comment]
Do you think is possible to set backlog search day to what needed in order to get all needed episode?

**Comment by abeloin** [comment]
@gborri It's already been done via the dailySearcher. The back is now these day is mostly used for forcing a show backlog(set episode to wanted, add a new show with wanted as default)

**Comment by TagForce** [comment]
@abeloin Maybe we should add a backlog search when changing providers in the search settings as well? As that's (as far as I can tell) the only scenario in which you might miss episodes that are old and wanted, at the moment. All the others are already backlogged before (indeed when adding a show, or manually changing to wanted).

**Comment by abeloin** [comment]
@TagForce The function [searchForNeededEpisodes](https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/search.py#L369)(which is run by DailySearchQueueItem) already does that.

It call [wantedEpisodes](https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/search.py#L332) with a fromDate=1, which it then check for quality status and WANTED.

I'm currently writing a doc on this because it's not easy to find and understand.

In the end, from my understanding of the way dailySearcher now work(found that out yesterday's while discussing with @fernandog about his backlog PR and looking at the code), backlog should only be called manually.

**Comment by fernandog** [comment]
@abeloin or we can "fix" the concept of dailysearch changing wantedEpisodes with a fromDate=1 to today()

**Comment by gborri** [comment]
@abeloin @TagForce @fernandog take in mind also that with the #1510 backlog (and also daily) will search also for SKIPPED status.

**Pull request closed without merging**
