### PR TITLE
Add news

### PR DESCRIPTION
**Pull request by miigotu**
@fernandog we can use this PR to keep track of changes and conversation.

Fixed the donate link.
Fixed formatting of markdown pages. CHANGES.md is a good placeholder for now.

### CODE REVIEW

**Comment by fernandog** [comment]
I tried cheetah mardown. It converted all page to MD. Missed top and botton.

**Comment by MGaetan89** [comment]
If this is merged in `master`, I think it will become necessary to update the `CHANGES.md` before each release.

It would also be nice to update the `Update available` message to include a link to this news section. Maybe something like this:

> **There is a newer version available** - [Update now]()
> A comprehensive list of changes can be found [here](), while the detailed changelog is [here]().

**Comment by fernandog** [comment]
This news will tell users about known issues too

**Comment by matigonkas** [comment]
should this use the changes.md from the develop branch? that way it would be always updated
becouse the one on master is almost always 1 version behind

**Comment by miigotu** [comment]
@fernandog maybe we should add this page as 'changelog' under the 'check for updates' menu item, and point it to develop CHANGES.md with a checkbox to show the git log (limited), and then make a new page that pulls news for big changes, plans, bugs, as we find/decide it. There we can also announce things like new team members, develop taking a break (yeah right? lol) and other things.

**Comment by neoatomic** [comment]
Related FR's : https://github.com/SiCKRAGETV/sickrage-issues/issues/854 https://github.com/SiCKRAGETV/sickrage-issues/issues/900

**Comment by fernandog** [comment]
I added the change log to "News" only to have some content as we didn't discuss layout and content.
Agree that changelog should be next to "check for updates".

**Comment by fernandog** [comment]
@miigotu what do you think we enable NEWS and add this:



**Default Episode Status**: 
We recently fixed this feature so you need  to:
- Edit your shows and set the default status to wanted instead of skipped (if you want unaired episodes to be downloaded)
- Set the ones that were marked skipped before that to wanted.

When adding a show you would be asked for two status: already aired episodes and unaired episodes.

**Providers**
- Sick beard index and Womble provider are blocking SR application so avoid use them

**Develop branch**
- We are upgrading Subliminal module and this may and will break your installation. Please avoid use  develop branch until we fully tested everything unless you know what you are doing

**Comment by fernandog** [comment]
@miigotu commited

**Comment by fernandog** [comment]
@SiCKRAGETV/moderators  

suggestions ?

image

**Comment by MGaetan89** [comment]
When I click on "News", I am redirected to the home page (`/home`), but the link associated with "News" is `/news`.

**Comment by fernandog** [comment]
Update

**Comment by MGaetan89** [comment]
I am using the latest version (or at least no new version is reported).
Otherwise I guess I wouldn't see the "News" link.

**Comment by fernandog** [comment]
Update

**Comment by fernandog** [comment]
@MGaetan89 everything ok?

**Comment by MGaetan89** [comment]
I update to 4.0.36 and restarted SickRage, now I have this in Chrome:
> This web page has a redirection loop

**Comment by miigotu** [comment]
@MGaetan89 try again?

**Comment by MGaetan89** [comment]
@miigotu It's working fine now.
"Changelog" section is also working.

**Comment by miigotu** [comment]
Cool

**Comment by fernandog** [comment]
Will add this to NEWS

**Pull request merged**
