### PR TITLE
Build tests fix, replaces #1525

### PR DESCRIPTION
**Pull request by miigotu**
Fixed travis build tests, all are working and being ran. None of the tests actually got done before.  Fix for #1525 without breaking the build.

Is it ok that I set journal_mode = OFF? Build does not work without this setting.

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu Is issue submitter test runned ok?
this one shouldnt run everytime otherwise will create a lot of issues.

**Comment by miigotu** [comment]
I'll either add the blacklisting from #1525 to avoid the issue_submitter_test, or make a change in the issue_submitter_test code now and push

**Comment by miigotu** [comment]
Ok, blacklisted, but the test does run. I dont have my github info in the ini (and travis doesnt either) so it doesnt actually post the issue though even when run manually :)

**Comment by fernandog** [comment]
@miigotu thanks and welcome! I sent you a invite to be moderator too

**Comment by miigotu** [comment]
Yeah, thanks. Already accepted/joined.

**Comment by abeloin** [comment]
@miigotu What is the error when PRAGMA is on?

**Comment by miigotu** [comment]
@abeloin If you mean without disabling journal_mode the errors are here: https://gist.github.com/miigotu/391b5577a822e5f6508e

The databases are not created, but the journals are created but are 0b and are not removed after the test. Strange bug but it is safer this way anyways. I even set the parent folder and all files 777 as well to make sure it wasnt a permissions problem.

**Comment by abeloin** [comment]
@miigotu Ok, I put this for v4.0.18. This leave us time to figure the issue

**Pull request merged**
