### PR TITLE
DisplayShow: ManualSearch ask if failed and/or download current qual 

### PR DESCRIPTION
**Pull request by abeloin**
Manual Search ask 2 questions:
* If failed enable, ask to mark release failed Yes/No.
* If to download: > or >= currQual Yes/No

See https://github.com/SiCKRAGETV/sickrage-issues/issues/1005 for more info

### CODE REVIEW

**Comment by fernandog** [comment]
@abeloin 

why changing this files?

```
patching file sickbeard/providers/ezrss.py
patching file sickbeard/providers/generic.py
patching file sickbeard/providers/iptorrents.py
patching file sickbeard/providers/nyaatorrents.py
patching file sickbeard/providers/tokyotoshokan.py
```

**Comment by fernandog** [comment]
ms

**Comment by abeloin** [comment]
@fernandog Because they implement findSearchResults() which now include a new parameter: downCurQuality

**Comment by fernandog** [comment]
@TagForce @neoatomic @Hellowlol @markheloking 
can you test this and give as some feedback?

**Pull request merged**
