### PR TITLE
Change libnotify import. 

### PR DESCRIPTION
**Pull request by WebSpider**
Fixes SiCKRAGETV/sickrage-issues#2648

### CODE REVIEW

**Comment by MGaetan89** [comment]
Shouldn't you change those two as well?
- https://github.com/WebSpider/SickRage/blob/fix_libnotify/sickbeard/notifiers/libnotify.py#L76
- https://github.com/WebSpider/SickRage/blob/fix_libnotify/sickbeard/notifiers/libnotify.py#L82

**Comment by WebSpider** [comment]
L76: No, just a logger line which has enough info imo
L82: Capitalization error there. Will push a new update on the same branch tomorrow

**Comment by miigotu** [comment]
There are a few other bugs in libnotify that I found in my other PR. Will be splitting that PR up and doing it again because some of the commit logs for fixes got lost.

Will merge this one now.

**Comment by MGaetan89** [comment]
@WebSpider For L76, I was talking about the capitalization error too in the log: `Unable to import gobject.`.

**Comment by miigotu** [comment]
@MGaetan89 Im gonna push a fix soon for it, working on autoflake and a few of my other fixes found when linting.

**Pull request merged**
