### PR TITLE
Prevent seeing debug and db log in viewlog when debug=0 in config.ini

### PR DESCRIPTION
**Pull request by abeloin**

### CODE REVIEW

**Comment by abeloin** [comment]
@fernandog Is this ok with you?

**Comment by fernandog** [comment]
this will prevent users to submit errors if debug=0 
or will submit log with debug missing

**Comment by abeloin** [comment]
Nope, it doesn't display debug/db line in vewlog page if debug=0:
Imgur

**Comment by fernandog** [comment]
@abeion! ok then!
do we have an option in UI to enabled debug or only editing config.ini?

**Comment by abeloin** [comment]
config.ini only

**Comment by fernandog** [comment]
ok! later we add it to the UI. not urgent

**Comment by maxcore** [comment]
@abeloin @fernandog  where we can actived the debug log ? in the ui

**Pull request merged**
