### PR TITLE
Fix shutil import error

### PR DESCRIPTION
**Pull request by TagForce**
- Fixes NameError: name 'shutil' is not defined caused by monkeypatching
shutil.copyfile

### CODE REVIEW

**Comment by TagForce** [comment]
@fernandog @abeloin Please merge this PR immediately, or fix the monkeypatch for shutil.copyfile another way, but be quick about it. In its current state it breaks SR completely without manually editing __init__.py to include above line.

**Comment by abeloin** [comment]
@TagForce Thank You

**Comment by fernandog** [comment]
what we do about python 2.6? Fallback to previous code?

**Comment by abeloin** [comment]
Make a PR that fix the issue: https://github.com/SiCKRAGETV/SickRage/pull/1469

**Pull request merged**
