### PR TITLE
Change log messages to format

### PR DESCRIPTION
**Pull request by fernandog**
@miigotu rarbg is ok but still is showing bad chars:

[Rarbg] :: Unable to connect to Rarbg provider: error ('Connection aborted.', gaierror(-2, 'Nome ou servi\xc3\xa7o desconhecido'))
https://github.com/SiCKRAGETV/SickRage/blob/master/sickbeard/providers/rarbg.py#L114

this pull was made because of rarbg but it code already uses .format

### CODE REVIEW

**Comment by miigotu** [comment]
just import ex and do ex(e) instead of str(e), that should fix it

**Comment by fernandog** [comment]
But rarbg already does that and its one of the providers that has special chars in error message


[Rarbg] :: Unable to connect to Rarbg provider: error ('Connection aborted.', gaierror(-2, 'Nome ou servi\xc3\xa7o desconhecido'))

**Comment by miigotu** [comment]
```python
                logger.log(u'{name} provider: No token found'.format(name=self.name), logger.ERROR)
                logger.log(u'{name} provider: No token found: {error}'.format(name=self.name, error=ex(e)), logger.DEBUG)
```
You can't format and ex(), just ex()

**Comment by miigotu** [comment]
Seems ex is messed up atm.

**Comment by miigotu** [comment]
@fernandog before merging this, check for the encoding problem with just ex() again with my new commits. ex/ss/ek was incorrectly detecting your encoding for serviço as TIS-620. My changes before updating chardet fixed that because I try them in a better order, and now also the updated chardet itself correctly guesses it as utf-8 rather than TIS-620.

**Comment by miigotu** [comment]
Old chardet:
```python
>>> chardet.detect('serviço')
{'confidence': 0.99, 'encoding': 'TIS-620'}
```
New chardet:
```python
>>> chardet.detect('serviço')
{'confidence': 0.505, 'encoding': 'utf-8'}
```

**Comment by fernandog** [comment]
why not get sys encoding first? mine is utf-8. after that you can try guess it

**Comment by miigotu** [comment]
That's what it does now. Order = sys_encoding , utf-8, latin1, chardet.

**Comment by miigotu** [comment]
Don't need to do this now right? Can you check? I rather fix the encoding than band-aid the log messages =P

**Comment by fernandog** [comment]
will close it for now then

**Comment by fernandog** [comment]
@miigotu still getting unicode chars:

```
Connection error to getURL http://thexem.de/map/all?id=260485&origin=tvdb&destination=scene. Error: ('Connection aborted.', error(104, 'Conex\xc3\xa3o fechada pela outra ponta'))
```

**Comment by miigotu** [comment]
@fernandog because you still have it using .format.
logger.log(u"Connection error to getURL {0}. Error: {1}".format(url,e.message), logger.WARNING)

Also, e.message is deprecated since python 2.5.

logger.log(u"Connection error to getURL %s. Error: %s" % (url, ex(e)), logger.WARNING)

**Comment by fernandog** [comment]
ok! thanks! a lot of changes =)

**Comment by miigotu** [comment]
Also, anywhere you use str(somevar) in a log line is a potential unicode problem. you have to use ek.ek, ex, or ek.ss

**Pull request closed without merging**
