### PR TITLE
Provider cache configuration

### PR DESCRIPTION
**Pull request by gsly**
Added the ability to configure a providers minimum cache time allowing the user to increase the time but not go below the minimum time as dictated by the provider.
Changed all providers having a cache to use this new configuration feature.
Fixed frenchtorrentdb.py provider as it didn't have a cache initialization call.
Added NetBeans IDE project to the ignore file.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
File "/home/travis/build/SiCKRAGETV/SickRage/sickbeard/providers/t411.py", line 42, in __init__
    elf.mincachetime = None
NameError: global name 'elf' is not defined

**Comment by romanocry** [comment]
frenchtorrentdb is not available anymore, since 2 weeks :(

**Comment by WebSpider** [comment]
Squash?

**Comment by miigotu** [comment]
The problem I have with it is that it introduces another field for a noob to ask questions about or confuse even experienced users as to wtf it is used for, when it provides no real benefit. End users have no need to modify this value.

We are trying to replace user configurable fields with intelligent code that removes the need for user configuration. not the other way around. Any new configuration MUST be absolutely necessary.

**Comment by WebSpider** [comment]
@miigotu agreed, how about not exposing advanced settings such as these in UI? Anyone wanting to modify such advanced behaviour would have to do so in config.ini directly, which we can discourage ... ?

**Comment by miigotu** [comment]
There is no reason to make this a setting at all. It provides no benefit, and merely complicates the code for no gain.

**Pull request closed without merging**
