### PR TITLE
Remove html tags from ui.notifications

### PR DESCRIPTION
**Pull request by fernandog**
@miigotu only these two lines in html tag in ui.notification

### CODE REVIEW

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1832

**Comment by miigotu** [comment]
Failed, also there are a lot more html tags in other notifications in webserve.py

**Comment by fernandog** [comment]
But they are not UI notifications. UI that is the problem isnt?

**Comment by miigotu** [comment]
They are ui notifications, but searching doesnt show some of them because they are split on 2 lines, like line 3372.

ui.notifications.error and ui.notifications.message, search for those two strings and look at each one.

**Comment by miigotu** [comment]
`'<br >\n'.join(errors)`

**Comment by miigotu** [comment]
Ok, so I just did some tests, and notifications can have a few select html tags in the message, but not the title.

Lists work <ul><li></li></ul>
Bold kinda works <b></b> makes *Text*

Images do not aparently, can you verify this works: https://github.com/fernandog/SickRage/blob/html_notification/sickbeard/webserve.py#L2023

**Comment by fernandog** [comment]
I only removed bold. That on works then?

**Pull request merged**
