### PR TITLE
Fix error: Filesize would require ZIP64 extensions

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/2210

@miigotu you asked user to do this in forum
https://sickrage.tv/forums/forum/help-support/general-support/24316-updating-zip-creation-error-filesize-would-require-zip64-extensions

### CODE REVIEW

**Comment by miigotu** [comment]
@fernandog I'm not sure if ZIP64 is available on all systems, thats is why it isn't enabled by default in the library, or I would have added it =P

Should we try to verify all modern systems support it or just merge and find out? lol
That guy just has an insanely large cache/library

**Comment by fernandog** [comment]
Whats the best solution? Fallback?

**Comment by miigotu** [comment]
Lets just merge it and see if anyone has problems with it?

**Comment by fernandog** [comment]
@miigotu "ZIP64 extensions are disabled by default because the default zip and unzip commands on Unix (the InfoZIP utilities) don’t support these extensions"

https://docs.python.org/2/library/zipfile.html

so restore won't work

**Comment by miigotu** [comment]
Lets just wait and see.

**Comment by miigotu** [comment]
noone is running unix btw ^

**Pull request merged**
