### PR TITLE
Added public/private class to provider list

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Ref: https://github.com/SiCKRAGETV/SickRage/pull/2548
Just add some CSS to change the `background-color` to whatever you want.

### CODE REVIEW

**Comment by miigotu** [comment]
@OmgImAlexis should the class names be more specific to make sure there are no future conflicts?

public-provider, private-provider ?

**Comment by OmgImAlexis** [comment]
Not really, we can use the scope of the list to effect the class.
For example `ul#provider_order_list li.public` and `ul#provider_order_list li.private`.

**Comment by fernandog** [comment]
did you test this? I'm getting mako error saying binsearch and newznab has not self.public

@miigotu how to separate like nzbgeek has is private from another nzb provider has is public? all of them use newznab.py

**Comment by miigotu** [comment]
@fernandog the css was not added yet, just the mako change.

Fixed in newznab, I need to add it in binsearch too?

https://github.com/SiCKRAGETV/SickRage/commit/0736f58383357abac1fda1b61a3f18b4ff9d46ad#diff-a3c751605f232a794456fb4bf2794b61R64

**Comment by fernandog** [comment]
@miigotu yes

```
Error !

AttributeError: BinSearchProvider instance has no attribute 'public'

curName = curProvider.getID() %> <li class="ui-state-default ${('private', 'public')[bool(curProvider.public)]}" id="${curName}"> <input type="checkbox" id="enable_${curName}" class="provider_enabler" ${('', 'checked="checked"')[curProvider.isEnabled() == True]}/> <a href="${anon_url(curProvider.url)}" class="imgLink" rel="noreferrer" onclick="window.open(this.href, '_blank'); return false;"><img src="${sbRoot}/images/providers/${curProvider.imageName()}" alt="${curProvider.name}" title="${curProvider.name}" width="16" height="16" style="vertical-align:middle;"/></a> <span style="vertical-align:middle;">${curProvider.name}</span> ${('*', '')[bool(curProvider.supportsBacklog)]} <span class="ui-icon ui-icon-arrowthick-2-n-s pull-right" style="vertical-align:middle;"></span>
/home/osmc/SickRage/gui/slick/views/config_providers.mako, line 82:
<li class="ui-state-default ${('private', 'public')[bool(curProvider.public)]}" id="${curName}">
/home/osmc/SickRage/gui/slick/views/layouts/main.mako, line 220:
/home/osmc/SickRage/lib/mako/runtime.py, line 853:
callable_(context, *args, **kwargs)
```

**Comment by fernandog** [comment]
I liked the 'lock' icon as in the other PR screenshot

**Pull request merged**
