### PR TITLE
Provider hounddawgs: Changes to fit new site layout

### PR DESCRIPTION
**Pull request by SickrageDK**

### CODE REVIEW

**Comment by fernandog** [comment]
@SickrageDK 

"NET::ERR_CERT_COMMON_NAME_INVALID" - the server cert is unsecure.

may broke the script. Did you test?

**Comment by abeloin** [comment]
Using https://hounddawgs.org/ would solve the invalid cert

**Comment by SickrageDK** [comment]
The reason for using the IP is because initially the login would not work using the hostname.Maybe because of some redirections. Could try to change it to the hostname and do some testing

**Comment by SickrageDK** [comment]
Also the reason for update is that they put some new tables on the site, so the provider needed update

**Comment by fernandog** [comment]
@SickrageDK any updates? Is it working with hostname or with IP? did you tested? can you send some logs of this PR working?

**Comment by abeloin** [comment]
@SickrageDK Any news?

**Comment by SickrageDK** [comment]
I have updated and done some initial testing. Seems to work with hostname.

**Pull request merged**
