### PR TITLE
Check if show is mapped in XEM before query site

### PR DESCRIPTION
**Pull request by fernandog**
Related: https://github.com/SiCKRAGETV/sickrage-issues/issues/2300

Avoid check every show for http://thexem.de/map/all?id=%s&origin=%s&destination=scene
Probably need to remove some code.

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/scene_numbering.py#L473

### CODE REVIEW

**Comment by fernandog** [comment]
don't reduce query to xem. only changed the URL
I need to cache 
http://thexem.de/map/havemap?origin=tvdb
http://thexem.de/map/havemap?origin=rage
http://thexem.de/map/havemap?origin=anidb

before start the update. not in show_queue =(

**Comment by fernandog** [comment]
@miigotu can I cache those here?

https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/showUpdater.py#L78

**Comment by miigotu** [comment]
Why would you do this in the show_queue instead of inside the xem_refresh, where it already has a session?

any call to getURL that doesn't already have a session (like providers) need session=requests.Session() added to the getURL call.

**Comment by fernandog** [comment]
because we need to cache those sites results before the loop th. shows
if we do in xem_refresh it will access the site N times(shows)

**Comment by fernandog** [comment]
new PR coming

**Pull request closed without merging**
