### PR TITLE
Fix#1453 - Fix 'NoneType' object has no attribute 'whitelist

### PR DESCRIPTION
**Pull request by Thraxis**
There should have always been a check if the show was anime here.  As
only anime had white and blacklists.  Added both check for is_anime and
that release_groups is not none

### CODE REVIEW

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1453

**Comment by dave-tucker** [comment]
This doesn't fix the issue completely, there is a missing check on https://github.com/Thraxis/SickRage/blob/Fix%231453/sickbeard/show_name_helpers.py#L203

**Comment by miigotu** [comment]
@Thraxis Status? what about the comment above by @dave-tucker ?

**Comment by Thraxis** [comment]
Added in the second set of checks.. not sure why there was never a check for is_anime at the least there to begin with.

**Pull request merged**
