### PR TITLE
Add more debug messages to HDT

### PR DESCRIPTION
**Pull request by fernandog**
TODO: check why it only get the first torrent of the result

### CODE REVIEW

**Comment by miigotu** [comment]
@fernandog why the DNM label?

**Comment by fernandog** [comment]
You were doing some changes in provider and asked to no change it until you finishes.

Also HDT only get the first torrent in search. 
There is a loop but still dont work

**Comment by miigotu** [comment]
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/providers/hdtorrents.py#L242
`mainblockcontenttt` ?

**Comment by fernandog** [comment]
@miigotu 
Here is the result of https:  hdts.ru/torrents.php?search=1080p&category[]=59&category[]=60&category[]=30&category[]=38

https://gist.github.com/fernandog/53f2eb544eb96e367e42

**Pull request closed without merging**
