### PR TITLE
Possible fix for Fix TypeError: object of type 'NoneType' has no len()

### PR DESCRIPTION
**Pull request by abeloin**
Possible fix for Fix TypeError: object of type 'NoneType' has no len()
See https://github.com/SiCKRAGETV/sickrage-issues/issues/231 and https://github.com/SiCKRAGETV/sickrage-issues/issues/764

### CODE REVIEW

**Comment by abeloin** [comment]
@fernandog FYI

**Comment by abeloin** [comment]
Ref #1247

**Comment by OmgImAlexis** [comment]
Pulled it and that seems to have fixed all the errors while using nginx.

**Comment by abeloin** [comment]
@OmgImAlexis Thank you for the testing and feedback.

**Comment by OmgImAlexis** [comment]
I'm not sure if you were trying to just fix the nginx issue but this also fixed the ``object of type 'NoneType' has no len()`` issue I was getting from running manual post processing.

**Comment by abeloin** [comment]
Nginx only exacerbated the thread safety issue with the missing ioloop.callback. It should fixes all related error like this one:
```
File "/home/media/sickrage/tornado/iostream.py", line 1383, in _merge_prefix
    if len(deque) == 1 and len(deque[0]) <= size:
TypeError: object of type 'NoneType' has no len()
```

**Comment by OmgImAlexis** [comment]
Okay good, I'll let it run tonight(it's 11:40AM here) as that's usually when I get the 100s of errors and let you know if it's fixed then.

**Comment by abeloin** [comment]
@OmgImAlexis Any issues so far?

**Comment by OmgImAlexis** [comment]
Sorry I got carried away with trying other pull requests and such. This worked fine.

**Pull request merged**
