### PR TITLE
Disable "Find Propers Search" if its disable

### PR DESCRIPTION
**Pull request by fernandog**

### CODE REVIEW

**Comment by abeloin** [comment]
FYI: You also could disable the button

**Comment by fernandog** [comment]
How to do that?

**Comment by abeloin** [comment]
In line 42: `<a class="#if not $sickbeard.DOWNLOAD_PROPERS then 'btn hidden' else 'btn' #" href="$sbRoot/manage/manageSearches/forceFindPropers"><i class="icon-exclamation-sign"></i> Force</a>`

Imgur

**Comment by fernandog** [comment]
@abeloin done

**Pull request merged**
