### PR TITLE
Try to get the best quality from the best/archived list on first snat…

### PR DESCRIPTION
**Pull request by miigotu**
…ch, but accept the highest from the any/allowed list otherwise

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu we shouldnt change the names as users are used to it

**Comment by miigotu** [comment]
@fernandog "Initial" doesn't make any sense anymore. Before SR would Initially only DL a quality from the 'Initial' list for the first snatch.

Also, in the code, it has always been "Any" not initial, and archive is "best" in code.
The previous setup only worked in one direction and didn't really make any sense.

'Preferred' is much closer to what the second list actually is/does than 'archived'

I think that people being used to something is less important than that thing being easy to understand to begin with and making sense =P.

**Comment by fernandog** [comment]
But we have Archived status. And a lot of screens have archived label.

**Comment by miigotu** [comment]
Yes, archived status, not quality. The functionality is improved now, the information/label did not make sense anymore. It didn't even work the way it was supposed to before these changes. It all works now and it makes sense.

We can't leave labels with incorrect names/descriptions just because people are used to it, its just incorrect then. Incorrect causes more issues and confusion than people having to understand something new that is correct.

**Comment by miigotu** [comment]
Its hard to explain, but before you could have an 'archived' quality, but it could download a different quality that was not preferred. When you archive something, you want it to be in your preferred list.  Archive status is totally separate from picking qualities though. It's like before someone confused two totally different features.

**Pull request merged**
