### PR TITLE
Added qbittorrent support

### PR DESCRIPTION
**Pull request by JustMaier**
Feature request [#838](https://github.com/SiCKRAGETV/sickrage-issues/issues/838)

### CODE REVIEW

**Comment by fernandog** [comment]
@JustMaier users will love this. thanks! It's an old request from forums

**Comment by JustMaier** [comment]
I'm glad to be able to contribute. I just recently switched over myself and saw the need.

**Comment by fernandog** [comment]
@JustMaier welcome! Feel free to make some more PR. We are short on PR and lots of issues and FR. thanks!

**Comment by fernandog** [comment]
@JustMaier is it fully tested?

**Comment by JustMaier** [comment]
@fernandog all unit tests ran successfully and I manually confirmed that the UI worked as expected.

**Pull request merged**
