### PR TITLE
Update cachecontrol, don't clear it's cache, dont build nameCache or …

### PR DESCRIPTION
**Pull request by miigotu**
…update nw times in SickBeard.py

### CODE REVIEW

**Comment by fernandog** [comment]
Will this fix the cache/sessions folders? Or unrelated?

**Comment by miigotu** [comment]
@fernandog It will, and also will fix the missing date header error.

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1778

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1720

**Pull request merged**
