### PR TITLE
Change comingEpisodes keys to be aligned with API

### PR DESCRIPTION
**Pull request by fernandog**
@MGaetan89 agree? I checked with ShowsRage

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
That's what it was before, right?

**Comment by fernandog** [comment]
didn't understand...

**Comment by OmgImAlexis** [comment]
Don't worry, I was thinking of another section.

**Comment by MGaetan89** [comment]
@fernandog What's the point of asking my opinion if you merge before I answer? XD

The change if fine for me. The only comment I have (had, since I refactored that part), is that "soon" and "later" is not really clear. I guess "soon" should rather be "next week" or something like that (only in the web UI, otherwise it breaks the API).

**Pull request merged**
