### PR TITLE
fix several front end bugs with initial setup

### PR DESCRIPTION
**Pull request by alisonatwork**
- fix a JS error on search settings screen
- don't let the browser cache notifications or directories, so we don't receive endless notifications or get stuck in an out of date directory
- fix small bug where using autocomplete and then the file browser left your values out of sync

There are still some styling problems with the autocomplete (it's all white on IE), but this should be a bit less wonky now.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [ ] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by alisonatwork** [comment]
Rebased on develop now, should be good to go.

**Comment by miigotu** [comment]
I dont think the js changes propagate without running the bower build?

**Comment by alisonatwork** [comment]
I'm not sure to be honest. I tested the changes locally by blasting my browser cache and reloading, but if bower is generating a cache breaker hash and needs to commit it somewhere for everyone else, I didn't do that bit 😃

**Comment by miigotu** [comment]
Will find out =P

**Comment by OmgImAlexis** [comment]
The only things that need to be "built" are external dependencies, our js still doesn't use grunt/bower.

**Comment by miigotu** [comment]
k, then this should be ok I guess. Good thing because I already merged it =p

**Comment by alisonatwork** [comment]
💃

**Pull request merged**
