### PR TITLE
Fix Layout of Black and Whitelist in editShow

### PR DESCRIPTION
**Pull request by Thraxis**
* Fixes the layout of the Black and Whitelist in editShow

Fix Ported from https://github.com/lad1337/Sick-Beard/pull/16

### CODE REVIEW

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/1198

**Comment by abeloin** [comment]
@Thraxis Is https://github.com/SiCKRAGETV/SickRage/pull/1749 deprecating this?

**Comment by Thraxis** [comment]
@ abeloin It doesn't, was two separate fixes... but I can roll this into 1749

**Comment by Thraxis** [comment]
merged with #1749

**Comment by abeloin** [comment]
@Thraxis Ok, thanks

**Pull request closed without merging**
