### PR TITLE
Remove duplicate CSS rules

### PR DESCRIPTION
**Pull request by MGaetan89**
This PR is here to help https://github.com/SiCKRAGETV/sickrage-issues/issues/2502.

A lot of rules in `style.css`, `light.css` and `dark.css` are duplicated. The goal here is to keep common rules in `style.css` and specific rules in either `light.css` and `dark.css`.

File size comparison:

Branch | `style.css` | `dark.css` | `light.css`
------------- | ------------- | ------------- | -------------
`master` | 67 ko (67 173 o) | 67 ko (66 681 o) | 66 ko (65 747 o)
`fr/css_optimizations` | 66 ko (67 114 o) | 22 ko (22 164 o) | 5,2 ko (5 361 o)

I didn't check that I didn't break anything yet, so don't merge this PR for the moment.

Known issues:
- `dark.css`:
  - [x] Tabs in the config section

### CODE REVIEW

**Comment by miigotu** [comment]
+1 on this @MGaetan89 
The `@media print` should go at the bottom of the style.css if style.css is applied after dark|light, otherwise it needs applied in dark|light at the bottom.

**Comment by MGaetan89** [comment]
Ok, thanks for the info.
Can you label this PR "Do not merge", to be sure?

**Comment by MGaetan89** [comment]
I updated `light.css`. Considering the few rules remaining there, I guess most of the light theme is in `style.css`. So maybe we could merge both and only include the extra file `dark.css` when necessary.

The only issue I found so far is the tab on the config part in the dark theme.

**Comment by MGaetan89** [comment]
The issue in `dark.css` is fixed. I will use these version in the next coming days to check if I didn't break something else.
After that, you are free to merge if you don't see anything else to change.

I found some other optimizations to do, but this PR is already big enough like that, so I'll do an other one.

**Comment by OmgImAlexis** [comment]
This broke the whole styling for the progressbars.

This is the old styling.
screen shot 2015-08-28 at 7 28 37 pm

This is the new styling.
screen shot 2015-08-28 at 7 28 16 pm

**Comment by MGaetan89** [comment]
Good catch. This was merged before I fully tested it.
I will submit a fix soon.

**Comment by OmgImAlexis** [comment]
@MGaetan89 keep in mind that both of the progressbars types are now using the progressbar class.

**Comment by miigotu** [comment]
`This was merged before I fully tested it.`

EAFP

**Comment by MGaetan89** [comment]
I wasn't blaming anyone ;)
While it's in `develop` there is no problem with that, and it helps other people to test it.
This is a rather big change and I was sure something would be wrong.

**Comment by miigotu** [comment]
Agreed, I wanted to merge it to get it tested longer before I merge dev->master. You could have been testing it for a week and maybe missed something someone else sees right away. Fresh eyes always help xD.

**Comment by miigotu** [comment]
@MGaetan89 
css broke menu-icon-* ?

https://cloud.githubusercontent.com/assets/7928052/9557752/c9dd980c-4dde-11e5-952e-9b9dd0f66713.png

**Comment by miigotu** [comment]
@MGaetan89 If you add the background-positions for menu-icon-* to dark.css they work again

**Comment by MGaetan89** [comment]
Thanks for reporting this. I will fix it.

**Pull request merged**
