### PR TITLE
Make missed episodes to appear in calendar view

### PR DESCRIPTION
**Pull request by fernandog**
https://github.com/SiCKRAGETV/sickrage-issues/issues/991

@abeloin I couldn't figure out how to not show weeks with no missed episodes. Can you help me?

calendar

### CODE REVIEW

**Comment by fernandog** [comment]
@abeloin I manage to remove the empty weeks by getting the max date between last_missed_data and coming_eps_missed_rage

but when I enable to show paused the UI becomes messy
do you know hot to fix it?

**Hidden Paused**


**Show paused**

**Comment by abeloin** [comment]
The check for paused is at this line:
https://github.com/fernandog/SickRage/blob/missed_in_calendar/gui/slick/interfaces/default/comingEpisodes.tmpl#L507

**Comment by abeloin** [comment]
This must be the culprit, you to sort differently depending on the selected paused option:
https://github.com/fernandog/SickRage/blob/missed_in_calendar/gui/slick/interfaces/default/comingEpisodes.tmpl#L484

**Comment by abeloin** [comment]
The way the code is designed, each day represent a table, so you must make modification to the display code if you want to show more than a week

**Comment by abeloin** [comment]
This is what I get with your patch:
Imgur
You can see what happen when you put multiple weeks together.

If you look being the code, it's just a bunch of table:
```
<table class="sickbeardTable tablesorter calendarTable cal-odd" cellpadding="0" cellspacing="0" border="0"></table>
<table class="sickbeardTable tablesorter calendarTable cal-even" cellpadding="0" cellspacing="0" border="0"></table>
<table class="sickbeardTable tablesorter calendarTable cal-odd" cellpadding="0" cellspacing="0" border="0"></table>
<table class="sickbeardTable tablesorter calendarTable cal-even" cellpadding="0" cellspacing="0" border="0"></table>
<table class="sickbeardTable tablesorter calendarTable cal-odd" cellpadding="0" cellspacing="0" border="0"></table>
<table class="sickbeardTable tablesorter calendarTable cal-even" cellpadding="0" cellspacing="0" border="0"></table><table class="sickbeardTable tablesorter calendarTable cal-odd" cellpadding="0" cellspacing="0" border="0"></table>
<table class="sickbeardTable tablesorter calendarTable cal-even" cellpadding="0" cellspacing="0" border="0"></table>
```

**Pull request closed without merging**
