### PR TITLE
Fix SiCKRAGETV/sickrage-issues/issues/3319

### PR DESCRIPTION
**Pull request by fernandog**
@miigotu @duramato

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
https://github.com/SiCKRAGETV/sickrage-issues/issues/256

**Comment by duramato** [comment]
After this changes I don't get the error anymore 
But it doesn't work either ,I get : 
`015-10-16 01:50:48 DEBUG    Thread-17 :: setAbsoluteSceneNumbering for 78847 from 0 to None`

**Comment by fernandog** [comment]
this comes from here:

```
        if isinstance(ep_obj, str):
            result['success'] = False
            result['errorMessage'] = ep_obj
        elif showObj.is_anime:
            logger.log(u"setAbsoluteSceneNumbering for %s from %s to %s" %
                       (show, forAbsolute, sceneAbsolute), logger.DEBUG)
```
https://github.com/SiCKRAGETV/SickRage/blob/develop/sickbeard/webserve.py#L1998

**Comment by miigotu** [comment]
Why did you go and change every log line? this situation is not possible in all of those other places.... Do not batch change code please...

**Comment by fernandog** [comment]
Because it will fail one time or another. Anime dont have season. Also for absolute number.

**Comment by miigotu** [comment]
That is too messy then. If it needs done in multiple places (I still dont think it does) then you should add a log helper function....

```python
def logshowinfo(show):
    return u'%r: %r' % (show.indexerid, show.name)

# This should also handle air by date...
def logepinfo(ep):
   info =  logshowinfo(ep.show)
    if show.isAnime:
        info += u' - %02d' % (ep.scene_absolute_number if ep.show.scene else ep.absolute_number)
    else:
        info += u'S%02dE%02d' % (ep.scene_season if ep.show.scene else ep.season, ep.scene_episode if ep.show.scene else ep.episode)
    return info

```
`logger.log(logepinfo(epObj) + 'whatever message')`
or
`logger.log(logshowinfo(showObj) + 'whatever message')`

**Comment by miigotu** [comment]
Ill just merge this for now. We can look for a better solution another time.

**Pull request merged**
