### PR TITLE
Linting frontend

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Mainly linting the js and mako files.

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
There a high chance this will break things as I'm using `===` instead of `==` everywhere I can.

I've tested as much as possible, the only real way to get this fully tested is to merge it and workout what's broken afterwards. At least with the js files if anything is really broken it'll show up in the js console.

**Comment by OmgImAlexis** [comment]
For reference you should have atom installed and be using these plugins when editing js files.

````
├── language-mako@0.6.0
├── linter@1.10.0
├── linter-csslint@1.1.0
├── linter-jshint@1.2.1
├── linter-tidy@1.0.1
├── tabs-to-spaces@0.11.1
````

**Comment by miigotu** [comment]
xD as long as you are here to fix it when its broken =P

We have a while before the next merge, to work out encoding errors from forcing the removal of the encoding hack.

**Comment by OmgImAlexis** [comment]
@miigotu yeah I'll be here daily again. :+1: 

Good!

**Pull request merged**
