### PR TITLE
Added missing User-agent for tvdb API.

### PR DESCRIPTION
**Pull request by Aeronaut**
This will fix the "No results found, try a different search."...

### CODE REVIEW

**Comment by dgburr** [comment]
Can confirm that this fix works

**Comment by 9ler** [comment]
Can confirm that this fix works - thanks Aeronaut :)

**Comment by VietTPham** [comment]
Confirm working as well.

**Comment by cbuckley** [comment]
Confirmed working

**Comment by uilino** [comment]
Works!! thanks!!

**Pull request closed without merging**
