### PR TITLE
Handle locked issues in issue submitter, better logging and ui notifi…

### PR DESCRIPTION
**Pull request by miigotu**
…cations for submitter

Fixes SiCKRAGETV/sickrage-issues/issues/3101

### CODE REVIEW

**Comment by miigotu** [comment]
@fernandog why does it not show build status in PR's anymore? Some setting got changed.

**Comment by fernandog** [comment]
@miigotu 
https://github.com/SiCKRAGETV/sickrage-issues/issues/3120

**Comment by miigotu** [comment]
Yep I know. Figuring out pygithub3 to see if I can update to that and use it. or maybe I need to check status.

**Comment by fernandog** [comment]
can't we check if param exist ?

**Comment by miigotu** [comment]
it doesnt exist

**Comment by fernandog** [comment]
yes, it does:
https://api.github.com/repos/SiCKRAGETV/sickrage-issues/issues

**Comment by miigotu** [comment]
That's api v3. PyGithub module does not support it. We don't interact with the api directly. That's why I'm working in updating to pygithub3.

**Comment by fernandog** [comment]
Ought. Sorry

**Comment by fernandog** [comment]
@miigotu can't we use this? https://github.com/copitux/python-github3

**Comment by miigotu** [comment]
Thats what Im already working on switching to -.-

**Pull request merged**
