### PR TITLE
Update readme.md a little

### PR DESCRIPTION
**Pull request by miigotu**
@fernandog does this look ok?

### CODE REVIEW

**Comment by fernandog** [comment]
@miigotu just 'sports' that has old issues and never got fixed. maybe we can remove from readme

**Comment by miigotu** [comment]
Sports not working??

**Comment by miigotu** [comment]
better?

**Comment by fernandog** [comment]
Check issue 16

**Comment by adaur** [comment]
Maybe add a list of supported providers?

**Comment by miigotu** [comment]
@adaur that would make us have to update the readme more often =P, not sure if I'm up for more work.

**Comment by miigotu** [comment]
AFAIK btw, only wwe/ufc not working. And wwe isn't even a sport =P

**Comment by fernandog** [comment]
ops! hehehe

**Pull request merged**
