### PR TITLE
Revert "Fix SiCKRAGETV/sickrage-issues/issues/3286"

### PR DESCRIPTION
**Pull request by OmgImAlexis**
Reverts SiCKRAGETV/SickRage#2886

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by docwho76** [comment]
This needs to be looked at again:

2015-11-02 22:10:02 Thread-29 :: PLEX: Error while trying to contact Plex Media Server: http protocol error : error 0 : got a bad status line

FYI I am on:
BRANCH: (master) / COMMIT: (667933d6dda190f813353477e7f82937ed343cbb) 
PMS: 0.9.12.18.1520-6833552 (this came out Oct 29 and is a PlexPass build)

I noticed that I had a new server auth token after this upgrade. I tried both updating the token as well as inputting a username and password, no joy.

**Comment by docwho76** [comment]
This is still broken under PMS: 0.9.14.* (the new PlexPass branch released) on latest master build of SickRage.

**Comment by OmgImAlexis** [comment]
It's definitely not broken. Using it myself and haven't had a single issue since we transfered back. I think your config may have issues.

**Comment by docwho76** [comment]
Explain how you make it work then, because this is what I am staring at:

2015-11-14 00:05:07 DEBUG    Thread-56 :: PLEX: Updating all hosts with TV sections: 
AAIOError: ('http protocol error', 0, 'got a bad status line', None)
AA    'got a bad status line', None)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 357, in open_http
AA    return getattr(self, name)(url)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 213, in open
AA    return opener.open(url)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 87, in urlopen
AA    xml_tree = etree.parse(urllib.urlopen(url))
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/notifiers/plex.py", line 224, in update_library
AATraceback (most recent call last):
2015-11-14 00:05:07 ERROR    Thread-56 :: PLEX: Error while trying to contact Plex Media Server: http protocol error : error 0 : got a bad status line
2015-11-14 00:04:55 DEBUG    Thread-50 :: PLEX: Updating all hosts with TV sections: 
AAIOError: ('http protocol error', 0, 'got a bad status line', None)
AA    'got a bad status line', None)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 357, in open_http
AA    return getattr(self, name)(url)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 213, in open
AA    return opener.open(url)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 87, in urlopen
AA    xml_tree = etree.parse(urllib.urlopen(url))
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/notifiers/plex.py", line 224, in update_library
AATraceback (most recent call last):
2015-11-14 00:04:55 ERROR    Thread-50 :: PLEX: Error while trying to contact Plex Media Server: http protocol error : error 0 : got a bad status line
2015-11-14 00:04:41 DEBUG    Thread-20 :: PLEX: Updating all hosts with TV sections: 
AAIOError: ('http protocol error', 0, 'got a bad status line', None)
AA    'got a bad status line', None)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 357, in open_http
AA    return getattr(self, name)(url)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 213, in open
AA    return opener.open(url)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 87, in urlopen
AA    xml_tree = etree.parse(urllib.urlopen(url))
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/notifiers/plex.py", line 224, in update_library
AATraceback (most recent call last):
2015-11-14 00:04:41 ERROR    Thread-20 :: PLEX: Error while trying to contact Plex Media Server: http protocol error : error 0 : got a bad status line
2015-11-14 00:04:40 DEBUG    Thread-20 :: PLEX: fetching plex.tv credentials for user: ********
2015-11-14 00:04:25 DEBUG    Thread-14 :: PLEX: Updating all hosts with TV sections: 
AAIOError: ('http protocol error', 0, 'got a bad status line', None)
AA    'got a bad status line', None)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 357, in open_http
AA    return getattr(self, name)(url)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 213, in open
AA    return opener.open(url)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 87, in urlopen
AA    xml_tree = etree.parse(urllib.urlopen(url))
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/notifiers/plex.py", line 224, in update_library
AATraceback (most recent call last):
2015-11-14 00:04:25 ERROR    Thread-14 :: PLEX: Error while trying to contact Plex Media Server: http protocol error : error 0 : got a bad status line
2015-11-13 23:57:34 DEBUG    Thread-44 :: PLEX: Updating all hosts with TV sections: 
2015-11-13 23:57:34 ERROR    Thread-44 :: PLEX: Error while trying to contact Plex Media Server: http protocol error : error 0 : got a bad status line
2015-11-13 23:57:26 DEBUG    Thread-44 :: PLEX: Updating all hosts with TV sections: 
AAIOError: ('http protocol error', 0, 'got a bad status line', None)
AA    'got a bad status line', None)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 357, in open_http
AA    return getattr(self, name)(url)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 213, in open
AA    return opener.open(url)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 87, in urlopen
AA    xml_tree = etree.parse(urllib.urlopen(url))
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/notifiers/plex.py", line 224, in update_library
AATraceback (most recent call last):
2015-11-13 23:57:26 ERROR    Thread-44 :: PLEX: Error while trying to contact Plex Media Server: http protocol error : error 0 : got a bad status line
2015-11-13 23:57:21 DEBUG    Thread-44 :: PLEX: Updating all hosts with TV sections: 
AAIOError: ('http protocol error', 0, 'got a bad status line', None)
AA    'got a bad status line', None)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 357, in open_http
AA    return getattr(self, name)(url)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 213, in open
AA    return opener.open(url)
AA  File "/usr/pbi/sickrage-amd64/lib/python2.7/urllib.py", line 87, in urlopen
AA    xml_tree = etree.parse(urllib.urlopen(url))
AA  File "/usr/pbi/sickrage-amd64/share/sickrage/SickRage/sickbeard/notifiers/plex.py", line 224, in update_library
AATraceback (most recent call last):
2015-11-13 23:57:21 ERROR    Thread-44 :: PLEX: Error while trying to contact Plex Media Server: http protocol error : error 0 : got a bad status line

**Comment by docwho76** [comment]
Because it WAS working, then is broke, then I fixed it then a master update BROKE it again.

**Comment by OmgImAlexis** [comment]
Open an issue on [here](https://github.com/SickRage/sickrage-issues/issues) and I've have a look but it honestly sounds more like an issue with your Plex install or config.

**Comment by miigotu** [comment]
It all depends on if the url is local or remote, never versions require https, some require http.

**Pull request merged**
