### PR TITLE
Trakt API Changes / Tweaks

### PR DESCRIPTION
**Pull request by Thraxis**
https://github.com/SiCKRAGETV/sickrage-issues/issues/1059

Changes the API URL to the Trakt V2.0 API URL
Fixes an error that can occur in TracktChecker if show is missing tvrage id on Trakt

### CODE REVIEW

**Comment by abeloin** [comment]
@Thraxis Can you squash these 3 commits into one? Thanks

**Comment by Thraxis** [comment]
@ Abeloin The three commits in this PR? or the three PR's?

https://github.com/SiCKRAGETV/SickRage/pull/1678
https://github.com/SiCKRAGETV/SickRage/pull/1676
https://github.com/SiCKRAGETV/SickRage/pull/1670 (not this one shouldn't need to be merged as it looks like the the ClientID sickrage is using is registered as a MediaCenter clientID, could be closed to keep for historical purposes)

**Comment by fernandog** [comment]
@Thraxis The three commits in this PR

**Comment by Thraxis** [comment]
Think that should do it... hard reset  to current develop and re-added the changes

**Comment by abeloin** [comment]
@Thraxis Thank You

**Pull request merged**
