### PR TITLE
Added NZBIndex.nl provider.

### PR DESCRIPTION
**Pull request by neoatomic**
NOTE: This is my first attempt modifying SR code.

### CODE REVIEW

**Comment by fernandog** [comment]
@neoatomic fully tested?

**Comment by neoatomic** [comment]
@fernandog Its working, but not "fully" tested. Also it seems the nzbindex RSS feed is down regularly.

**Comment by fernandog** [comment]
@neoatomic no issues so far with this?

**Comment by neoatomic** [comment]
@fernandog  I need to modify this provider a little. Think i will close this and try again when i have more time to test.

**Pull request closed without merging**
