### PR TITLE
Fixes viewlog disabling inputs till refresh

### PR DESCRIPTION
**Pull request by OmgImAlexis**

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by fernandog** [comment]
@OmgImAlexis it try to search in the first letter. I can't write more then one letter without running search

**Comment by miigotu** [comment]
It supposed to search as you type, and the dropdowns/input disabled for me half the time.

**Comment by fernandog** [comment]
Well, I cant type a full word.

They are disable (logFilter feature) because you are using  logSearch feature (typing)

**Comment by miigotu** [comment]
1. There is no reason you shouldn't be able to filter by a specific thread AND search those results.
2. Everything gets disabled, search and both dropdowns.

**Comment by fernandog** [comment]
LogSearch dont read logFilter values

**Comment by miigotu** [comment]
Then whoever wrote it didnt do it correctly.

**Comment by fernandog** [comment]
You know I did.
The feature was only that.
To do that needs new FR

**Comment by OmgImAlexis** [comment]
@fernandog I'll fix the single character typing issue today.

**Pull request merged**
