### PR TITLE
Fixed qualityChooser not expanding custom qualities fields

### PR DESCRIPTION
**Pull request by pkoutsias**
@OmgImAlexis Please do not lint this file because it breaks functionality

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [x] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by OmgImAlexis** [comment]
@pkoutsias if it's breaking from lint then it needs to be fixed, instead of just patching it back.

**Comment by pkoutsias** [comment]
We could try changing it to === "0" but may still be broken

**Comment by OmgImAlexis** [comment]
`if (parseInt(preset) === 0) {` That should fix it.

**Comment by pkoutsias** [comment]
done

**Comment by OmgImAlexis** [comment]
You'll want to rebase so you can change the commit name.

**Comment by pkoutsias** [comment]
and done

**Pull request merged**
