### PR TITLE
Updated subliminal (develop) to newest version

### PR DESCRIPTION
**Pull request by medariox**

### CODE REVIEW

**Comment by SiCKRAGEB0T** [comment]
Thanks for the pull request! Before a real human comes by, please make sure your report has all the below criteria checked

- [ ] Give a description on what the PR is for.
- [x] Make sure you send a PR against the DEVELOP branch
- [x] Don't send big changes in one go. Split up big PRs into multiple smaller (easier manageble) PRs

Please make sure you also read [contribution guide](https://github.com/SiCKRAGETV/SickRage/blob/master/contributing.md) and followed all the steps.

Thanks!

**Comment by miigotu** [comment]
There is a lot of code changes in SR to use the new features of this new version of subliminal, adding commits to this or another PR?

most notably the ability to pass a dir where the external subs are along with the path to the video removes hella code from sickrage.

**Comment by miigotu** [comment]
I'll merge for now, we can work on using those new features in another PR.

**Comment by medariox** [comment]
Yes, this one has potential, but I need some time to weight all situations and decide what should go and what not. As the current implementation is working flawlessly since a few weeks, I don't see this as a priority, but I will work on it asap.

**Pull request merged**
