### PR TITLE
FNT & BLUETIGERS PROVIDERS

### PR DESCRIPTION
**Pull request by raver2046**

### CODE REVIEW

**Comment by neoatomic** [comment]
Thanks for contributing/helping out. Really appreciate that. :)

(Could you resize the icon FNT.png to 16x16.? its currently 85x81.)

**Comment by maxcore** [comment]
Nice pull req !!!!! :) :)

**Comment by raver2046** [comment]
yes no problem

**Comment by miigotu** [comment]
Tested or copy pasta? xD Thanks for pr too.

**Comment by raver2046** [comment]
tested with a little bit of copy and paste but it fully works

**Comment by maxcore** [comment]
Work for me !

**Comment by miigotu** [comment]
Looks pretty good, but those AuthBase classes are unused (and not needed afaik), besides, where does the token come from?

**Comment by miigotu** [comment]
It's already using cookie auth

**Comment by raver2046** [comment]
Ho dude you know it's a copy and paste froom t411 provider. Sure it's works well but,sure they are a some unused things. If someone want tout optimize ,i fully agree

**Comment by miigotu** [comment]
It's cool lol, just pointing it out. (there is also the propers bug in there)  Either way, I've been going over them and fixing em up anyways, so i will merge this now.

**Comment by miigotu** [comment]
Can you remake this PR to develop please?

**Pull request merged**
